### PR TITLE
prevent unnecessary operations on write actions to read-only repository in s3 gateway

### LINKED ISSUE #7466: [Bug]: Upload object using s3 gateway/lakectl to read-only repo should fail at the beginning of the request
### What happened?

Instead, failed only at the end of the request

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by yonipeleg33**
Closes #7466

### Testing Details
I ran a local lakefs against a real s3 bucket (storage namespace = "s3://yoni-peleg-s3-test/repos/read_only-test"), created a read-only repo, and then tried to upload a 10MB file into it.

Before the change:
```
aws s3 cp /tmp/yoni-test.txt s3://yoni-test-read-only/main/upload-test.txt  0.35s user 0.05s system 17% cpu 2.253 total
```
After the change:
```
aws s3 cp /tmp/yoni-test.txt s3://yoni-test-read-only/main/upload-test.txt  0.36s user 0.03s system 98% cpu 0.392 total
```
Both commands produced the same error:
```
upload failed: ../../tmp/yoni-test.txt to s3://yoni-test-read-only/main/upload-test.txt An error occurred (ErrReadOnlyRepository) when calling the PutObject operation: Attempted to write to a read-only repository
```
This is circumstantial evidence that the file was not being handled before the command failed.

### CODE REVIEW

**Review by idanovo — APPROVED** [review]
I believe this is the right place to put this check.
Asked @arielshaqed just to see what he thinks.

File: pkg/gateway/handler.go [hunk 1]
```diff
@@ -218,6 +218,10 @@ func PathOperationHandler(sc *ServerContext, handler operations.PathOperationHan
 		if authOp == nil {
 			return
 		}
+		if perms.Permission.Action == permissions.WriteObjectAction && repo.ReadOnly {
```
[the remark this answers is not in the document]
Comment (yonipeleg33) [reply pkg/gateway/handler.go:221]: Wouldn't it be beneficial to check for deleteObject permission as well here?

[the remark this answers is not in the document]
Comment (idanovo) [reply pkg/gateway/handler.go:221]: Let's check how delete object acts and add it if we don't fail fast

[the remark this answers is not in the document]
Comment (yonipeleg33) [reply pkg/gateway/handler.go]: I have checked and deletion is the same case as upload - so I added `DeleteObjectAction` to the condition as well.

**Review by arielshaqed — CHANGES_REQUESTED** [review]

File: esti/s3_gateway_test.go [hunk 2]
```diff
@@ -54,6 +55,45 @@ func newMinioClient(t *testing.T, getCredentials GetCredentials) *minio.Client {
...
+	minioClient := newMinioClient(t, credentials.NewStaticV4)
+	content := "some random data"
+	contentReader := strings.NewReader(content)
+
+	_, err := minioClient.PutObject(ctx, readOnlyRepo, gatewayTestPrefix+"/test", contentReader, int64(len(content)), minio.PutObjectOptions{})
+	require.NotNil(t, err)
+	require.Contains(t, err.Error(), "read-only")
+}
+
+func TestS3DeleteFromReadOnlyRepoError(t *testing.T) {
```
Comment (arielshaqed) [inline esti/s3_gateway_test.go:74]: Nice!  A much needed test.

**Review by arielshaqed — COMMENTED** [review]
Thanks!

Let's just make sure TestS3UploadToReadonly would fail without the change, and I think we're done here.  This is a _really_ useful change, it will prevent some expensive failures on readonly repositories.

File: esti/s3_gateway_test.go [hunk 3]
```diff
@@ -54,6 +55,69 @@ func newMinioClient(t *testing.T, getCredentials GetCredentials) *minio.Client {
...
+func TestS3UploadToReadOnlyRepoError(t *testing.T) {
+	ctx, _, repo := setupTest(t)
+	defer tearDownTest(repo)
+
+	readOnlyRepo := createReadOnlyRepositoryByName(ctx, t, "tests3uploadobjectdestreadonly")
+	defer deleteRepositoryIfAskedTo(ctx, readOnlyRepo)
+
+	minioClient := newMinioClient(t, credentials.NewStaticV4)
+	// create a file that's larger than any internal buffering minio does
+	const tenMBInBytes = 10 * 1024 * 1024
```
Comment (arielshaqed) [inline esti/s3_gateway_test.go:67]: Consider
```suggestion
	const tenMega = 10 * 1024 * 1024
```
or
```suggestion
	const tenMibi = 10 * 1024 * 1024
```
The current phrasing reads a bit awkwardly to me, perhaps because I am too much of a physicist: you take 10Mi, multiply it by bytes to get 10MiB, and then divide by bytes to get 10Mi.

File: esti/s3_gateway_test.go [hunk 4]
```diff
@@ -54,6 +55,69 @@ func newMinioClient(t *testing.T, getCredentials GetCredentials) *minio.Client {
...
+	tmpFile, cleanup, tmpErr := MakeTmpFile(tenMBInBytes)
+	require.NoError(t, tmpErr)
+	defer func() {
+		cleanupErr := cleanup()
+		require.NoError(t, cleanupErr)
+	}()
+
+	reader := NewWrappedReader(tmpFile)
```
Comment (arielshaqed) [inline esti/s3_gateway_test.go:75]: I don't understand: why do I need to create a 10-MiB file if I'm not going to read all 10 MiB of it?  Can't I just implement a reader that makes up blocks, say blocks of zeroes?

File: esti/tmp_file_util.go [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+import (
+	crand "crypto/rand"
+	"math"
+	"os"
+)
+
+const defaultChunkSize = 1024
+
+func MakeTmpFile(numBytes int) (*os.File, func() error, error) {
+	file, err := os.CreateTemp("/tmp", "test")
```
Comment (arielshaqed) [inline esti/tmp_file_util.go:12]: Package testing has a specific routine for creating temporary files, and you should use it.  Using `/tmp` is generally a bad idea, because it ignores possible environment settings of _other_ directories to use (useful when my /tmp is too small), and because its name is not associated with the test.

Just use [testing.TempDir](https://pkg.go.dev/testing#B.TempDir); you won't even need to clean it up.

File: esti/tmp_file_util.go [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+	if err != nil {
+		return nil, nil, err
+	}
+
+	chunkSizeBytes := int(math.Min(defaultChunkSize, float64(numBytes)))
+	chunk := make([]byte, chunkSizeBytes)
+	for written := 0; written < numBytes; written += chunkSizeBytes {
+		_, err := crand.Read(chunk)
```
Comment (arielshaqed) [inline esti/tmp_file_util.go:20]: Strongly cryptographic random numbers are overkill in a test.

File: esti/wrapped_reader.go [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+		reader:       reader,
+		numBytesRead: 0,
+	}
+}
+
+func (w *WrappedReader) Read(p []byte) (n int, err error) {
+	n, err = w.reader.Read(p)
+	w.numBytesRead += n
+	return n, err
+}
```
Comment (arielshaqed) [inline esti/wrapped_reader.go:21]: Not sure why we need to wrap a reader here.  Couldn't I just implement something like

```go
type CountingReader struct {
	Count int
}

func (r *CountingReader) Read(p []byte) (n int, err error) {
	p[0] = 0
	r.Count += 1
	return 1, nil
}
```
?

Or if I were afraid of buffering working against me, I could replace with
```go
type CountingReader struct {
	Count int
}

func (r *CountingReader) Read(p []byte) (n int, err error) {
	for i := range p {
		p[i] = 0
	}
	r.Count += len(p)
	return len(p), nil
}
```

**Review by arielshaqed — COMMENTED** [review]
Thanks!

I want to simplify the test further, if possible.  I don't think we need that large file.

**Review by arielshaqed — APPROVED** [review]
This is great, thanks: PR adds feature but improves testing, wow!
