### PR TITLE
Return an informative error message when using 'api/v1' for S3 GW endpoint

### LINKED ISSUE #3082: gateway should identify wrong endpoints requests and return a friendly error
Users often set the gateway endpoint in the clients with `/api/v1/` which is the openAPI endpoint. The return error in such cases isn't very informative:
```
java.nio.file.AccessDeniedException: s3a://<my-repo>/<my-branch>/<path-to-file>: getFileStatus on s3a://<my-repo>/<my-branch>/<path-to-file>: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 4442587FB7D0A2F9; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden
```

We should try and identify those cases and return a more informative error.

### PR DESCRIPTION
**Pull request by itaigilo**
Closes #3082 

## Change Description

Quite a few users are trying sometimes to access the S3 Gateway using an endpoint starting with `/api/v1`.
This used to lead to a `NoSuchBucket` 404 error.

After the fix, such scenario leads to a 404 error, but with a different message:
> Using lakeFS API URI as the endpoint. Try removing the 'api/v1/' part from the endpoint.

### CODE REVIEW

File: pkg/gateway/errors/errors.go [hunk 1]
```diff
@@ -341,6 +342,11 @@ var Codes = errorCodeMap{
 		Description:    "The bucket lifecycle configuration does not exist",
 		HTTPStatusCode: http.StatusNotFound,
 	},
+	ErrNoSuchBucketPossibleAPIEndpoint: {
+		Code:           "ErrNoSuchBucketPossibleAPIEndpoint",
+		Description:    "Using lakeFS API URI as the endpoint. Try removing the 'api/v1/' part from the endpoint.",
```
Comment (arielshaqed) [inline pkg/gateway/errors/errors.go:347]: Perhaps afford people an explanation? I'm thinking of the poor user who has a repo named "api" and manages to mitype a branch name "v1"

File: pkg/gateway/middleware.go [hunk 2]
```diff
@@ -184,6 +184,13 @@ func EnrichWithRepositoryOrFallback(c *catalog.Catalog, authService auth.Gateway
 				fallbackProxy.ServeHTTP(w, req)
 				return
 			}
+
+			// see: github.com/treeverse/lakeFS/issues/3082
```
Comment (arielshaqed) [inline pkg/gateway/middleware.go:188]: Or just state what this is. If I want to know who added this code, GitHub has excellent blame.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Thanks, great improvement! Requesting changes to help users who legitimately have a bucket "api" and a tag "v1".

File: pkg/gateway/middleware.go [hunk 3]
```diff
@@ -184,6 +184,13 @@ func EnrichWithRepositoryOrFallback(c *catalog.Catalog, authService auth.Gateway
...
+			if strings.HasPrefix(req.RequestURI, "/api/v1") {
```
[the remark this answers is not in the document]
Comment (itaigilo) [reply pkg/gateway/middleware.go]: Nope. As far as I understand this, it's the last line before turning to the `ErrNoSuchBucket` error.

[the remark this answers is not in the document]
Comment (itaigilo) [reply pkg/gateway/middleware.go]: You are right. Done.

File: pkg/gateway/errors/errors.go (hunk 1 above)
Comment (arielshaqed) [reply pkg/gateway/errors/errors.go:347]: Hmmm... good thing they don't deduct bandwidth for errors from my paycheck.  I'd go with a definitive error message, followed by a suggestion:

```suggestion
		Description:    `Repository "api" not found; this can happen if your endpoint URL mistakenly ends in "` + apiutil.BaseURL + `".`,
```

(the `` ` `` is an alternative quotation mark that reduces the number of backslashes needed here.)

**Review by arielshaqed — APPROVED** [review]
Thanks!

How was this tested?  OK to pull with only a manual test, but if you do then please also add a test in a later PR.

File: esti/s3_gateway_test.go [hunk 4]
```diff
@@ -655,3 +655,26 @@ func TestS3ReadObjectRedirect(t *testing.T) {
...
 	})
 }
+
+func TestPossibleAPIEndpointError(t *testing.T) {
+	ctx, _, repo := setupTest(t)
+	defer tearDownTest(repo)
+
+	accessKeyID := viper.GetString("access_key_id")
+	secretAccessKey := viper.GetString("secret_access_key")
+	endpoint := "/api/v1" + viper.GetString("s3_endpoint")
```
Comment (arielshaqed) [inline esti/s3_gateway_test.go:665]: I think that this is backwards!?

**Review by arielshaqed — CHANGES_REQUESTED** [review]
You added the test -- yay! -- but I suspect that it is broken because `/api/v1` needs to be a prefix of the _path_ of the URL.  So now I'm requesting that change.

File: esti/s3_gateway_test.go (hunk 4 above)
Comment (N-o-Z) [inline esti/s3_gateway_test.go:665]:
```suggestion
	endpoint := viper.GetString("s3_endpoint") + apiutil.BaseURL
```

File: esti/s3_gateway_test.go [hunk 5]
```diff
@@ -655,3 +655,26 @@ func TestS3ReadObjectRedirect(t *testing.T) {
...
+		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
+		Secure: endpointSecure,
+	})
+	if err != nil {
+		t.Fatalf("minio.New: %s", err)
+	}
+
+	t.Run("use_api_v1_for_client_endpoint", func(t *testing.T) {
+		_, err := minioClient.GetObject(ctx, repo, "main/some", minio.GetObjectOptions{})
+		require.Contains(t, err.Error(), "Using lakeFS API URI as the endpoint")
```
Comment (N-o-Z) [inline esti/s3_gateway_test.go:678]: This will panic if err is nil. You need to check

File: esti/s3_gateway_test.go [hunk 6]
```diff
@@ -655,3 +655,26 @@ func TestS3ReadObjectRedirect(t *testing.T) {
...
+
+	minioClient, err := minio.New(endpoint, &minio.Options{
+		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
+		Secure: endpointSecure,
+	})
+	if err != nil {
+		t.Fatalf("minio.New: %s", err)
+	}
+
+	t.Run("use_api_v1_for_client_endpoint", func(t *testing.T) {
```
Comment (N-o-Z) [inline esti/s3_gateway_test.go:676]: Better for forward compatibility

```suggestion
	t.Run("use_open_api_for_client_endpoint", func(t *testing.T) {
```

File: esti/s3_gateway_test.go (hunk 5 above)
Comment (N-o-Z) [reply esti/s3_gateway_test.go:678]: also, not sure but I think you can use `require.ErrorIs`

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Thanks!
The code looks good, some comments on the test

**Comment by itaigilo** [comment]
Well, the test I've added fails, for:
> minio.New: Endpoint url cannot have fully qualified paths.

I'm using `s3.local.lakefs.io:8000/api/v1` for the endpoint of minio, but this isn't allowed (no extra path is allowed, only hostname).

@arielshaqed  @N-o-Z Can you think of another way to test this, or should I release it without the test?

**Comment by itaigilo** [comment]
> > Well, the test I've added fails, for:
> > > minio.New: Endpoint url cannot have fully qualified paths.
> > 
> > 
> > I'm using `s3.local.lakefs.io:8000/api/v1` for the endpoint of minio, but this isn't allowed (no extra path is allowed, only hostname).
> > @arielshaqed @N-o-Z Can you think of another way to test this, or should I release it without the test?
> 
> One possible option is not using a minio client. Bottom line you are testing an http server and want to check that when you initiate a request with a certain path prefix you get a specific error. There are several ways to test that I assume

Yeah this makes sense - 
But I don't think it's worth the effort for this case.
Unless you think it'll be a useful infra for the future (I don't think so, but I probably don't have enough context)?

**Comment by N-o-Z** [comment]
> > One possible option is not using a minio client. Bottom line you are testing an http server and want to check that when you initiate a request with a certain path prefix you get a specific error. There are several ways to test that I assume
> 
> Yeah this makes sense - But I don't think it's worth the effort for this case. Unless you think it'll be a useful infra for the future (I don't think so, but I probably don't have enough context)?

If there's a scenario, we need to test it.
Adding an automated test protects us from regression

File: esti/s3_gateway_test.go [hunk 7]
```diff
@@ -655,3 +657,31 @@ func TestS3ReadObjectRedirect(t *testing.T) {
...
+	secretAccessKey := viper.GetString("secret_access_key")
+
+	t.Run("use_open_api_for_client_endpoint", func(t *testing.T) {
+		endpoint := viper.GetString("s3_endpoint") + apiutil.BaseURL
+		s3Client, err := testutil.SetupTestS3Client(endpoint, accessKeyID, secretAccessKey)
+		require.NoError(t, err, "failed creating s3 client")
+
+		_, listErr := s3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{Bucket: aws.String("test")})
+		require.NotNil(t, listErr)
+		require.Contains(t, listErr.Error(), `Repository "api" not found`)
```
Comment (N-o-Z) [inline esti/s3_gateway_test.go:675]:
```suggestion
require.ErrorContains(t, listErr, gtwerrors.ErrNoSuchBucketPossibleAPIEndpoint.Error())
```

File: esti/s3_gateway_test.go [hunk 8]
```diff
@@ -655,3 +657,31 @@ func TestS3ReadObjectRedirect(t *testing.T) {
...
+
+	accessKeyID := viper.GetString("access_key_id")
+	secretAccessKey := viper.GetString("secret_access_key")
+
+	t.Run("use_open_api_for_client_endpoint", func(t *testing.T) {
+		endpoint := viper.GetString("s3_endpoint") + apiutil.BaseURL
+		s3Client, err := testutil.SetupTestS3Client(endpoint, accessKeyID, secretAccessKey)
+		require.NoError(t, err, "failed creating s3 client")
+
+		_, listErr := s3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{Bucket: aws.String("test")})
```
Comment (N-o-Z) [inline esti/s3_gateway_test.go:673]:
```suggestion
		_, listErr := s3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{Bucket: aws.String("not-exists")})
```

File: esti/s3_gateway_test.go [hunk 9]
```diff
@@ -655,3 +657,31 @@ func TestS3ReadObjectRedirect(t *testing.T) {
...
+	})
+
+	t.Run("use_proper_client_endpoint", func(t *testing.T) {
+		endpoint := viper.GetString("s3_endpoint")
+		s3Client, err := testutil.SetupTestS3Client(endpoint, accessKeyID, secretAccessKey)
+		require.NoError(t, err, "failed creating s3 client")
+
+		_, listErr := s3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{Bucket: aws.String("test")})
+		require.NotNil(t, listErr)
+		require.NotContains(t, listErr.Error(), `Repository "api" not found`)
```
Comment (N-o-Z) [inline esti/s3_gateway_test.go:685]:
```suggestion
		_, listErr := s3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{Bucket: aws.String("not-exist")})
		require.ErrorContains(t, listErr, gtwerrors.ErrNoSuchBucket.Error())
```

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Some additional comments

**Comment by itaigilo** [comment]
Rewrote the tests, PTAL 🙏

File: pkg/testutil/setup.go
Comment (N-o-Z) [inline pkg/testutil/setup.go:1]: Nice one

File: esti/s3_gateway_test.go [hunk 10]
```diff
@@ -658,30 +658,27 @@ func TestS3ReadObjectRedirect(t *testing.T) {
 	})
 }
 
+func createS3Client(endpoint string, t *testing.T) *s3.Client {
```
Comment (N-o-Z) [inline esti/s3_gateway_test.go:661]: Just as thought,
There are several places who use `testutil.SetupTestS3Client` to change the endpoint (as you already noticed).
Suggest to put this func under the testutil package and use it in all the places where `testutil.SetupTestS3Client` is called.

**Review by N-o-Z — APPROVED** [review]
Excellent work! I have one suggestion but not blocking

File: esti/catalog_export_test.go [hunk 11]
```diff
@@ -177,7 +177,7 @@ func testSymlinkS3Exporter(t *testing.T, ctx context.Context, repo string, tmplD
 	storageURL, err := url.Parse(symlinksPrefix)
 	require.NoError(t, err, "failed extracting bucket name")
 
-	s3Client, err := testutil.SetupTestS3Client("https://s3.amazonaws.com", testData.AWSAccessKeyID, testData.AWSSecretAccessKey)
+	s3Client, err := testutil.SetupTestS3Client("https://s3.amazonaws.com", testData.AWSAccessKeyID, testData.AWSSecretAccessKey, viper.GetBool("force_path_style"))
```
Comment (arielshaqed) [inline esti/catalog_export_test.go:180]: I'd prefer the same style as in delete_objects_test.go, below.  But what I _really_ want is for both calls to look the same.

File: esti/s3_gateway_test.go (hunk 10 above)
Comment (arielshaqed) [reply esti/s3_gateway_test.go:661]: I would prefer _not_ to do this.  `viper` state is, by definition, **global**.  So I want all uses of viper to appear in the test, rather than in a "don't worry about it" setup function.

**Review by arielshaqed — APPROVED** [review]
Thanks!

Would really like _not_ to read config in testutil.
