### PR TITLE
Show skipped hooks for failed action run

### LINKED ISSUE #3098: Skipped hooks should be visible in the Action Run view
When some hook fails during an Action Run, the next hooks are not executed.
The view should explicitly mention the those hooks were skipped. Currently, the view simply doesn't display them.

### PR DESCRIPTION
**Pull request by tshradheya**
Fixes #3098 

image

### CODE REVIEW

File: pkg/actions/service.go [hunk 1]
```diff
@@ -310,10 +306,10 @@ func buildRunManifestFromTasks(record graveler.HookRecord, tasks [][]*Task) RunM
 				ActionName: task.Action.Name,
 				StartTime:  task.StartTime,
 				EndTime:    task.EndTime,
-				Passed:     task.Err == nil,
+				Passed:     task.Err == nil && !task.StartTime.IsZero(), // mark skipped tasks as failed
 			})
-			// keep min run start time
-			if manifest.Run.StartTime.IsZero() || task.StartTime.Before(manifest.Run.StartTime) {
+			// keep min run start time using non-skipped tasks
+			if manifest.Run.StartTime.IsZero() || (!task.StartTime.IsZero() && task.StartTime.Before(manifest.Run.StartTime)) {
```
Comment (nopcoder) [inline pkg/actions/service.go:312]: 1. Using a variable called 'taskStarted' set by '!manifest.Run.StartTime.IsZero()' it can simplify the code and reduce the number of checks
2. Previous commit also skipped the run end time

File: pkg/api/controller.go [hunk 2]
```diff
@@ -1532,9 +1533,12 @@ func (c *Controller) ListRunHooks(w http.ResponseWriter, r *http.Request, reposi
 			StartTime: val.StartTime,
 			EndTime:   &val.EndTime,
```
Comment (nopcoder) [inline pkg/api/controller.go:1534]: This is also true before your PR - but because the task didn't start and end time is optional, we should keep it nil.

**Review by nopcoder — CHANGES_REQUESTED** [review]
Thanks for your contribution! Added my review comments - also the code needs to handle how 'lakectl actions' handles the new status.

File: pkg/actions/service.go (hunk 1 above)
Comment (tshradheya) [reply pkg/actions/service.go:312]: 1. Do you mean `taskStarted` can be set by `!task.StartTime.IsZero()`
2. I am not sure what you meant by previous commit?

**Comment by tshradheya** [comment]
@nopcoder addressed the changes for `lakectl action` command. Please help take a look again

File: pkg/actions/service.go (hunk 1 above)
Comment (nopcoder) [reply pkg/actions/service.go]: 1. Yes
2. Previous commit in this pr, you checked if the task didn't start and skipped the set of start and end time

Comment (tshradheya) [reply pkg/actions/service.go]: For 2. I realized that I don't need to do for endtime because when the condition is to check .After so it won't affect it

**Review by nopcoder — APPROVED** [review]
LGTM Thanks again!
I see we still have an issue with rendering the start time in case of zero value. I think it is related to the server-side loading it from the database.
Will address it in a different issue.

**Comment by tshradheya** [comment]
Hi, can I know what's the issue with rendering the start time currently? I may have missed that

**Comment by itaiad200** [comment]
Thanks for the awesome contribution @tshradheya ! @nopcoder can we merge this? I see that tests were skipped, should we run them in another branch?

**Comment by nopcoder** [comment]
Thanks @itaiad200 looks all green! merge it
