### PR TITLE
Write downloaded file to temp location first for avoiding other readers inconsistencies

### LINKED ISSUE #1149: github.com/treeverse/lakefs/pyramid TestMultipleConcurrentReads flakes out
E.g.:
```sh
ariels@redqueen:~/dev/lakeFS$ go test --count=20 --race github.com/treeverse/lakefs/pyramid
--- FAIL: TestMultipleConcurrentReads (0.01s)
    tier_fs_test.go:175: 
                Error Trace:    tier_fs_test.go:206
                                                        tier_fs_test.go:175
                                                        asm_amd64.s:1374
                Error:          Not equal: 
                                expected: []byte{0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x21}
                                actual  : []byte{}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,2 @@
                                -([]uint8) (len=12) {
                                - 00000000  68 65 6c 6c 6f 20 77 6f  72 6c 64 21              |hello world!|
                                +([]uint8) {
                                 }
                Test:           TestMultipleConcurrentReads
FAIL
FAIL    github.com/treeverse/lakefs/pyramid     53.283s
FAIL
```

### PR DESCRIPTION
**Pull request by itaiad200**
closes #1149

### CODE REVIEW

File: pyramid/tier_fs.go [hunk 1]
```diff
@@ -232,19 +233,33 @@ func (tfs *TierFS) openFile(fileRef localFileRef, fh *os.File) (*ROFile, error)
...
+func (tfs *TierFS) openWithLock(fileRef localFileRef) (*os.File, error) {
 	_, err := tfs.keyLock.Compute(fileRef.filename, func() (interface{}, error) {
-		var err error
+		// check again file existence, now that we have the lock
+		fh, err := os.Open(fileRef.fullPath)
+		if err == nil {
+			// file exists after all
+			cacheAccess.WithLabelValues(tfs.fsName, "Hit").Inc()
+			_ = fh.Close()
+			return nil, nil
```
Comment (arielshaqed) [inline pyramid/tier_fs.go:247]: The file exists  and all is good; why not return it?
```suggestion
			return fh, nil
```

Comment (arielshaqed) [reply pyramid/tier_fs.go:247]: In fact, I would expect this case to crash on the `tfs.openFile` call.

File: pyramid/tier_fs.go [hunk 2]
```diff
@@ -253,12 +268,18 @@ func (tfs *TierFS) readFromBlockStorage(fileRef localFileRef) (*os.File, error)
 		if err != nil {
 			return nil, fmt.Errorf("copying date to file: %w", err)
```
Comment (arielshaqed) [inline pyramid/tier_fs.go:269]: nit:
```suggestion
			return nil, fmt.Errorf("copying data to file: %w", err)
```

File: pyramid/tier_fs.go [hunk 3]
```diff
@@ -253,12 +268,18 @@ func (tfs *TierFS) readFromBlockStorage(fileRef localFileRef) (*os.File, error)
...
 		}
-		downloadHistograms.WithLabelValues(tfs.fsName).Observe(float64(written))
-		return nil, err
+
+		// copy from temp path to actual path
+		if err = tfs.syncDir.renameFile(tmpFullPath, fileRef.fullPath); err != nil {
+			return nil, fmt.Errorf("rename temp file: %w", err)
+		}
+
+		return nil, nil
```
Comment (arielshaqed) [inline pyramid/tier_fs.go:282]:
```suggestion
		return fh, nil
```

Comment (arielshaqed) [reply pyramid/tier_fs.go:282]: Again, this is really a race.  On line 289 you *again* try to open the file.  But the file might already have been removed.  This is rare, but easy enough to fix: keep the return value from `keyLock.Compute` and return it here if possible.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Small race remains between opening the file and re-opening it.  Also that's inefficient -- but I think we can fix it easily enough.

File: pyramid/tier_fs.go (hunk 2 above)
Comment (itaiad200) [reply pyramid/tier_fs.go]: Done.

File: pyramid/tier_fs.go (hunk 3 above)
Comment (itaiad200) [reply pyramid/tier_fs.go:282]: I agree that it's a better habit to return the file-handler and I'll fix it.
However notice it's not a race. The file wasn't stored in the eviction cache yet, it happens in the `openFile` func.
So file wasn't stored in the eviction -> can't be evicted -> file is always there.

File: pyramid/tier_fs.go (hunk 1 above)
Comment (itaiad200) [reply pyramid/tier_fs.go:247]: See discussion below.

File: pyramid/tier_fs.go (hunk 3 above)
Comment (itaiad200) [reply pyramid/tier_fs.go:282]: Actually, after applying the change, it is wrong.
`Compute` only calls the function once for concurrent calls, so returning the same file-handler isn't right.

Comment (arielshaqed) [reply pyramid/tier_fs.go:282]: Yikes!  True...  So the way to do this would be to keep an external `var fh *os.File`, and set that here (and still `return nil, nil`), then use that `fh` if not `nil` after this `Compute` call.  Which is unpleasant.  (oh, and I forgot to rewind the file before returning, of course).
I still don't like this double-open (you open a file twice when you download it), but I do not see a race to cause trouble here - just some inefficiency.

**Review by arielshaqed — APPROVED** [review]
THANKS!  Good change.
