### PR TITLE
Fix ObjectCopy for imported objects

### LINKED ISSUE #9756: CopyObject metadata copy for imported data
Currently, lakeFS performs metadata cloning for uploaded data within the last 5 hours (a grace period before it becomes a candidate for garbage collection). When data is imported, staged, or committed, there is no risk of GC deleting the cloned data, so we can skip the grace time check and enable metadata copying.

### LINKED ISSUE #9944: CopyObject API returns incorrect physical address for imported objects
## Description

The CopyObject API handler incorrectly returns physical addresses for objects with absolute paths (imported objects).

## Impact

When copying imported objects (with absolute physical addresses), the API response contains an incorrectly formatted physical address instead of preserving the absolute path.
When copy object performs actual copy, based on the object grace time - this is not an issue as the copied object is a object with relative address.

## Expected Behavior

The physical address in the CopyObject response should match the new entry's address type.
In case we clone a new object it will be relative and when it is imported and kept abs. path it will be full.

### PR DESCRIPTION
**Pull request by nopcoder**
## Summary

Fixes CopyObject operations for imported/absolute path objects.

## Issues Fixed

1. **Allow cloning of imported objects (#9756)**: Imported objects (with `AddressTypeFull`) are not subject to GC, so we can skip the grace period check on the underlying storage object's last-modified timestamp. This allows CopyObject to clone imported objects efficiently instead of copying data.

2. **Fix CopyObject API response address type (#9944)**: The CopyObject handler was using hardcoded `IdentifierTypeRelative` when resolving physical addresses. Now uses `entry.AddressType.ToIdentifierType()` to return the correct address based on entry type.

## Changes
- Skip object timestamp check in `cloneEntry` for `AddressTypeFull` entries
- Use correct identifier type when resolving namespace in CopyObject response
- Add test case for copying imported objects

Closes #9756
Closes #9944

### CODE REVIEW

File: pkg/api/controller.go [hunk 1]
```diff
@@ -3989,7 +3989,7 @@ func (c *Controller) CopyObject(w http.ResponseWriter, r *http.Request, body api
 		return
 	}
 
-	qk, err := c.BlockAdapter.ResolveNamespace(repo.StorageID, repo.StorageNamespace, entry.PhysicalAddress, block.IdentifierTypeRelative)
```
Comment (N-o-Z) [inline pkg/api/controller.go:3992]: ‼️

**Review by N-o-Z — CHANGES_REQUESTED** [review]
I like the modifications that you did but I think we should have a different approach here.
It's good the we're using the actual entry's path type - however I think the criteria itself to whether this should be cloned or copied is not the path type but rather if the path lies under the namespace data path. 
i.e.:
If path is not relative && path does not contain (storage namespace + data) path
This is a much more accurate definition which excludes scenarios where we save full path under storage namespace data prefix (whether we do that to day or not - or if we decide to do that somewhere in the future)

**Comment by nopcoder** [comment]
> If path is not relative && path does not contain (storage namespace + data) path
> This is a much more accurate definition which excludes scenarios where we save full path under storage namespace data prefix (whether we do that to day or not - or if we decide to do that somewhere in the future)

Thank. I understand the concern -- which is what I expect the import/stage/link API implementation to make sure we align the full vs relative in the path type.

Having the path type as the indicator to what is managed and what is not managed by lakeFS is a better way and it was one of the reasons we added it.

I will address it as it is the current implementation of the spark gc job.

**Review by N-o-Z — APPROVED** [review]
Thanks for addressing the comments! 
Can we add a unit test for that exact scenario - verifying that an entry with absolute path in the storage namespace is not being cloned (since we don't explicitly block this in the code)

**Comment by nopcoder** [comment]
> Thanks for addressing the comments! Can we add a unit test for that exact scenario - verifying that an entry with absolute path in the storage namespace is not being cloned (since we don't explicitly block this in the code)

Good point, at first I thought the current copy object does that - but it turned everything to clone. 
Added a test that make sure we copy object.
