### PR TITLE
Fix Stuck Goroutins

### LINKED ISSUE #10054: Flaky TestController_MergeIntoBranchAsyncOperations test
Across multiple PRs, the `TestController_MergeIntoBranchAsyncOperations` test has been flaky.

**Examples:**

https://github.com/treeverse/lakeFS-Enterprise/actions/runs/21255437674/job/61177734222

https://github.com/treeverse/lakeFS-Enterprise/actions/runs/21332449353/job/61399262863

### PR DESCRIPTION
**Pull request by Annaseli**
Closes #10054

## Change Description

Across multiple PRs, the `TestController_MergeIntoBranchAsyncOperations` test has been flaky.

**Example:**

https://github.com/treeverse/lakeFS-Enterprise/actions/runs/21255437674/job/61177734222

1. 

Changed the `pkg/graveler/committed/meta_range_writer.go` because:
We have goroutines stuck in `(*BatchCloser).handleClose`. They’re blocked on line 59 of `batch.go`, inside `handleClose`, which is created by `NewBatchCloser` (line 31) , meaning they’re waiting to receive from `bc.ch`.
Looking at `batch.go`, the channel is only closed by `Wait()`. `Wait()` is called only from `GeneralMetaRangeWriter.Close()`.

In `committed/manager.go`, both `(*committedManager).merge` and `(c *committedManager) Commit` call `mwWriter.Close(ctx)` only on success. If the operation fails before `Close()`, only `Abort()` runs (via `defer`). Since `Abort()` doesn’t close `bc.ch`, the workers remain stuck.

2.

Changed the `pkg/batch/executor.go` because:
We have goroutine 7077 stuck in `(*StoreService).Stop (lakeFS-Enterprise/lakefs-oss/pkg/actions/service.go:234)` at `s.wg.Wait()`. That means Stop() is waiting for a goroutine to finish, but it never does.

We also have goroutine 15391 which, after calling `(*StoreService).PostMergeHook.(*StoreService).asyncRun.func1()`, gets stuck in `(*ConditionalExecutor).BatchFor (lakeFS-Enterprise/lakefs-oss/pkg/batch/executor.go:130)` at `res := <-cb` i.e., it’s blocked waiting to receive from a channel.

`BatchFor` sends a request to `e.requests` and then waits on `res := <-cb`. If the test times out / the context is canceled, `(*Executor).Run ` in `executor.go` goroutine hits `case <-ctx.Done(): return` and exits immediately. In that case, the request was sent, but no response is ever delivered to cb, so goroutine 15391 waits forever.

In `BatchFor`, `cb` is passed as `onResponse` in the request, and in `executor.go` only `(*Executor).Run ` sends on `onResponse`. So if `Run` exits without responding, BatchFor gets stuck.

### CODE REVIEW

File: pkg/graveler/committed/meta_range_writer.go [hunk 1]
```diff
@@ -182,6 +182,11 @@ func (w *GeneralMetaRangeWriter) writeRangesToMetaRange(ctx context.Context) (*g
 }
 
 func (w *GeneralMetaRangeWriter) Abort() error {
+	// Release workers by closing the channel
+	if w.batchWriteCloser != nil {
+		_, _ = w.batchWriteCloser.Wait()
+	}
```
Comment (nopcoder) [inline pkg/graveler/committed/meta_range_writer.go]: can remove the nil check
