### PR TITLE
Simplify branch protect interface

### LINKED ISSUE #6674: [Bug]: Quickstart is broken when creating sample repo
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Run the container: `docker run --name lakefs --pull always \
             --rm --publish 8000:8000 \
             treeverse/lakefs:latest \
             run --quickstart`
2. Open the UI and login
3. Click `Create Sample Repository`

image

### Expected behavior

Sample repo is created successfully. 

### lakeFS version

0.111.0

### How lakeFS is installed

docker, local

### Affected clients

_No response_

### Relevant log output

```shell
2023/10/02 08:07:01 http: panic serving 172.17.0.1:50112: assignment to entry in nil map
goroutine 303 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xb0
panic({0x166c8a0, 0x4ebed40})
	/usr/local/go/src/runtime/panic.go:890 +0x248
github.com/treeverse/lakefs/pkg/samplerepo.AddBranchProtection({0x4ee1b30, 0x400e4e8060}, 0x400e1db9a0, {0x4f0a040, 0x40003aa820})
	/build/pkg/samplerepo/samplecontent.go:126 +0xe0
github.com/treeverse/lakefs/pkg/api.(*Controller).CreateRepository(0x400047a380, {0x4edeca0, 0x400e1ad818}, 0x400e1e7e00, {0x400e48b1e0, {0x400e4e2210, 0xa}, 0x400e4e220c, {0x400e0bbec0, 0x12}}, ...)
	/build/pkg/api/controller.go:1623 +0x89c
github.com/treeverse/lakefs/pkg/api/apigen.(*ServerInterfaceWrapper).CreateRepository.func1({0x4edeca0?, 0x400e1ad818?}, 0x1980001?)
	/build/pkg/api/apigen/lakefs.gen.go:20518 +0x68
github.com/treeverse/lakefs/pkg/api/apigen.(*ServerInterfaceWrapper).CreateRepository(0x400c6bcba0, {0x4edeca0, 0x400e1ad818}, 0x400e1e7d00)
	/build/pkg/api/apigen/lakefs.gen.go:20525 +0x4ac
net/http.HandlerFunc.ServeHTTP(0x400cc86910?, {0x4edeca0?, 0x400e1ad818?}, 0xffffbc338108?)
	/usr/local/go/src/net/http/server.go:2122 +0x38
....
```
```


### Contact details

_No response_

### PR DESCRIPTION
**Pull request by johnnyaug**
Following @nopcoder's comments on #6682.

Resolves #6674.

### CODE REVIEW

File: pkg/graveler/branch/protection_manager.go [hunk 1]
```diff
@@ -36,39 +31,33 @@ func NewProtectionManager(settingManager *settings.Manager) *ProtectionManager {
...
-	return m.settingManager.Save(ctx, repository, ProtectionSettingKey, rules)
-}
-
-func (m *ProtectionManager) SetRulesIf(ctx context.Context, repository *graveler.RepositoryRecord, rules *graveler.BranchProtectionRules, lastKnownChecksum *string) error {
-	err := m.settingManager.SaveIf(ctx, repository, ProtectionSettingKey, rules, lastKnownChecksum)
-	if errors.Is(err, kv.ErrPredicateFailed) {
-		return graveler.ErrPreconditionFailed
-	}
-	return err
+func (m *ProtectionManager) SetRules(ctx context.Context, repository *graveler.RepositoryRecord, rules *graveler.BranchProtectionRules, lastKnownChecksum *string) error {
```
Comment (nopcoder) [inline pkg/graveler/branch/protection_manager.go:47]:
```suggestion

func (m *ProtectionManager) SetRules(ctx context.Context, repository *graveler.RepositoryRecord, rules *graveler.BranchProtectionRules, lastKnownChecksum *string) error {
```

File: pkg/graveler/branch/protection_manager.go [hunk 2]
```diff
@@ -36,39 +31,33 @@ func NewProtectionManager(settingManager *settings.Manager) *ProtectionManager {
...
 	if errors.Is(err, graveler.ErrNotFound) {
-		return &graveler.BranchProtectionRules{}, nil, nil
+		return &graveler.BranchProtectionRules{}, swag.String(""), nil
 	}
 	if err != nil {
 		return nil, nil, err
 	}
 	if proto.Size(rulesMsg) == 0 {
 		return &graveler.BranchProtectionRules{}, nil, nil
 	}
```
Comment (nopcoder) [inline pkg/graveler/branch/protection_manager.go:44]: In this case we have data, so we should return the checksum. Even if the data is an empty slice.

File: pkg/graveler/settings/manager.go [hunk 3]
```diff
@@ -105,52 +108,52 @@ func computeChecksum(value []byte) (*string, error) {
...
+// It returns a checksum representing the version of the setting, which can be passed to SaveIf for conditional updates.
+// The checksum of a non-existent setting is the empty string.
+func (m *Manager) GetLatest(ctx context.Context, repository *graveler.RepositoryRecord, key string, dst proto.Message) (*string, error) {
 	settings, err := m.store.Get(ctx, []byte(graveler.RepoPartition(repository)), []byte(graveler.SettingsPath(key)))
 	if err != nil {
 		if errors.Is(err, kv.ErrNotFound) {
 			err = graveler.ErrNotFound
 		}
-		return nil, nil, err
+		return swag.String(""), err
```
Comment (nopcoder) [inline pkg/graveler/settings/manager.go:120]: I understood why we would like to return a value in case of an error, specific not found. But I hope that the caller will work based on the error and the convention of the API and not use the checksum value in case of an error.

File: pkg/graveler/settings/manager.go [hunk 4]
```diff
@@ -105,52 +108,52 @@ func computeChecksum(value []byte) (*string, error) {
...
+		return tmp, err
 	})
 	if err != nil {
-		return nil, err
+		return err
 	}
 	if setting == nil {
-		return nil, graveler.ErrNotFound
+		return graveler.ErrNotFound
 	}
```
Comment (nopcoder) [inline pkg/graveler/settings/manager.go:154]: About graveler.ErrNotFound: we check for the specific error inside the callback and also have `if settings == nil` to return the same error.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/graveler/settings/manager.go (hunk 4 above)
Comment (johnnyaug) [reply pkg/graveler/settings/manager.go:154]: That's because it may arrive from the cache, which doesn't return this error.

File: pkg/graveler/settings/manager.go (hunk 3 above)
Comment (johnnyaug) [reply pkg/graveler/settings/manager.go:120]: Done - not returning empty string.

File: pkg/graveler/branch/protection_manager.go (hunk 2 above)
Comment (johnnyaug) [reply pkg/graveler/branch/protection_manager.go:44]: Removed

**Review by nopcoder — APPROVED** [review]
LGTM!
