### PR TITLE
fix bug: wrong timestamp after ORC import + testing

### LINKED ISSUE #571: When importing from an ORC inventory, last modified date is wrong (set to 51 years ago).
Need to check if also happens with Parquet inventory.

### PR DESCRIPTION
**Pull request by johnnyaug**
Closes #571

### CODE REVIEW

File: block/inventory.go [hunk 1]
```diff
@@ -18,12 +18,12 @@ type Inventory interface {
...
-	Bucket          string
-	Key             string
-	Size            int64
-	LastModified    int64
-	Checksum        string
-	PhysicalAddress string
+	Bucket             string
+	Key                string
+	Size               int64
+	LastModifiedMillis int64
```
Comment (arielshaqed) [inline block/inventory.go:24]: Can we use a `time` type here?  This is precisely what causes unit failures...

**Review by arielshaqed — CHANGES_REQUESTED** [review]
This (adding units to field names) is a good change, but I think it would be even better just to use `time.Time`, converting only at the storage level.

File: inventory/s3/orc_reader.go [hunk 2]
```diff
@@ -57,7 +57,7 @@ func (r *OrcInventoryFileReader) inventoryObjectFromRow(rowData []interface{}) I
 	}
 	var lastModified *int64
 	if lastModifiedIdx, ok := r.orcSelect.IndexInSelect["last_modified_date"]; ok && rowData[lastModifiedIdx] != nil {
-		lastModified = swag.Int64(rowData[lastModifiedIdx].(time.Time).Unix())
+		lastModified = swag.Int64(rowData[lastModifiedIdx].(time.Time).UnixNano() / int64(time.Millisecond))
```
Comment (arielshaqed) [inline inventory/s3/orc_reader.go:60]: Please use  [`time.Unix`](https://golang.org/pkg/time/#Unix) rather than perform this conversion.  It would be less typing, also because my reading of the documentation]says it doesn't work:
>  The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC. As this time is unlikely to come up in practice, the IsZero method gives a simple way of detecting a time that has not been initialized explicitly. 
Also I don't understand how you can cast an integer type to `time.Time`, which is [a big-ish struct](https://golang.org/src/time/time.go?s=6278:7279#L117).

Does this function run in any test?

File: inventory/s3/orc_reader.go [hunk 3]
```diff
@@ -72,13 +72,13 @@ func (r *OrcInventoryFileReader) inventoryObjectFromRow(rowData []interface{}) I
...
-		Key:            rowData[r.orcSelect.IndexInSelect["key"]].(string),
-		Size:           size,
-		LastModified:   lastModified,
-		Checksum:       eTag,
-		IsLatest:       isLatest,
-		IsDeleteMarker: isDeleteMarker,
+		Bucket:             rowData[r.orcSelect.IndexInSelect["bucket"]].(string),
+		Key:                rowData[r.orcSelect.IndexInSelect["key"]].(string),
+		Size:               size,
+		LastModifiedMillis: lastModified,
```
Comment (arielshaqed) [inline inventory/s3/orc_reader.go:78]: Why do we need `millis` here?  Alternatively, if `lastModified` is already `int64` milliseconds, can we either convert it to `time.Time` when created, or at least call it `lastModifiedMillis`?

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Great to use `time.Time`, but not sure about the conversion in one place from integers to Time.

File: inventory/s3/orc_reader.go (hunk 2 above)
Comment (arielshaqed) [reply inventory/s3/orc_reader.go:60]: After f2fing I realize I'm holding it backwards.  Just rename to `lastModifiedMillis` and it will be clearer.

**Review by arielshaqed — APPROVED** [review]
Good to go once all millis are called millis.

File: block/s3/inventory_test.go [hunk 4]
```diff
@@ -182,14 +192,21 @@ func TestIterator(t *testing.T) {
 		if len(objects) != len(test.ExpectedObjects) {
 			t.Fatalf("unexpected number of objects in inventory. expected=%d, got=%d", len(test.ExpectedObjects), len(objects))
 		}
-		if !reflect.DeepEqual(objects, test.ExpectedObjects) {
-			t.Fatalf("objects in inventory differrent than expected. expected=%v, got=%v", test.ExpectedObjects, objects)
+		for i, obj := range objects {
+			if obj.Key != test.ExpectedObjects[i] {
+				t.Fatalf("retuned object in index %d different than expected. expected=%s, got=%s", i, test.ExpectedObjects[i], obj.Key)
```
Comment (arielshaqed) [inline block/s3/inventory_test.go:197]:
```suggestion
				t.Fatalf("returned object at index %d different than expected. expected=%s, got=%s", i, test.ExpectedObjects[i], obj.Key)
```
or even (more Go-ish?)
```suggestion
				t.Fatalf("at index %d: expected=%s, got=%s", i, test.ExpectedObjects[i], obj.Key)
```

**Review by arielshaqed — APPROVED** [review]
Cool, stillLGTM.
