### PR TITLE
Fix docs links on new empty repository UI page

### LINKED ISSUE #2104: Get started with this repository docs link to page not found
The new repository tree includes the get started page with an invalid link to 'docs' - page not found.

### PR DESCRIPTION
**Pull request by nopcoder**
Close #2104

### CODE REVIEW

File: webui/src/lib/components/repository/tree.jsx [hunk 1]
```diff
@@ -272,7 +272,13 @@ const GetStarted = ({ onUpload }) => {
 
             <Row className="pt-2 ml-2">
                 <DotIcon className="mr-1 mt-1"/>
-                See the &nbsp;<a href="https://docs.lakefs.io/using/" target="_blank" rel="noopener noreferrer">docs</a>&nbsp;for other ways to import data to your repository.
+                See the&nbsp;<a href="https://docs.lakefs.io/integrations/distcp.html" target="_blank" rel="noopener noreferrer">DistCp</a>&nbsp;and&nbsp;
```
Comment (johnnyaug) [inline webui/src/lib/components/repository/tree.jsx:275]: I'd change to:
Use [DistCp] or [Rclone] to copy data into your repository

**Review by johnnyaug — CHANGES_REQUESTED** [review]

**Review by johnnyaug — APPROVED** [review]
