### PR TITLE
Fix: Failing HTTP request hook should be logged

### LINKED ISSUE #3099: Failing HTTP request hook should be logged
When a webhook fails before the http request was sent (e.g "no such host"), the failed action log doesn't display the error.
It does appear in the returned error to the client.

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #3099

### CODE REVIEW

**Comment by N-o-Z** [comment]
Before:
image

After:
image

File: pkg/actions/webhook.go [hunk 1]
```diff
@@ -147,6 +147,7 @@ func executeAndLogResponse(ctx context.Context, req *http.Request, buf *bytes.Bu
 	elapsed := time.Since(start)
 	buf.WriteString(fmt.Sprintf("\nRequest duration: %s\n", elapsed))
 	if err != nil {
+		buf.WriteString(fmt.Sprintf("\nError: %s\n", err))
```
Comment (itaiad200) [inline pkg/actions/webhook.go:150]: What happens if it fail on line 85?

Comment (N-o-Z) [reply pkg/actions/webhook.go:150]: In that case we didn't even try to execute the URL.
I suggest creating a new method "logRunError" which will just write error to buffer and close it.
In that case we might want to map all possible error types and format them properly

Comment (nopcoder) [reply pkg/actions/webhook.go:150]: - Think we can long the `err` of the failed task at the `service.go` (runTasks) level.
- We can use `fmt.Fprintf(buf, "\nError: %s\n", err)` instead of the combination of `Sprintf` and `WriteString`

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/actions/service.go [hunk 2]
```diff
@@ -203,16 +203,25 @@ func (s *Service) runTasks(ctx context.Context, record graveler.HookRecord, task
...
 				task.StartTime = time.Now().UTC()
-				task.Err = task.Hook.Run(ctx, record, hookOutputWriter)
+
+				task.Err = task.Hook.Run(ctx, record, &buf)
 				task.EndTime = time.Now().UTC()
 
 				s.stats.CollectEvent("actions_service", string(record.EventType))
 
-				if task.Err != nil {
+				if task.Err != nil { // log error in buffer
```
Comment (itaiad200) [inline pkg/actions/service.go:214]:
```suggestion
				if task.Err != nil { 
				// log error in buffer
```

File: pkg/actions/service.go [hunk 3]
```diff
@@ -203,16 +203,25 @@ func (s *Service) runTasks(ctx context.Context, record graveler.HookRecord, task
...
 					// wrap error with more information and return
 					task.Err = fmt.Errorf("hook run id '%s' failed on action '%s' hook '%s': %w",
 						task.HookRunID, task.Action.Name, task.HookID, task.Err)
+					_, _ = fmt.Fprint(&buf, task.Err)
+				}
+				err := hookOutputWriter.OutputWrite(ctx, &buf, int64(buf.Len()))
+				if err != nil {
+					return fmt.Errorf("failed to write action log. %w", err)
+				}
+				if task.Err != nil { // stop execution of tasks and return error
```
Comment (itaiad200) [inline pkg/actions/service.go:224]:
```suggestion
				if task.Err != nil { 
				// stop execution of tasks and return error
```

File: pkg/actions/service.go [hunk 4]
```diff
@@ -203,16 +203,25 @@ func (s *Service) runTasks(ctx context.Context, record graveler.HookRecord, task
...
-				if task.Err != nil {
+				if task.Err != nil { // log error in buffer
 					// wrap error with more information and return
 					task.Err = fmt.Errorf("hook run id '%s' failed on action '%s' hook '%s': %w",
 						task.HookRunID, task.Action.Name, task.HookID, task.Err)
+					_, _ = fmt.Fprint(&buf, task.Err)
+				}
+				err := hookOutputWriter.OutputWrite(ctx, &buf, int64(buf.Len()))
+				if err != nil {
+					return fmt.Errorf("failed to write action log. %w", err)
```
Comment (itaiad200) [inline pkg/actions/service.go:222]:
```suggestion
					return fmt.Errorf("failed to write action log: %w", err)
```

**Review by itaiad200 — APPROVED** [review]
LGTM

File: pkg/actions/service.go [hunk 5]
```diff
@@ -203,16 +203,25 @@ func (s *Service) runTasks(ctx context.Context, record graveler.HookRecord, task
...
 				task.EndTime = time.Now().UTC()
 
 				s.stats.CollectEvent("actions_service", string(record.EventType))
 
-				if task.Err != nil {
+				if task.Err != nil { // log error in buffer
 					// wrap error with more information and return
 					task.Err = fmt.Errorf("hook run id '%s' failed on action '%s' hook '%s': %w",
 						task.HookRunID, task.Action.Name, task.HookID, task.Err)
+					_, _ = fmt.Fprint(&buf, task.Err)
```
Comment (nopcoder) [inline pkg/actions/service.go:218]: - Optional: long of the original error is extra information we format is for our logs as far as I remember.
- Just in case we like to print something after, and we will need a new-line at the end

```suggestion
					_, _ = fmt.Fprintf(&buf, "%s\n", task.Err)
```

File: pkg/actions/service.go (hunk 4 above)
Comment (nopcoder) [reply pkg/actions/service.go:222]: I think we will also need to format - task.HookRunID, task.Action.Name, task.HookID
For additional information

File: pkg/actions/service.go (hunk 2 above)
Comment (nopcoder) [reply pkg/actions/service.go:214]: Don't need extra comments ;)

**Review by nopcoder — APPROVED** [review]
LGTM - minor comments
