### PR TITLE
Fix & Reenable TestRunResultsIterator

### LINKED ISSUE #3623: Fix and reenable TestRunResultsIterator
It's flaky and we need to fix it and unskip it

### PR DESCRIPTION
**Pull request by itaiad200**
closes #3623

### CODE REVIEW

File: pkg/actions/kv_run_results_iterator_test.go [hunk 1]
```diff
@@ -213,12 +223,23 @@ func createTestData(t *testing.T, ctx context.Context, kvStore kv.StoreMessage)
...
-	keyList[msgIdx] = key
+	keyList = append(keyList, key)
+
+	// reverse the list to make it sorted in ascending order
+	reverse(keyList)
+
+	return keyMap, keyList
+}
+
+func reverse(s []string) {
```
Comment (N-o-Z) [inline pkg/actions/kv_run_results_iterator_test.go:241]: You know the size of the list, you can create an array and insert the items in reverse order, I think this func is redundant

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Thanks - one small comment

File: pkg/actions/kv_run_results_iterator_test.go [hunk 2]
```diff
@@ -20,16 +21,14 @@ const (
 	testByCommit       = "testCommit1"
 	testMissingPrimary = "branchPartialPrimary"
 	IndexOutOfRange    = "zzz"
+	withHooks          = 100
```
Comment (N-o-Z) [inline pkg/actions/kv_run_results_iterator_test.go:24]: What does withHooks mean?

Comment (itaiad200) [reply pkg/actions/kv_run_results_iterator_test.go]: rephrased.

File: pkg/actions/kv_run_results_iterator_test.go (hunk 1 above)
Comment (itaiad200) [reply pkg/actions/kv_run_results_iterator_test.go:244]: It is, but with all the mappings it makes handling `keyList` & `keyMap` so much harder that I wish to avoid another off-by-one mistake. Reversing is much easier than inserting in reverse order.
