### PR TITLE
Fix missing error in UI after failed login

### LINKED ISSUE #9662: webUI: No Error Message Displayed on Failed Login Attempt
When trying to log in with incorrect credentials, no error message is displayed to the user.

### PR DESCRIPTION
**Pull request by zubron**
Closes #9662 

### Background
The Login endpoint was not checking for errors from the authenticator that would indicate invalid credentials (ErrNotFound and ErrInvalidSecretAccessKey). These errors would fall through and result in 500 responses instead of 401 to indicate invalid credentials.

The login form in the UI would only check for 401 errors and so would fail to give any feedback to the user.

### Bug Fix

This change adds handling for ErrNotFound and ErrInvalidSecretAccessKey, returning a 401 error response. It also updates the UI to check for different error types and displays an appropriate message in each case.

### Testing Details

Unit tests were added for the controller changes.
The UI changes were tested manually with the following scenarios:
- Providing invalid access key or invalid secret access key (401 error, displays "The credentials don't match.")
- Stopping lakeFS server before clicking Login (500 fetch error, displays "Unable to connect to the authentication service.")
- Simulating the network being unavailable in Chrome devtools (fetch error `net::ERR_INTERNET_DISCONNECTED`, displays message from the thrown error, e.g. "Failed to fetch"

## Additional info

Invalid credentials
Screenshot 2025-12-10 at 12 39 45 PM

lakeFS server not available
Screenshot 2025-12-10 at 12 40 13 PM

Other network error
Screenshot 2025-12-10 at 12 40 26 PM

### CODE REVIEW

File: pkg/api/controller.go [hunk 1]
```diff
@@ -772,8 +772,12 @@ func (c *Controller) Login(w http.ResponseWriter, r *http.Request, body apigen.L
 	ctx := r.Context()
 	user, err := userByAuth(ctx, c.Logger, c.Authenticator, c.Auth, body.AccessKeyId, body.SecretAccessKey)
 	if err != nil {
-		if errors.Is(err, ErrAuthenticatingRequest) {
-			writeResponse(w, r, http.StatusUnauthorized, http.StatusText(http.StatusUnauthorized))
+		// Check for authentication-related errors that should return 401
```
Comment (N-o-Z) [inline pkg/api/controller.go]: This might be an old code. We should probably use handleApiErrorCallback instead of in-lining these error checks?

File: webui/src/pages/auth/login.tsx [hunk 2]
```diff
@@ -92,9 +92,16 @@ const LoginForm = ({loginConfig}: {loginConfig: LoginConfig}) => {
...
                             if (err instanceof AuthenticationError && err.status === 401) {
-                                const contents = {__html: `${loginConfig.login_failed_message}` ||
-                                        "Credentials don't match."};
-                                setLoginError(<span dangerouslySetInnerHTML={contents}/>);
+                                // Invalid credentials - show custom message from config
+                                const message = loginConfig.login_failed_message || "The credentials don't match.";
+                                setLoginError(message);
+                            } else if (err instanceof AuthenticationError) {
+                                // Other auth errors (500 server errors during authentication)
+                                setLoginError("Unable to connect to the authentication service. Please try again in a few moments.");
```
Comment (itaigilo) [inline webui/src/pages/auth/login.tsx]: From your comment, seems that this error message might be misleading - 
Not every 500 error is "Unable to connect" (might be other internal server errors, etc.).

File: pkg/api/controller.go (hunk 1 above)
Comment (zubron) [reply pkg/api/controller.go]: I didn't know about this function, I'll take a look!

File: webui/src/pages/auth/login.tsx (hunk 2 above)
Comment (zubron) [reply webui/src/pages/auth/login.tsx]: Really good point - thanks! I've updated this to use unique error types for the different status codes and removed the status code checking from the component. I changed the messages so that they're a bit more generic. Hopefully these are better, but let me know if you would prefer something different.

File: pkg/api/controller.go (hunk 1 above)
Comment (zubron) [reply pkg/api/controller.go]: Thanks for the pointer, I've updated it to use this approach.

**Review by N-o-Z — APPROVED** [review]
LGTM, thanks!
