### PR TITLE
Write GC summary file using UTF-8

### LINKED ISSUE #4644: GC: writeJsonSummary writes file with interleaved null characters
The function uses `stream.writeChars` on a JObject which results in a an invalid string, which causes an exception when trying to read into json object afterwards

```
[, {, , ", , r, , u, , n, , _, , i, , d, , ", , :, , ", , 1, , 4, , 1, , 9, , f, , c, , e, , a, , -, , a, , 4, , 4, , 1, , -, , 4, , 9, , 7, , b, , -, , b, , 3, , 0, , 1, , -, , 2, , 4, , 6, , c, , 7, , f, , 3, , 6, , 0, , 1, , b, , a, , ", , ,, , ", +178 more]
```

Suggested solution to use `writeBytes` instead

### PR DESCRIPTION
**Pull request by arielshaqed**
Tested by adding a unit test for writeJsonSummary.

Fixes #4644.

### CODE REVIEW

File: clients/spark/core/src/test/scala/io/treeverse/clients/GarbageCollectorSpec.scala [hunk 1]
```diff
@@ -1,12 +1,29 @@
...
+import org.json4s.native.JsonMethods
+
+import java.nio.file.{Files, Path, Paths}
+
+trait TempDirectory {
+  def withTempDirectory(testMethod: (Path) => Any) {
+    val tempDir = Files.createTempDirectory("test-gc")
+
+    testMethod(tempDir)
+    FileUtils.deleteDirectory(tempDir.toFile)
```
Comment (johnnyaug) [inline clients/spark/core/src/test/scala/io/treeverse/clients/GarbageCollectorSpec.scala:24]: What happens if an exception is thrown in the test? Will the file still be deleted?

Comment (arielshaqed) [reply clients/spark/core/src/test/scala/io/treeverse/clients/GarbageCollectorSpec.scala]: True.  Fixed to delete.

**Review by arielshaqed — COMMENTED** [review]
Thanks, good catch!

Pulling once tests pass.
