### PR TITLE
gateway: enforce 2kb limit on user-defined metadata

### LINKED ISSUE #9728: Enforce 2KB size limit on user-defined object metadata
S3 enforces a 2KB size limit on user-defined metadata. lakeFS currently doesn't enforce this, allowing applications to write metadata that would fail when used with real S3.

S3 behaviour:
```
Input:  {'key': 'a' * 2100}  (>2KB)
Response: Error 400 - MetadataTooLarge
```

Current lakeFS behaviour:
```
Input:  {'key': 'a' * 2100}  (>2KB)
Response: Success (accepted and stored)
```

From [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#:~:text=The%20PUT%20request%20header%20is%20limited%20to%208%20KB%20in%20size.%20Within%20the%20PUT%20request%20header%2C%20the%20user%2Ddefined%20metadata%20is%20limited%20to%202%20KB%20in%20size.%20The%20size%20of%20user%2Ddefined%20metadata%20is%20measured%20by%20taking%20the%20sum%20of%20the%20number%20of%20bytes%20in%20the%20UTF%2D8%20encoding%20of%20each%20key%20and%20value.):
> "Within the PUT request header, the user-defined metadata is limited to 2 KB in size. The size of user-defined metadata is measured by taking the sum of the number of bytes in the UTF-8 encoding of each key and value."

### PR DESCRIPTION
**Pull request by skshetry**
Closes #9728.

## Change Description

This PR enforces 2kb limit for user-defined metadata.

### Testing Details

How were the changes tested?

Unit tested, and verified manually.

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

S3 Gateway now returns `MetadataTooLarge` instead of `InvalidArgument` when user-defined metadata exceeds the size limit (which is 2KiB).

### CODE REVIEW

File: pkg/gateway/errors/errors.go [hunk 1]
```diff
@@ -669,8 +669,8 @@ var Codes = errorCodeMap{
 		HTTPStatusCode: http.StatusBadRequest,
 	},
 	ErrMetadataTooLarge: {
-		Code:           "InvalidArgument",
-		Description:    "Your metadata headers exceed the maximum allowed metadata size.",
+		Code:           "MetadataTooLarge",
+		Description:    "Your metadata headers exceed the maximum allowed metadata size",
 		HTTPStatusCode: http.StatusBadRequest,
```
Comment (skshetry) [inline pkg/gateway/errors/errors.go:674]: I was getting a slight different message on AWS S3, hence I made this change.

Happy to rollback if you think it's not necessary.

```
botocore.exceptions.ClientError: An error occurred (MetadataTooLarge) when calling the PutObject operation: Your metadata headers exceed the maximum allowed metadata size
```

File: pkg/gateway/operations/operation_utils.go [hunk 2]
```diff
@@ -22,13 +26,21 @@ var (
...
+		name, found := strings.CutPrefix(k, amzMetaHeaderPrefix)
+		if found {
 			value, decodeErr := rfc2047Decoder.DecodeHeader(req.Header.Get(k))
 			if decodeErr != nil {
 				err = errors.Join(err, decodeErr)
 				continue
 			}
+			userMetadataSize += len(name) + len(value)
+			if userMetadataSize > maxUserMetadataSize {
+				err = gatewayErrors.ErrMetadataTooLarge
```
Comment (skshetry) [inline pkg/gateway/operations/operation_utils.go]: I was not fully sure about the error conventions here. Since this is a utility function, I didn’t create a new error type. 
I'm happy to hear suggestions on what would be best here.

File: pkg/gateway/operations/putobject.go [hunk 3]
```diff
@@ -114,6 +114,10 @@ func handleCopy(w http.ResponseWriter, req *http.Request, o *PathOperation, copy
 
 	metadata, err := amzMetaAsMetadata(req)
 	if err != nil {
+		if errors.Is(err, gatewayErrors.ErrMetadataTooLarge) {
```
[the remark this answers is not in the document]
Comment (skshetry) [reply pkg/gateway/operations/putobject.go:117]: It's not an unexpected failure, so no need to log them.

File: pkg/gateway/errors/errors.go (hunk 1 above)
Comment (skshetry) [reply pkg/gateway/errors/errors.go:674]: This was also fixed in Minio a few years ago: https://github.com/minio/minio/commit/34ea1d21676e144c7a4df469b2c35b8294437d92.

File: pkg/gateway/errors/errors.go [hunk 4]
```diff
@@ -669,8 +669,8 @@ var Codes = errorCodeMap{
...
 	},
 	ErrMetadataTooLarge: {
-		Code:           "InvalidArgument",
-		Description:    "Your metadata headers exceed the maximum allowed metadata size.",
+		Code:           "MetadataTooLarge",
```
Comment (nopcoder) [inline pkg/gateway/errors/errors.go:672]: nice. we will need to add it as a fix in the changelog.

File: pkg/gateway/operations/operation_utils.go [hunk 5]
```diff
@@ -8,12 +8,16 @@ import (
 	"time"
 
 	"github.com/treeverse/lakefs/pkg/catalog"
+	gatewayErrors "github.com/treeverse/lakefs/pkg/gateway/errors"
```
Comment (nopcoder) [inline pkg/gateway/operations/operation_utils.go]: prefer lower, I am sure there are other places need to fix and we need to add a linter.
https://go.dev/blog/package-names#package-names

File: pkg/gateway/operations/postobject.go [hunk 6]
```diff
@@ -67,6 +67,10 @@ func (controller *PostObject) HandleCreateMultipartUpload(w http.ResponseWriter,
 	}
 	metadata, err := amzMetaAsMetadata(req)
 	if err != nil {
+		if errors.Is(err, gatewayErrors.ErrMetadataTooLarge) {
+			_ = o.EncodeError(w, req, err, gatewayErrors.Codes.ToAPIErr(gatewayErrors.ErrMetadataTooLarge))
+			return
```
Comment (nopcoder) [inline pkg/gateway/operations/postobject.go:73]: relevant to the other places we check this one - can we log this, in warn level so we know that the request failed.

File: pkg/gateway/operations/operation_utils.go [hunk 7]
```diff
@@ -22,13 +26,21 @@ var (
...
 	for k := range req.Header {
-		if strings.HasPrefix(k, amzMetaHeaderPrefix) {
+		name, found := strings.CutPrefix(k, amzMetaHeaderPrefix)
+		if found {
 			value, decodeErr := rfc2047Decoder.DecodeHeader(req.Header.Get(k))
 			if decodeErr != nil {
 				err = errors.Join(err, decodeErr)
 				continue
 			}
+			userMetadataSize += len(name) + len(value)
```
Comment (nopcoder) [inline pkg/gateway/operations/operation_utils.go:39]: 1. Need to use 'k' instead of 'name' when we calculate the length.
2. What is the point of collecting errors until we get to ErrMetadataTooLarge? consider checking the length first or just return the error and not partial data with the error.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/gateway/operations/operation_utils.go (hunk 7 above)
Comment (skshetry) [reply pkg/gateway/operations/operation_utils.go:39]: > 1. Need to use 'k' instead of 'name' when we calculate the length.

If you are using MinIO to verify this, it behaves differently from AWS S3 here. [MinIO sums the full `X-Amz-Meta-*` header length](https://github.com/minio/minio/blob/27742d469462e1561c776f88ca7a1f26816d69e2/cmd/generic-handlers.go#L93), while AWS S3 appears to count only the bytes of the metadata key and value. I ran into that issue as I test with MinIO locally, but that did not match with AWS.

The [docs say](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#:~:text=The%20size%20of%20user%2Ddefined%20metadata%20is%20measured%20by%20taking%20the%20sum%20of%20the%20number%20of%20bytes%20in%20the%20UTF%2D8%20encoding%20of%20each%20key%20and%20value.):

> The size of user-defined metadata is measured by taking the sum of the number of bytes in the UTF-8 encoding of each key and value.

The term “key” is ambiguous, but I verified via a script that AWS S3 excludes the `X-Amz-Meta-` prefix in the sum.

```python
import boto3

client = boto3.client("s3")

def upload(bucket, key, meta_length):
  metadata = {"key": "a" * (meta_length - len("key"))}
  print(sum(len(k) + len(v) for k, v in metadata.items()))
  client.put_object(Bucket=bucket, Key=key, Body=b"content", Metadata=metadata)

upload("saugat-lakefs", "key", 2048)
upload("saugat-lakefs", "key", 2049)
```

<details><summary>Output of the above script</summary>
<p>

```pytb
2048
2049
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
Cell In[6], line 10
      8 client = boto3.client("s3")
      9 upload("saugat-lakefs", "key", 2048)
---> 10 upload("saugat-lakefs", "key", 2049)

Cell In[6], line 6, in upload(bucket, key, meta_length)
      4 metadata = {"key": "a" * (meta_length - len("key"))}
      5 print(sum(len(k)+ len(v) for k, v in metadata.items()))
----> 6 client.put_object(Bucket=bucket, Key=key, Body=b"content", Metadata=metadata)

File ~/projects/treeverse/lakeFS/.venv/lib/python3.13/site-packages/botocore/client.py:602, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    598     raise TypeError(
    599         f"{py_operation_name}() only accepts keyword arguments."
    600     )
    601 # The "self" in this scope is referring to the BaseClient.
--> 602 return self._make_api_call(operation_name, kwargs)

File ~/projects/treeverse/lakeFS/.venv/lib/python3.13/site-packages/botocore/context.py:123, in with_current_context.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    121 if hook:
    122     hook()
--> 123 return func(*args, **kwargs)

File ~/projects/treeverse/lakeFS/.venv/lib/python3.13/site-packages/botocore/client.py:1078, in BaseClient._make_api_call(self, operation_name, api_params)
   1074     error_code = request_context.get(
   1075         'error_code_override'
   1076     ) or error_info.get("Code")
   1077     error_class = self.exceptions.from_code(error_code)
-> 1078     raise error_class(parsed_response, operation_name)
   1079 else:
   1080     return parsed_response

ClientError: An error occurred (MetadataTooLarge) when calling the PutObject operation: Your metadata headers exceed the maximum allowed metadata size
```

</p>
</details>

> 2. What is the point of collecting errors until we get to ErrMetadataTooLarge? consider checking the length first or just return the error and not partial data with the error.

I was not sure what the convention was, but I can do the latter, i.e return the error when length of the key-value crosses the threshold.

File: pkg/gateway/errors/errors.go (hunk 4 above)
Comment (skshetry) [reply pkg/gateway/errors/errors.go:672]: I don’t think this error code is returned elsewhere. I believe this PR returns it for the first time, so I don't think we need to add it to the changelog. Could it appear anywhere else?

File: pkg/gateway/operations/operation_utils.go (hunk 5 above)
Comment (skshetry) [reply pkg/gateway/operations/operation_utils.go]: Fixed by 1102fc05050958c724f7910adaadcd6d1b3ec6aa.

File: pkg/gateway/operations/postobject.go (hunk 6 above)
Comment (skshetry) [reply pkg/gateway/operations/postobject.go:73]: Fixed by 75d9eecff3101491379de117c86e46fa89c755f9.

File: pkg/gateway/operations/operation_utils.go (hunk 7 above)
Comment (skshetry) [reply pkg/gateway/operations/operation_utils.go:39]: e797235 changed to just return the error and no partial data when it crosses the threshold.

File: pkg/gateway/errors/errors.go (hunk 4 above)
Comment (nopcoder) [reply pkg/gateway/errors/errors.go:672]: I mean we update the error we return and when we release lakefs we can specify that we fixed a bug because we align an error we return for this call.

File: pkg/gateway/operations/base_test.go [hunk 8]
```diff
@@ -153,3 +154,55 @@ func TestOperation_EncodeResponse_NormalResponse(t *testing.T) {
...
+func TestAmzMetaAsMetadata_ExceedingLimit(t *testing.T) {
+	req := httptest.NewRequest(http.MethodPut, "/test", nil)
+	valueSize := maxUserMetadataSize - len("Key") + 1
+	req.Header.Set("X-Amz-Meta-Key", strings.Repeat("a", valueSize))
+
+	metadata, err := amzMetaAsMetadata(req)
+
+	assert.Nil(t, metadata)
+	assert.Error(t, err)
+	assert.ErrorIs(t, err, gwerrors.ErrMetadataTooLarge)
```
Comment (nopcoder) [inline pkg/gateway/operations/base_test.go]: 1. Check the error first as usually when we expect an error to be checked first.
2. Checking error is is enough to match the error

File: pkg/gateway/operations/base_test.go [hunk 9]
```diff
@@ -153,3 +154,55 @@ func TestOperation_EncodeResponse_NormalResponse(t *testing.T) {
...
+	value := strings.Repeat("a", 1000)
+	req.Header.Set("X-Amz-Meta-Key1", value)
+	req.Header.Set("X-Amz-Meta-Key2", value)
+	req.Header.Set("X-Amz-Meta-Key3", value)
+
+	metadata, err := amzMetaAsMetadata(req)
+
+	assert.Nil(t, metadata)
+	assert.Error(t, err)
+	assert.ErrorIs(t, err, gwerrors.ErrMetadataTooLarge)
```
Comment (nopcoder) [inline pkg/gateway/operations/base_test.go]: check the error first. don't see the reason to check Error if we Check ErrorIs

File: pkg/gateway/errors/errors.go (hunk 4 above)
Comment (skshetry) [reply pkg/gateway/errors/errors.go:672]: Done in 94d9b3e2a. Let me know if I did that correctly.

File: pkg/gateway/operations/base_test.go (hunk 8 above)
Comment (skshetry) [reply pkg/gateway/operations/base_test.go]: Done in 3b21a7478.

File: pkg/gateway/operations/base_test.go (hunk 9 above)
Comment (skshetry) [reply pkg/gateway/operations/base_test.go]: Done in 3b21a7478.

**Comment by skshetry** [comment]
> lgtm
> 
> About the changelog, I didn't want to have it updated right now; just include the information in the next release changelog as part of changes that need to be included.
> 
> Usually we take the PR with include-changelog and add them; so having the information in the description should be fine.

Sorry about that. The thread confused me because it appeared as the first comment under "Requesting Changes" and the GitHub UI made it look like you were asking to do it now, to document it explicitly.

Since you approved, I’m assuming the changelog is OK. If not, let me know and I’ll revert the last commit. I have also updated the PR description.
