### PR TITLE
fix precondition 500

### LINKED ISSUE #6457: UploadObject returns 500 when "precondition fails"
`ErrPredicateFailed` is not handled in the api controller. Not sure if by design or not. When kv returns the error `ErrPredicateFailed` it propagates to the api and 500 is returned to the client.

Example log:

```
log | {"error":"predicate failed","file":"build/pkg/api/controller.go:2104","func":"pkg/api.(*Controller).handleAPIErrorCallback","host":"******","level":"error","method":"POST","msg":"API call returned status internal server error","operation_id":"UploadObject","path":"/api/v1/repositories/<repo>/branches/<branch>/objects?path=<path>","request_id":"<>","service":"api_gateway","service_name":"rest_api","time":"<>","user":"<>"}
```

### PR DESCRIPTION
**Pull request by nadavsteindler**
Closes #6457

### Bug Fix

We return 500 on precondition failed when really we should be returning 412

Details:
  Catalog.CreateEntry can return kv.ErrPredicateFailed when there's a race condition during concurrent writes to the same staging token.

### Testing Details

Unit test

### Breaking Change?

  Impact:
  - Before fix: kv.ErrPredicateFailed → 500 → lakectl retries (incorrectly, since retrying won't help)
  - After fix: kv.ErrPredicateFailed → 412 → lakectl doesn't retry (correct behavior!)

### CODE REVIEW

File: pkg/api/controller_internal_test.go
Comment (itaiad200) [inline pkg/api/controller_internal_test.go:1]: What's wrong with the existing controller tests file that we had to create a different one?

File: pkg/api/controller.go [hunk 1]
```diff
@@ -3208,7 +3208,8 @@ func handleApiErrorCallback(log logging.Logger, w http.ResponseWriter, r *http.R
 		log.Debug("KV Throttling")
 		cb(w, r, http.StatusServiceUnavailable, "Throughput exceeded. Slow down and retry")
 
-	case errors.Is(err, graveler.ErrPreconditionFailed):
+	case errors.Is(err, graveler.ErrPreconditionFailed),
+		errors.Is(err, kv.ErrPredicateFailed):
```
Comment (itaiad200) [inline pkg/api/controller.go]: This feels very dangerous. `kv.ErrPredicateFailed` is returned by the `kv` pkg when the `SetIf` function failed after the predicate changed. It is much more general than what this PR solves.
For example, writing to a branch while it's being committed will return that after some retries. 
Parallel committing to a branch will return that as well.

Are we sure we're not solving 1 issue and creating a few others? Isn't it better to find the code path where this error surfaces in actions execution and wrap it with a different error code?

Comment (nadavsteindler) [reply pkg/api/controller.go]: Oh I just realized that I read the issue description and code wrong and ready these two types of error as a single one thrown at different layers...

File: pkg/api/controller.go [hunk 2]
```diff
@@ -3830,6 +3830,11 @@ func (c *Controller) UploadObject(w http.ResponseWriter, r *http.Request, reposi
 		writeError(w, r, http.StatusPreconditionFailed, "path already exists")
 		return
 	}
+	if errors.Is(err, kv.ErrPredicateFailed) {
+		c.Logger.WithError(err).Warn("KV predicate failed in UploadObject")
```
Comment (itaiad200) [inline pkg/api/controller.go]: This could become too chatty, there's really nothing to warn here about since the system is working exactly as intended by the user.

File: pkg/api/controller.go [hunk 3]
```diff
@@ -3830,6 +3830,11 @@ func (c *Controller) UploadObject(w http.ResponseWriter, r *http.Request, reposi
...
+		writeError(w, r, http.StatusPreconditionFailed, "path already exists")
```
Comment (itaiad200) [inline pkg/api/controller.go]: Wrong error message, isn't it?

File: pkg/api/controller.go (hunk 2 above)
Comment (nadavsteindler) [reply pkg/api/controller.go]: ok

File: pkg/api/controller_test.go [hunk 4]
```diff
@@ -6828,3 +6828,68 @@ func TestController_ImportStart_Disabled(t *testing.T) {
 	require.NotNil(t, resp.JSON403, "expected a 403 forbidden response, but got none")
 	require.Contains(t, resp.JSON403.Message, "import is not supported for this storage")
 }
+
+// TestController_ErrorHandling tests that different error types are properly mapped to HTTP status codes.
+// This is a regression test to ensure that errors from the graveler and KV layers are correctly handled.
+func TestController_UploadObject_ErrorHandling(t *testing.T) {
```
Comment (itaiad200) [inline pkg/api/controller_test.go:6834]: Nice tests. Consider adding one for `if-match` too

**Review by itaiad200 — APPROVED** [review]
Approved with one comment

File: pkg/api/controller_test.go (hunk 4 above)
Comment (nadavsteindler) [reply pkg/api/controller_test.go:6834]: So claude pointed out that we don't support if-match: see build.go line 56
