### PR TITLE
Fix login worked on second try

### LINKED ISSUE #2524: Pressing "Logout" button requires two logins to get back to a useful page
# Steps to reproduce

1. Log out of GUI.
   *Result:* Get logged out, redirect to page `auth/login?next=%2Fauth%2Flogin`.
2. Log in.
   *Result:* Get logged in, _but redirected to `auth/login`_ as requested.
3. Ignore URL bar, ask "what just happened?" and log in again.
   *Result:* Get logged in, redirect to main page.

# Analysis

The `next` query parameter after logging out seems wrong.  It should probably try to be the referring page.

### PR DESCRIPTION
**Pull request by nopcoder**
The first time the login acquired credentials but redirect to the login page.
Second time was optional, but this time there was no redirect instruction and we moved to root.

Fix include:
1. Redirect to login when route to login is skipped
2. Handle react state update on unmounted component - https://stackoverflow.com/questions/53949393/cant-perform-a-react-state-update-on-an-unmounted-component. Triggered when API call fail with authorization.

Fix #2524

### CODE REVIEW

File: webui/src/pages/auth/login.jsx [hunk 1]
```diff
@@ -23,18 +23,16 @@ const LoginForm = () => {
...
-                                    return router.push((!!next) ? next : '/');
-                                })
-                                .catch(err => {
-                                    setLoginError(err);
-                                })
-
+                            try {
+                                await auth.login(e.target.username.value, e.target.password.value);
+                                setLoginError(null);
+                                const nextOrRoot = next && next !== router.route ? next : '/';
```
[the remark this answers is not in the document]
Comment (arielshaqed) [reply webui/src/pages/auth/login.jsx:31]: Not a fan of this change, then.  In general I do not trust setting a known-incorrect value of `next` and then attempting to fix it at the last moment; I would much prefer to set a correct value.

To amplify on my previous points:

## 1. Where is the special treatment of a falsy `next`?

Before the change it would redirect to `/`, now it redirects to whatever the falsy value does.

## 2. Let's set the correct value!

## 3. Behaviour on JWT timeout

I believe that this does the wrong thing whenever I am logged out, e.g. (also) if my cookie times out.

I tried this experiment:
1. Log in.
2. Navigate to repos page.
3. Erase the token cookie.
4. Click a repo, get redirected to login page (expected behaviour).
5. ... login page has a bad `next`.

With this patch, the login page will _still_ have  a bad `next`, and my reading of the fix above is that it will bring me to the main page.  The **expected** behaviour is to redirect to the old page after logging in -- AFAICT this patch does not do that.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Sorry, I will need more convincing not to change it at the source.  I believe that this sometimes redirects to the right page but other times does not... and that it *usually* goes to the wrong place.

File: webui/src/pages/auth/login.jsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (nopcoder) [reply webui/src/pages/auth/login.jsx:31]: Moved the check before we set the value of 'next' when route to the login page.

[the remark this answers is not in the document]
Comment (nopcoder) [reply webui/src/pages/auth/login.jsx:31]: Moved the check before we set the value of 'next' when route to the login page.

File: webui/src/lib/hooks/api.jsx [hunk 2]
```diff
@@ -51,43 +51,49 @@ const initialAPIState = {
...
         const execute = async () => {
-            setRequest(initialAPIState);
             try {
                 const response = await promise();
-                // setResponse(response)
-                // setLoading(false)
                 setRequest({
                     loading: false,
                     error: null,
                     response
```
Comment (arielshaqed) [inline webui/src/lib/hooks/api.jsx:79]:
```suggestion
                    response,
```

File: webui/src/pages/auth/login.jsx [hunk 3]
```diff
@@ -23,18 +23,19 @@ const LoginForm = () => {
...
-                        }}>
+                            auth
+                                .login(e.target.username.value, e.target.password.value)
+                                .then(user => {
+                                    setLoginError(null);
+                                    return router.push((!!next) ? next : '/');
+                                })
+                                .catch(err => {
+                                    setLoginError(err);
+                                })
```
Comment (arielshaqed) [inline webui/src/pages/auth/login.jsx:36]: I think this may be more readable as an async function (cannot put it as a suggestion because GitHub).

Something like this (untested, of course):
```js
async (e) => {
  e.preventDefault();
  try {
    const _user = await auth.login(e.target.username.value, e.target.password.value);
    setLoginError(null);
    return router.push((!!next) ? next : '/');
    } catch (e) {
      setLoginError(e);
    }
}
```

File: webui/src/pages/auth/login.jsx [hunk 4]
```diff
@@ -23,18 +23,19 @@ const LoginForm = () => {
...
-                                setLoginError(err);
-                            }
-                        }}>
+                            auth
+                                .login(e.target.username.value, e.target.password.value)
+                                .then(user => {
+                                    setLoginError(null);
+                                    return router.push((!!next) ? next : '/');
+                                })
+                                .catch(err => {
```
Comment (arielshaqed) [inline webui/src/pages/auth/login.jsx]: What is "`err`"?  The golang is up outside of webui and down cmd or pkg :stuck_out_tongue_closed_eyes:

**Review by arielshaqed — APPROVED** [review]
Thanks!  Reckon this should fix it nicely in all scenarios.

(To be fair, the redirect-to-login logic seems a bit convoluted.)

File: webui/src/pages/auth/login.jsx (hunk 3 above)
Comment (nopcoder) [reply webui/src/pages/auth/login.jsx:36]: :) I revered this change because I didn't wanted to add code style changes to the PR - but I also found the async syntax better to read.
