### PR TITLE
Use pure-Java RocksDB reader in Spark metadata client

### LINKED ISSUE #1847: Metadata client doesn't work on Databricks
Metadata client doesn't work on Databricks, probably due to a conflict in RocksJava version.

Steps to reproduce:
1. Have a public lakeFS installation ready (you can use Terraform), with a repository and a commit.
2. Start a Databricks cluster.
3. In the cluster configuration > _Libraries_ tab, click Install new.
4. Put in the Maven coordinates for the metadata client: `io.treeverse:lakefs-spark-client-301_2.12:0.1.0-SNAPSHOT`
5. Put in the repository: `https://s01.oss.sonatype.org/content/repositories/snapshots`
6. In the cluster configuration > _Configuration_ tab > _Advanced options_ > _Spark_ tab, configure the lakeFS client:
   ```
   spark.hadoop.lakefs.api.url http://<lakefs api endpoint>/api/v1/
   spark.hadoop.lakefs.api.access_key <lakefs access key>
   spark.hadoop.lakefs.api.secret_key <lakefs secret key>
   ```
7. In a Scala notebook attached to the cluster, run the following code:
   ```scala
   import io.treeverse.clients.LakeFSContext
   var df = LakeFSContext.newDF(spark, "example-repo", "your-lakefs-commit-id")
   df.show
   ```

The following error appears:
```
IllegalAccessError: tried to access field org.rocksdb.RocksObject.nativeHandle_ from class org.rocksdb.SstFileReader
```

The reason may be that Databricks has an old `rocksdb-jni` jar in the classpath.
A possible solution could be to shade the rocksdb jni in the lakeFS uber-jar, and install the uber-jar on Databricks instead of using the Maven coordinates. However, this will also be challenging since the underlying native library needs to somehow be wired to the shaded jars.

### PR DESCRIPTION
**Pull request by arielshaqed**
DataBricks supplies an _ancient_ version of `rocksdbjni` that does not export pure SSTable operations.  So we cannot use it.  Because `rocksdbjni` is a JNI library, it cannot be shaded (renamed) without major changes and recompilation and distribution and non-trivial fork chasing.  Instead, write our own RocksDB format parser, and use that in the client.

The majority of the PR is the new RocksDB format reader.

Please _do not pull_ until we are
1. Sure that it works;
1. Know that it works with 2-level RocksDB index files, or that `lakefs` can never generate those.
1. Confident that we can test it against future versions that `lakefs` may generate.

# Fixes #1847 :-) :smiley: :turtle: :skull:

### CODE REVIEW

**Comment by arielshaqed** [comment]
Works on EMR 3.0.1: I set one up, configured lakeFS access and secret keys and endpoint, and then ran:
```
[ec2-user@ip-10-20-3-61 ~]$ spark-shell --jars s3://treeverse-ariels-test-us/clients/lakefs-spark-client-301-assembly-0.1.5.jar --master local
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/08/12 13:52:01 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
21/08/12 13:52:01 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
Spark context Web UI available at http://ip-10-20-3-61.ec2.internal:4042
Spark context available as 'sc' (master = local, app id = local-1628776321129).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.1-amzn-0
      /_/
         
Using Scala version 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_272)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import io.treeverse.clients.LakeFSContext; var df = LakeFSContext.newDF(spark, "foo", "main"); df.show
21/08/12 13:52:06 WARN SharedState: Not allowing to set spark.sql.warehouse.dir or hive.metastore.warehouse.dir in SparkSession's options, it should be set statically for cross-session usages
+----------+--------------------+--------------------+-------------------+----+ 
|       key|             address|                etag|      last_modified|size|
+----------+--------------------+--------------------+-------------------+----+
|   test1/1|4705d4f1817e4dfeb...|27bc8de95026209eb...|2021-08-08 10:54:50|   9|
|  test1/10|bce2f70445fa49cca...|0d81641648c6f5691...|2021-08-08 10:54:50|  10|
| test1/100|c5ecce57863445308...|68d89a66262a84844...|2021-08-08 10:54:49|  11|
|test1/1000|64be2ce234b14572a...|fff0b8896e1fd8857...|2021-08-08 10:54:58|  12|
| test1/101|9beb8ae62d274836a...|5315e6fdbe3a80411...|2021-08-08 10:54:49|  11|
| test1/102|46a8b031f815469bb...|f77ee7c1f79a966c8...|2021-08-08 10:54:49|  11|
| test1/103|a8d0d56a824d44a6b...|6ce5697f4a19aeb01...|2021-08-08 10:54:49|  11|
| test1/104|c3b90677a8de49508...|022011cc176128a49...|2021-08-08 10:54:49|  11|
| test1/105|ac585b85a63740d1b...|d844f89ac9583dfa3...|2021-08-08 10:54:49|  11|
| test1/106|c25bb64c981a47a4b...|3f6eef0fe1b5ed359...|2021-08-08 10:54:49|  11|
| test1/107|3fca29fc99b943c39...|a3aea4693761dcbeb...|2021-08-08 10:54:49|  11|
| test1/108|0d4acaef2b744f23b...|8a708fcfafc279d9b...|2021-08-08 10:54:49|  11|
| test1/109|4241c0bf729848099...|f0a0eec70602862d7...|2021-08-08 10:54:48|  11|
|  test1/11|49601c95f77b46c8a...|1dca97e4b449db7cc...|2021-08-08 10:54:48|  10|
| test1/110|7c0c82760e4840278...|bda8c8c92cd03cae0...|2021-08-08 10:54:49|  11|
| test1/111|33fc6bfe5cf04fcdb...|6d33f2e259a993eb3...|2021-08-08 10:54:49|  11|
| test1/112|c1f2cd7c94d447e18...|e1cd9fbc2e5503957...|2021-08-08 10:54:49|  11|
| test1/113|690b8d789fe041df9...|de164babfe6ec7fef...|2021-08-08 10:54:50|  11|
| test1/114|abb3ff95f34b475c8...|2688de85c7d6e21a2...|2021-08-08 10:54:50|  11|
| test1/115|932d16009a5448719...|2dcd8657d41ac8e45...|2021-08-08 10:54:49|  11|
+----------+--------------------+--------------------+-------------------+----+
only showing top 20 rows

import io.treeverse.clients.LakeFSContext
df: org.apache.spark.sql.DataFrame = [key: string, address: string ... 3 more fields]
```

:-)

**Comment by arielshaqed** [comment]
Also works on emr-5.33.0, with Spark 2.4.7.

File: clients/spark/core/src/main/scala/io/treeverse/jpebble/BlockParser.scala [hunk 1]
```diff
@@ -0,0 +1,303 @@
...
+    (bytes.next() & 0xff) + 256 * ((bytes
+      .next() & 0xff) + 256 * ((bytes.next() & 0xff) + 256 * (bytes.next() & 0xff)))
+
+  /** Mix bits of CRC32C to match its use in RocksDB SSTables.  (That format
+   *  includes CRCs inside checksummed data, meaning further CRCs of that
+   *  block can fail to detect anything; defining this mixing protects that
+   *  protocol.  We need to follow the format regardless of whether or not
+   *  using CRCs like this is justified!)
+   */
+  def fixupCRC(crc: Int): Int = (crc >>> 15 | crc << 17) + 0xa282ead8
```
Comment (itaiad200) [inline clients/spark/core/src/main/scala/io/treeverse/jpebble/BlockParser.scala:199]: :facepalm:

File: clients/spark/core/src/main/scala/io/treeverse/jpebble/BlockParser.scala [hunk 2]
```diff
@@ -0,0 +1,303 @@
...
+      val block = BlockParser.startBlockParse(bytes)
+      entryIt = BlockParser.parseDataBlock(block)
+    }
+    return true
+  }
+
+  advanceToEntry() // Move to first entry
+
+  private def stripInternalKey(entry: Entry) =
+    new Entry(entry.key.slice(0, entry.key.length - 8), entry.value)
```
Comment (itaiad200) [inline clients/spark/core/src/main/scala/io/treeverse/jpebble/BlockParser.scala:298]: Can you explain this? Does the format add an internal key of some sort?

**Review by itaiad200 — COMMENTED** [review]
Read everything except for the tests, will continue later. Looks great so far!

File: clients/spark/core/src/test/scala/io/treeverse/jpebble/ByteBufferIndexedBytesSpec.scala [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+import funspec._
+
+class ByteBufferIndexedBytesSpec extends AnyFunSpec with Matchers {
+  val bytesSeq = Array[Byte](2, 3, 5, 7, 11, 13)
+
+  describe("ByteBufferIndexedBytes") {
+    it("returns bytes in buffer through iterator") {
+      val bytes = IndexedBytes.create(ByteBuffer.wrap(bytesSeq)).iterator.toSeq
+
+      bytes should contain theSameElementsInOrderAs bytesSeq
```
Comment (itaiad200) [inline clients/spark/core/src/test/scala/io/treeverse/jpebble/ByteBufferIndexedBytesSpec.scala:16]: What sorcery is this?

**Review by itaiad200 — APPROVED** [review]

File: clients/spark/core/src/main/scala/io/treeverse/jpebble/IndexedBytes.scala [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+
+/** Iterator over a ByteByffer.
+ */
+class ByteBufferIterator(private val buf: ByteBufferIndexedBytes) extends Iterator[Byte] {
+  var index = 0
+  override def hasNext = index < buf.size
+  override def next(): Byte = {
+    val ret = buf(index)
+    index += 1
+    ret
```
[the remark this answers is not in the document]
Comment (arielshaqed) [reply clients/spark/core/src/main/scala/io/treeverse/jpebble/IndexedBytes.scala]: You're right.  The [Java iterator interface](https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--) specifies throwing a particular exception.  Special-cased to throw the desired exception (and added tests).

File: clients/spark/core/src/test/scala/io/treeverse/jpebble/ByteBufferIndexedBytesSpec.scala (hunk 3 above)
Comment (arielshaqed) [reply clients/spark/core/src/test/scala/io/treeverse/jpebble/ByteBufferIndexedBytesSpec.scala:16]: It's Scala.  These tests are written in the BDD style, which traditionally use this beautiful style of [matchers](https://www.scalatest.org/user_guide/using_matchers#workingWithContainers) instead of assertions.  Ruby-like in its simplicity, unfortunately.

So... why BDD-ish specs?  Well, I wanted to be able to nest tests (`describe(...) { describe(...) { it(...) {} it(...) {..}}}`), and this was the first standard style I saw in ScalaTest that supports nesting.  Also [Google says BDD is Better](https://google.com/search?q=why+bdd+is+better).

**Review by arielshaqed — COMMENTED** [review]
Thanks!

PTAL...

**Review by itaiad200 — APPROVED** [review]

**Comment by arielshaqed** [comment]
Tested on big metadata on EMR with the _old_ version (that uses rocksdbjni), `SELECT SUM(size)...` returns an identical value -- so we are _not losing any rows_.

Re-merging #2347 (didn't work out, not sure what happened), and pulling.

**Comment by arielshaqed** [comment]
> Re-merging #2347 (didn't work out, not sure what happened), and pulling.

Ah...
 
> @arielshaqed arielshaqed force-pushed the feature/1847-add-jpebble branch from ee8fddf to 63540a0 6 days ago  

was the culprit.  The merge from ee8fddf just moved the tip (it was based off of this branch),  so rebasing removed it.  So redoing the merge makes sense.

**Comment by arielshaqed** [comment]
Pulling once tests...
