### PR TITLE
lakectl to present error while writing to protected branch

### LINKED ISSUE #8333: [Bug]: lakectl local doesn't mention the reason commit fails when writing to a protected branch
### What happened?

When running lakectl local commit using a protected branch I get:

object to backing store: request failed (403 Forbidden)
Error executing command.

### Expected behavior

We should mention why we've got 403 which is in our case, writing to a protected branch.

### lakeFS version

1.40.0

### Affected clients

lakectl

### PR DESCRIPTION
**Pull request by ItamarYuran**
Closes #8333

### CODE REVIEW

**Comment by idanovo** [comment]
@ItamarYuran please move the PR to ready for review.
And please avoid next time from creating branches with 90 chars length 😅

**Review by idanovo — CHANGES_REQUESTED** [review]
There are a couple of issues with the current solution:
1) 403 (forbidden) status code might be a result of another issue than writing to a protected branch.
2) Your solution works specifically for uploading an object with presign mode without using multiparts.
What if I delete an object instead of uploading one? I'll still have the same issue.
3) I would like to have some tests here to validate we show the reason why we failed when trying to apply changes (write/delete) to a protected branch.

File: esti/lakectl_test.go [hunk 1]
```diff
@@ -726,6 +726,21 @@ func getStorageConfig(t *testing.T) *apigen.StorageConfig {
 	}
 	return storageResp.JSON200
 }
+func TestLakectlFsUpload_protectedBranch(t *testing.T) {
```
Comment (idanovo) [inline esti/lakectl_test.go:729]:
```suggestion

func TestLakectlFsUpload_protectedBranch(t *testing.T) {
```

Comment (idanovo) [inline esti/lakectl_test.go:729]: Same here, please add a test for `lakectl fs rm`

**Review by idanovo — CHANGES_REQUESTED** [review]
Great job!
Please add tests for lakectl fs rm and deleting an object with lakectl local commit

**Review by idanovo — APPROVED** [review]
THANKS!

File: esti/lakectl_test.go [hunk 2]
```diff
@@ -10,10 +10,13 @@ import (
 
 	"github.com/stretchr/testify/require"
 	"github.com/treeverse/lakefs/pkg/api/apigen"
+	"github.com/treeverse/lakefs/pkg/graveler"
 )
 
 var emptyVars = make(map[string]string)
 
+const branchProtectTimeout = graveler.BranchUpdateMaxInterval + 1
```
Comment (idanovo) [inline esti/lakectl_test.go:18]: `graveler.BranchUpdateMaxInterval` is a `time.Duration `unit you should add `time.Second` instead of 1 to it

File: esti/lakectl_test.go [hunk 3]
```diff
@@ -727,6 +730,43 @@ func getStorageConfig(t *testing.T) *apigen.StorageConfig {
...
+	vars := map[string]string{
+		"REPO":    repoName,
+		"STORAGE": storage,
+		"BRANCH":  mainBranch,
+	}
+	RunCmdAndVerifySuccessWithFile(t, Lakectl()+" repo create lakefs://"+vars["REPO"]+" "+vars["STORAGE"], false, "lakectl_repo_create", vars)
+	runCmd(t, Lakectl()+" branch-protect add lakefs://"+vars["REPO"]+"/  '*'", false, false, vars)
+	RunCmdAndVerifyContainsText(t, Lakectl()+" branch-protect list lakefs://"+vars["REPO"]+"/ ", false, "*", vars)
+	// BranchUpdateMaxInterval - sleep in order to overcome branch update caching
+	time.Sleep(branchProtectTimeout * time.Second)
```
Comment (idanovo) [inline esti/lakectl_test.go:745]: change branchProtectTimeout to be `graveler.BranchUpdateMaxInterval + time.Second` and then change `time.Sleep(branchProtectTimeout * time.Second)` to be `time.Sleep(branchProtectTimeout)`

Comment (ItamarYuran) [reply esti/lakectl_test.go]: Changing, Thank you!
