### PR TITLE
Restrict lakectl local to common prefixes only

### LINKED ISSUE #6416: `lakectl local clone` doesn't work for a single object but doesn't tell the user that
```
$ lakectl local clone lakefs://quickstart/main/lakes.parquet ./quickstart/

Successfully cloned lakefs://quickstart/main/lakes.parquet to /Users/rmoff/quickstart.

Clone Summary:

No changes
$ 
```

```
$ ls -la /Users/rmoff/quickstart
total 8
drwxr-xr-x   3 rmoff  staff    96 16 Aug 10:36 .
drwxr-x---+ 86 rmoff  staff  2752 16 Aug 10:36 ..
-rw-r--r--   1 rmoff  staff   118 16 Aug 10:36 .lakefs_ref.yaml
```

This is very misleading: 

```
Successfully cloned lakefs://quickstart/main/lakes.parquet to /Users/rmoff/quickstart
```

since it didn't clone the object. In fact, it will happily report that it cloned an object that doesn't even exist: 

```
$ lakectl local clone lakefs://quickstart/main/foobar ./quickstart/

Successfully cloned lakefs://quickstart/main/foobar to /Users/rmoff/quickstart.

Clone Summary:

No changes
```

If `lakectl local` is only for cloning folders then it should perform some kind of validation. As a stop-gap measure, don't display `Successfully cloned` if there were no objects downloaded. 

Also the help text for `local clone` suggests that it *should* work for a single object ("clone a path")

```
$ lakectl local clone --help
Clone a path from a lakeFS repository into a new directory.
```

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #6416

### Background

Restrict lakectl local to work with common prefixes only (i.e. directories) and prohibit passing lakeFS uri for object or prefix

### Testing Details

Added system tests for it

### Breaking Change?

No

### CODE REVIEW

File: cmd/lakectl/cmd/local_init.go [hunk 1]
```diff
@@ -20,6 +22,25 @@ const (
 )
 
 func localInit(ctx context.Context, dir string, remote *uri.URI, force, updateIgnore bool) (string, error) {
+	client := getClient()
+	if len(remote.GetPath()) > 0 { // Verify path is not an existing object
```
Comment (arielshaqed) [inline cmd/lakectl/cmd/local_init.go:26]: Consider
```suggestion
	if remote.GetPath() != "" { // Verify path is not an existing object
```
Java is down the hall 17 doors on the right; Go has string values.

File: cmd/lakectl/cmd/local_init.go [hunk 2]
```diff
@@ -20,6 +22,25 @@ const (
...
+			Path: *remote.Path,
+		})
+		switch {
+		case err != nil:
+			DieErr(err)
+		case stat.JSON200 != nil:
+			DieFmt("lakeFS path %s is an existing object and cannot be used as a reference source", remote.String())
+		case stat.JSON404 == nil:
+			dieOnResponseError(stat, err)
+		}
```
Comment (arielshaqed) [inline cmd/lakectl/cmd/local_init.go:37]: Can we use `DieOnErrorOrUnexpectedStatusCode`?

**Review by arielshaqed — APPROVED** [review]
This is much better, thanks!  Still a bit confusing though: If I try to use local on an object, it will complain about a _different_ path.

Can we do better?  (I have no suggestion with a good UX for this, sorry).

File: cmd/lakectl/cmd/local_init.go (hunk 2 above)
Comment (N-o-Z) [reply cmd/lakectl/cmd/local_init.go:37]: Unfortunately no - since here we are expecting a status code which is "not" OK (not 2xx) we will fail. 
Unless we decide to change this logic and allow expecting also other status codes

**Review by arielshaqed — COMMENTED** [review]
For other readers: After talking f2f this seems great!  Only one bad case remains: Both S3A and Rclone directory markers have a trailing slash on their key.  

In this case, cloning `a/` when there actually _is_ a directory marker `a/` will fail.  So we agreed only to stat when the path doesn't end in a slash.

**Comment by N-o-Z** [comment]
@arielshaqed Please have another look

**Comment by arielshaqed** [comment]
StillLGTM thanks!
