### PR TITLE
Fix retry branch update

### LINKED ISSUE #4076: retryBranchUpdate fails on the last (3rd) retry

### PR DESCRIPTION
**Pull request by eden-ohana**
closes #4076

### CODE REVIEW

File: pkg/graveler/graveler.go [hunk 1]
```diff
@@ -1742,7 +1742,7 @@ func (g *KVGraveler) retryBranchUpdate(ctx context.Context, repository *Reposito
 		}
 		return nil
 	}, bo)
-	if try == setTries {
+	if try > setTries {
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1745]: @eden-ohana  There's still a bug on the if statement above this line (1736)
If `err != nil` and `try >= setTries` we return nil - which is incorrect
We should return the error if err != nil regardless of `try`

**Review by N-o-Z — CHANGES_REQUESTED** [review]
I think there's still a bug in this flow. Please see comment

File: pkg/graveler/graveler.go (hunk 1 above)
Comment (eden-ohana) [reply pkg/graveler/graveler.go:1745]: The branch update will returns nil, and then the retry branch update will return an error because of line 1745. It's returning nil to exit the backoff.retry if you return an error it keeps retrying.

Comment (N-o-Z) [reply pkg/graveler/graveler.go:1745]: `if try == setTries` and `err != nil` we return nil - This is a bug

Comment (eden-ohana) [reply pkg/graveler/graveler.go:1748]: done

File: pkg/graveler/graveler.go [hunk 2]
```diff
@@ -1740,10 +1740,13 @@ func (g *KVGraveler) retryBranchUpdate(ctx context.Context, repository *Reposito
...
 		}
+		if err != nil {
+			return backoff.Permanent(err)
+		}
 		return nil
 	}, bo)
-	if try == setTries {
-		return fmt.Errorf("update branch: %w", ErrTooManyTries)
+	if try > setTries {
+		return backoff.Permanent(fmt.Errorf("update branch: %w", ErrTooManyTries))
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1749]: No need to wrap this with backoff.Permanent

Comment (eden-ohana) [reply pkg/graveler/graveler.go:1749]: oops

File: pkg/graveler/graveler.go (hunk 1 above)
Comment (eden-ohana) [reply pkg/graveler/graveler.go]: added changes to make it work

**Review by N-o-Z — APPROVED** [review]
Looks great, thanks!
