### PR TITLE
GC+ fix delete

### LINKED ISSUE #4648: GC+: Implement actual delete

### PR DESCRIPTION
**Pull request by eden-ohana**
closes #4648

### CODE REVIEW

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala [hunk 1]
```diff
@@ -168,29 +167,26 @@ object UncommittedGarbageCollector {
...
+        val region = getRegion(args)
+        val hcValues = spark.sparkContext.broadcast(
+          HadoopUtils.getHadoopConfigurationValues(hc, "fs.", "lakefs.")
+        )
+        val configMapper = new ConfigMapper(hcValues)
+
+        val removed = GarbageCollector
+          .bulkRemove(configMapper, markedAddresses, storageNSForSdkClient, region, storageType)
+          .toDF()
+        removed.collect()
```
Comment (itaiad200) [inline clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:189]: Was the missing collect the issue?

**Review by itaiad200 — APPROVED** [review]

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala (hunk 1 above)
Comment (eden-ohana) [reply clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:189]: yes spark didn't perform the delete because the df wasn't used
