### PR TITLE
Fix: s3 gateway returning 200 instead of 206 for range requests

### LINKED ISSUE #6100: Bug: S3 Gateway returns 200 OK for Range requests
On AWS S3, passing a valid `Range` header will result in S3 returning a `206 Partial Content` HTTP status code. This is true for both `HeadObject` and `GetObject` operations.

lakeFS currently returns an `200 OK` response, regardless of the existence of a range header (And even when the response is actually really partial content).

This breaks HTTP clients that may cache a 200 OK response because the client might reuse a response returned for a different range request, resulting in wrong data being used.

### PR DESCRIPTION
**Pull request by ozkatz**
Fixes #6100 
Notably, this bug currently impacts duckdb-wasm - the browser itself might cache a range request's response and reuse the response when responding to requests to the same file on another range (ouch).

@rmoff  - this should also unblock the improved quickstart from using duckdb-wasm to write.

### CODE REVIEW

**Comment by rmoff** [comment]
Sounds good - I'm +1 on the assumption the code is good; I've not actually reviewed it because I'm not qualified :)

**Review by rmoff — APPROVED** [review]

File: pkg/httputil/range.go [hunk 1]
```diff
@@ -17,6 +19,9 @@ type Range struct {
 func (r Range) String() string {
 	return fmt.Sprintf("start=%d, end=%d (total=%d)", r.StartOffset, r.EndOffset, r.EndOffset-r.StartOffset+1)
 }
+func (r Range) Size() int64 {
```
Comment (nopcoder) [inline pkg/httputil/range.go:22]:
```suggestion

func (r Range) Size() int64 {
```

File: pkg/httputil/range.go [hunk 2]
```diff
@@ -40,18 +45,24 @@ func ParseRange(spec string, length int64) (Range, error) {
...
-		if err != nil || endOffset > length {
+		if err != nil {
 			return r, ErrBadRange
 		}
-		r.StartOffset = length - endOffset
+		if length-endOffset < 0 {
+			r.StartOffset = 0
+		} else {
+			r.StartOffset = length - endOffset
+		}
```
Comment (nopcoder) [inline pkg/httputil/range.go:55]:
```suggestion
		r.StartOffset = length - endOffset
		if r.StartOffset < 0 {
			r.StartOffset = 0
		}
```

File: pkg/httputil/range_test.go [hunk 3]
```diff
@@ -11,41 +12,55 @@ func TestParseRange(t *testing.T) {
...
-			if (err != nil) != c.ExpectedError {
-				t.Fatalf("got err=%s, expected error %t", err, c.ExpectedError)
+			if c.ExpectedError != nil && err == nil {
+				t.Fatalf("epxected error: %s, got nil!", c.ExpectedError)
+			}
+			if c.ExpectedError == nil && err != nil {
+				t.Fatalf("unepxected error: %s!", err)
+			}
+			if c.ExpectedError != nil && err != nil && !errors.Is(err, c.ExpectedError) {
+				t.Fatalf("epxected error: %s, got %s!", c.ExpectedError, err)
```
Comment (nopcoder) [inline pkg/httputil/range_test.go:49]: You can just use `errors.Is` and use %v while report mismatch as %v will print also the case when err is nil

File: pkg/gateway/operations/headobject.go [hunk 4]
```diff
@@ -43,10 +43,33 @@ func (controller *HeadObject) Handle(w http.ResponseWriter, req *http.Request, o
...
+	// range query
+	rangeSpec := req.Header.Get("Range")
+	if len(rangeSpec) > 0 {
+		rng, rngErr = httputil.ParseRange(rangeSpec, entry.Size)
+		if rngErr != nil {
+			o.Log(req).WithError(err).WithField("range", rangeSpec).Debug("invalid range spec")
+			if errors.Is(rngErr, httputil.ErrUnsatisfiableRange) {
+				w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
+				return
+			}
```
Comment (nopcoder) [inline pkg/gateway/operations/headobject.go:58]: Do we have also a way to handle `ErrBadRange`?

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/gateway/operations/headobject.go [hunk 5]
```diff
@@ -43,10 +43,33 @@ func (controller *HeadObject) Handle(w http.ResponseWriter, req *http.Request, o
...
+	var rng httputil.Range
+	var rngErr error
+	// range query
+	rangeSpec := req.Header.Get("Range")
+	if len(rangeSpec) > 0 {
+		rng, rngErr = httputil.ParseRange(rangeSpec, entry.Size)
+		if rngErr != nil {
+			o.Log(req).WithError(err).WithField("range", rangeSpec).Debug("invalid range spec")
+			if errors.Is(rngErr, httputil.ErrUnsatisfiableRange) {
+				w.WriteHeader(http.StatusRequestedRangeNotSatisfiable)
```
Comment (arielshaqed) [inline pkg/gateway/operations/headobject.go:56]: Why is the behaviour on HEAD different from the behaviour on GET?  I didn't check the spec, but [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) it should send the exact same headers -- why not the same response?

("Because S3" is a good answer!)

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Thanks, this looks neat!

* Does DuckDB also use [multiple ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range#syntax) as exist in HTTP?
* Does DuckDB also use [If-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#conditional_range_requests)s?
* Different HTTP responses for invalid ranges between GET and HEAD.

File: pkg/gateway/operations/headobject.go (hunk 4 above)
Comment (ozkatz) [reply pkg/gateway/operations/headobject.go:58]: Nope. Bad ranges are ignored by S3.
The response would be a 200 OK with the full object content.

File: pkg/gateway/operations/headobject.go (hunk 5 above)
Comment (ozkatz) [reply pkg/gateway/operations/headobject.go:56]: Because S3 :)
In case of GetObject, the returned response would also be a 416 but with an XML body describing the error. For HeadObject it's simply a 416

**Comment by ozkatz** [comment]
> Thanks, this looks neat!
> 
> * Does DuckDB also use [multiple ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range#syntax) as exist in HTTP?

S3 treats multiple ranges as invalid ranges (meaning, it will return the full object with 200 OK)

> * Does DuckDB also use [If-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#conditional_range_requests)s?

S3 does not support If-Range (except for in the deprecated but still available(!!) [SOAP API](https://docs.aws.amazon.com/AmazonS3/latest/API/SOAPGetObjectExtended.html)). We probably shouldn't either.

> * Different HTTP responses for invalid ranges between GET and HEAD.

Both will return an HTTP 416, while GetObject also returns an XML body describing the error.

File: pkg/httputil/range.go (hunk 1 above)
Comment (ozkatz) [reply pkg/httputil/range.go:23]: Fixed

File: pkg/httputil/range.go (hunk 2 above)
Comment (ozkatz) [reply pkg/httputil/range.go]: Fixed :)

File: pkg/httputil/range_test.go (hunk 3 above)
Comment (ozkatz) [reply pkg/httputil/range_test.go]: Nice! good call. Fixed.

**Review by nopcoder — APPROVED** [review]
LGTM!
Wonder if the esti S3 test that uses S3 client should have caught this is one.

File: pkg/gateway/operations/headobject.go (hunk 5 above)
Comment (arielshaqed) [reply pkg/gateway/operations/headobject.go:56]: So not "because S3" but "because S3 and XML" 🤦🏽.  Now I'm sorry I ever asked this.

**Review by arielshaqed — APPROVED** [review]
Thanks!  I <3 the S3 API.
