### PR TITLE
Fix: Use repository root commit for import branch in import from UI

### LINKED ISSUE #3375: Import branches should be created from the repo root commit
**Actual**

The import branch is created from the HEAD of the given branch. When merging the import branch to the origin branch, it will delete all entries that existed when the import branch was created, due to the nature of 3-way merge.

**Desired**

Entries that existed before the import are not deleted. This can be achieved if the import branch is created from the repository root commit.

### PR DESCRIPTION
**Pull request by N-o-Z**
- Closes #3375

### CODE REVIEW

File: webui/src/pages/repositories/repository/objects.jsx [hunk 1]
```diff
@@ -137,7 +132,13 @@ const ImportButton = ({ config, repo, reference, path, onDone, onClick, variant
                 importBranchResp = await branches.get(repo.id, importBranch)
             } catch (error) {
                 if (error instanceof NotFoundError) {
-                    await branches.create(repo.id, importBranch, currBranch)
+                    // Find root commit for repository
+                    let response = await commits.log(repo.id, repo.default_branch, "", 1000)
+                    while (response.pagination.has_more) {
+                        response = await commits.log(repo.id, repo.default_branch, response.pagination.next_offset, 1000)
+                    }
```
Comment (itaiad200) [inline webui/src/pages/repositories/repository/objects.jsx:139]: Does JS has a `do {...} while(...)` option?

File: webui/src/pages/repositories/repository/objects.jsx [hunk 2]
```diff
@@ -81,7 +77,6 @@ const ImportButton = ({ config, repo, reference, path, onDone, onClick, variant
     const sourceRef = useRef(null);
     const destRef = useRef(null);
     const commitMsgRef = useRef(null);
-    const storageType = config.blockstore_type
     const storageNamespaceValidityRegexStr = config.blockstore_namespace_ValidityRegex;
     const storageNamespaceValidityRegex = RegExp(storageNamespaceValidityRegexStr);
     const sourceURIExample = config ? config.blockstore_namespace_example : "s3://my-bucket/path/";
```
Comment (itaiad200) [inline webui/src/pages/repositories/repository/objects.jsx:82]: Lines 86-90 are wrong, think about importing to a branch named `main_2`

**Review by itaiad200 — APPROVED** [review]
LGTM but I would wait for a native JS reader to review as well.

File: webui/src/pages/repositories/repository/objects.jsx (hunk 1 above)
Comment (N-o-Z) [reply webui/src/pages/repositories/repository/objects.jsx:139]: There is a do-while but since I need the response I need to define it outside the scope of the while, I can separate the definition from the assignment if you think it looks better.
Can you recommend on a native JS reader to review? :D

File: webui/src/pages/repositories/repository/objects.jsx (hunk 2 above)
Comment (N-o-Z) [reply webui/src/pages/repositories/repository/objects.jsx:82]: Opened #3416 for it, we should address it there

File: webui/src/pages/repositories/repository/objects.jsx [hunk 3]
```diff
@@ -137,7 +132,13 @@ const ImportButton = ({ config, repo, reference, path, onDone, onClick, variant
                 importBranchResp = await branches.get(repo.id, importBranch)
             } catch (error) {
                 if (error instanceof NotFoundError) {
-                    await branches.create(repo.id, importBranch, currBranch)
+                    // Find root commit for repository
+                    let response = await commits.log(repo.id, repo.default_branch, "", 1000)
```
Comment (eden-ohana) [inline webui/src/pages/repositories/repository/objects.jsx:136]:
```suggestion
                    let response = await commits.log(repo.id, reference.id, "", 1000)
```
for consistency

**Review by eden-ohana — APPROVED** [review]
Thanks! it works smoothly

File: webui/src/pages/repositories/repository/objects.jsx (hunk 1 above)
Comment (itaiad200) [reply webui/src/pages/repositories/repository/objects.jsx:139]: So maybe:

```suggestion
                    // Find root commit for repository
                    let hasMore = true;
                    let nextOffset = "";
                    let baseCommit = reference.id;
                    do {
                    	let response = await commits.log(repo.id, reference.id, nextOffset, 1000);
                    	hasMore = response.pagination.has_more;
                    	nextOffset = response.pagination.next_offset;
                    	baseCommit = response.results.at(-1);
                    } while (hasMore)
```

**Review by itaiad200 — APPROVED** [review]
LGTM
Thanks for making the fix! Please test the new version as well.
