### PR TITLE
Exclude non-existing objects from absolute addresses list

### LINKED ISSUE #4366: GC backup and restore fails when list of expired addresses contains path to non-existing object
When the addresses file GC backup and restore includes a non-existing path, backup and restore fail with 
```
org.apache.hadoop.tools.CopyListing$InvalidInputException: s3a://tal-test-1/distcp/notthere doesn't exist
	at org.apache.hadoop.tools.GlobbedCopyListing.doBuildListing(GlobbedCopyListing.java:84)
	at org.apache.hadoop.tools.CopyListing.buildListing(CopyListing.java:86)
	at org.apache.hadoop.tools.FileBasedCopyListing.doBuildListing(FileBasedCopyListing.java:70)
	at org.apache.hadoop.tools.CopyListing.buildListing(CopyListing.java:86)
	at org.apache.hadoop.tools.DistCp.createInputFileListing(DistCp.java:368)
	at org.apache.hadoop.tools.DistCp.prepareFileListing(DistCp.java:96)
	at org.apache.hadoop.tools.DistCp.createAndSubmitJob(DistCp.java:205)
	at org.apache.hadoop.tools.DistCp.execute(DistCp.java:182)
	at org.apache.hadoop.tools.DistCp.run(DistCp.java:153)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.tools.DistCp.main(DistCp.java:441)
	at io.treeverse.clients.GCBackupAndRestore$.main(GCBackupAndRestore.scala:168)
	at io.treeverse.clients.GCBackupAndRestore.main(GCBackupAndRestore.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:956)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1045)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1054)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
22/10/12 19:44:11 INFO SparkContext: Invoking stop() from shutdown hook
```

The failure is due to distCp limitation - it first builds the listing of files to copy, and fails if some objects are missing. 

The addresses file is likely to include paths to non-existing objects for the following reasons: 
* GC in not incremental. that is, in any subsequent run GC will include paths to objects that were already deleted. 
* Deletion may fail at the SDK client level

### PR DESCRIPTION
**Pull request by talSofer**
Fixes #4366

### How was this tested 

- Tested manually in aws and azure on databricks: 1. created an addresses file that includes paths to non-existing objects 2. run backup and restore utility.

### CODE REVIEW

File: clients/spark/core/src/main/scala/io/treeverse/clients/GCBackupAndRestore.scala [hunk 1]
```diff
@@ -113,6 +114,39 @@ object GCBackupAndRestore {
...
+      hc: Configuration
+  ): Dataset[String] = {
+    // Spark operators will need to generate configured FileSystems to check if objects exist.
+    // They will not have a JobContext to let them do that. Transmit (all) Hadoop filesystem configuration values to
+    // let them generate a (close-enough) Hadoop configuration to build the
+    // needed FileSystems.
+    val hcValues =
+      spark.sparkContext.broadcast(HadoopUtils.getHadoopConfigurationValues(hc, "fs."))
+    val configMapper = new ConfigMapper(hcValues)
+    absolutePathsDF.filter(x => isPathExist(x, configMapper))
```
Comment (johnnyaug) [inline clients/spark/core/src/main/scala/io/treeverse/clients/GCBackupAndRestore.scala:147]: Why not use `fs.exists`?

```suggestion
    absolutePathsDF.filter(x => {
      val p = new Path(x)
      p.getFileSystem(configMapper.configuration).exists(p)
    }
```

**Review by johnnyaug — APPROVED** [review]

File: clients/spark/core/src/main/scala/io/treeverse/clients/GCBackupAndRestore.scala (hunk 1 above)
Comment (Jonathan-Rosenberg) [reply clients/spark/core/src/main/scala/io/treeverse/clients/GCBackupAndRestore.scala:147]: I also think that to unify our usage we should get the FS from the path, and also `exists` saves a few lines of code, but you should catch `IOException`, and it might be still implemented under the `isPathExist` method.

**Review by Jonathan-Rosenberg — APPROVED** [review]
LGTM (only @johnnyaug's comment)

**Review by johnnyaug — APPROVED** [review]
