### PR TITLE
Fix spark lakefsfs test app work on EMR

### LINKED ISSUE #2095: Run lakefsfs spark test app on EMR
Explore what it takes to run `test/lakefsfs` under EMR cluster

### PR DESCRIPTION
**Pull request by nopcoder**
Close #2095

- Fix dependencies by building using `hadoop-lakefs-assembly` and not the lakefs java client.
- Create a repository that fails will not stop the test.
- Print the fail result into the log.

### CODE REVIEW

File: test/lakefsfs/src/main/scala/io/lakefs/fs/LakeFSFS.scala [hunk 1]
```diff
@@ -36,11 +37,16 @@ object LakeFSFS {
...
-    repositoriesApi.createRepository(repositoryCreation, false)
+    try {
+      val repositoryCreation = new RepositoryCreation()
+        .name(repository)
+        .defaultBranch(branch)
+        .storageNamespace(storageNamespace)
+      repositoriesApi.createRepository(repositoryCreation, false)
+      LOG.info("Repository created repository={}, branch={}, storageNamespace={}", repository, branch, storageNamespace)
+    } catch {
+      case e: ApiException => LOG.error("Create repository failed (code " + e.getCode() + ")", e)
```
Comment (arielshaqed) [inline test/lakefsfs/src/main/scala/io/lakefs/fs/LakeFSFS.scala:48]: Please log the actual message, not just the code.

**Review by arielshaqed — APPROVED** [review]
Nice work!

File: test/lakefsfs/build.sbt [hunk 2]
```diff
@@ -26,11 +29,10 @@ def generateProject(buildType: BuildType) =
       settingsToCompileIn(),
       scalaVersion := buildType.scalaVersion,
       libraryDependencies ++= Seq(
-        "io.lakefs" % "api-client" % "0.40.3",
+        "io.lakefs" % "hadoop-lakefs-assembly" % "0.1.0-RC.0-SNAPSHOT",
```
Comment (arielshaqed) [inline test/lakefsfs/build.sbt:32]: Can you document in the PR (say in a response here) why this works?  Just in case we run into this again ;-(

File: test/lakefsfs/src/main/scala/io/lakefs/fs/LakeFSFS.scala (hunk 1 above)
Comment (nopcoder) [reply test/lakefsfs/src/main/scala/io/lakefs/fs/LakeFSFS.scala:48]: The message is part of Java's Exception, passed it as part of the last argument in the log call.

File: test/lakefsfs/build.sbt (hunk 2 above)
Comment (nopcoder) [reply test/lakefsfs/build.sbt:37]: Updated the build.sbt with a comment on why we used the lakefs-assembly
