### PR TITLE
Addresses the vertical misalignment between the branch name and the "…

### LINKED ISSUE #7890: [Bug]: The delete icon and the name of the branch are not aligned in the UI
### What happened?

The delete icon and the name of the branch are not aligned in the UI. The name of the branch is aligned to the top of the cell, while the icon is aligned to the bottom of the cell. This can cause someone to delete the wrong branch by mistake.

image

### Expected behavior

Should be aligned

### lakeFS version

1.25.0

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by iddoavn**
…Default" badge in the list group item

Closes #7890 

## Change Description
Addresses the vertical misalignment between the branch name and the "Default" badge in the list group item.

### Background

This issue can cause a customer to mistakenly delete the wrong branch.

### Bug Fix

If this PR is a bug fix, please let us know about:

1. Problem - The delete icon and the name of the branch are not aligned in the UI. The name of the branch is aligned to the top of the cell, while the icon is aligned to the bottom of the cell. This can cause someone to delete the wrong branch by mistake.
2. Root cause - There is no alignment for the object
3. Solution - use flexbox to achieve proper vertical centering of both elements

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

### Contact Details

How can we get in touch with you if we need more info? (ex. email@example.com)

### CODE REVIEW

**Comment by eladlachmi** [comment]
Fix for the fix

Screenshot 2024-06-19 at 19 12 54

@iddoavn Is this ok?

**Comment by iddoavn** [comment]
> Fix for the fix
> 
> Screenshot 2024-06-19 at 19 12 54
> 
> @iddoavn Is this ok?

Amazing. Thank you!

File: webui/src/pages/repositories/repository/branches.jsx [hunk 1]
```diff
@@ -55,27 +56,28 @@ const BranchWidget = ({ repo, branch, onDelete }) => {
...
+                                <Badge variant="info">Default</Badge>
+                            </>
+                        }     
                     </h6>
-                </div>
+                </Col>
 
 
-                <div className="float-end">
+                <Col md="3" className="d-flex justify-content-end">
```
Comment (itaigilo) [inline webui/src/pages/repositories/repository/branches.jsx:80]: Does this look ok if you remove the `md="3"`, or is it required in this case?

**Review by itaigilo — APPROVED** [review]
Looking good.

Left two small comments.

File: webui/src/pages/repositories/repository/branches.jsx (hunk 1 above)
Comment (eladlachmi) [reply webui/src/pages/repositories/repository/branches.jsx:80]: The `row` class has `.row > * { width: 100% }`, so something needs to have specific sizing if we want anything but a 50/50 split. It also has the added benefit of having responsiveness built in.
