### PR TITLE
Use new Delta Lake client registration flow

### LINKED ISSUE #8852: [Bug]: Delta exporter hook failure
### What happened?

When running a hook that uses the delta client lua functions, it fails due to:
```bash
Error: runtime error: lakefs/catalogexport/delta_exporter.lua:82: fail to get protocol and metadata when initializing snapshots: : blob (key "<version>.checkpoint.parquet") (code=Unknown): operation error S3: GetObject, https response error StatusCode: 403, RequestID: <RID>, HostID: <HID>, api error AccessDenied: Access Denied.
```
It still manages to traverse JSON files though.

### Expected behavior

Traverse and build a Delta Table using both JSON and Parquet (checkpoint) delta log files.

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by Jonathan-Rosenberg**
Closes #8852

### CODE REVIEW

File: pkg/actions/lua/formats/delta.go [hunk 1]
```diff
@@ -4,15 +4,15 @@ import (
 	"context"
 	"errors"
 	"fmt"
-	"net/url"
 	"regexp"
 
+	"github.com/csimplestring/delta-go/storage"
+	"gocloud.dev/blob"
+
```
Comment (nopcoder) [inline pkg/actions/lua/formats/delta.go:11]:
```suggestion
	"github.com/csimplestring/delta-go/storage"
	"gocloud.dev/blob"
```

File: pkg/actions/lua/formats/delta.go [hunk 2]
```diff
@@ -27,6 +27,7 @@ var errUnimplementedProvided = errors.New("unimplemented provider")
 type DeltaClient struct {
 	accessProvider AccessProvider
 	ctx            context.Context
+	m              *blob.URLMux
```
Comment (nopcoder) [inline pkg/actions/lua/formats/delta.go:30]: - mux
- use non pointer (value) and pass the address as needed

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: go.mod [hunk 3]
```diff
@@ -96,7 +96,12 @@ require (
 	github.com/hashicorp/go-version v1.6.0
 	github.com/jackc/pgx/v5 v5.6.0
 	github.com/puzpuzpuz/xsync v1.5.2
+	github.com/treeverse/lakefs/modules/auth/factory v0.0.0-20250326081441-236e1a74dfde
+	github.com/treeverse/lakefs/modules/block/factory v0.0.0-20250326081441-236e1a74dfde
+	github.com/treeverse/lakefs/modules/config/factory v0.0.0-20250326081441-236e1a74dfde
+	github.com/treeverse/lakefs/webui v0.0.0-20250326081441-236e1a74dfde
```
[the remark this answers is not in the document]
Comment (Jonathan-Rosenberg) [reply go.mod]: done

File: pkg/actions/lua/formats/delta.go (hunk 2 above)
Comment (Jonathan-Rosenberg) [reply pkg/actions/lua/formats/delta.go]: done

File: pkg/actions/lua/formats/delta.go [hunk 4]
```diff
@@ -194,7 +186,7 @@ func newS3DeltaClient(l *lua.State, ctx context.Context, lakeFSAddr string) *Del
 		awsProps.Region = lua.CheckString(l, 3)
 	}
 
-	storage.RegisterS3CompatBucketURLOpener("lakefs", &awsProps)
-
-	return &DeltaClient{accessProvider: AWSInfo{AWSProps: awsProps}, ctx: ctx}
+	mux := new(blob.URLMux)
+	storage.RegisterS3CompatBucketURLOpener("lakefs", &awsProps, mux)
+	return &DeltaClient{accessProvider: AWSInfo{AWSProps: awsProps}, ctx: ctx, m: mux}
```
[the remark this answers is not in the document]
Comment (Jonathan-Rosenberg) [reply pkg/actions/lua/formats/delta.go]: done

**Review by nopcoder — APPROVED** [review]
LGTM!
