### PR TITLE
Truncated long value names in groups, users and policies

### LINKED ISSUE #8665: [Bug]: A long value for a group, user, or policy name causes overflow in the modal.
### What happened?

A long value for a group, user, or policy name causes overflow in the modal.

### Screenshot from the Groups page:

Image

same happens in the Users and Policies pages
    
### Steps to Reproduce:
1. Run ACL server with lakeFS
2. Go to Administration -> Groups -> click on the long name

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by Annaseli**
Closes #8665

## Issue
Long values names overflowed modal windows across Groups, Users and Policies pages in the "Administration" tab. 

## Fix
1. Applied truncation for long values in modals.
2. Users can hover to see full value and copy the truncated value.

### In "Groups", "Users" and "Policies" Pages
Go to Administration -> "Groups", "Users" or "Policies" page -> click on the long name to enter to it's page

#### The issue screenshot:
long_name_title_issue_1

#### The fix screenshot:
long_name_title_fix

#### Changed in file:
webui/src/lib/components/auth/nav.jsx (GroupHeader, PolicyHeader, UserHeader)
* Chaned in PolicyHeader since it has the same structure as GroupHeader and UserHeader

## Testing
Verified on lakeFS OSS using local DB & object store & ACL

### CODE REVIEW

File: webui/src/lib/components/auth/nav.jsx [hunk 1]
```diff
@@ -87,7 +87,19 @@ export const UserHeader = ({ userEmail, userId, page }) => {
                 <Link component={BreadcrumbItem} href='/auth/users'>
                     Users
                 </Link>
-                <Link component={BreadcrumbItem} href={{pathname: '/auth/users/:userId', params: {userId}}}>
+                <Link
+                    component={BreadcrumbItem}
+                    href={{pathname: '/auth/users/:userId', params: {userId}}}
+                    className="
+                        d-inline-block
```
Comment (itaigilo) [inline webui/src/lib/components/auth/nav.jsx:94]: Consider extracting the className into a local string, and use it as the class for the three instances it's repeated here.
Or in other words - DRY 😎

Comment (itaigilo) [reply webui/src/lib/components/auth/nav.jsx:94]: It will also make it easier to understand what you're achieving with these classes - 
Something like:
`const truncatedField = "d-inline-block w-50 text-nowrap overflow-hidden text-truncate align-middle";`

Comment (itaigilo) [reply webui/src/lib/components/auth/nav.jsx]: It's actually a great idea, to unify these <Link> elements into one.

It will make this change bigger, so:
1. It's up to you if you want to do this or not. It might be out of scope, but if you want to, it'll improve our code.
2. If you do make this change, make sure you check/validate all the refactored components.

**Review by itaigilo — APPROVED** [review]
Nice work 👍

File: webui/src/lib/components/auth/nav.jsx (hunk 1 above)
Comment (Annaseli) [reply webui/src/lib/components/auth/nav.jsx]: Great thanks! I have a doc where I write all the code that I think need to be generalized so i'll add it for myself now and will check with Guy weather i should do it now.
