### PR TITLE
Fix UI copy presigned URL not working when presign ui disabled

### LINKED ISSUE #6702: [Bug]: Copy Presigned URL doesn't work properly
### What happened?

Steps to Reproduce:
1. Click on object's gear icon
2. Click on Copy Presigned UR
3. Paste

### Expected behavior

Get presigned URL

### lakeFS version

0.111.1

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by nopcoder**
Fix #6702 

Tested manually using azure when presign UI disabled and enabled.

### CODE REVIEW

File: webui/src/lib/components/repository/tree.jsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ import Row from "react-bootstrap/Row";
 import Col from "react-bootstrap/Col";
 import Dropdown from "react-bootstrap/Dropdown";
 
-import { commits, linkToPath } from "../../api";
+import {config, commits, linkToPath, objects} from "../../api";
```
Comment (idanovo) [inline webui/src/lib/components/repository/tree.jsx:28]: do you know what the linter shows this message= `'config' is defined but never used`?

Comment (idanovo) [reply webui/src/lib/components/repository/tree.jsx:28]: ha ok, got it, it's not the same config
please remove if not needed 🙂
