### PR TITLE
Retry DB connection on Migration

### LINKED ISSUE #2017: Retry DB connection on startup
Got [this failure](https://github.com/treeverse/lakeFS/pull/2007/checks?check_run_id=2703565284#step:7:88):
```
lakefs_1    | panic: could not open DB: failed to connect to `host=postgres user=lakefs database=postgres`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
```
This looks like a race during startup, so need to retry _at least on this error_. This will also be useful for simplifying system automation.

### PR DESCRIPTION
**Pull request by adunuthulan**
Fixes #2017 

Retries the database connection after encountering any error while connecting for a migration task, specifically within the `getMigrate(params params.Database)` function. Both `lakefs run` and `lakefs setup` connect to the db to perform migration tasks, and will retry the connection if they encounter an error.

### CODE REVIEW

File: pkg/db/migration.go [hunk 1]
```diff
@@ -109,13 +110,28 @@ func getMigrate(params params.Database) (*migrate.Migrate, error) {
...
 	}
 	return m, nil
 }
 
+func tryNewWithSourceInstance(sourceName string, sourceInstance source.Driver, databaseURL string) (*migrate.Migrate, error) {
+	strategy := params.DatabaseRetryStrategy
+	var err error
+	for a := retry.Start(strategy, nil); a.Next(); {
+		m, err := migrate.NewWithSourceInstance(sourceName, sourceInstance, databaseURL)
+		if err == nil {
```
Comment (itaiad200) [inline pkg/db/migration.go:125]: Without checking the actual error for the cause of the failure, how can we know that the failure was because of a connection and not a failure to perform the actual action?

File: pkg/db/connect.go [hunk 2]
```diff
@@ -106,13 +103,7 @@ func normalizeDBParams(p *params.Database) {
...
-		retry.Exponential{
-			Initial: firstWait,
-			Factor:  waitGrowth,
-			Jitter:  true,
-		},
-	)
+	strategy := params.DatabaseRetryStrategy
 	var pool *pgxpool.Pool
 	var err error
 	for a := retry.Start(strategy, nil); a.Next(); {
```
Comment (itaiad200) [inline pkg/db/connect.go:109]: Here too, the actual error isn't being checked. Does the package expose the error types?

File: pkg/db/migration.go (hunk 1 above)
Comment (itaiad200) [reply pkg/db/migration.go:125]: Also not sure if it's safe to try to migrate twice, it might failed half way through..

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Looks good, but I think we need to check for the returned errors and not retry on every possible error.

File: pkg/db/migration.go (hunk 1 above)
Comment (adunuthulan) [reply pkg/db/migration.go:126]: `migrate.NewWithSourceInstance` doesn't actually perform the migration, it only gets the Migrate instance

File: pkg/db/migration.go [hunk 3]
```diff
@@ -125,8 +126,13 @@ func tryNewWithSourceInstance(sourceName string, sourceInstance source.Driver, d
 		if err == nil {
 			return m, nil
 		}
-
-		logging.Default().WithError(err).Error("could not open DB: Trying again")
+		netError := &net.OpError{}
+		if !(errors.As(err, &netError) && netError.Op == "dial") {
+			return nil, err
+		}
```
Comment (itaiad200) [inline pkg/db/migration.go:132]: Extract this repeated logic to a common place.

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Single minor comment. Also - how was this tested?

**Review by nopcoder — APPROVED** [review]

File: pkg/db/migration.go (hunk 3 above)
Comment (adunuthulan) [reply pkg/db/migration.go]: I moved the logic to the errors.go file in the db package. I haven't seen code like this within other errors.go files, but an errors file seems like an appropriate place for code checking for errors. Is this okay?

The function is exported since it could conceivably be used elsewhere.

**Comment by adunuthulan** [comment]
> Single minor comment. Also - how was this tested?

@itaiad200 This was tested by running the lakeFS image through VSCode. I put break points within both the 'lakefs run' code (where the first connection is made through `BuildDatabaseConnection()`) and 'lakefs setup' code (where the first connection is through `migrate.newWithSourceInstance()`), and I was able to confirm that running either command will perform the db connection retries before exiting execution, if postgres is not running yet.

File: pkg/db/migration.go (hunk 3 above)
Comment (itaiad200) [reply pkg/db/migration.go]: This file is the right place. As for exporting it, I would usually make it unexported until the first external use-case (which sometimes forces you to move it to an entirely different package anyhow). Not blocking anyways..

**Review by itaiad200 — APPROVED** [review]
Great work! see minor non-blocking comment..
