### PR TITLE
Esti: Fix nil pointer dereference

### LINKED ISSUE #8888: Esti: Fix lakectl GetAuthor method
Avoid nil pointer reference when checking pointer value

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #8888

### CODE REVIEW

File: esti/lakectl_util.go [hunk 1]
```diff
@@ -6,6 +6,7 @@ import (
 	"errors"
 	"flag"
 	"fmt"
+	"github.com/go-openapi/swag"
```
Comment (idanovo) [inline esti/lakectl_util.go:9]: go imports
