### PR TITLE
Fix/clientside validation in repo creation 833

### LINKED ISSUE #833: Wrong UI error when repo name contains underscore (on repo creation)

### PR DESCRIPTION
**Pull request by Sufiyan1997**
Closes #833 

Added client side validation while creating a repository as follows:

- Repository name should match `^[a-z0-9][a-z0-9-]{2,62}$`
- Storage namespace should match `^(s3|gs|mem|local|transient):\/.*$`
- Default branch name should not be empty

### CODE REVIEW

File: webui/src/components/RepositoryCreateForm.js [hunk 1]
```diff
@@ -51,20 +64,35 @@ export const RepositoryCreateForm = connect(
             <Form.Group as={Row} controlId="id">
                 <Form.Label column sm={fieldNameOffset}>Repository ID</Form.Label>
                 <Col sm={sm}>
-                    <Form.Control type="text" autoFocus ref={repoIdField} onChange={checkValidity}/>
+                    <Form.Control type="text" autoFocus ref={repoIdField} onChange={checkRepoValidity}/>
+                    {!repoValid &&
+                        <Form.Text className="text-danger">
+                            Min 2 characters. Only Alpahnumeric characters and '-' allowed.
```
Comment (itaiad200) [inline webui/src/components/RepositoryCreateForm.js:70]: Add 'lowercase' to the error message.

File: webui/src/components/RepositoryCreateForm.js [hunk 2]
```diff
@@ -18,20 +18,33 @@ export const RepositoryCreateForm = connect(
...
-            storageNamespaceField.current.value.length === 0 ||
-            defaultBranchField.current.value.length === 0) {
-            setFormValid(false);
-            return;
-        }
-        setFormValid(true);
+    const checkRepoValidity = () => {
+        const isRepoValid = repoValidityRegex.test(repoIdField.current.value)
+        setRepoValid(isRepoValid);
+        setFormValid(isRepoValid);
```
Comment (itaiad200) [inline webui/src/components/RepositoryCreateForm.js:35]: Here and elsewhere.
This is wrong, form validity should be AND of all three, not the state of the last validity function running.

**Review by itaiad200 — CHANGES_REQUESTED** [review]

File: webui/src/components/RepositoryCreateForm.js [hunk 3]
```diff
@@ -18,20 +18,33 @@ export const RepositoryCreateForm = connect(
     };
   })(({ error, onSubmit, onCancel, create, sm = 6, config }) => {
     const fieldNameOffset = 3;
+    const repoValidityRegex = /^[a-z0-9][a-z0-9-]{2,62}$/;
+    const storageNamespaceValidityRegex = /^(s3|gs|mem|local|transient):\/.*$/;
 
     const [formValid, setFormValid] = useState(false);
+    const [repoValid, setRepoValid] = useState(true);
```
Comment (itaiad200) [inline webui/src/components/RepositoryCreateForm.js:25]: This should start as false since it's empty, right?

File: webui/src/components/RepositoryCreateForm.js [hunk 4]
```diff
@@ -18,20 +18,33 @@ export const RepositoryCreateForm = connect(
...
+    const [storageNamespaceValid, setStorageNamespaceValid] = useState(true);
```
Comment (itaiad200) [inline webui/src/components/RepositoryCreateForm.js:26]: Here too.

File: webui/src/components/RepositoryCreateForm.js (hunk 3 above)
Comment (Sufiyan1997) [reply webui/src/components/RepositoryCreateForm.js:25]: Ideally yes. But if it starts as false then the error messages will be displayed the first time the modal opens. And as we have initialized `formValid` as false, it will anyways prevent the user from submitting the form without any input.

Comment (itaiad200) [reply webui/src/components/RepositoryCreateForm.js:25]: Gotcha, that will do.

**Review by itaiad200 — APPROVED** [review]
