### PR TITLE
Fix create and delete branch protection error and lakectl output

### LINKED ISSUE #5548: [DX] `lakectl branch-protect add` does not give a success message
When the user adds branch protection from `lakectl` they do not get any confirmation that it succeeded:
```
$ lakectl branch-protect add lakefs://quickstart main

$
```
There should be a message such as "branch protection rule sucessfully created for repository xxx"

### LINKED ISSUE #6138: Branch protection API missing and exits status code
- Existing branch protection rule should return 409. Currently it is not part of the openapi spec and fallback to 500.
- Missing branch protection rule should return 404. Currently returns 500.

### PR DESCRIPTION
**Pull request by nopcoder**
- API returns 409 conflict on existing rule
- API returns 404 not found on missing rule
- lakectl message on add or delete rule

Fix #5548
Fix #6138

### CODE REVIEW

File: cmd/lakectl/cmd/branch_protect.go [hunk 1]
```diff
@@ -74,6 +76,7 @@ var branchProtectDeleteCmd = &cobra.Command{
 			Pattern: args[1],
 		})
 		DieOnErrorOrUnexpectedStatusCode(resp, err, http.StatusNoContent)
+		fmt.Printf("Branch protection rule deleted to '%s' repository.\n", u.Repository)
```
Comment (johnnyaug) [inline cmd/lakectl/cmd/branch_protect.go:79]:
```suggestion
		fmt.Printf("Branch protection rule deleted from '%s' repository.\n", u.Repository)
```

**Review by johnnyaug — APPROVED** [review]
