### PR TITLE
Fix lakeFSFS stage<->copy fallback mechanism

### LINKED ISSUE #5160: Bug: Fallback mechanism from copyObject to stageObject is broken
In lakeFSFS, during renameObject, there's a fallback mechanism to support older lakeFS server versions.
That mechanism is broken due to a bug in error comparison.

### PR DESCRIPTION
**Pull request by itaiad200**
closes #5160

### CODE REVIEW

File: clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java [hunk 1]
```diff
@@ -456,7 +456,7 @@ private boolean renameObject(LakeFSFileStatus srcStatus, Path dst) throws IOExce
                         creationReq);
             } catch (ApiException e) {
                 if (e.getCode() != HttpStatus.SC_INTERNAL_SERVER_ERROR ||
-                        !e.getMessage().contains("invalid API endpoint")) {
+                        !e.getResponseBody().contains("invalid API endpoint")) {
```
Comment (nopcoder) [inline clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java:459]: The `getReponseBody()` method can return nil can you verify before calling `contains`.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java (hunk 1 above)
Comment (itaiad200) [reply clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java:460]: Done.

**Review by nopcoder — APPROVED** [review]
