### PR TITLE
Fixed - long branch name overflows selected branch button and path

### LINKED ISSUE #8930: [Bug]: A long branch name overflows the selected branch button
### What happened?

In the UI, creating a long branch name causes it to overflow the selected branch button that is located at the top of each tab.

Image

### Notes:
I opened this issue as a follow-up to [Issue#8639](https://github.com/treeverse/lakeFS/issues/8639) to isolate and address only the problem in  the selected branch button, allowing for a smaller, more focused PR separate from the other issues mentioned in #8639.

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by Annaseli**
Closes #8930 #8639

### Bug Fix

This PR fixes a UI issue where long branch names caused the "selected branch" button at the top-left corner of multiple pages to overflow, and also caused the branch name in the path to wrap onto multiple lines, as shown below:

image
image

### Fix

- Applied React Bootstrap utility classes to **truncate** long branch names.
- Added a **max-width** to the branch button to prevent it from growing indefinitely.
- These changes were made in `refDropdown.jsx`.
- Applied React Bootstrap utility classes to **truncate** long branch names in the path in `tree.jsx`.

Fix:
image

### Testing Details

Tested locally on lakeFS with Fluffy.

### CODE REVIEW

File: webui/src/lib/components/repository/tree.jsx [hunk 1]
```diff
@@ -650,30 +650,34 @@ export const URINavigator = ({
...
-            </Link>
-            <strong>{"/"}</strong>
-            <Link
-              href={{
-                pathname: "/repositories/:repoId/objects",
-                params,
-                query: { ref: reference.id },
-              }}
+            <div
+                title={reference.type === RefTypeCommit ? reference.id.substr(0, 12) : reference.id}
```
Comment (itaigilo) [inline webui/src/lib/components/repository/tree.jsx:654]: Is `title` the tooltip?
If so, and it's really required - 
Please unify the `reference.type === RefTypeCommit ? reference.id.substr(0, 12) : reference.id` that appears three times.

File: webui/src/lib/components/repository/tree.jsx [hunk 2]
```diff
@@ -650,30 +650,34 @@ export const URINavigator = ({
...
-              {repo.id}
-            </Link>
-            <strong>{"/"}</strong>
-            <Link
-              href={{
-                pathname: "/repositories/:repoId/objects",
-                params,
-                query: { ref: reference.id },
-              }}
+            <div
```
Comment (itaigilo) [inline webui/src/lib/components/repository/tree.jsx:653]: The exact same dive appears twice. Any reason not to place it above the condition?

**Review by itaigilo — CHANGES_REQUESTED** [review]
Nice work, thanks for spotting these.

Requires some cleanup though.

File: webui/src/lib/components/repository/tree.jsx (hunk 1 above)
Comment (Annaseli) [reply webui/src/lib/components/repository/tree.jsx:654]: I think it’s important to include a tooltip showing the full branch name—don’t you agree?

Also, I’ve removed the duplication.

**Review by itaigilo — APPROVED** [review]
Looking good 👍

File: webui/src/lib/components/repository/tree.jsx (hunk 1 above)
Comment (itaigilo) [reply webui/src/lib/components/repository/tree.jsx]: Yeah, agree.
Looking good.
