### PR TITLE
Make update object metadata API atomic

### LINKED ISSUE #8262: Fix update metadata on old uncommitted / delete / GC race
#8253 describes a _very_ rare race.  It will be hard even to reproduce it on purpose, but a race is a race.

Start with an uncommitted but old object (e.g., upload an object to a branch and wait for a fortnight without committing it).  Now perform these 3 operations concurrently: update the object metadata, delete the object, and quickly run GC.

- Thread 1 gets object metadata to update its user metadata
- Thread 2 deletes the object
- 👉🏽  **Thread 3 performs UGC and cleans up the physical object**
- Thread 1 writes a new entry for the object with the same physical address

Result: Update metadata succeeds, leaving an object with the updated metadata but with no physical object to back it up.  GETting that object will return `410 Gone`.  There is no way to sequence "update object metadata" and "delete object" to get this behaviour, so this is a bug.

It is also probably impossible to get this result: thread 1 will need to sleep for close to an entire GC cycle.

Nonetheless, a bug is a bug.

### PR DESCRIPTION
**Pull request by arielshaqed**
Protect updating object metadata on an existing entry to be safe against concurrent modifications, deletions, and commits and merges to the branch. This is a bit tricky because it needs to work for both committed and staged objects.

Fixes #8262 - a race that would give an odd result if update object metadata managed to lose against concurrent delete and uncommitted GC, or potentially merges into the branch.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Reviewers: I know that tests fail.  Please review anyway, we will likely need >1 round -- and these will be easy enough to fix, and _not_ in the areas modified in this PR.

**Review by N-o-Z — APPROVED** [review]
LGTM!

**Comment by arielshaqed** [comment]
# Look**ED** good to Nir 😭

**Comment by N-o-Z** [comment]
> # Look**ED** good to Nir 😭

I'll review it today 😃

File: pkg/graveler/graveler.go [hunk 1]
```diff
@@ -1841,6 +1873,46 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+	err = g.safeBranchWrite(ctx, log, repository, branchID, safeBranchWriteOptions{MaxTries: options.MaxTries}, func(branch *Branch) error {
+		value, onStaging, err := g.getFromBranchWithStaging(ctx, repository, branch, key)
+		if err != nil && !errors.Is(err, ErrNotFound) {
+			return fmt.Errorf("get existing entry to update user metadata: %w", err)
+		}
+
+		return g.StagingManager.Update(ctx, branch.StagingToken, key, func(currentValue *Value) (*Value, error) {
+			if currentValue == nil {
+				if onStaging {
+					// Object previously on staging, and
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1901]: nit: 
I know this is your line length configuration but this way of breaking the comment makes it very confusing to understand. Consider leaving it in a single line

File: pkg/graveler/graveler.go [hunk 2]
```diff
@@ -1841,6 +1873,46 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+
+	err = g.safeBranchWrite(ctx, log, repository, branchID, safeBranchWriteOptions{MaxTries: options.MaxTries}, func(branch *Branch) error {
+		value, onStaging, err := g.getFromBranchWithStaging(ctx, repository, branch, key)
+		if err != nil && !errors.Is(err, ErrNotFound) {
+			return fmt.Errorf("get existing entry to update user metadata: %w", err)
+		}
+
+		return g.StagingManager.Update(ctx, branch.StagingToken, key, func(currentValue *Value) (*Value, error) {
+			if currentValue == nil {
+				if onStaging {
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1900]: Do we really need this piece of code?
Considering this will just fail during the update due to the change on the branch?
This can also result in inconsistent behavior:
If we catch the deletion before this part we will return `ErrNotFound` but if the delete occurs after this check we will get `PreconditionFalied`.
This might also cause confusion when debugging

File: pkg/graveler/graveler.go [hunk 3]
```diff
@@ -1841,6 +1873,46 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+					// Object previously on staging, and
+					// was deleted since
+					// getFromBranchWithStaging.
+					return nil, ErrNotFound
+				}
+				// Use committed value (in practice it came
+				// from committed, so it is non-nil).
+				currentValue = value
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1908]: If I understand correctly, the only reason we get the value before the update is because we perform retries. In that case I think it's important to document that so it will be clear what we're doing here.

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Thanks - looks neat.
I did not review the tests yet as I had some questions regarding the logic itself

**Review by arielshaqed — COMMENTED** [review]
THANKS for a thorough review!  PTAL, I think I changed the bits you did not like.  It is definitely shorter now; this implies fewer bugs if we assume equal bug densities.

File: pkg/catalog/catalog.go [hunk 4]
```diff
@@ -1000,6 +1000,40 @@ func (c *Catalog) GetEntry(ctx context.Context, repositoryID string, reference s
...
+		}
+		entry, err := ValueToEntry(value)
+		if err != nil {
+			return nil, err
+		}
+		entry.Metadata = newUserMetadata
+		return EntryToValue(entry)
+	})
+	err = c.Store.UpdateObjectMetadata(ctx, repository, branchID, key, updater)
+	return err
```
Comment (itaiad200) [inline pkg/catalog/catalog.go:1034]:
```suggestion
	return c.Store.UpdateObjectMetadata(ctx, repository, branchID, key, updater)
```

File: pkg/graveler/graveler.go [hunk 5]
```diff
@@ -1841,6 +1845,47 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+
+	err = g.safeBranchWrite(ctx, log, repository, branchID, safeBranchWriteOptions{MaxTries: options.MaxTries}, func(branch *Branch) error {
+		return g.StagingManager.Update(ctx, branch.StagingToken, key, func(currentValue *Value) (*Value, error) {
+			if currentValue == nil {
+				// Object not on staging: need to update committed value.
+				if committedValue == nil {
+					committedValue, err = g.Get(ctx, repository, Ref(branchID), key)
+					if err != nil {
+						// (Includes ErrNotFound)
+						return nil, fmt.Errorf("read %s/%s/%s from committed: %w", repository.RepositoryID, branchID, key, err)
```
Comment (itaiad200) [inline pkg/graveler/graveler.go:1877]: I see this PR writes 'repo/branch/path' in errors, we usually don't do that.. I think I also found a scenario where this info is written twice, by Graveler and by Catalog.

File: pkg/graveler/graveler.go [hunk 6]
```diff
@@ -541,6 +541,11 @@ type KeyValueStore interface {
 	// Set stores value on repository / branch by key. nil value is a valid value for tombstone
 	Set(ctx context.Context, repository *RepositoryRecord, branchID BranchID, key Key, value Value, opts ...SetOptionsFunc) error
 
+	// UpdateObjectMetadata atomically runs update on repository /
+	// branch by key.  (Of course, if entry is only on committed, the
+	// updated entry will still be created (atomically) on staging.)
+	UpdateObjectMetadata(ctx context.Context, repository *RepositoryRecord, branchID BranchID, key Key, update ValueUpdateFunc, opts ...SetOptionsFunc) error
```
Comment (itaiad200) [inline pkg/graveler/graveler.go:547]: I don't know if you meant to write it this way, but you can update more than just the metadata. If it's intended, let's rename the func. If not, let's rewrite the logic.
```suggestion
	UpdateObject(ctx context.Context, repository *RepositoryRecord, branchID BranchID, key Key, update ValueUpdateFunc, opts ...SetOptionsFunc) error
```

File: pkg/api/controller_test.go [hunk 7]
```diff
@@ -2299,47 +2299,73 @@ func TestController_UpdateObjectUserMetadataHander(t *testing.T) {
...
-		const objPath = "foo/bar"
-		entry := catalog.DBEntry{
-			Path:            objPath,
-			PhysicalAddress: "this_is_bars_address",
-			CreationDate:    time.Now(),
-			Size:            666,
-			Checksum:        "this_is_a_checksum",
-		}
-		testutil.Must(t, deps.catalog.CreateEntry(ctx, repo, "main", entry))
+	bools := []bool{false, true}
```
Comment (itaiad200) [inline pkg/api/controller_test.go:2302]: Nice tests!

File: pkg/graveler/graveler.go [hunk 8]
```diff
@@ -1841,6 +1845,47 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+
+	log := g.log(ctx).WithFields(logging.Fields{"key": key, "operation": "update_user_metadata"})
+
+	// committedValue, if non-nil is a value read from either uncommitted or committed.  Usually
+	// it it is read from committed.  If there is a value on staging, that entry will be
+	// modified and committedValue will never be read.
+	var committedValue *Value
+
+	err = g.safeBranchWrite(ctx, log, repository, branchID, safeBranchWriteOptions{MaxTries: options.MaxTries}, func(branch *Branch) error {
+		return g.StagingManager.Update(ctx, branch.StagingToken, key, func(currentValue *Value) (*Value, error) {
```
Comment (itaiad200) [inline pkg/graveler/graveler.go:1870]: I believe you shouldn't retry if the entry was changed, i.e. the StagingManager `SetMsgIf` failed due to the predicate

File: pkg/catalog/catalog.go [hunk 9]
```diff
@@ -1000,6 +1000,40 @@ func (c *Catalog) GetEntry(ctx context.Context, repositoryID string, reference s
...
+		return fmt.Errorf("%w: %s %s %s", err, repositoryID, branchID, path)
+	}
+
+	repository, err := c.getRepository(ctx, repositoryID)
+	if err != nil {
+		return nil
+	}
+
+	key := graveler.Key(path)
+	updater := graveler.ValueUpdateFunc(func(value *graveler.Value) (*graveler.Value, error) {
```
Comment (N-o-Z) [inline pkg/catalog/catalog.go:1021]: I think I have forgotten to submit this comment in the previous review.
It also relates to @itaiad200  [comment](https://github.com/treeverse/lakeFS/pull/8264/files#r1793663660):
If the intention of the function is to update the metadata only - let's pass the metadata instead of an update function. make it explicit, inline and easier to read.
Otherwise lets modify the graveler function to be `UpdateObject` and provide the update function accordingly (which is infact exactly the same as calling `g.StagingManager.Update`).

File: pkg/graveler/graveler.go (hunk 8 above)
Comment (N-o-Z) [reply pkg/graveler/graveler.go:1870]: If staging operation fails (i.e. predicate failed) there will not be any retry

File: pkg/graveler/graveler.go [hunk 10]
```diff
@@ -1841,6 +1845,47 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+			if currentValue == nil {
+				// Object not on staging: need to update committed value.
+				if committedValue == nil {
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1873]:
```suggestion
			if currentValue == nil && committedValue == nil {
				// Object not on staging: need to update committed value.
```

File: pkg/graveler/graveler.go (hunk 2 above)
Comment (N-o-Z) [reply pkg/graveler/graveler.go]: Well due to the code changes it is not relevant but, consider the two timings:
1. Object is deleted from staging before this line - we will return ErrNotFound
2. Object is initially read (with pred) at the beginning of `g.StagingManager.Update` then immediately deleted and we use the setMsgIf using the pred - and we get `ErrPredicateFailed`
In both scenarios the object was deleted in staging during UpdateMetadata

**Review by N-o-Z — COMMENTED** [review]
Code is much clearer now IMO!
Added one more major comment which I seem to have left out of the previous review

**Review by arielshaqed — COMMENTED** [review]
Thanks!

I ended up accepting comments about naming and error messages, but _not_ changing the interface, using StagingManager.Update directly, or changing the interface of Graveler.Update.  I hope I explained why in my comments.

PTAL...

**Review by itaiad200 — APPROVED** [review]
LGTM, thanks for the quick fixes

**Comment by arielshaqed** [comment]
ObMeme:
scumbag steve meme: Writes fix for rare race condition.  Is late to every meeting.

File: pkg/graveler/graveler.go [hunk 11]
```diff
@@ -1841,6 +1844,47 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
...
+
+	options := NewSetOptions(opts)
+	if repository.ReadOnly && !options.Force {
+		return ErrReadOnlyRepository
+	}
+
+	log := g.log(ctx).WithFields(logging.Fields{"key": key, "operation": "update_user_metadata"})
+
+	// committedValue, if non-nil is a value read from either uncommitted or committed.  Usually
+	// it it is read from committed.  If there is a value on staging, that entry will be
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1864]:
```suggestion
	// it is read from committed.  If there is a value on staging, that entry will be
```

File: pkg/graveler/graveler.go [hunk 12]
```diff
@@ -1841,6 +1844,47 @@ func (g *Graveler) safeBranchWrite(ctx context.Context, log logging.Logger, repo
 	return nil
 }
 
+func (g *Graveler) Update(ctx context.Context, repository *RepositoryRecord, branchID BranchID, key Key, update ValueUpdateFunc, opts ...SetOptionsFunc) error {
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1847]: 🙏🏽 👍🏽

**Review by N-o-Z — APPROVED** [review]
Thanks!!!!
One typo comment

File: pkg/graveler/graveler.go (hunk 2 above)
Comment (arielshaqed) [reply pkg/graveler/graveler.go]: Thanks!

I think that you were right and still are, and that this still happens.  But only during a race.  It is legit to fail an update if it occurs concurrently with a deletion.  Returning ErrNotFound is the best way, which serializes DELETE before UPDATE.  But returning ErrPredicateFailed is equally valid - it indicates that Graveler was unable to serialize the operations.

I doubt this will matter in practice.  If it does, we will need to add a retry.

File: pkg/graveler/graveler.go (hunk 11 above)
Comment (arielshaqed) [reply pkg/graveler/graveler.go:1864]: scumbag steve meme: reviews distributed code for idempotency.  complains about "it it" in comment.

**Review by arielshaqed — COMMENTED** [review]
Thanks!  Pulling...
