### PR TITLE
Fix `lakectl login` redirects when lakeFS uses OIDC authentication

### LINKED ISSUE #9711: UI redirects to the the wrong page after logging in when using OIDC
When not logged in, the UI redirects to login.  When using OIDC it does not redirect back to the original URL.  This is surprising for users, especially with `lakectl login`.

See @Annaseli 's amazing analysis (and a solution) [here](https://github.com/treeverse/lakeFS/pull/9644#discussion_r2554059574).

### PR DESCRIPTION
**Pull request by arielshaqed**
- Redirect through /auth/login, let the web UI extract the "next" URL from its state.

  This is trickier than it sounds!  In particular, if you configure lakectl to use a _numeric_ IP address for the lakeFS server then logging in does not work: the session state belongs to the wrong IP.  (I'll warn about it in #9659 during initial configuration, it will be usable...)
- Include the query string (if any) during /api/v1 redirections.  This has not immediate effect, but it is correct unlike the previous form.

Tested against a local OIDC configuration.

Fixes #9711.

### CODE REVIEW

File: pkg/api/controller.go [hunk 1]
```diff
@@ -954,13 +954,13 @@ func (c *Controller) ReleaseTokenToMailbox(w http.ResponseWriter, r *http.Reques
 			WithField("accept", r.Header.Get("Accept")).
 			Debug("Failed to get user - redirect to login")
 
-		redirectURL, err := url.Parse(c.Config.AuthConfig().GetLoginURL())
```
Comment (Annaseli) [inline pkg/api/controller.go:957]: Should we remove this implementation now that it’s no longer used?
`c.Config.AuthConfig().GetLoginURL()`

File: webui/src/pages/index.jsx
Comment (Annaseli) [inline webui/src/pages/index.jsx:1]: If we’re already changing this file, can we align the routes for readability?
I mean, can we move
```
<Route path="*" element={<Navigate to="/repositories" replace />} />
```
to appear directly under
```
<Route path="api/v1/auth/get-token/release-token/*" element={<Redirect />} />
```

That way it’s clearer that both are inside the block:
```
<Route element={<RequiresAuth />} >
```

File: pkg/api/controller.go (hunk 1 above)
Comment (arielshaqed) [reply pkg/api/controller.go:957]: Done (here).  The next PR will remove its overrides in the enterprise module.

File: webui/src/pages/index.jsx
Comment (arielshaqed) [reply webui/src/pages/index.jsx:1]: Not done, it's unrelated and I prefer to do one thing at a time.
