### PR TITLE
Fix miscellaneous code linting issues

### LINKED ISSUE #4151: Fix miscellaneous code linting issues
Run and fix linter warnings found in the code - from spell checking to error checking.

### PR DESCRIPTION
**Pull request by nopcoder**
Fix #4151

### CODE REVIEW

File: clients/spark/core/src/test/resources/parser-test/sst_files_generator.go [hunk 1]
```diff
@@ -65,7 +65,10 @@ func writeSstWithBadMagic() {
 	if err != nil {
 		panic(err)
 	}
-	os.Truncate(testFileName+".sst", fi.Size()-MagicLengthBytes/2)
+	err = os.Truncate(testFileName+".sst", fi.Size()-MagicLengthBytes/2)
```
Comment (arielshaqed) [inline clients/spark/core/src/test/resources/parser-test/sst_files_generator.go:68]: Rather more than spelling here, I think. Consider updating the PR title.

File: cmd/lakectl/cmd/config/config.go [hunk 2]
```diff
@@ -58,7 +58,7 @@ type Config struct {
 func ReadConfig() (c *Config) {
 	c = &Config{}
 
-	// Inform viper of all expected fields.  Otherwise it fails to deserialize from the
+	// Inform viper of all expected fields.  Otherwise, it fails to deserialize from the
```
Comment (arielshaqed) [inline cmd/lakectl/cmd/config/config.go:61]: Arguably incorrect (but not blocking).

File: cmd/lakectl/cmd/fs.go [hunk 3]
```diff
@@ -132,7 +132,7 @@ var fsCatCmd = &cobra.Command{
 			DieErr(err)
 		}
 
-		defer body.Close()
+		defer func() { _ = body.Close() }()
```
Comment (arielshaqed) [inline cmd/lakectl/cmd/fs.go:135]: This might actually still hide some (usually minor) errors. I'm not sure that network reads are guaranteed to succeed or fail before completion.

Consider opening a separate issue to report errors here.

Comment (arielshaqed) [inline cmd/lakectl/cmd/fs.go:135]: This might actually still hide some (usually minor) errors. I'm not sure that network reads are guaranteed to succeed or fail before completion.

Consider opening a separate issue to report errors here.

File: esti/s3_gateway_test.go [hunk 4]
```diff
@@ -48,7 +48,7 @@ func TestS3UploadAndDownload(t *testing.T) {
 	for _, sig := range sigs {
 		t.Run("Sig"+sig.Name, func(t *testing.T) {
 			// Use same sequence of pathnames to test each sig.
-			rand := rand.New(rand.NewSource(17))
+			randomizer := rand.New(rand.NewSource(17))
```
Comment (arielshaqed) [inline esti/s3_gateway_test.go:51]: This name confuses me. It's a Rand, a randomizer is something else
I'd be happier with r,  or if that's too short for comfort perhaps prng. Or rand, really...

File: esti/system_test.go [hunk 5]
```diff
@@ -126,8 +126,12 @@ func createRepository(ctx context.Context, t *testing.T, name string, repoStorag
 func deleteRepositoryIfAskedTo(ctx context.Context, repositoryName string) {
 	deleteRepositories := viper.GetBool("delete_repositories")
 	if deleteRepositories {
-		client.DeleteRepositoryWithResponse(ctx, repositoryName)
-		logger.WithField("repo", repositoryName).Info("Deleted repository")
+		_, err := client.DeleteRepositoryWithResponse(ctx, repositoryName)
+		if err != nil {
+			logger.WithError(err).WithField("repo", repositoryName).Error("Deleted repository")
```
Comment (arielshaqed) [inline esti/system_test.go:131]:
```suggestion
			logger.WithError(err).WithField("repo", repositoryName).Error("Deleting repository")
```

It might not have been deleted!

File: esti/system_test.go [hunk 6]
```diff
@@ -172,7 +176,7 @@ func uploadContent(ctx context.Context, repo string, branch string, objPath stri
 	if err != nil {
 		return nil, fmt.Errorf("write content: %w", err)
 	}
-	w.Close()
+	_ = w.Close()
```
Comment (arielshaqed) [inline esti/system_test.go:179]: This Close can fail and destroy the test. Can we fail of this happens?

File: pkg/actions/kv_migrate_test.go [hunk 7]
```diff
@@ -47,9 +47,14 @@ func benchmarkMigrate(runCount int, b *testing.B) {
...
 	kvStore := kvtest.MakeStoreByName(postgres.DriverName, kvparams.KV{Postgres: &kvparams.Postgres{ConnectionString: databaseURI}})(b, ctx)
-	buf, _ := os.CreateTemp("", "migrate")
-	defer os.Remove(buf.Name())
-	defer buf.Close()
+	buf, err := os.CreateTemp("", "migrate")
+	if err != nil {
+		b.Fatal("Create temp file for migrate", err)
+	}
+	defer func() {
+		_ = os.Remove(buf.Name())
```
Comment (arielshaqed) [inline pkg/actions/kv_migrate_test.go:55]: Could immediately delete. That's better if the program crashes.

File: pkg/api/helpers/adapters.go [hunk 8]
```diff
@@ -27,7 +27,7 @@ type ObjectStats struct {
 
 // ClientAdapter abstracts operations on a backing store.
 type ClientAdapter interface {
-	// Upload upload data from contents to physicalAddress and returns stored stats.
+	// Upload - upload data from contents to physicalAddress and returns stored stats.
```
Comment (arielshaqed) [inline pkg/api/helpers/adapters.go:30]: I think godoc is
```suggestion
	// Upload uploads data from contents to physicalAddress and returns stored stats.
```

File: pkg/auth/service.go [hunk 9]
```diff
@@ -64,7 +64,7 @@ type GatewayService interface {
 }
 
 type Authorizer interface {
-	// authorize user for an action
+	// Authorize user for an action
```
Comment (arielshaqed) [inline pkg/auth/service.go:67]: Can this be godoc please?

File: pkg/batch/executor_test.go [hunk 10]
```diff
@@ -78,7 +78,7 @@ func testReadAfterWrite(t *testing.T) {
 	read2Done := make(chan bool)
 	read2Batched := make(chan struct{})
 
-	// we pass a custom delay func that ensures we make the write only after
+	// we pass a custom delay func that ensures we make to write only after
```
Comment (arielshaqed) [inline pkg/batch/executor_test.go:81]: I don't understand the sentence.  Perhaps "wait" not "make"?

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Reviewed up to pkg/cataloged. This is really neat! But as punishment for coaching things up, you get into arguments about really small things. So nothing here is horrible, and if they're are _any_ objections I'll relent.

Thanks!

File: clients/spark/core/src/test/resources/parser-test/sst_files_generator.go (hunk 1 above)
Comment (nopcoder) [reply clients/spark/core/src/test/resources/parser-test/sst_files_generator.go:68]: You are right, it started with my spelling linter and from there other linters started to pull me in.

File: cmd/lakectl/cmd/config/config.go (hunk 2 above)
Comment (nopcoder) [reply cmd/lakectl/cmd/config/config.go:61]: Reverting autofix

File: cmd/lakectl/cmd/fs.go (hunk 3 above)
Comment (nopcoder) [reply cmd/lakectl/cmd/fs.go:135]: Adding DieErr to capture error on close.

File: esti/s3_gateway_test.go (hunk 4 above)
Comment (nopcoder) [reply esti/s3_gateway_test.go:51]: Done, went with 'r'.

File: esti/system_test.go (hunk 5 above)
Comment (nopcoder) [reply esti/system_test.go:131]: Updated message and also checked the status code from the response

File: pkg/actions/kv_migrate_test.go (hunk 7 above)
Comment (nopcoder) [reply pkg/actions/kv_migrate_test.go:55]: True - I follow the docs, saying delete after use. Updated the code not to use files.

File: pkg/auth/service.go (hunk 9 above)
Comment (nopcoder) [reply pkg/auth/service.go:67]: Updated - let me know if it makes sense now.

File: pkg/batch/executor_test.go (hunk 10 above)
Comment (nopcoder) [reply pkg/batch/executor_test.go]: Update the comment to reflect the right behavior

File: esti/system_test.go (hunk 6 above)
Comment (nopcoder) [reply esti/system_test.go]: Added check and to fail the upload in case of an error.

File: pkg/catalog/diff.go [hunk 11]
```diff
@@ -18,7 +18,6 @@ type Difference struct {
 type DiffResultRecord struct {
 	TargetEntryNotInDirectBranch bool // the entry is reflected via lineage, NOT in the branch itself
 	Difference
-	EntryCtid *string // CTID of the modified/added entry. Do not use outside of catalog diff-by-iterators. https://github.com/treeverse/lakeFS/issues/831
```
Comment (arielshaqed) [inline pkg/catalog/diff.go:21]: # 🪄 😄 😸 

Best diff lines look like
```diff
-         ...Ctid...
```

File: pkg/config/config.go [hunk 12]
```diff
@@ -139,18 +138,17 @@ const (
 	AuthOIDCInitialGroupsClaimName = "auth.oidc.initial_groups_claim_name"
 	AuthLogoutRedirectURL          = "auth.logout_redirect_url"
 
-	BlockstoreTypeKey                    = "blockstore.type"
-	BlockstoreLocalPathKey               = "blockstore.local.path"
-	BlockstoreDefaultNamespacePrefixKey  = "blockstore.default_namespace_prefix"
```
Comment (arielshaqed) [inline pkg/config/config.go:144]: OT: Did we delete that?  Isn't this how we recommend a namespace prefix to users, for instance in the playground?

**Review by arielshaqed — APPROVED** [review]
THANKS!

File: pkg/config/config.go (hunk 12 above)
Comment (nopcoder) [reply pkg/config/config.go:144]: Didn't remove the feature - the const key values are usually used for settings defaults.
Didn't find the use of that constant - the default is empty.
