### PR TITLE
Fix: Gateway wrong error description for copy object

### LINKED ISSUE #7452: S3 Gateway: Wrong error message when try to use copy_object with size > 5GB
When trying to use boto's copy_object on a file > 5GB the returned error is:
```
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyObject operation: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```
Even though the underlying error message from S3 states:
```
api error InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source
```

This is because of error mapping in the gateway:
```golang
var Codes = errorCodeMap{
	ErrInvalidCopyDest: {
		Code:           "InvalidRequest",
		Description:    "This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.",
		HTTPStatusCode: http.StatusBadRequest,
	},
```

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #7452

Partial fix for the issue.
Fix error description for copy object errors in S3 GW

### CODE REVIEW

File: pkg/gateway/operations/deleteobject.go [hunk 1]
```diff
@@ -31,12 +31,12 @@ func (controller *DeleteObject) HandleAbortMultipartUpload(w http.ResponseWriter
 	mpu, err := o.MultipartTracker.Get(ctx, uploadID)
 	if err != nil {
 		o.Log(req).WithError(err).Error("upload id not found in tracker")
-		_ = o.EncodeError(w, req, err, gatewayerrors.Codes.ToAPIErr(gatewayerrors.ErrNoSuchKey))
+		_ = o.EncodeError(w, req, err, gatewayerrors.Codes.ToAPIErr(gatewayerrors.ErrNoSuchKey, nil))
```
Comment (itaiad200) [inline pkg/gateway/operations/deleteobject.go:34]: Any reason not to pass the actual error instead of nil to all of these calls?

File: pkg/gateway/errors/errors.go [hunk 2]
```diff
@@ -176,20 +176,24 @@ const (
 
 type errorCodeMap map[APIErrorCode]APIError
 
-func (e errorCodeMap) ToAPIErr(errCode APIErrorCode) APIError {
+func (e errorCodeMap) ToAPIErr(errCode APIErrorCode, err error) APIError {
```
Comment (itaiad200) [inline pkg/gateway/errors/errors.go:179]: Maybe add a function 
```
func (e errorCodeMap) ToAPIErrWithInternalError(errCode APIErrorCode, err error) APIError {
``` 
It could leverage the existing `ToAPIErr` func.
That way you won't have dozens of calls to `ToAPIErr` with `nil` as the err, although an actual error does exist. I also wonder what the next caller to this funciton would do, pass an `err` or `nil`?

File: esti/s3_gateway_test.go [hunk 3]
```diff
@@ -536,3 +536,58 @@ func TestS3PutObjectTagging(t *testing.T) {
...
 }
+
+func TestS3CopyObjectErrors(t *testing.T) {
+	ctx, _, repo := setupTest(t)
+	defer tearDownTest(repo)
+
+	// additional repository for copy between repos
+	const destRepoName = "tests3copyobjectdest"
+	//destRepo := createRepositoryByName(ctx, t, destRepoName)
+	//defer deleteRepositoryIfAskedTo(ctx, destRepoName)
```
Comment (itaiad200) [inline esti/s3_gateway_test.go:547]: Delete?

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Thanks for the fix and for adding a test! I suggest a minor refactor to avoid future confusion

File: pkg/gateway/operations/deleteobject.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/gateway/operations/deleteobject.go:34]: We decided to limit the scope of the current fix to the CopyObject API.
We need to consider a more holistic approach for the actual solution that might require a deeper fix

File: pkg/gateway/errors/errors.go (hunk 2 above)
Comment (N-o-Z) [reply pkg/gateway/errors/errors.go:179]: Done
