### PR TITLE
Fix: quickstart validation

### LINKED ISSUE #6400: [Bug]: Quickstart is broken in v0.106.0
### What happened?

1. Go to https://docs.lakefs.io/quickstart/launch.html
2. As instructed, run 
```
$ docker run --name lakefs --pull always \
             --rm --publish 8000:8000 \
             treeverse/lakefs:latest \
             run --quickstart
```

3. Fails:

```
latest: Pulling from treeverse/lakefs
Digest: sha256:c54ee0daaa98dd0e673de791551221c70616a3f733a7ada883bf93a75374bd8d
Status: Image is up to date for treeverse/lakefs:latest

WARNING!

Using quickstart parameters configuration. This is suitable only for testing! It is NOT SUPPORTED for production.
quickstart mode can only run with local settings

$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ 
```

😢 

### Expected behavior

Docker container should launch successfully

### lakeFS version

v0.106.0

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #6400

## Change Description

Bug fix - logical error in condition which checks the supported refstore and blockstore for quickstart mode

### Testing Details

Manual testing

### CODE REVIEW

File: cmd/lakefs/cmd/root.go [hunk 1]
```diff
@@ -49,15 +49,15 @@ func init() {
 }
 
 func validateQuickstartEnv(cfg *config.Config) {
-	if !((cfg.Database.Type == local.DriverName || cfg.Database.Type == mem.DriverName) && cfg.Blockstore.Type != block.BlockstoreTypeLocal) {
-		fmt.Printf("quickstart mode can only run with local settings\n")
+	if !((cfg.Database.Type == local.DriverName || cfg.Database.Type == mem.DriverName) && cfg.Blockstore.Type == block.BlockstoreTypeLocal) {
```
Comment (itaiad200) [inline cmd/lakefs/cmd/root.go:52]: I think this is simpler.
```suggestion
	if ((cfg.Database.Type != local.DriverName && cfg.Database.Type != mem.DriverName) || cfg.Blockstore.Type != block.BlockstoreTypeLocal) {
```

**Review by itaiad200 — APPROVED** [review]
Let's open a task to have an test for the quickstart logic - it's important .

**Comment by N-o-Z** [comment]
> Let's open a task to have an test for the quickstart logic - it's important .

There's a larger issue we need to tackle: "Test lakefs commands" 🥲

File: cmd/lakefs/cmd/root.go [hunk 2]
```diff
@@ -49,8 +49,8 @@ func init() {
 }
 
 func validateQuickstartEnv(cfg *config.Config) {
-	if ((cfg.Database.Type != local.DriverName && cfg.Database.Type != mem.DriverName) || cfg.Blockstore.Type != block.BlockstoreTypeLocal) {
-		fmt.Println("quickstart mode can only run with local settings")
+	if (cfg.Database.Type != local.DriverName && cfg.Database.Type != mem.DriverName) || cfg.Blockstore.Type != block.BlockstoreTypeLocal {
+		_, _ = fmt.Fprint(os.Stderr, "\nERROR: quickstart mode can only run with local settings\n")
```
Comment (rmoff) [inline cmd/lakefs/cmd/root.go:53]: Would `FATAL` be more accurate than `ERROR`?

**Review by rmoff — APPROVED** [review]

File: cmd/lakefs/cmd/root.go (hunk 2 above)
Comment (N-o-Z) [reply cmd/lakefs/cmd/root.go:53]: Sure

Comment (N-o-Z) [reply cmd/lakefs/cmd/root.go]: @rmoff  Is this what you meant in #6401? Can we close it?

Comment (rmoff) [reply cmd/lakefs/cmd/root.go]: thumbs-up-double-thumbs-up-gif

File: cmd/lakefs/cmd/root.go [hunk 3]
```diff
@@ -49,19 +49,17 @@ func init() {
...
+	if (cfg.Database.Type != local.DriverName && cfg.Database.Type != mem.DriverName) || cfg.Blockstore.Type != block.BlockstoreTypeLocal {
+		_, _ = fmt.Fprint(os.Stderr, "\nFATAL: quickstart mode can only run with local settings\n")
 		os.Exit(1)
 	}
 
 	if cfg.Installation.UserName != config.DefaultQuickstartUsername ||
 		cfg.Installation.AccessKeyID != config.DefaultQuickstartKeyID ||
 		cfg.Installation.SecretAccessKey != config.DefaultQuickstartSecretKey {
-		fmt.Printf("installation parameters must not be changed in quickstart mode\n")
+		fmt.Println("installation parameters must not be changed in quickstart mode")
```
Comment (rmoff) [inline cmd/lakefs/cmd/root.go:60]: To match the above: 

```suggestion
		_, _ = fmt.Fprint(os.Stderr, "\nFATAL: installation parameters must not be changed in quickstart mode\n")
```
