### PR TITLE
Actions control hook execution expression

### LINKED ISSUE #5652: Enhancement request: Notification on Failed Actions (Hooks)
In some cases, users would like to be notified of a failed Treeverse action. For example, if a data quality check failed as a part of a pre-merge hook, send an email. As opposed to writing specific code to send emails, it might be better to have generic notifications on failed actions.

### PR DESCRIPTION
**Pull request by nopcoder**
Added new 'if' property to action's hook.
The 'if' expression used to control if we execute the hook.
The default is `success()` which is evaluated to true when new previous step failed.
The func `failure()` can be used to query for previous hook that failed - good for cases we like to notify in case of an error.
Note that the value `true` or `false` can be used to control the execute of the step - and ignore the current action status.

Close #5652

### CODE REVIEW

File: pkg/actions/action.go
Comment (itaiad200) [inline pkg/actions/action.go:1]: Missing matching documentation

File: pkg/actions/service.go [hunk 1]
```diff
@@ -357,22 +372,47 @@ func (s *StoreService) runTasks(ctx context.Context, record graveler.HookRecord,
...
+func runHookIfEval(task *Task, actionErr error) (bool, error) {
+	result := actionErr == nil // by default, we run based on current status - success: no error
+	if task.If == "" {
+		return result, nil
+	}
+	env := map[string]any{
+		"success": func() bool { return actionErr == nil },
+		"failure": func() bool { return actionErr != nil },
+	}
+	output, err := expr.Eval(task.If, env)
```
Comment (itaiad200) [inline pkg/actions/service.go:406]: What limits `task.If`? How do protect from bad code execution?

**Review by itaiad200 — COMMENTED** [review]
Partial review

File: pkg/actions/service.go (hunk 1 above)
Comment (nopcoder) [reply pkg/actions/service.go:406]: The expression evaluation language definition is found here: https://expr.medv.io/docs/Language-Definition.
It is built to evaluate expression no functionality that communicate or have side effect outside the expression itself.

File: pkg/actions/action.go
Comment (nopcoder) [reply pkg/actions/action.go:1]: Wanted to agree on what we planning

File: docs/hooks/overview.md [hunk 2]
```diff
@@ -67,7 +67,9 @@ This allows configuration-as-code inside lakeFS, where Action files are declarat
 {: .no_toc }
 
 An **Action** is a list of Hooks with the same trigger configuration, i.e. an event will trigger all Hooks under an Action or none at all.
-The Hooks under an Action are ordered and so is their execution. A Hook will only be executed if all the previous Hooks that were triggered with it had passed.
+The Hooks under an Action are ordered and so is their execution.
+Before each hook execution the `if` boolean expression is evaluated. The expression can use `success()` which evaluate to true in case of no error was occured while running the hoook's actions. It can also use `failure()` which evaluate to true when previous step failed - can be used to report failures.
```
Comment (N-o-Z) [inline docs/hooks/overview.md:71]:
```suggestion
Before each hook execution the `if` boolean expression is evaluated. The expression can use `success()` which evaluate to true in case no error has occurred while running the hook's actions. It can also use `failure()` which evaluates to true if a previous step failed and can be used to report failures as well.
```

File: docs/hooks/overview.md [hunk 3]
```diff
@@ -67,7 +67,9 @@ This allows configuration-as-code inside lakeFS, where Action files are declarat
...
+By default, when `if` is empty or omitted, the step will run only if no error occurred (same as evaluate of success function).
```
[the remark this answers is not in the document]
Comment (nopcoder) [reply docs/hooks/overview.md:72]: very similar to GitHub actions. it evaluates to a check of the last error that is set once a hook fails. It is what we did so far, just broke the processing loop. now we continue to evaluate each step.

File: pkg/actions/service.go [hunk 4]
```diff
@@ -342,10 +347,20 @@ func (s *StoreService) runTasks(ctx context.Context, record graveler.HookRecord,
 					ActionName:       task.Action.Name,
 					HookID:           task.HookID,
 				}
-				buf := bytes.Buffer{}
-				task.StartTime = time.Now().UTC()
 
-				task.Err = task.Hook.Run(ctx, record, &buf)
+				ifHook, err := runHookIfEval(task, actionErr)
+				if err == nil && !ifHook {
```
Comment (N-o-Z) [inline pkg/actions/service.go:352]: I think this if and the next if else can be written simpler

File: pkg/actions/service.go [hunk 5]
```diff
@@ -31,8 +32,9 @@ const (
 )
 
 var (
-	ErrNotFound = errors.New("not found")
-	ErrNilValue = errors.New("nil value")
+	ErrNotFound      = errors.New("not found")
```
Comment (N-o-Z) [inline pkg/actions/service.go:35]: Do we need to control the new error types somewhere?

File: docs/hooks/overview.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (N-o-Z) [reply docs/hooks/overview.md:72]: Yes but how would you write the condition to continue in case of errors in practice? I think this might be confusing

[the remark this answers is not in the document]
Comment (nopcoder) [reply docs/hooks/overview.md:72]: Maybe I don't understand the question. But in practice you write `if: success()` or nothing in case you like the step to execute if everything green until that point.
In case you like to run always `if: true`.
In case you like to run if something failed `if: failure()`.

**Comment by nopcoder** [comment]
> Thanks @nopcoder, great addition. One question though - why do we need both failure and success? Isn't one just the negation of the other?

We don't need both - one is the negative of the other. Wanted a way to describe each state like GitHub, which is more readable.

File: pkg/actions/service.go (hunk 5 above)
Comment (nopcoder) [reply pkg/actions/service.go:35]: What do you mean in control? the errors will be reflected like other errors that each action may fail with.

Comment (N-o-Z) [reply pkg/actions/service.go:35]: Talked f2f. Errors in actions are just written to the event

**Comment by nopcoder** [comment]
> Thanks for addressing the comments

Thank you!
