### PR TITLE
Change branch locker logic - remove try locks

### LINKED ISSUE #1466: branch locker test fails: "should not acquire writer while committer is waiting"
"It failed on my machine".  Once.  Uggh.

```
--- FAIL: TestBranchLock (0.94s)
    --- FAIL: TestBranchLock/committer_wait_for_writers (0.00s)
        branch_locker_test.go:158: Should not acquire writer while committer is waiting, err=<nil>
FAIL
coverage: 16.6% of statements
FAIL	github.com/treeverse/lakefs/graveler/ref	6.068s
```

### PR DESCRIPTION
**Pull request by guy-har**
closes #1466

### CODE REVIEW

File: graveler/ref/branch_locker.go [hunk 1]
```diff
@@ -21,54 +23,37 @@ func NewBranchLocker(db db.Database) *BranchLocker {
...
+		_, err := tx.Exec(`SELECT pg_advisory_xact_lock($1);`, writerLockKey)
 		if err != nil {
 			return nil, fmt.Errorf("%w (%d): %s", graveler.ErrLockNotAcquired, writerLockKey, err)
 		}
 		return lockedFn()
 	}, db.WithIsolationLevel(pgx.ReadCommitted))
 }
 
-func calculateBranchLockerKeys(repositoryID graveler.RepositoryID, branchID graveler.BranchID) (writerLockKey int64, committerLockKey int64) {
+func calculateBranchLockerKeys(repositoryID graveler.RepositoryID, branchID graveler.BranchID) int64 {
```
Comment (nopcoder) [inline graveler/ref/branch_locker.go:52]:
```suggestion
func calculateBranchLockerKey(repositoryID graveler.RepositoryID, branchID graveler.BranchID) int64 {
```

**Review by nopcoder — APPROVED** [review]
LGTM - just a small comment about func name

File: graveler/ref/branch_locker.go (hunk 1 above)
Comment (guy-har) [reply graveler/ref/branch_locker.go]: Done
Thanks
