### PR TITLE
Use heap.Push not [slice].Push to initialize a Heap

### LINKED ISSUE #9748: "graveler/ref".CommitIterator can give incorrect results
(... and possibly waste memory).

It has a queue.  But the Golang "containers"/heap Interface confusingly requires a "Push" _method_... while code should use heap.Push.  This can cause incorrect ordering in some cases.  It _might_ also waste a significant amount of memory, as some parents might not be removed on time.

Suspect code is [here](https://github.com/treeverse/lakeFS/blob/6d738635778e706fcacc29039d019b05ee01956c/pkg/graveler/ref/commit_iterator.go#L113-L116):
```go
		// skip commits that are older than since time
		if ci.since == nil || !rec.CreationDate.Before(*ci.since) {
			ci.queue.Push(rec)
		}
	}
```

### PR DESCRIPTION
**Pull request by arielshaqed**
Fixes #9748.

As a bonus, add a commit_iterator_test!  In fact only _one_ line is the fix, the other 100+ are to add that test.

This commit _also_ shows that no breakage was possible even before this change!  Indeed, the mistaken call to Push() occurs during initialization, and the heap is empty.  On an _empty_ heap, appending to the slice is _exactly_ the same as Pushing onto the heap.

Still, new code does not break the heap abstraction.

### CODE REVIEW

File: pkg/graveler/ref/commit_iterator.go [hunk 1]
```diff
@@ -63,25 +63,25 @@ func (c *commitsPriorityQueue) Pop() interface{} {
...
 type CommitIteratorConfig struct {
-	repository  *graveler.RepositoryRecord
-	start       graveler.CommitID
-	firstParent bool
-	manager     graveler.RefManager
-	since       *time.Time
+	Repository  *graveler.RepositoryRecord
+	Start       graveler.CommitID
+	FirstParent bool
+	Manager     CommitGetter
```
Comment (nopcoder) [inline pkg/graveler/ref/commit_iterator.go]: Can we name the member also CommitGetter

Comment (arielshaqed) [reply pkg/graveler/ref/commit_iterator.go]: Done!  To avoid repeating words, and because of the nice small scope, I renamed it "Getter".
