### PR TITLE
fix error on conflict

### LINKED ISSUE #1217: [rocks] "internal error" when merging a branch with conflicts
Should fail with a _good_ error message.

```
   # set up conflicting file contents
ariels@redqueen:~/dev/lakeFS$ echo 99 | AWS_PROFILE=lake aws --endpoint-url=http://s3.local.lakefs.io:8000  s3 cp - s3://foo/trunk/run1/a
ariels@redqueen:~/dev/lakeFS$ echo brfrr | AWS_PROFILE=lake aws --endpoint-url=http://s3.local.lakefs.io:8000  s3 cp - s3://foo/branch/run1/a
ariels@redqueen:~/dev/lakeFS$ ./lakectl commit lakefs://foo@branch --message branchme
ariels@redqueen:~/dev/lakeFS$ ./lakectl commit lakefs://foo@trunk --message trunkit

   # try to merge
ariels@redqueen:~/dev/lakeFS$ ./lakectl merge lakefs://foo@{branch,trunk}
Error executing command: internal error
```

### PR DESCRIPTION
**Pull request by johnnyaug**
Closes #1217

### CODE REVIEW

File: catalog/rocks/cataloger.go [hunk 1]
```diff
@@ -552,6 +552,12 @@ func (c *cataloger) Merge(ctx context.Context, repository string, leftBranch str
 	rightBranchID := graveler.BranchID(rightBranch)
 	meta := graveler.Metadata(metadata)
 	commitID, err := c.EntryCatalog.Merge(ctx, repositoryID, leftRef, rightBranchID, committer, message, meta)
+	if errors.Is(err, graveler.ErrConflictFound) {
+		// for compatibility with old cataloger
+		return &catalog.MergeResult{
+			Summary: map[catalog.DifferenceType]int{catalog.DifferenceTypeConflict: 1},
```
Comment (arielshaqed) [inline catalog/rocks/cataloger.go:558]: Shouldn't `MergeResult` hold a _summary_ of the merge?  Shouldn't this be the count of what happened during the merge?

**Review by arielshaqed — CHANGES_REQUESTED** [review]

File: catalog/rocks/cataloger.go (hunk 1 above)
Comment (johnnyaug) [reply catalog/rocks/cataloger.go:558]: Yes, we didn't implement this yet. So in case of a successful merge, the summary would be empty. It's an issue, but no a release-blocker (IMO). Will open an issue for that
In case of conflict, the MVCC would return a summary of {Conflict:1}, regardless of the number of conflicts. This PR aligns with this behavior.

Comment (arielshaqed) [reply catalog/rocks/cataloger.go:558]: Cool, thanks!

**Review by arielshaqed — APPROVED** [review]
Thanks for explaining!  If not a degradation, then presumably nobody's *really* dependent upon this.

However please _do_ open a bug.

Thanks!
