### PR TITLE
Fix: Git package error handling

### LINKED ISSUE #8086: lakectl local init on a branch used for the same purpose with another user fails with git error
### What happened?

One user ran lakectl local init on a lakeFS branch and completed successfully. Output:
lakectl local init \<lakefs URL\> \<local dir\>
Successfully linked local directory '\<mount path\>/users/\<user\>/\<local path\>' with remote '\<lakefs URL\>

A 2nd user is trying to run the same and runs into this error:
lakectl local init \<same lakefs URL\> \<2nd local dir\>
**fatal: Not a git repository** (or any parent up to mount point  \<same mount path as above\> )
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
: exit status 128
Error executing command. 

Additional information - running on RHEL7, original user directory does not contain a .git file.

### Expected behavior

lakectl local init should not depend on previous mount path from a different user

### lakeFS version

1.31.0

### How lakeFS is installed

Cloud

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

offir.cohen@treeverse.io

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #8086

### Background

Parsing git shell commands response to classify into comprehensible errors, seems like some FS return different strings for the same errors.

### Bug Fix

The bug resulted from difference in output when not a git repository

The fix was to lowercase the out put before comparison

### Testing Details

Added unit test

### Breaking Change?

No

### CODE REVIEW

File: pkg/git/internal/shared.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+	lowerOut := strings.ToLower(out)
+	switch {
+	case err == nil:
+		return strings.TrimSpace(out), nil
+	case strings.Contains(lowerOut, "not a git repository"):
+		return "", errors.ErrNotARepository
+	case strings.Contains(lowerOut, "remote not found"):
+		return "", errors.ErrRemoteNotFound
+	default:
+		return "", fmt.Errorf("%s: %w", out, err)
```
Comment (arielshaqed) [inline pkg/git/internal/shared.go:20]: Odd: This error has a different format, it includes `out`.

**Review by arielshaqed — APPROVED** [review]
This is of course cool, but also unpleasant.  E.g. this code still breaks because
```sh
❯ LANGUAGE=sv   git status
På grenen docs/getting-started-on-the-project
inget att checka in, arbetskatalogen ren
```
will happen in some places in Northern Europe.

Perhaps open an issue to discover a proper way to run Git plumbing?

File: pkg/git/internal/shared.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/git/internal/shared.go:20]: This is the only place where the output has any relevance

**Comment by N-o-Z** [comment]
> This is of course cool, but also unpleasant. E.g. this code still breaks because
> 
> ```shell
> ❯ LANGUAGE=sv   git status
> På grenen docs/getting-started-on-the-project
> inget att checka in, arbetskatalogen ren
> ```
> 
> will happen in some places in Northern Europe.
> 
> Perhaps open an issue to discover a proper way to run Git plumbing?

Opened https://github.com/treeverse/lakeFS/issues/8348
