### PR TITLE
5522 remove stack trace from UI

### LINKED ISSUE #5522: Remove stack trace from error messages
HTTP request fetch errors are displayed in the UI with a full stack trace. This is unhelpful because the code is minified and makes the actual error message less readable.

### PR DESCRIPTION
**Pull request by eladlachmi**
Resolves #5522

### CODE REVIEW

File: webui/src/lib/components/controls.jsx [hunk 1]
```diff
@@ -85,7 +85,7 @@ export const Error = ({error, onDismiss = null, className = null}) => {
         return <Alert className={className} variant="danger" dismissible onClose={onDismiss}>{content}</Alert>;
     }
     if (err.stack) {
-        content = `${content}: ${err.stack}`
+        content = `${content}`
     }
```
Comment (guy-har) [inline webui/src/lib/components/controls.jsx:89]: This block is redundant now, you can remove it

**Review by guy-har — APPROVED** [review]

File: webui/src/lib/components/controls.jsx (hunk 1 above)
Comment (eladlachmi) [reply webui/src/lib/components/controls.jsx]: Right! 🤦🏻‍♂️
Fixed.
