### PR TITLE
Fix: Copy object mtime

### LINKED ISSUE #8290: BUG: CopyObject: modified time updated before actual blockstore copy
Performing the mtime update before performing the actual copy on the blockstore could potentially cause a substantial gap between underlying storage object mtime and lakeFS mtime.
This could cause issues in flows using functionality such as `IfUnmodifiedSince`

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #8290

### CODE REVIEW

File: pkg/catalog/catalog.go [hunk 1]
```diff
@@ -2741,6 +2740,9 @@ func (c *Catalog) CopyEntry(ctx context.Context, srcRepository, srcRef, srcPath,
 		return nil, err
 	}
 
+	// Update creation date only after actual copy!!!
```
Comment (yonipeleg33) [inline pkg/catalog/catalog.go:2743]:
```suggestion
	// Update creation date only after actual copy to prevent potential discrepancy between lakefs and the underlying blockstore mtimes
```

File: pkg/catalog/catalog.go [hunk 2]
```diff
@@ -2741,6 +2740,9 @@ func (c *Catalog) CopyEntry(ctx context.Context, srcRepository, srcRef, srcPath,
...
+	dstEntry.CreationDate = time.Now()
```
Comment (yonipeleg33) [inline pkg/catalog/catalog.go:2744]: I wonder - shouldn't we use the blockstore's mtime instead of `time.Now`? Is this even possible?

**Review by yonipeleg33 — COMMENTED** [review]
Thanks!
Not approving, but I do not wish to block this PR either.
Also, please change the title to "Fix: change object mtime after blockstore copy" or something a bit more indicative

File: pkg/catalog/catalog.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/catalog/catalog.go:2743]: This comment is incorrect, it does not prevent any discrepancy

File: pkg/catalog/catalog.go (hunk 2 above)
Comment (N-o-Z) [reply pkg/catalog/catalog.go:2744]: Out of scope for this fix. Your suggestion is a valid question which has implications that we are currently  evaluating since it requires another call to the underlying storage

File: pkg/catalog/catalog.go (hunk 1 above)
Comment (yonipeleg33) [reply pkg/catalog/catalog.go:2743]: Huh, this is kind of what I understood from reading the issue description. Maybe "prevent" isn't accurate, as this fix aims to minimise the time difference rather than making it equal, but maybe I got it all wrong 😄
In any case, my point is to add a _why_ for this comment, not only _what_.

**Comment by N-o-Z** [comment]
> Approving with couple of suggestions:
> 
> * Include `CompletePresignMultipartUpload` & `StageObject` similar fixes in this PR (or at the very least open an issue for the same phenomena)
> * If there's some easy way to test it I'd add that timestamp validation there. We know it causes bug for users, so it's best to try and prevent regressions.

@itaiad200 StageObject is irrelevant since no writes to the storage are being performed. Modified the code in `CompletePresignMultipartUpload` though in reality it's not an issue.
Added tests

**Comment by N-o-Z** [comment]
Gave up on adding tests - too complicated and does not justify the overhead. Tested manually
