### PR TITLE
Pass context to async tasks to keep context fields intact

### LINKED ISSUE #8319: [Bug]: Importing fails if a pre commit hook is defined
### What happened?

If a pre commit hook is defined, import operations will fail.
        
Steps to Reproduce:
1. Define a pre commit hook
2. Import data

### Root cause

Import uses multiple async Go routines to import the data. Those Go routines start their own contexts, thus dropping the middleware-initialized contexts with a username field in them. This results in a `user not found` error when the import operation tries to commit (and the pre commit hook validates the user that ran the import).

### Expected behavior

_No response_

### lakeFS version

1.39.2

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by Jonathan-Rosenberg**
Closes #8319 

Details in the issue

### CODE REVIEW

File: pkg/catalog/catalog.go [hunk 1]
```diff
@@ -2296,8 +2296,8 @@ func (c *Catalog) GetRange(ctx context.Context, repositoryID, rangeID string) (g
 	return c.Store.GetRange(ctx, repository, graveler.RangeID(rangeID))
 }
 
-func (c *Catalog) importAsync(repository *graveler.RepositoryRecord, branchID, importID string, params ImportRequest, logger logging.Logger) error {
-	ctx, cancel := context.WithCancel(context.Background()) // Need a new context for the async operations
+func (c *Catalog) importAsync(ctx context.Context, repository *graveler.RepositoryRecord, branchID, importID string, params ImportRequest, logger logging.Logger) error {
+	ctx, cancel := context.WithCancel(ctx) // Need a new context for the async operations
```
Comment (N-o-Z) [inline pkg/catalog/catalog.go:2300]: Remove comment

**Review by N-o-Z — APPROVED** [review]
LGTM!
One comment

File: pkg/catalog/catalog.go (hunk 1 above)
Comment (Jonathan-Rosenberg) [reply pkg/catalog/catalog.go]: done
