### PR TITLE
Fix S3 bucket validation for inter-region storage

### LINKED ISSUE #7846: Don't allow repositories with storage region different than the block storage region
The lakeFS API should disable by default the option to create a repository in a cloud region different than the region in which the block storage resides in.

Allowing it should be a server configuration option.

### PR DESCRIPTION
**Pull request by itaigilo**
Closes #7846 

## Change Description

For the validation of inter-region storage (if it's not allowed):
When getting storage namespace region from S3, the code was trying to get the region (from the S3 API) for the whole namespace (for example, `bucket-name/path-1/`), instead of using only the bucket name (i.e `bucket-name`).

This fix is about getting the region only for the bucket name (which the S3 API can handle).

### Testing Details

Tested this manually on a local server (configured with S3 of course).

### CODE REVIEW

File: pkg/block/s3/adapter.go [hunk 1]
```diff
@@ -870,11 +870,13 @@ func (a *Adapter) ResolveNamespace(storageNamespace, key string, identifierType
 }
 
 func (a *Adapter) GetRegion(ctx context.Context, storageNamespace string) (string, error) {
-	bucket, found := strings.CutPrefix(storageNamespace, fmt.Sprintf("%s://", block.BlockstoreTypeS3))
+	namespace, found := strings.CutPrefix(storageNamespace, fmt.Sprintf("%s://", block.BlockstoreTypeS3))
```
Comment (arielshaqed) [inline pkg/block/s3/adapter.go:873]: This seems somewhat fragile.  Proposal: I think you can use "net/url".Parse and then the bucket _is_ the Host field of the URL.  [Here's an example](https://go.dev/play/p/TKGisHOpbxL) of how this can work.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Thanks!

I believe that we should avoid writing code to parse URLs as far as possible.  Here I think we can just use a parser from the standard library.

**Review by N-o-Z — COMMENTED** [review]
This is nor a bucket or a namespace.
This is most likely a path in a bucket (e.g. <my-bucket>/<path>/<to>/<repo>/<namespace>
So both terms are innaccurate

File: pkg/block/s3/adapter.go [hunk 2]
```diff
@@ -870,12 +870,12 @@ func (a *Adapter) ResolveNamespace(storageNamespace, key string, identifierType
 }
 
 func (a *Adapter) GetRegion(ctx context.Context, storageNamespace string) (string, error) {
-	bucket, found := strings.CutPrefix(storageNamespace, fmt.Sprintf("%s://", block.BlockstoreTypeS3))
-	if !found {
-		return "", fmt.Errorf(`%w: "s3://" prefix not found %s`, block.ErrInvalidNamespace, storageNamespace)
+	namespaceUrl, err := url.Parse(storageNamespace)
+	if err != nil {
+		return "", fmt.Errorf(`%w: %s isn't a valid url'`, block.ErrInvalidNamespace, storageNamespace)
```
Comment (N-o-Z) [inline pkg/block/s3/adapter.go:875]: The current convention for err messages
```suggestion
		return "", fmt.Errorf(`%s isn't a valid url': %w`, storageNamespace, block.ErrInvalidNamespace)
```

**Review by N-o-Z — APPROVED** [review]
Approved with one comment

**Review by arielshaqed — APPROVED** [review]
Thanks!
