### PR TITLE
fixed yet another slice pointer bug with iterator keys

### LINKED ISSUE #1263: rocks: merge operation doesn't apply all changes
diffing two branches (say A and B), then merging B into A, results in most of the changes on B being applied to A, except for a single one. Doing a diff does show that there's a single object in B not in A. This is also consistent with listing the objects at both A and B (B showing 1 object that A doesn't have).

I can give access to an environment where this reproduces in DM

### PR DESCRIPTION
**Pull request by ozkatz**
closes #1263

### CODE REVIEW

File: graveler/committed/unmarshal_iterator.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func (r *UnmarshalIterator) Next() bool {
 		}
 	}
 	r.value = &graveler.ValueRecord{
-		Key:   graveler.Key(val.Key),
+		Key:   graveler.Key(val.Key.Copy()),
```
Comment (arielshaqed) [inline graveler/committed/unmarshal_iterator.go:37]: This is something of an opportunity to get some benefit from what little type safety Go gives: if we wrote this as a function that copies and converts, it would be easier and lazier to do the right thing.

**Review by arielshaqed — APPROVED** [review]
If it works, what's not to like? Pull like the wind! 
That said, I'd like some tools to help human programmers avoid this and similar errors.
