### PR TITLE
Correct clean existing cache files during startup

### LINKED ISSUE #1183: Pyramid | removing file fails
I am getting the following error when running lakeFS:

```
ERRO[0034] Removing file failed                          error="remove /tmp/experiment/ranges/tmp/experiment/ranges/repo/test/ba87edb6b02b7213af0f5fd928459d3b59ecf932d75b27d1280502e5c37a0349: no such file or directory" path=/tmp/experiment/ranges/tmp/experiment/ranges/repo/test/ba87edb6b02b7213af0f5fd928459d3b59ecf932d75b27d1280502e5c37a0349
```

### PR DESCRIPTION
**Pull request by arielshaqed**
Also improve warnings on immediate rejection from cache.

Fixes #1183.

### CODE REVIEW

File: pyramid/tier_fs.go [hunk 1]
```diff
@@ -59,30 +59,31 @@ func NewFS(c *params.InstanceParams) (FS, error) {
...
+		c.Eviction, err = newRistrettoEviction(c.AllocatedBytes(), tfs.removeFromLocal)
 		if err != nil {
 			return nil, fmt.Errorf("creating eviction control: %w", err)
 		}
 	}
 
-	tierFS.eviction = c.Eviction
-	if err := handleExistingFiles(tierFS.eviction, fsLocalBaseDir); err != nil {
+	tfs.eviction = c.Eviction
+	if err := tfs.handleExistingFiles(tfs.eviction); err != nil {
```
Comment (itaiad200) [inline pyramid/tier_fs.go:69]: Why do you pass the eviction if you already set it in the tierFS instance?

File: pyramid/tier_fs.go [hunk 2]
```diff
@@ -240,13 +239,15 @@ func (tfs *TierFS) openFile(fileRef localFileRef, fh *os.File) (*ROFile, error)
...
 	if !tfs.eviction.Store(fileRef.fsRelativePath, stat.Size()) {
-		// This is where we get less strict.
-		// Ideally, newly fetched file will never be rejected by the cache.
-		// But if it did, we prefer to serve the file and delete it.
-		// When the user will close the file, the file will be deleted from the disk too.
-		if err := os.Remove(fileRef.fullPath); err != nil {
-			return nil, err
-		}
+		// Ideally, the cache will accept this newly fetched file.  If it was still
+		// rejected, the rejection callback has already been called and has deleted
```
Comment (itaiad200) [inline pyramid/tier_fs.go:243]: > the rejection callback has already been called

Are you sure about that?

File: pyramid/tier_fs.go [hunk 3]
```diff
@@ -363,13 +353,24 @@ type localFileRef struct {
...
 }
 
+func (tfs *TierFS) storeLocalFile(rPath params.RelativePath, size int64, eviction params.Eviction) {
+	if !eviction.Store(rPath, size) {
+		// Rejected from cache, so deleted.  This is safe, but can only happen when
+		// the cache size was lowered -- so warn.
+		tfs.logger.WithFields(logging.Fields{
+			"path": rPath,
+			"size": size,
+		}).Warn("existing file immediately rejected from cache on startup (safe if cache size changed; continue)")
```
Comment (itaiad200) [inline pyramid/tier_fs.go:363]: This is the most common case where this could happen, but I'm not sure it's the only one.
For instance, if there were multiple deletions taking place while the system crashed.

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Minor comments, requesting changes to make sure I get it.

**Review by arielshaqed — COMMENTED** [review]
Thanks!

PTAL...

**Review by itaiad200 — APPROVED** [review]
LGTM!
