### PR TITLE
8422 list multipart uploads

### LINKED ISSUE #8422: [Bug]: LakeFS does not support the S3 `ListMultipartUploads` API
### What happened?

I'm trying to use Apache NiFi together with LakeFS backed by S3 storage on Minio. To write to LakeFS, I have configured the standard PutS3 Processor and I can write objects to LakeFS. But I also get an error on the PutS3 processor in NiFI, which is a bit "distracting" and misleading.

I am currently in the **process of developing and contributing LakeFS support for Apache NiFi**, so it would be great to have the`ListMultipartUploads` API supported. 

Here the Stack trace in Apache NiFi

```
nifi2-1  | 2024-12-13 15:05:36,096 ERROR [Timer-Driven Process Thread-1] o.a.nifi.processors.aws.s3.PutS3Object PutS3Object[id=fb0d70a0-ec72-3e07-0f5c-e92027c09cff] Error checking S3 Multipart Upload list for demo
nifi2-1  | com.amazonaws.services.s3.model.AmazonS3Exception: This operation is not supported in LakeFS (Service: Amazon S3; Status Code: 405; Error Code: ERRLakeFSNotSupported; Request ID: 7e99337b-03f6-4d36-ad8e-04e5953d4d68; S3 Extended Request ID: F3D5600CFAEC9006; Proxy: null)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1912)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1450)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1419)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1183)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:838)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:805)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:779)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:735)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:717)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:581)
nifi2-1  | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
nifi2-1  | 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5590)
nifi2-1  | 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5537)
nifi2-1  | 	at com.amazonaws.services.s3.AmazonS3Client.listMultipartUploads(AmazonS3Client.java:3873)
nifi2-1  | 	at org.apache.nifi.processors.aws.s3.PutS3Object.getS3AgeoffListAndAgeoffLocalState(PutS3Object.java:889)
nifi2-1  | 	at org.apache.nifi.processors.aws.s3.PutS3Object.ageoffS3Uploads(PutS3Object.java:873)
nifi2-1  | 	at org.apache.nifi.processors.aws.s3.PutS3Object.onTrigger(PutS3Object.java:519)
nifi2-1  | 	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
nifi2-1  | 	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1274)
nifi2-1  | 	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:244)
nifi2-1  | 	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:102)
nifi2-1  | 	at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
nifi2-1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
nifi2-1  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
nifi2-1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
nifi2-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
nifi2-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
nifi2-1  | 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

It is caused when Nifi invokes the AmazonS3Client.listMultipartUploads() method. After doing some additional tests, I realized that `ListParts` (which you support) is a different API than `ListMultipartUploads`.

Below the documentation of the tests I have done and some python code to reproduce the error:

-----
# Problem with `ListMultipartUploads`

LakeFS does not implement the [ListMultipartUploads](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListMultipartUploads.html) API but "only" the [ListParts](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html) API.

## Against LakeFS with AWS S3 backend

My lakefs setup is exposed on port `28220`.

```bash
guido.schmutz@AMAXDKFVW0HYY ~/w/platys-test> aws s3api --endpoint-url http://192.168.1.129:28220 list-parts --bucket demo --key main/mpu --upload-id SkGl58QIBUa.R0lvR3dbiUrmEDaGfCMhA9lxmgz.sXUhArNBKdtyryHsFE12erxy1oLWH4zGCp65QC_KHYvzzh4D08MS1Xuz_hugPHgnQZjmD6CJWo6UqphAcz6ha13K
{
    "Parts": [
        {
            "PartNumber": 1,
            "LastModified": "2024-12-14T07:59:08+00:00",
            "ETag": "d3b07384d113edec49eaa6238ad5ff00",
            "Size": 4
        }
    ],
    "ChecksumAlgorithm": null,
    "Initiator": null,
    "Owner": null,
    "StorageClass": null
}
```

```bash
guido.schmutz@AMAXDKFVW0HYY ~/w/platys-test> echo foo > temp_body.txt
guido.schmutz@AMAXDKFVW0HYY ~/w/platys-test> aws s3api --endpoint-url http://192.168.1.129:28220 upload-part --bucket demo --key main/mpu --upload-id SkGl58QIBUa.R0lvR3dbiUrmEDaGfCMhA9lxmgz.sXUhArNBKdtyryHsFE12erxy1oLWH4zGCp65QC_KHYvzzh4D08MS1Xuz_hugPHgnQZjmD6CJWo6UqphAcz6ha13K --part-number 1 --body temp_body.txt
{
    "ServerSideEncryption": "AES256",
    "ETag": "\"d3b07384d113edec49eaa6238ad5ff00\""
}
```

```bash
aws s3api --endpoint-url http://192.168.1.129:28220 list-parts --bucket demo --key main/mpu --upload-id SkGl58QIBUa.R0lvR3dbiUrmEDaGfCMhA9lxmgz.sXUhArNBKdtyryHsFE12erxy1oLWH4zGCp65QC_KHYvzzh4D08MS1Xuz_hugPHgnQZjmD6CJWo6UqphAcz6ha13K
{
    "Parts": [
        {
            "PartNumber": 1,
            "LastModified": "2024-12-14T07:59:08+00:00",
            "ETag": "d3b07384d113edec49eaa6238ad5ff00",
            "Size": 4
        }
    ],
    "ChecksumAlgorithm": null,
    "Initiator": null,
    "Owner": null,
    "StorageClass": null
```    

This is using the [ListParts](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html) API.

## Against LakeFS with AWS S3 backend

```bash
guido.schmutz@AMAXDKFVW0HYY ~/w/platys-test [254]> aws s3api create-multipart-upload --bucket gschmutz-lakefs --key main/mpu
{
    "ServerSideEncryption": "AES256",
    "Bucket": "gschmutz-lakefs",
    "Key": "main/mpu",
    "UploadId": "jDemmVS6ehIHetSwp.64YMXF_55gUsWTdHlqgrlynFcJgSjFsIpRAAsoZX61cCjGW8WvtekeTJU989M7mU6o7Rhu9hLrCd6IskH0kkI914olV4guT5escT4NaC9NBnOw"
}
```   

```bash
guido.schmutz@AMAXDKFVW0HYY ~/w/platys-test> aws s3api upload-part --bucket gschmutz-lakefs  --key main/mpu --upload-id jDemmVS6ehIHetSwp.64YMXF_55gUsWTdHlqgrlynFcJgSjFsIpRAAsoZX61cCjGW8WvtekeTJU989M7mU6o7Rhu9hLrCd6IskH0kkI914olV4guT5escT4NaC9NBnOw --part-number 1 --body temp_body.txt
{
    "ServerSideEncryption": "AES256",
    "ETag": "\"d3b07384d113edec49eaa6238ad5ff00\""
}
```

```bash
guido.schmutz@AMAXDKFVW0HYY ~/w/platys-test> aws s3api list-parts --bucket gschmutz-lakefs  --key main/mpu --upload-id jDemmVS6ehIHetSwp.64YMXF_55gUsWTdHlqgrlynFcJgSjFsIpRAAsoZX61cCjGW8WvtekeTJU989M7mU6o7Rhu9hLrCd6IskH0kkI914olV4guT5escT4NaC9NBnOw
{
    "Parts": [
        {
            "PartNumber": 1,
            "LastModified": "2024-12-14T08:06:19+00:00",
            "ETag": "\"d3b07384d113edec49eaa6238ad5ff00\"",
            "Size": 4
        }
    ],
    "ChecksumAlgorithm": null,
    "Initiator": {
        "ID": "arn:aws:iam::663559919114:user/s3user",
        "DisplayName": "s3user"
    },
    "Owner": {
        "ID": "c484141daec5bf65c3e44cd50a2dfe98b3f7982ca41bcffb402e4077e90cdf2a"
    },
    "StorageClass": "STANDARD"
}
```

## Testing the `list_multiparts_uploads` against LakeFS with AWS S3 backend

```
pip install boto3
```

```python
import boto3

# Create an S3 client
s3_client = boto3.client('s3', endpoint_url='http://192.168.1.129:28220')  # Use endpoint_url for custom S3-like services like MinIO

# Bucket name
bucket_name = 'demo'

try:
    # Call list_multipart_uploads
    response = s3_client.list_multipart_uploads(Bucket=bucket_name)

    # Print the uploads
    if 'Uploads' in response:
        print(f"Multipart uploads in bucket '{bucket_name}':")
        for upload in response['Uploads']:
            print(f"Key: {upload['Key']}, Upload ID: {upload['UploadId']}")
    else:
        print(f"No multipart uploads found in bucket '{bucket_name}'.")

except Exception as e:
    print(f"Error listing multipart uploads: {e}")
```

Running it in Jupyter produces the error

```
Error listing multipart uploads: An error occurred (ERRLakeFSNotSupported) when calling the ListMultipartUploads operation: This operation is not supported in LakeFS
```

## Testing the `list_multiparts_uploads` against AWS S3 backend

```
pip install boto3
```

```python
import boto3

# Create an S3 client
import boto3

# Create an S3 client
s3_client = boto3.client('s3')  # Use endpoint_url for custom S3-like services like MinIO

# Bucket name
bucket_name = 'gschmutz-lakefs'

try:
    # Call list_multipart_uploads
    response = s3_client.list_multipart_uploads(Bucket=bucket_name)

    # Print the uploads
    if 'Uploads' in response:
        print(f"Multipart uploads in bucket '{bucket_name}':")
        for upload in response['Uploads']:
            print(f"Key: {upload['Key']}, Upload ID: {upload['UploadId']}")
    else:
        print(f"No multipart uploads found in bucket '{bucket_name}'.")

except Exception as e:
    print(f"Error listing multipart uploads: {e}")
```

Running it in Jupyter produces the follwoing result

```
Multipart uploads in bucket 'gschmutz-lakefs':
Key: lakefs/data/gbosm0m84jhc72i1jlk0/ctejj8u84jhc72i1jll0, Upload ID: SkGl58QIBUa.R0lvR3dbiUrmEDaGfCMhA9lxmgz.sXUhArNBKdtyryHsFE12erxy1oLWH4zGCp65QC_KHYvzzh4D08MS1Xuz_hugPHgnQZjmD6CJWo6UqphAcz6ha13K
Key: main/mpu, Upload ID: jDemmVS6ehIHetSwp.64YMXF_55gUsWTdHlqgrlynFcJgSjFsIpRAAsoZX61cCjGW8WvtekeTJU989M7mU6o7Rhu9hLrCd6IskH0kkI914olV4guT5escT4NaC9NBnOw
```

We can see that both multi-part uploads created in the 2 tests (once against LakeFS and once directly against S3) above are returned.

### Expected behavior

That the `ListMultipartUploads` API is invoked in S3 by LakeFS and the in-progress multipart uploads in a bucket or returned to the caller.

### lakeFS version

1.44.0

### How lakeFS is installed

Docker Compose with LakeFS running against AWS S3 storage backend

### Affected clients

n.a.

### Relevant log output

_No response_

### Contact details

schmutz68@gmail.com

### PR DESCRIPTION
**Pull request by ItamarYuran**
Closes #8422

Introducing List Multiupart uploads command to the s3 gateway.

example command:
 ✗ aws s3api --endpoint-url=http://127.0.0.1:8000/ list-multipart-uploads  --bucket itamar  --profile default

This will return all multipart uploads (upload id and path) that are held by the tracker.

### CODE REVIEW

**Comment by idanovo** [comment]
@ItamarYuran Can you please make sure the CI passes first? 🙏

File: pkg/block/s3/adapter.go [hunk 1]
```diff
@@ -849,6 +849,38 @@ func (a *Adapter) ListParts(ctx context.Context, obj block.ObjectPointer, upload
...
+	resp, err := client.ListMultipartUploads(ctx, input)
+	if err != nil {
+		lg.WithError(err).Error("ListParts multipart uploads failed")
+		return nil, err
+	}
+
+	mpuResp := block.ListMultipartUploadsResponse{
+		Uploads: []types.MultipartUpload{},
+	}
+	mpuResp.Uploads = append(mpuResp.Uploads, resp.Uploads...)
```
Comment (nopcoder) [inline pkg/block/s3/adapter.go:880]: no need to initialize empty slice and append another - you can initialize the Uploads member with resp.Uploads.

File: pkg/block/azure/adapter.go [hunk 2]
```diff
@@ -644,6 +644,9 @@ func (a *Adapter) GetPresignUploadPartURL(_ context.Context, _ block.ObjectPoint
 func (a *Adapter) ListParts(_ context.Context, _ block.ObjectPointer, _ string, _ block.ListPartsOpts) (*block.ListPartsResponse, error) {
 	return nil, block.ErrOperationNotSupported
 }
+func (a *Adapter) ListMultipartUploads(_ context.Context, _ block.ObjectPointer) (*block.ListMultipartUploadsResponse, error) {
```
Comment (idanovo) [inline pkg/block/azure/adapter.go:647]: @Isan-Rivkin I agree with @ItamarYuran's decision to implement this only for s3.
WDYT?

File: pkg/gateway/operations/listobjects.go [hunk 3]
```diff
@@ -393,3 +399,43 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+			_ = o.EncodeError(w, req, err, gatewayerrors.Codes.ToAPIErr(gatewayerrors.ErrInternalError))
+			return
+		}
+		uploads = append(uploads, serde.Upload{
+			Key:      mpu.Path,
+			UploadID: *upload.UploadId,
+		})
+	}
+	resp.Uploads = uploads
+	o.EncodeResponse(w, req, resp, http.StatusOK)
```
Comment (idanovo) [inline pkg/gateway/operations/listobjects.go:440]: @nopcoder נrought to my attention this one-
Since in `HandleCreateMultipartUpload` we update the `MultipartTracker` with all the upload IDs we have, we might spare the `ListMultipartUploads` request for the object store by implementing a new `List` method for the `MultipartTracker` that will return the uploaded parts.

**Review by idanovo — CHANGES_REQUESTED** [review]
Looks good!!!
Few minor comments

File: esti/s3_gateway_test.go [hunk 4]
```diff
@@ -289,6 +289,88 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+		return ""
+	}
+	var allKeys string
+	for _, upload := range output.Uploads {
+		if upload.Key != nil {
+			allKeys += *upload.Key + " "
+		}
+	}
+	return allKeys + "\n"
+}
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:372]: Just passing through, not a full review.

It is not a good option to use the full string of the results (keys) and assert substring search as values can be sub values of others.

Return a []string with the values (keys) you like to extract
Use the same assert func Contains should work the same - but this time it will exact result and more verbose message in case the assert fail.
Better func name can be `extractUploadKeys`

```go
func extractUploadKeys(output *s3.ListMultipartUploadsOutput) []string {
	if output == nil {
		return nil
	}
	keys : = make([]string, 0, len(output.Uploads))
	for _, upload := range output.Uploads {
		if upload.Key != nil {
			keys = append(keys, *upload.Key)
		}
	}
	return keys
}
```

File: esti/s3_gateway_test.go [hunk 5]
```diff
@@ -289,6 +289,88 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+	defer tearDownTest(repo)
+	s3Endpoint := viper.GetString("s3_endpoint")
+	s3Client := createS3Client(s3Endpoint, t)
+	multipartNumberOfParts := 3
+	multipartPartSize := 5 * 1024 * 1024
+
+	blockStoreType := viper.GetString(ViperBlockstoreType)
+	if blockStoreType != "s3" {
+		t.Skip("Skipping test - blockstore type is not s3")
+	}
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:303]: Think you wanted this check to be the first thing - before we create s3 client and etc.

File: pkg/block/s3/adapter.go [hunk 6]
```diff
@@ -849,6 +849,38 @@ func (a *Adapter) ListParts(ctx context.Context, obj block.ObjectPointer, upload
...
+	lg := a.log(ctx).WithFields(logging.Fields{
+		"qualified_ns":  qualifiedKey.GetStorageNamespace(),
+		"qualified_key": qualifiedKey.GetKey(),
+		"key":           obj.Identifier,
+	})
+
+	client := a.clients.Get(ctx, bucket)
+	resp, err := client.ListMultipartUploads(ctx, input)
+	if err != nil {
+		lg.WithError(err).Error("ListParts multipart uploads failed")
```
Comment (nopcoder) [inline pkg/block/s3/adapter.go:873]: the error should be related to list multipart uploads

File: pkg/gateway/operations/listobjects.go [hunk 7]
```diff
@@ -393,3 +399,43 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+	for _, upload := range mpuResp.Uploads {
+		if upload.UploadId == nil {
+			continue
+		}
+		mpu, err := o.MultipartTracker.Get(req.Context(), *upload.UploadId)
+		if err != nil {
+			if errors.Is(err, kv.ErrNotFound) {
+				continue
+			}
+			o.Log(req).WithError(err).Error("could not read multipart record")
```
Comment (nopcoder) [inline pkg/gateway/operations/listobjects.go:430]: Upload ID will be a good field to add to the error log in this case

**Review by nopcoder — CHANGES_REQUESTED** [review]
We should make sure that the request align with S3 `ListMultipartUploads`.
For example: the call should return up to 1000 items and respect `max-uploads` (the number of uploads that can be returned in a response).

File: pkg/gateway/operations/base.go [hunk 8]
```diff
@@ -92,7 +92,7 @@ func (o *Operation) HandleUnsupported(w http.ResponseWriter, req *http.Request,
 	}
 	query := req.URL.Query()
 	if slices.ContainsFunc(keys, query.Has) {
-		_ = o.EncodeError(w, req, nil, gwerrors.ERRLakeFSNotSupported.ToAPIErr())
+		_ = o.EncodeError(w, req, nil, gwerrors.ErrAllAccessDisabled.ToAPIErr())
```
[the remark this answers is not in the document]
Comment (ItamarYuran) [reply pkg/gateway/operations/base.go:95]: Its not! forgot that when was debugging

**Comment by ItamarYuran** [comment]
Thank you @nopcoder @idanovo for your reviews!
This new version introduces most of the changes you commented, we are left with the following questions:
 - should we ask the block for the list of ids or implement tracker List func
 - i've aligned the code with the s3 maxuplaods option, but there are a few more [options](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListMultipartUploads.html#API_ListMultipartUploads_RequestSyntax), which ones do we want to implement?

File: esti/s3_gateway_test.go [hunk 9]
```diff
@@ -289,6 +289,86 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+		UploadId: resp1.UploadId,
+		MultipartUpload: &types.CompletedMultipartUpload{
+			Parts: completedParts1,
+		},
+	}
+	// check first mpu appears
+	output, err := s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket})
+	require.NoError(t, err, "error listing multiparts")
+	str := extractUploadKeys(output)
+	require.Contains(t, str, obj1)
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:340]:
```suggestion
	keys := extractUploadKeys(output)
	require.Contains(t, keys, obj1)
```

File: esti/s3_gateway_test.go [hunk 10]
```diff
@@ -289,6 +289,86 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+
+	// create second mpu check both appear
+	_, err = s3Client.CreateMultipartUpload(ctx, input2)
+	require.NoError(t, err, "failed to create multipart upload")
+	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket})
+	str = extractUploadKeys(output)
+	require.Contains(t, str, obj1)
+	require.Contains(t, str, obj2)
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:348]:
```suggestion
	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket})
	require.NoError(t, err, "error listing multiparts")
	keys = extractUploadKeys(output)
	require.Contains(t, keys, obj1)
	require.Contains(t, keys, obj2)
```

File: esti/s3_gateway_test.go [hunk 11]
```diff
@@ -289,6 +289,86 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+
+	// finish first mpu check only second appear
+	_, err = s3Client.CompleteMultipartUpload(ctx, completeInput1)
+	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket})
+	require.NoError(t, err, "error listing multiparts")
+	str = extractUploadKeys(output)
+	require.NotContains(t, str, obj1)
+	require.Contains(t, str, obj2)
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:356]:
```suggestion
	str = extractUploadKeys(output)
	require.NotContains(t, keys, obj1)
	require.Contains(t, keys, obj2)
```

File: esti/s3_gateway_test.go [hunk 12]
```diff
@@ -289,6 +289,86 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+	// create second mpu check both appear
+	_, err = s3Client.CreateMultipartUpload(ctx, input2)
+	require.NoError(t, err, "failed to create multipart upload")
+	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket})
+	str = extractUploadKeys(output)
+	require.Contains(t, str, obj1)
+	require.Contains(t, str, obj2)
+
+	// finish first mpu check only second appear
+	_, err = s3Client.CompleteMultipartUpload(ctx, completeInput1)
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:351]: check `err` returned from complete multipart as later it will be hard to understand why the list fail to work.

File: pkg/block/s3/adapter.go [hunk 13]
```diff
@@ -849,6 +849,38 @@ func (a *Adapter) ListParts(ctx context.Context, obj block.ObjectPointer, upload
...
+	var err error
+	defer reportMetrics("ListMultipartUploads", time.Now(), nil, &err)
+	bucket, key, qualifiedKey, err := a.extractParamsFromObj(obj)
+	if err != nil {
+		return nil, err
+	}
+	input := &s3.ListMultipartUploadsInput{
+		Bucket:     aws.String(bucket),
+		Prefix:     aws.String(key),
+		MaxUploads: opts.MaxUploads,
```
Comment (nopcoder) [inline pkg/block/s3/adapter.go:862]: We support MaxUploads, but it means we also need to support KeyMarker in order to perform full listing.
My previous comment gave MaxUploads an as example of one of the capabilities that this API support.
We should verify with product all the functionality we are going to support or not including the fact that this feature will be only supported for s3.

File: pkg/gateway/operations/listobjects.go [hunk 14]
```diff
@@ -393,3 +400,57 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+func handleListMultipartUploads(w http.ResponseWriter, req *http.Request, o *RepoOperation) {
+	query := req.URL.Query()
+	maxUploadsStr := query.Get(QueryParamMaxUploads)
+	opts := block.ListMultipartUploadsOpts{}
+	if maxUploadsStr != "" {
+		maxUploads, err := strconv.ParseInt(maxUploadsStr, 10, 32)
+		if err != nil {
+			o.Log(req).WithField("MaxParts", maxUploadsStr).
+				WithError(err).Error("malformed query parameter 'MaxParts'")
+			_ = o.EncodeError(w, req, err, gatewayerrors.Codes.ToAPIErr(gatewayerrors.ErrInternalError))
```
Comment (nopcoder) [inline pkg/gateway/operations/listobjects.go:413]: - Verify that this is the response from aws's s3 service? usually it is BadRequest.
- Same for using invalid value (not 1-1000) for this parameter

File: pkg/gateway/operations/listobjects.go [hunk 15]
```diff
@@ -393,3 +400,57 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+			return
+		}
+		maxUploads32 := int32(maxUploads)
+		opts.MaxUploads = &maxUploads32
+	}
+	// partNumberMarker := query.Get(QueryParamPartNumberMarker)
```
Comment (nopcoder) [inline pkg/gateway/operations/listobjects.go:419]: support marker in order to enable pagination

File: pkg/gateway/operations/listobjects.go [hunk 16]
```diff
@@ -393,3 +400,57 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+			o.Log(req).WithError(err).Error("could not read multipart record %s", *upload.UploadId)
+			_ = o.EncodeError(w, req, err, gatewayerrors.Codes.ToAPIErr(gatewayerrors.ErrInternalError))
+			return
+		}
+		uploads = append(uploads, serde.Upload{
+			Key:      mpu.Path,
+			UploadID: *upload.UploadId,
+		})
+	}
+	o.Incr("list_multipart_uploads", o.Principal, o.Repository.Name, "")
```
Comment (nopcoder) [inline pkg/gateway/operations/listobjects.go:450]: we usually increment before we perform the operation

**Review by nopcoder — CHANGES_REQUESTED** [review]
- Added new comments.
- Suggest not to go with the Tracker's List option if we already got confirmation that implementing this feature only for s3. It is a better source of truth for now.
- Should verify with product on which options we will not support. I assume that the minimum will be what is required for this feature request to work. This is why I think that valid pagination is required.

**Comment by ItamarYuran** [comment]
Hi @talSofer Would love your opinion in this matter - 
This current Implementation of the s3 gateway's ListMultipartUploads can only receive some of the original flags (maxUploads, keyMarker, UploadIdMarker) is that satisfactory in your opinion?
The rest of the flags can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListMultipartUploads.html)

**Review by nopcoder — CHANGES_REQUESTED** [review]
I'm taking a step back and looking on the request which accepts Path and KeyMarker.

The underlaying storage can't provide this information as it holds the physical address and not the logical path the user provides.

I suggest having a test / use-case that test this code first to provide a working solution.
Implementation wise - it means that the information can be tracked and it means you will need this capability from the tracker. and in this case consider adding it to all the adapters and not specific s3 feature.

**Comment by nopcoder** [comment]
Update our (@ItamarYuran and myself) conversion output:
- ListMultipartUploads implementation uses s3 adapter, similar to how ListParts works today (only on s3)
- We verified that Apache Nifi PutS3 source code to understand that there is no use of 'prefix' or other special case paramters
- The API should support pagination
- Calling the API with 'prefix' or unsupported options should fail

File: esti/s3_gateway_test.go [hunk 17]
```diff
@@ -289,6 +289,121 @@ func TestS3IfNoneMatch(t *testing.T) {
 	}
 }
 
+func TestListMultipartUploads(t *testing.T) {
+	blockStoreType := viper.GetString(ViperBlockstoreType)
+	if blockStoreType != "s3" {
+		t.Skip("Skipping test - blockstore type is not s3")
+	}
```
Comment (idanovo) [inline esti/s3_gateway_test.go:296]: I would check that we return the correct error for other blockstores (`NotImplemented`)

File: esti/s3_gateway_test.go [hunk 18]
```diff
@@ -289,6 +289,121 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+	s3Endpoint := viper.GetString("s3_endpoint")
+	s3Client := createS3Client(s3Endpoint, t)
+	multipartNumberOfParts := 3
+	multipartPartSize := 5 * 1024 * 1024
+
+	// create two objects for two mpus
+	obj1 := "object1"
+	obj2 := "object2"
+	path1 := "main/" + obj1
+	path2 := "main/" + obj2
```
Comment (idanovo) [inline esti/s3_gateway_test.go:308]:
```suggestion
	obj1 := "object1"
	obj2 := "object2"
	keysPrefix := "main/"
	key1 :=  keysPrefix+ obj1
	key2 :=  keysPrefix+ obj2
```

File: esti/s3_gateway_test.go [hunk 19]
```diff
@@ -289,6 +289,121 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "NotImplemented")
+
+	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket, Prefix: prefix})
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "NotImplemented")
+
+	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket, EncodingType: encodingType})
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "NotImplemented")
```
Comment (idanovo) [inline esti/s3_gateway_test.go:391]: I think these checks should be in a different test @nopcoder WDYT?

File: pkg/gateway/errors/errors.go [hunk 20]
```diff
@@ -204,6 +205,11 @@ func (a APIErrorCode) ToAPIErr() APIError {
 // Codes - error code to APIError structure, these fields carry respective
 // descriptions for all the error responses.
 var Codes = errorCodeMap{
+	ErrInvalidArgument: {
```
Comment (idanovo) [inline pkg/gateway/errors/errors.go:208]: This name is too generic for this error.
If I wouldn't read the description I could use this error in other places.
Maybe call it `ErrInvalidMaxUploads`?

**Review by idanovo — CHANGES_REQUESTED** [review]
I have a few minor comments, but overall, it looks good!

File: pkg/gateway/errors/errors.go (hunk 20 above)
Comment (ItamarYuran) [reply pkg/gateway/errors/errors.go:208]: This is the err i got from s3 while trying it with bad input

File: esti/s3_gateway_test.go (hunk 19 above)
Comment (ItamarYuran) [reply esti/s3_gateway_test.go:391]: I think in general you are right but because we are going to skip this one for now for control-plane, might be nice to keep it in one spot. WDYT?

File: pkg/block/s3/adapter.go [hunk 21]
```diff
@@ -881,6 +881,7 @@ func (a *Adapter) ListMultipartUploads(ctx context.Context, obj block.ObjectPoin
 		Uploads:            resp.Uploads,
 		NextUploadIDMarker: resp.NextUploadIdMarker,
 		NextKeyMarker:      resp.NextKeyMarker,
+		IsTruncated:        *resp.IsTruncated,
```
Comment (nopcoder) [inline pkg/block/s3/adapter.go:884]: aws.BooleanValue?

File: pkg/gateway/serde/xml.go [hunk 22]
```diff
@@ -170,6 +170,7 @@ type ListMultipartUploadsOutput struct {
 	Uploads            []Upload `xml:"Upload"`
 	NextKeyMarker      string   `xml:"NextKeyMarker"`
 	NextUploadIDMarker string   `xml:"NextUploadIDMarker"`
+	IsTruncated        bool     `xml:"IsTruncated"`
```
Comment (nopcoder) [inline pkg/gateway/serde/xml.go]: Please verify that if there is no pagination required, does S3 remove these fields - which means that we need to set them as omitempty

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/gateway/serde/xml.go (hunk 22 above)
Comment (ItamarYuran) [reply pkg/gateway/serde/xml.go]: in case there is no pagination, itTruncated does not appear in s3's answer

File: esti/s3_gateway_test.go [hunk 23]
```diff
@@ -289,6 +289,134 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+	_, err = s3Client.CompleteMultipartUpload(ctx, completeInput1)
+	require.NoError(t, err, "failed to complete multipart upload")
+	output, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: resp1.Bucket})
+	require.NoError(t, err, "error listing multiparts")
+	keys = extractUploadKeys(output)
+	require.NotContains(t, keys, obj1)
+	require.Contains(t, keys, obj2)
+
+}
+func TestListMultipartUploadsUnsupported(t *testing.T) {
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:379]:
```suggestion
}

func TestListMultipartUploadsUnsupported(t *testing.T) {
```

File: esti/s3_gateway_test.go [hunk 24]
```diff
@@ -289,6 +289,134 @@ func TestS3IfNoneMatch(t *testing.T) {
...
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "NotImplemented")
+
+	_, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: Bucket, Prefix: prefix})
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "NotImplemented")
+
+	_, err = s3Client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: Bucket, EncodingType: encodingType})
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "NotImplemented")
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:404]: 1. As far as I remember we don't capture unsupported states. Wonder if need this extra test as we don't do it for all the adapters.
2. Can use t.Run to capture each state

File: pkg/gateway/operations/listobjects.go [hunk 25]
```diff
@@ -409,6 +413,13 @@ func handleListMultipartUploads(w http.ResponseWriter, req *http.Request, o *Rep
 	maxUploadsStr := query.Get(QueryParamMaxUploads)
 	uploadIDMarker := query.Get(QueryParamUploadIDMarker)
 	keyMarker := query.Get(QueryParamKeyMarker)
+	prefix := query.Get(QueryParampPrefix)
+	delimiter := query.Get(QueryParampDelimiter)
```
[the remark this answers is not in the document]
Comment (nopcoder) [reply pkg/gateway/operations/listobjects.go:418]: true, my concern is that the SDK or aws cli provides default or document that the default is '/' and we should support it if it was passed in the request - need to verify that.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: esti/s3_gateway_test.go (hunk 19 above)
Comment (nopcoder) [reply esti/s3_gateway_test.go]: I think that the multipart upload was the only test that we used esti to check as it requires 5M uploads per part.
Agree with Idean - this part can be part the adapter package test as it should represent the spec we supprot.

File: pkg/gateway/errors/errors.go (hunk 20 above)
Comment (nopcoder) [reply pkg/gateway/errors/errors.go]: I missed this one - The problem is not with the generic name is the format of the message and how we map the errors in the gateway.
Each error is mapped latest inside:

```
// Codes - error code to APIError structure, these fields carry respective
// descriptions for all the error responses.
var Codes = errorCodeMap
```

Map the specific error message and add it into both places.

File: pkg/gateway/serde/xml.go (hunk 22 above)
Comment (nopcoder) [reply pkg/gateway/serde/xml.go]: This is why we should use omitempty

File: esti/s3_gateway_test.go [hunk 26]
```diff
@@ -289,6 +289,134 @@ func TestS3IfNoneMatch(t *testing.T) {
 	}
 }
 
+func TestListMultipartUploads(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (ItamarYuran) [reply esti/s3_gateway_test.go:292]: As @idanovo asked, these tests run for other adapters as well, only until the the first list mpu request in which they are expected to fail. then they are being skipped.

[the remark this answers is not in the document]
Comment (idanovo) [reply esti/s3_gateway_test.go:292]: @nopcoder I wanted to make sure we get the right error for other block stores

[the remark this answers is not in the document]
Comment (nopcoder) [reply esti/s3_gateway_test.go:292]: Sure, but I don't understand how it works as we currently do not support this flow for all adapters.

[the remark this answers is not in the document]
Comment (idanovo) [reply esti/s3_gateway_test.go:292]:
```
	if blockStoreType != "s3" {
		require.Contains(t, err.Error(), "NotImplemented")
		return
	}
```

File: pkg/gateway/operations/listobjects.go [hunk 27]
```diff
@@ -393,3 +407,74 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+	if maxUploadsStr != "" {
+		maxUploads, err := strconv.ParseInt(maxUploadsStr, 10, 32)
+		if err != nil {
+			o.Log(req).WithField("maxUploadsStr", maxUploadsStr).
+				WithError(err).Error("malformed query parameter 'maxUploadsStr'")
+			_ = o.EncodeError(w, req, err, gatewayerrors.Codes.ToAPIErr(gatewayerrors.ErrInvalidMaxUploads))
+			return
+		}
+		maxUploads32 := int32(maxUploads)
+		opts.MaxUploads = &maxUploads32
```
[the remark this answers is not in the document]
Comment (ItamarYuran) [reply pkg/gateway/operations/listobjects.go:435]: now aligned with s3, the input is checked and expects a value between  0-2147483647. other values will raise s3's err

File: pkg/gateway/operations/listobjects.go (hunk 25 above)
[the remark this answers is not in the document]
Comment (ItamarYuran) [reply pkg/gateway/operations/listobjects.go:419]: There is no mentioning of a default value in s3's api

File: pkg/gateway/operations/listobjects.go [hunk 28]
```diff
@@ -393,3 +407,74 @@ func (controller *ListObjects) Handle(w http.ResponseWriter, req *http.Request,
...
+			Key:      mpu.Path,
+			UploadID: *upload.UploadId,
+		})
+	}
+	resp := &serde.ListMultipartUploadsOutput{
+		Bucket:             o.Repository.Name,
+		Uploads:            uploads,
+		NextKeyMarker:      aws.StringValue(mpuResp.NextKeyMarker),
+		NextUploadIDMarker: aws.StringValue(mpuResp.NextUploadIDMarker),
+		IsTruncated:        mpuResp.IsTruncated,
```
[the remark this answers is not in the document]
Comment (ItamarYuran) [reply pkg/gateway/operations/listobjects.go:478]: Added omitempty to the xml file.

File: esti/s3_gateway_test.go (hunk 26 above)
[the remark this answers is not in the document]
Comment (nopcoder) [reply esti/s3_gateway_test.go:292]: ok, I see the check down the code of this function - but why do we even start to upload if we can't test it on non-s3 implementation?

[the remark this answers is not in the document]
Comment (idanovo) [reply esti/s3_gateway_test.go:292]: It can be tested in another test.
@ItamarYuran, my suggestion is to:
1. Change `TestListMultipartUploads` `TestListMultipartUploadsUnsupported` back to t.skipp with a proper message `if blockStoreType != "s3"`
2. Change `TestListMultipartUploadsUnsupported` name to indicate it checks only unsupported parameters
3. Add another test that only checks that ListMultipartUpload returns the right error `if blockStoreType != "s3"`
@nopcoder WDYT?

File: pkg/gateway/operations/listobjects.go [hunk 29]
```diff
@@ -21,8 +21,9 @@ import (
 
 const (
 	ListObjectMaxKeys = 1000
-	maxUploadsRange   = 2147483647
-	minUploadsRange   = 0
+	maxUploadsListMPU = 2147483647
+	minUploadsListMPU = 0
```
Comment (nopcoder) [inline pkg/gateway/operations/listobjects.go:25]: 1. if we leave the verification to the underlaying library - you can remove maxUploadsListMPU - it is MaxInt32 value and it will not pass this value as the cast will not let you.

2. if we plan to pass 0 as a valid value and let the underlying package handle it - we just need to check if maxUploads32 < 0

**Review by idanovo — APPROVED** [review]
Please address all @nopcoder's comments before merging 🙏

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: esti/s3_gateway_test.go (hunk 26 above)
[the remark this answers is not in the document]
Comment (idanovo) [reply esti/s3_gateway_test.go:292]: It doesn't
1. We are returning and not skipping
2. We don't test the error we get for object storage that are not s3

**Review by nopcoder — APPROVED** [review]
LGTM.

**Comment by ItamarYuran** [comment]
This PR adds list mpu functionality only to s3 underlying storage.
Follow compatibility with other backends at  #8563
