### PR TITLE
duckdb: handle line breaks after a string constant

### LINKED ISSUE #6095: [Bug]: DuckDB-WASM gets upset with invalid paths - no/poor error message
### What happened?

If you run a query in DuckDB-WASM against an object that doesn't exist the screen hangs at `Executing…` and `Loading…` and doesn't return control or an error to the user. 

1. Query valid object (e.g. `lakes.parquet`)

    CleanShot_2023-06-15_at_16 39 37

2. Amend path but keep object name - UI hangs.

    CleanShot_2023-06-15_at_16 40 02

---

Edit: it only happens if an object has been previously queried. For a completely spurious path an Error (and literally `Error` only) is returned

`SELECT * FROM READ_PARQUET('lakefs://quickstart/I_do_not_exist/main/foo.bar') LIMIT 20`

CleanShot_2023-06-15_at_16 34 55

This also descends into a second problem - if you query above spurious path *and then try a valid one* it still fails (the network window shows a HTTP 200 success for the valid file, so something's up in the page handling)

`SELECT * FROM READ_PARQUET('lakefs://quickstart/main/lakes.parquet') LIMIT 20`

CleanShot_2023-06-15_at_16 37 50

---

Edit2: Sometimes a completely spurious path (such as the above) will also hang the UI

### Expected Behavior

- Never hang the UI
- The `Error` message that _does_ get shown should tell the user what the actual error is. 
- If a valid query is run, return data and not an erroneous `Error`

### lakeFS Version

0.103.0

### Deplyoment

Docker

### Affected Clients

_No response_

### Relevant logs output

_No response_

### Contact Details

_No response_

### LINKED ISSUE #6107: lakeFS' DuckDB editor silently ignores the write part of a COPY command if no semi-colon and a linebreak after the command
DuckDB will happily run a SQL statement with no terminator like this: 

```
CREATE TABLE t1 AS SELECT 42 AS i, 84 AS j;

COPY t1 TO 'lakefs://quickstart/main/t1.parquet'
```

But if there is a line break after the `COPY` it _seems_ to execute it (a row count is returned in the results) but will **silently fail to actually write the data!**

So this returns a result but doesn't write the file:

```
CREATE TABLE t1 AS SELECT 42 AS i, 84 AS j;

COPY t1 TO 'lakefs://quickstart/main/t1.parquet'

```

Whilst this returns a result and *does* write a file

```
CREATE TABLE t1 AS SELECT 42 AS i, 84 AS j;

COPY t1 TO 'lakefs://quickstart/main/t1.parquet';

```

https://github.com/treeverse/lakeFS/assets/3671582/3acffee3-76f0-414c-bc60-5cf6fb3d1926

### PR DESCRIPTION
**Pull request by ozkatz**
Fixes #6107

DuckDB's tokenizer returns only starting offsets, not ending ones. since whitespaces are meaningless in SQL, the next token might only appear after line breaks or spaces.

This fixes handling of trailing whitespaces.

Additionally, this PR removes the unnecessary cleanup done after closing the connection - calling `dropFiles` when there are no files to drop returns a promise that never rejects nor accepts - resulting in a query browser that appears stuck (potentially, closes #6095 together with #6101)

### CODE REVIEW

File: webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ async function getDuckDB(): Promise<duckdb.AsyncDuckDB> {
 // taken from @duckdb/duckdb-wasm/dist/types/src/bindings/tokens.d.ts
 // which, unfortunately, we cannot import.
 const DUCKDB_STRING_CONSTANT = 2;
-const LAKEFS_URI_PATTERN = /^(['"]?)(lakefs:\/\/(.*))(['"])$/;
+const LAKEFS_URI_PATTERN = /^(['"]?)(lakefs:\/\/(.*))(['"])\s*$/;
```
Comment (nopcoder) [inline webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx:46]: can we just drop the $ from the end of the patter? unless a full match is required only the second group match is what we after.

File: webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx [hunk 2]
```diff
@@ -94,16 +94,7 @@ export async function runDuckDBQuery(sql: string):  Promise<arrow.Table<any>> {
         // remove registrations
         await Promise.all(fileNames.map(fileName => db.dropFile(fileName)))
     } finally {
-        await closeDuckDBConnection(conn)
-    }
-    return result
-}
-
-async function closeDuckDBConnection(conn: AsyncDuckDBConnection | null) {
```
Comment (nopcoder) [inline webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx:102]: Please check the case where the data is updated outside, while you continue to query the same file from duckdb.
If I remember the code was to handle this case as the cache hold the previous data and the user was getting previous results.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx (hunk 2 above)
Comment (ozkatz) [reply webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx:102]: Indeed - this is now handled explicitly inside `runDuckDBQuery`, only dropping the files it registered (see line L95)
```typescript
await Promise.all(fileNames.map(fileName => db.dropFile(fileName)))
``` 

tested to work.

**Review by nopcoder — APPROVED** [review]

File: webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx (hunk 1 above)
Comment (ozkatz) [reply webui/src/pages/repositories/repository/fileRenderers/duckdb.tsx:46]: Wanted to keep the token structure explicit to not accidentally capture something beyond the token. whitespaces are the only ignored characters so I prefer to add them explicitly
