### PR TITLE
Uncommitted gc always read deleted addresses for bulk remove

### LINKED ISSUE #5421: Uncommitted GC running of a large dataset of committed data gets out of disk-space
Current partitioning causes the UGC to fill the temporary storage used by each executer.
The UGC fails with out of disk-space.

### PR DESCRIPTION
**Pull request by nopcoder**
Fix #5421 

- The dataset addressesToDelete holds the cached results and unpersist the uncommitted and committed datasets to free memory/disk space.
- Instead using GarbageCollector.bulkRemove - `bulkRemove` implemented. We loop by taking chunk of items from the `addressesToDelete` (size is based on the bulk remover getMaxBulkSize) and calling the `bulkRemover` deleteObjects.

_Note_ work done related to the cache probably helped the out-of-disk and not working with a local iterator.
More data to delete over time will probably help us more to understand which changes need to be made to distribute the bulk delete without abuse or throttle the API.

### CODE REVIEW

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala [hunk 1]
```diff
@@ -182,29 +180,35 @@ object UncommittedGarbageCollector {
           .repartition(dataDF.col("address"))
           .except(committedDF)
           .except(uncommittedDF)
+          .cache()
+
+        committedDF.unpersist()
```
Comment (N-o-Z) [inline clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:185]: I tried to find the documentation for this but it wasn't very clear.
What exactly does unpersist do - and what are the performance implications for this change

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala [hunk 2]
```diff
@@ -182,29 +180,35 @@ object UncommittedGarbageCollector {
...
-        if (shouldMark) { // get the expired addresses from the mark id run
-          markedAddresses = addressesToDelete
-        } else {
-          jobID = markID
-          markedAddresses = readMarkedAddresses(storageNamespace, markID)
-        }
-        println("deleting marked addresses from job: " + jobID)
+        val jobID = if (shouldMark) runID else markID
+        println("deleting marked addresses from job ID: " + jobID)
+        val markedAddresses = readMarkedAddresses(storageNamespace, jobID)
```
Comment (N-o-Z) [inline clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:201]: If I understand correctly, now we are writing and reading the marked addresses every time we run the GC. What is the impact performance-wise?

**Review by N-o-Z — COMMENTED** [review]
@nopcoder  Thanks
Added some questions.
Also how was this tested? Did you check changes in performance in comparison with previous code?

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala (hunk 1 above)
Comment (nopcoder) [reply clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:185]: Release memory associated with the dataframe - in this code I assume that from this point I'll go over the `addressesToDelete` cached results and do not process committed and uncommitted dataframe again.
In the we would had to process these data frame, it would run the processing again - which will be very bad for performance.

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala (hunk 2 above)
Comment (nopcoder) [reply clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:201]: Still testing the two options:
- use the cached results
- use the dataframe we just saved

Will update the PR with the preferred way.

**Comment by nopcoder** [comment]
> @nopcoder Thanks Added some questions. Also how was this tested? Did you check changes in performance in comparison with previous code?

Running the latest code with full mark and sweep ended with out of disk space.
This code with just sweep too 1:20h to delete the marked addresses.
I'm rerunning the full ugc with cache and parquet as source to see if there is any performance difference - the thing is that we will have to wait until we will have more objects to delete to understand the impact or create a fake env.

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala (hunk 2 above)
Comment (nopcoder) [reply clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala]: @N-o-Z updated the code it reuse the cached dataset

**Review by N-o-Z — APPROVED** [review]
@nopcoder approved - thanks!
Can you add a summary of the changes done in the delete process which were required to solve the issue?
