### PR TITLE
Default squash-merge behaviour must be OFF

### LINKED ISSUE #8482: Squash merges is ON by default
#8464 mistakenly set squash merges ON by default.  This is incorrect **AND** a breaking change.

It must be OFF by default.

### PR DESCRIPTION
**Pull request by arielshaqed**
My original PR introduced an entirely wrong behaviour which is _also_ a breaking change.  Fix this bad default.

Closes #8482.

### CODE REVIEW

**Review by N-o-Z — APPROVED** [review]
👍🏽

File: pkg/api/controller_test.go [hunk 1]
```diff
@@ -3826,27 +3826,33 @@ func TestController_MergeSquashing(t *testing.T) {
 
 	cases := []struct {
 		Name               string
-		Squash             bool
+		Squash             *bool
```
Comment (N-o-Z) [inline pkg/api/controller_test.go:3829]: I think adding a scenario where the parameter is not passed explicitly would have caught this.
Might want to add another flavor

Comment (arielshaqed) [reply pkg/api/controller_test.go:3829]: Great ide!  That's exactly what "default" does here :-)

**Review by arielshaqed — COMMENTED** [review]
Thanks for the speedy review!  Pulling, then releasing soon.

**Comment by arielshaqed** [comment]
I suspect [the Python HL wrapper Esti test](https://github.com/treeverse/lakeFS/actions/runs/12693417936/job/35381230972?pr=8483) is failing because of #8484.  (It didn't catch this bug when I made it, in #8482, exactly because it doesn't run the current version!)

So force-pushing.

File: pkg/api/controller_test.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/api/controller_test.go:3829]: Missed that 😅
