### PR TITLE
Fix committed iterator

### LINKED ISSUE #8648: Commited Iterator should be iniotialized with storage ID

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #8648

This is a quick fix to the issue.
In no way do I feel this is the appropriate approach - but it's good enough to unblock us for now

### CODE REVIEW

File: pkg/graveler/committed/iterator.go [hunk 1]
```diff
@@ -21,12 +21,13 @@ type iterator struct {
...
 }
 
-func NewIterator(ctx context.Context, manager RangeManager, namespace Namespace, rangesIt ValueIterator) Iterator {
+func NewIterator(ctx context.Context, manager RangeManager, storageID StorageID, namespace Namespace, rangesIt ValueIterator) Iterator {
 	return &iterator{
 		ctx:       ctx,
 		manager:   manager,
 		namespace: namespace,
 		rangesIt:  rangesIt,
+		storageID: storageID,
```
Comment (itaigilo) [inline pkg/graveler/committed/iterator.go:30]: According to the convention, should be placed just before namespace.

**Comment by itaigilo** [comment]
> This is a quick fix to the issue. In no way do I feel this is the appropriate approach - but it's good enough to unblock us for now

@N-o-Z You don't feel this is the appropriate approach because it doesn't prevent this from happening again in another place?
Or something else?

**Comment by N-o-Z** [comment]
> > This is a quick fix to the issue. In no way do I feel this is the appropriate approach - but it's good enough to unblock us for now
> 
> @N-o-Z You don't feel this is the appropriate approach because it doesn't prevent this from happening again in another place? Or something else?

The whole solution for tier fs requires refactoring. Optimally iterator should not be aware of storage id

File: pkg/graveler/committed/iterator.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/graveler/committed/iterator.go:30]: It's a struct intialization code - I find this irrelevant

**Review by itaigilo — APPROVED** [review]
