### PR TITLE
Fix s3 adapter access content length without nil check

### LINKED ISSUE #5498: S3 block adater access content-length without nil check
S3 get-object and get-object-range can panic in case no content-length is sent in response.

### PR DESCRIPTION
**Pull request by nopcoder**
Fix #5498

### CODE REVIEW

File: pkg/block/s3/adapter.go [hunk 1]
```diff
@@ -308,7 +308,7 @@ func (a *Adapter) Get(ctx context.Context, obj block.ObjectPointer, _ int64) (io
 		log.WithError(err).Errorf("failed to get S3 object bucket %s key %s", qualifiedKey.StorageNamespace, qualifiedKey.Key)
 		return nil, err
 	}
-	sizeBytes = *objectOutput.ContentLength
+	sizeBytes = aws.Int64Value(objectOutput.ContentLength)
```
Comment (arielshaqed) [inline pkg/block/s3/adapter.go:311]: This looks good, but TBH I don't understand what this line does: it copies the value into a variable, which it then ignores.  `sizeBytes` is not a pointer, I don't see what effect this assignment can have.
```suggestion
```

(I'm actually shocked that Go doesn't flag an unused variable here.  It's the sort of thing gcc has been doing for ages now, at least when optimizing.)

Same applies below, too.   It looks like a bad leftover.

**Review by arielshaqed — APPROVED** [review]
I say we delete these lines entirely!  But approving for velocity: the change itself is safe.

File: pkg/block/s3/adapter.go (hunk 1 above)
Comment (nopcoder) [reply pkg/block/s3/adapter.go:311]: The variable is referenced in the defer function - so it is just for report the file size as part of the metric.
