### PR TITLE
Fix lakectl branch protection set 400 response

### LINKED ISSUE #7589: [Bug]: Setting Branch Protection from lakectl fails
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Create a new repo.
2. use lakectl to create branch protection rule: `lakectl branch-protect add lakefs://test main`

You'll get a 400 bad response result. It works from the UI.
If a branch protection rules exist prior to the operation, then lakectl branch protection rule creation works.

Root Cause: lakectl first tries to fetch the rules and then uses Etag (checksum) for an atomic update. If no rule exists, then the value is an empty string which is forbidden. The Swagger API declares `allowEmptyValue: true` which is misleading. It allows for the header `If-Match` with no value, not an empty string value.

### Expected behavior

The command should create a branch protection rule successfuly. 

### lakeFS version

latest

### How lakeFS is installed

all

### Affected clients

lakectl 

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by itaiad200**
Closes #7589

### CODE REVIEW

File: esti/lakectl_test.go [hunk 1]
```diff
@@ -811,3 +811,17 @@ func TestLakectlUsage(t *testing.T) {
...
+
+func TestLakectlBranchProtection(t *testing.T) {
+	repoName := generateUniqueRepositoryName()
+	storage := generateUniqueStorageNamespace(repoName)
+	vars := map[string]string{
+		"REPO":    repoName,
+		"STORAGE": storage,
+		"BRANCH":  mainBranch,
+	}
+	r := strings.NewReplacer("{lakectl}", Lakectl(), "{repo}", repoName, "{storage}", storage, "{branch}", "main")
```
Comment (N-o-Z) [inline esti/lakectl_test.go:823]: Can we be consistent with how we create the lakectl command

**Review by N-o-Z — APPROVED** [review]
One comment
