### PR TITLE
Fix: UI ADLS import validity regex

### LINKED ISSUE #6507: [Bug]: Import - UI blocks from import from ADLS Gen2
### What happened?

When trying to import from ADLS Gen2 we get an error message `Import source should match the following pattern: "^https?://[a-z,0-9]+\.blob\.core\.windows\.net"`

### Expected behavior

_No response_

### lakeFS version

0.107.1

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #6507

### Background

Added validity regex to prevent users from creating lakeFS repos with invalid namespaces, but this regex is also used to validate import source in UI and therefore fails when we providing source with adls hint

### Bug Fix

Cannot import from UI when source is an Azure ADLS storage
Added explicit import validation regex in the StorageConfig
      
### Testing Details

Tested manually

### Breaking Change?

No

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/block/azure/adapter.go [hunk 1]
```diff
@@ -570,7 +570,8 @@ func (a *Adapter) CompleteMultiPartUpload(ctx context.Context, obj block.ObjectP
 
 func (a *Adapter) GetStorageNamespaceInfo() block.StorageNamespaceInfo {
 	info := block.DefaultStorageNamespaceInfo(block.BlockstoreTypeAzure)
-	info.ValidityRegex = `^https?://[a-z,0-9]+\.blob\.core\.windows\.net`
+	info.ImportValidityRegex = `^https?://[a-z,0-9,_,-]+\.(blob|adls)\.core\.windows\.net` // added adls for import hint validation in UI
+	info.ValidityRegex = `^https?://[a-z,0-9,_,-]+\.blob\.core\.windows\.net`
```
Comment (nopcoder) [inline pkg/block/azure/adapter.go:574]:
```suggestion
	info.ImportValidityRegex = `^https?://[a-z0-9_-]+\.(blob|adls)\.core\.windows\.net` // added adls for import hint validation in UI
	info.ValidityRegex = `^https?://[a-z0-9_-]+\.blob\.core\.windows\.net`
```

**Review by nopcoder — APPROVED** [review]
LGTM!
