### PR TITLE
DynamoDB: Make credentials expiry window + jitter configurable

### LINKED ISSUE #9428: Possible issue in dynamoDB KV store when receiving slow down
reported by a user due to dynamoDB throttling which may uncovered an underlying issue in lakeFS.

It seems that while retrying, the token used to write to dynamoDB expires and we get an error.

Logs (redacted):
* Slowdown from dynamoDB:
```
{
  "file": "-oss/pkg/kv/dynamodb/store.go:338",
  "func": "pkg/kv/dynamodb.(*Store).setWithOptionalPredicate",
  "host": "<redacted>",
  "level": "error",
  "method": "PUT",
  "msg": "put item: %wslow down",
  "operation_id": "LinkPhysicalAddress",
  "partition_key": "aGFncmlkaGFuZHMtbWFpbjo1MDE3NGY5Mi1kZmE3LTQxMmQtODY5OC0wNDY4ZDFjODkzZDQ=",
  "path": "/api/v1/repositories/<redacted>/branches/main/staging/backing?path=<redacted>",
  "request_id": "a534b3a7-c232-40fe-8452-7e35106618b9",
  "service_name": "rest_api",
  "store": "dynamodb",
  "time": "2025-08-12T08:38:19Z",
  "user": "<redacted>"
}
````

* Internal Server Error in lakeFS due to request token expiry:
```
{
  "error": "put item: operation error DynamoDB: PutItem, https response error StatusCode: 400, RequestID: LQBA2KTEKB5LF7UH57KMSVHAT3VV4KQNSO5AEMVJF66Q9ASUAAJG, api error ExpiredTokenException: The security token included in the request is expired",
  "file": "-oss/pkg/api/controller.go:3033",
  "func": "pkg/api.(*Controller).handleAPIErrorCallback",
  "host": "<redacted>",
  "level": "error",
  "method": "PUT",
  "msg": "API call returned status internal server error",
  "operation_id": "LinkPhysicalAddress",
  "path": "/api/v1/repositories/hagridhands/branches/main/staging/backing?path=<redacted>",
  "request_id": "8555f7d5-ad7e-4240-a73e-cf7cb61ef421",
  "service": "api_gateway",
  "service_name": "rest_api",
  "time": "2025-08-12T08:37:32Z",
  "user": "<redacted>"
}
```

More context: https://github.com/treeverse/cloud-controlplane/issues/4588

### PR DESCRIPTION
**Pull request by Jonathan-Rosenberg**
Closes #9428 

In addition to making it configurable, change the default expiration window to 60 seconds (instead of 30) to fix the bug mentioned above (read my comment in the issue for more details).

~~Created an [issue](https://github.com/aws/aws-sdk-go-v2/issues/3192) in the AWS Go SDK repo~~

The AWS SDK bug was actually fixed in a later version. I've upgraded the packages to include the fix.

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -125,6 +125,14 @@ type Database struct {
...
 		// Maximum amount of connections to DDB. 0 means no limit.
 		MaxConnections int `mapstructure:"max_connections"`
+
+		// CredentialsCacheExpiryWindow - The expiry window for cached credentials.
+		// Default is 60 seconds.
+		CredentialsCacheExpiryWindow time.Duration `mapstructure:"credentials_cache_expiry_window"`
+
+		// CredentialsCacheExpiryWindowJitter - The jitter fraction for credentials cache expiry.
+		// Default is 0.5 (50% jitter).
+		CredentialsCacheExpiryWindowJitter float64 `mapstructure:"credentials_cache_expiry_window_jitter"`
```
Comment (nopcoder) [inline pkg/config/config.go]: Add 'Frac' as suffix. it will be hard to understand the unit is not in duration.

**Review by nopcoder — APPROVED** [review]
Looks good; just missing unit in the jitter parameter name.

**Comment by lucix-aws** [comment]
FYI https://github.com/aws/aws-sdk-go-v2/issues/3192#issuecomment-3302982317

**Comment by N-o-Z** [comment]
@Jonathan-Rosenberg are these changes relevant considering the investigation you made and the suggestion from AWS to update the dynamodb package?
Perhaps we should wait with these and first update the package?

**Comment by Jonathan-Rosenberg** [comment]
@N-o-Z just seen the comment now. Amazing so I'll update it. Anyways, I still think these should be configurable and not constant, but I'll definitly try to update it first.

File: pkg/config/config.go (hunk 1 above)
Comment (arielshaqed) [reply pkg/config/config.go]: "Fraction", please: "frac" is 4 characters shorter but harder to understand.  Or (I prefer) "proportion"; just let's not abbreviate here.

**Review by arielshaqed — APPROVED** [review]
Neat, thanks!

But really cool that newer versions actually have the fix you wanted 😎
