### PR TITLE
Different dbpool for branch-locker

### LINKED ISSUE #1446: BranchLocker deadlocks lakeFS
When using branch locker 2 DB connections are needed, one for the lock and the other for the actual action.
In some cases, when the system is under high load, some thread acquires the lock, but fails to create another connection to the DB since they were exhausted (by other requests. Default is 25 connections)

### PR DESCRIPTION
**Pull request by itaiad200**
closes #1446

### CODE REVIEW

File: catalog/rocks_cataloger.go [hunk 1]
```diff
@@ -28,8 +28,12 @@ const (
 
 var ErrUnknownDiffType = errors.New("unknown graveler difference type")
 
-func NewCataloger(db db.Database, cfg *config.Config) (Cataloger, error) {
-	entryCatalog, err := NewEntryCatalog(cfg, db)
+func NewCatalogerSingleWriter(db db.Database, cfg *config.Config) (Cataloger, error) {
```
Comment (ozkatz) [inline catalog/rocks_cataloger.go:31]: Why do we need to special case this? why not always pass 2 pools?

**Review by ozkatz — APPROVED** [review]
That was fast!

File: catalog/rocks_cataloger.go (hunk 1 above)
Comment (itaiad200) [reply catalog/rocks_cataloger.go]: Discuss f2f, switched to config struct.
