### PR TITLE
Fix import start race condition

### LINKED ISSUE #9640: [Bug]: ImportStart race condition with ImportStatus
### What happened?

This is a race condition, so it might not be that easy to reproduce. 
Steps to Reproduce:
1. Start import with `ImportStart` request.
2. When it returns, immediatly request for status with `ImportStatus`
3. Sometimes, it will return 404

### Expected behavior

It should always find the import id in the status request.

The root cause is that `ImportStart` returns the response to the client before it persists the operation in the KV. When the client asks for the status with `ImportStatus`, the status might not been saved to the KV yet, resulting with 404 response to the client.

### lakeFS version

latest

### How lakeFS is installed

_No response_

### Affected clients

All

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #9640

### Background

Start import returns ID before import status is being persisted causing a race were getting import status results in not found

### Bug Fix

persist import status before returning response from import start
      
### Testing Details

Existing tests

### Breaking Change?

No

### CODE REVIEW

File: pkg/catalog/catalog.go [hunk 1]
```diff
@@ -2498,7 +2498,7 @@ func (c *Catalog) importAsync(ctx context.Context, repository *graveler.Reposito
 	}
 
 	// Update import status
-	status := importManager.Status()
+	status = importManager.Status()
```
Comment (AliRamberg) [inline pkg/catalog/catalog.go]: nitnitnit: 
I was confused initially thinking this line is redundant. 
Maybe rename the `status` parameter as `initialStatus` to avoid shadowing?

**Review by AliRamberg — APPROVED** [review]
Thanks, small comment

File: pkg/catalog/catalog.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/catalog/catalog.go]: Will do
