### PR TITLE
Warn when path displayed in webui is empty and contains no objects

### LINKED ISSUE #5117: [Bug]: UI: changing branch from objects window retains previous context object path
### What happened?

Current Behavior:
What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. In a given branch "a" objects viewer got to a path that doesn't exist in branch "b"
image

2. From this view change branch to "b"
image

3. The branch shows no objects because the given object path doesn't exist

### Expected Behavior

Expected Behavior:
If this is a feature - it is not clear that we don't see objects due to the non-existing path
Otherwise, changing a branch in the objects view should reset the path to the branch root

### lakeFS Version

master

### Deplyoment

_No response_

### Affected Clients

_No response_

### Relevant logs output

_No response_

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by arielshaqed**
This can happen when you go to a path and switch to another branch where that path does not exist.

When reviewing, please pay special attention to what it looks like, and whether the warning is clear and not too scary.

Fixes #5117.

## Pics or it never happened!

Branch where path does not exist:
Path does not exist, shows warning

Branch where the path does exist:
Path does exist, show tree view

### CODE REVIEW

**Comment by arielshaqed** [comment]
@Annaseli changed.  It now looks like this:
&quot;Nothing here. Switch to another branch or tag to see something&quot; displayed as formatted text rather than as a warning.

File: webui/src/lib/components/repository/tree.jsx [hunk 1]
```diff
@@ -836,6 +837,17 @@ export const Tree = ({
...
+  } else if (results.length === 0) {
+    body = (
+      <>
+        <div className="me-3">
+          <div className="d-flex flex-column align-items-center">
+            <AlertIcon size={36} /><br/>
+            Nothing here.  Switch to another branch or tag to see something.
+          </div>
+        </div>
+      </>
```
Comment (Annaseli) [inline webui/src/lib/components/repository/tree.jsx:847]: If you add the classes `mb-3 mt-3` to the `<div className="d-flex flex-column align-items-center">` and remove the outer `<div className="me-3">`, i.e:

```
body = (
      <>
          <div className="d-flex flex-column align-items-center mb-3 mt-3">
              <AlertIcon size={36} /><br/>
              Nothing here.  Switch to another branch or tag to see something.
          </div>
      </>
);
```

This will give the error message proper margin and also remove the extra wrapper `<div>`:

image

**Comment by idanovo** [comment]
@arielshaqed any reason we don't merge this one?

**Comment by arielshaqed** [comment]
> @arielshaqed any reason we don't merge this one?

Thanks, missed that one!

File: webui/src/lib/components/repository/tree.jsx (hunk 1 above)
Comment (arielshaqed) [reply webui/src/lib/components/repository/tree.jsx:847]: Thanks!
