### PR TITLE
Fix: UGC no uncommitted data

### LINKED ISSUE #5450: Uncommitted GC: Fix uncommitted file location
Server side: when no uncommitted data return empty address
Client side: for backwards compatibility catch exception when trying to read from address that doesn't exist

### PR DESCRIPTION
**Pull request by N-o-Z**
### Linked Issue

Closes #5450

### Testing Details

Tested manually on client side
Modified unit tests on server side

### Breaking Change?

No

### CODE REVIEW

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala [hunk 1]
```diff
@@ -157,13 +157,28 @@ object UncommittedGarbageCollector {
...
-              ApiClient
-                .translateURI(new URI(uncommittedGCRunInfo.uncommittedLocation), storageType)
-                .toString
-            spark.read.parquet(uncommittedLocation)
+            try {
+              val uncommittedLocation =
+                ApiClient
+                  .translateURI(new URI(uncommittedGCRunInfo.uncommittedLocation), storageType)
+                  .toString
+              spark.read.parquet(uncommittedLocation)
```
Comment (nopcoder) [inline clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:165]: can we verify the location or catch the exception without string compare?

File: clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala [hunk 2]
```diff
@@ -157,13 +157,28 @@ object UncommittedGarbageCollector {
...
+              // Backwards compatibility with lakefs servers that return address even when there's no uncommitted data
+              case e: org.apache.spark.sql.AnalysisException =>
+                if (!e.message.contains("Path does not exist")) {
+                  throw e
+                }
+                println(
+                  "WARN: Uncommitted file list (" + uncommittedGCRunInfo.uncommittedLocation + ") not found - assuming no uncommitted data"
+                )
+                // in case of no uncommitted entries
+                spark.emptyDataFrame.withColumn("physical_address", lit(""))
```
Comment (nopcoder) [inline clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala:176]: we can just fall throw or change the check so in case there is no path or no data we return an empty data frame

File: pkg/catalog/catalog.go [hunk 3]
```diff
@@ -1868,14 +1869,17 @@ func (c *Catalog) PrepareGCUncommitted(ctx context.Context, repositoryID string,
...
-	}
-
 	// Upload parquet file to object store
-	var name string
+	var (
+		uncommittedLocation string
+		name                string
+	)
 	if hasData {
+		uncommittedLocation, err = c.Store.GCGetUncommittedLocation(repository, runID)
```
Comment (nopcoder) [inline pkg/catalog/catalog.go:1878]: This means that no location == no data, right?

**Review by nopcoder — CHANGES_REQUESTED** [review]
We should handle the exception better or check before we try

File: pkg/catalog/catalog.go (hunk 3 above)
Comment (N-o-Z) [reply pkg/catalog/catalog.go:1878]: True

**Review by nopcoder — APPROVED** [review]
LGTM, thanks!
