### PR TITLE
Fix UI showing wrong field removed when deleting metadata field

### LINKED ISSUE #9665: [Bug]: Deleting metadata field appears to remove wrong field in UI
### What happened?
When deleting a metadata key-value pair in the Commit/Merge/Import modals, the UI appears to delete the last field in the list, even though the correct field is removed from the state.
       
Steps to Reproduce:
1. Open a Commit, Merge, or Import modal
2. Click "Add metadata field" multiple times to create 3 or more fields
3. Fill different values in each key (e.g. key1/value1, key2/value2, key3/value3)
4. Click the X button on any field except the last one.

### Expected behavior
The field that was deleted should be removed from the UI.

Actual behaviour:
The last field in the list appears to be deleted visually, but the state is correctly updated. The UI is showing stale data. If you close the modal and reopen the modal, the view is refreshed and you can see the correct data in the fields.

The issue appears to be caused by the `MetadataFields` component using the [array index as the key](https://github.com/treeverse/lakeFS/blob/master/webui/src/lib/components/repository/changes.jsx#L285). When a field is deleted, all fields after it shift down by one index. React sees the same key values and reuses the existing DOM elements. 

Example:
Before: [key1/1, key2/2, key3/3]  Keys: [0, 1, 2]
Delete index 1 (key2/2)
After:  [key1/1, key3/3]         Keys: [0, 1]

React keeps the DOM element at key "1" (which was showing "key2/2")
and just removes the element at key "2" (which was showing "key3/3")

### How lakeFS is installed

lakeFS cloud

### PR DESCRIPTION
**Pull request by zubron**
Closes #9665 

### Background
Fixes a bug where deleting a metadata key-value pair visually removed the last field in the list instead of the selected one, even though the correct field was removed from state. The issue was caused by using array indices as React keys, which caused DOM element reuse when fields were removed.

This change:

- Extracts the `MetadataFields` component into its own file.
- Converts the component to be controlled rather than uncontrolled by using `value` instead of `defaultValue` in the inputs.
- Removes unnecessary `useCallback` wrappers from `onChangeKey`, `onChangeValue`, and `onRemovePair`, since they return new closures on every render and memoization offers no benefit.

### Testing Details
Manually tested: Added multiple fields, deleted from beginning/middle/end of list, verified correct fields removed and remaining fields editable, and that the correct values were persisted.

### CODE REVIEW

File: webui/src/lib/components/repository/metadata.jsx [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+            const value = e.currentTarget.value;
+            setMetadataFields(prev => [...prev.slice(0,i),  {...prev[i], value}, ...prev.slice(i+1)]);
+        };
+    };
+
+    const onRemovePair = (i) => {
+        return () => setMetadataFields(prev => [...prev.slice(0, i), ...prev.slice(i + 1)]);
+    };
+
+    const onAddPair = useCallback(() => {
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx]: Is the `useCallback` here still required?

File: webui/src/lib/components/repository/metadata.jsx [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+    };
+
+    const onChangeValue = (i) => {
+        return e => {
+            const value = e.currentTarget.value;
+            setMetadataFields(prev => [...prev.slice(0,i),  {...prev[i], value}, ...prev.slice(i+1)]);
+        };
+    };
+
+    const onRemovePair = (i) => {
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx]: It was there before, but while you're at it,
I _think_ that renaming to `onRemoveKeyValue` will be clearer.

File: webui/src/lib/components/repository/metadata.jsx [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+/**
+ * MetadataFields is a component that allows the user to add/remove key-value pairs of metadata.
+ * @param {Array<{key: string, value: string}>} metadataFields - initial metadata fields to display
+ * @param {Function} setMetadataFields - callback to update the metadata fields
+*/
+export const MetadataFields = ({ metadataFields, setMetadataFields, ...rest}) => {
+    const onChangeKey = (i) => {
+        return e => {
+            const key = e.currentTarget.value;
+            setMetadataFields(prev => [...prev.slice(0,i), {...prev[i], key}, ...prev.slice(i+1)]);
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx]: I probably mis-read this confusing code (which I know you didn't write), but -
Isn't this setting the _value_ of the field?

(This seems identical to `onChangeValue()`...)

File: webui/src/lib/components/repository/metadata.jsx [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+    const onRemovePair = (i) => {
+        return () => setMetadataFields(prev => [...prev.slice(0, i), ...prev.slice(i + 1)]);
+    };
+
+    const onAddPair = useCallback(() => {
+        setMetadataFields(prev => [...prev, {key: "", value: ""}])
+    }, [setMetadataFields]);
+
+    return (
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx:38]: Just making sure - 
Nothing has changed in the return value,
expect for replacing the `defaultValue`s with `value`s?

**Review by itaigilo — CHANGES_REQUESTED** [review]
Nicely done -
Extracting to a component is a good decision.

It actually looks good,
Blocking basically because of a potential bug, or because of confusing code 😄 

Plus - 
When testing, did you make sure the updates are persistent?
That the values being saved to the server are as expected?

File: webui/src/lib/components/repository/metadata.jsx (hunk 1 above)
Comment (zubron) [reply webui/src/lib/components/repository/metadata.jsx]: It's not really required, but it was the only instance where it could correctly cache the function so I left it in. The React docs state that [`useCallback` should only be used as a performance optimization](https://react.dev/reference/react/useCallback#usage:~:text=on%20this%20page.-,Note,problem%20and%20fix%20it%20first.%20Then%20you%20may%20add%20useCallback%20back.,-DEEP%20DIVE). This doesn't seem like an area where we need to worry about performance so we can remove it if you prefer - I'm happy either way.

File: webui/src/lib/components/repository/metadata.jsx (hunk 3 above)
Comment (zubron) [reply webui/src/lib/components/repository/metadata.jsx]: Yep, this is confusing! I had to read it a few times. The `{...prev[i], key}` is using the object shorthand syntax so it's equivalent to `{...prev[i], key: key}`. I'll update this to be a bit more explicit because I think it will help readability!

File: webui/src/lib/components/repository/metadata.jsx (hunk 4 above)
Comment (zubron) [reply webui/src/lib/components/repository/metadata.jsx:38]: Correct! The only change in the return is `defaultValue` → `value`. This makes the inputs controlled components - React manages the state and keeps the inputs in sync with `metadataFields`, rather than the DOM managing its own state. This is what fixes the bug where deleting a field appeared to remove the wrong one.

**Comment by zubron** [comment]
Thanks for the review @itaigilo! Yes, I tested that the values were persisted correctly - added/edited/deleted fields and verified that the final state in the form was saved to the server as expected.

I'll tidy up the confusing parts of the code in the handlers to make them more readable 👍

File: webui/src/lib/components/repository/metadata.jsx [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+ * MetadataFields is a component that allows the user to add/remove key-value pairs of metadata.
+ * @param {Array<{key: string, value: string}>} metadataFields - current metadata fields to display
+ * @param {Function} setMetadataFields - callback to update the metadata fields
+ * @param rest - any other props to pass to the component
+ */
+export const MetadataFields = ({ metadataFields, setMetadataFields, ...rest}) => {
+    const onChangeKey = (i) => {
+        return e => {
+            const newKey = e.currentTarget.value;
+            setMetadataFields(prev => [...prev.slice(0,i), {...prev[i], key: newKey}, ...prev.slice(i+1)]);
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx]:
```suggestion
            const updatedFields = [...prev];
            updatedFields[i].key = e.currentTarget.value;
            setMetadataFields(prev => updatedFields);
```

Comment (itaigilo) [reply webui/src/lib/components/repository/metadata.jsx]: Just a suggestion.
Uses the same amount of memory, but much more readable imho...
(Plz double-check this actually works 😄)

File: webui/src/lib/components/repository/metadata.jsx [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+        };
+    };
+
+    const onChangeValue = (i) => {
+        return e => {
+            const newValue = e.currentTarget.value;
+            setMetadataFields(prev => [...prev.slice(0,i),  {...prev[i], value: newValue}, ...prev.slice(i+1)]);
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx]:
```suggestion
            const updatedFields = [...prev];
            updatedFields[i].value = e.currentTarget.value;
            setMetadataFields(prev => updatedFields);
```

File: webui/src/lib/components/repository/metadata.jsx [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+        };
+    };
+
+    const onRemoveKeyValue = (i) => {
+        return () => setMetadataFields(prev => [...prev.slice(0, i), ...prev.slice(i + 1)]);
```
Comment (itaigilo) [inline webui/src/lib/components/repository/metadata.jsx]: I can also argue that `splice` will be cleaner here, but that's just nit.

File: webui/src/lib/components/repository/metadata.jsx (hunk 5 above)
Comment (zubron) [reply webui/src/lib/components/repository/metadata.jsx]: Thanks for the suggestion! I avoided that pattern because spreading the array only shallow-copies it, so changing `updatedFields[i]` would also mutate `prev[i]`, which can cause issues with React's rendering or memoization.

The readability could definitely be improved though. I’ve updated the functions to use `map`/`filter`, which should hopefully make the intent clearer.

File: webui/src/lib/components/repository/metadata.jsx (hunk 7 above)
Comment (zubron) [reply webui/src/lib/components/repository/metadata.jsx]: We could use `splice` here, but we'd have to clone the array first to avoid mutating state. I've just updated it to use `filter` which keeps it immutable by default and hopefully is a bit clearer.

**Comment by zubron** [comment]
Thanks for the suggestions, @itaigilo! I've updated the handlers to use `map`/`filter` which is hopefully a bit more readable while keeping state immutable. Let me know if you're okay with this approach 😄

**Comment by itaigilo** [comment]
> Thanks for the suggestions, @itaigilo! I've updated the handlers to use `map`/`filter` which is hopefully a bit more readable while keeping state immutable. Let me know if you're okay with this approach 😄

@zubron Well, apologies for the mess, and thanks for the effort trying to making this better and more readable.

I personally find your previous versions clearer, so I guess it's better keep the (already verified) old ones.
Though your current version also works an LGTM.

**Comment by zubron** [comment]
> I personally find your previous versions clearer, so I guess it's better keep the (already verified) old ones. Though your current version also works an LGTM.

Works for me! I'll revert the last commit.
