### PR TITLE
Fix: lakectl local commit to use lakefs upload with user metadata

### LINKED ISSUE #6421: `lakectl local commit` failed: upload to backing store: MissingRegion: could not find region configuration
I am using https://github.com/treeverse/lakeFS-samples/blob/main/docker-compose.yml along with `lakectl` run locally from the Docker host machine, connecting to lakeFS on Docker which in turn is using MinIO for its object store (also on Docker).  

When I do a `commit` the upload fails: 

```
failed: upload to backing store: MissingRegion: could not find region configuration
```

---

Steps to reproduce

1. Run https://github.com/treeverse/lakeFS-samples/blob/main/docker-compose.yml
2. Configure local `lakectl` for connecting to & auth for lakeFS in Docker container
3. Manually upload the contents of the `/data` folder in the samples github repo to a lakeFS repo called `quickstart`
4. Clone a path into local `orion` folder

    ```
    $ lakectl local clone lakefs://quickstart/main/data/OrionStar/ orion --pre-sign=false
    ```
5. Switch to dev branch

    ```
    $ lakectl local checkout . --ref dev
    ```

6. Create a `RATINGS.csv` file locally, and delete some files `rm -v EMPLOYEE_*`

7. Check status

    ```
    $ lakectl local status
    
    diff 'local:///Users/rmoff/work/orion' <--> 'lakefs://quickstart/7eaeafd3fb90df419ca26eca69ba2b153eae13bd3dccf80ba47cbed1260cb0c1/data/OrionStar/'...
    diff 'lakefs://quickstart/7eaeafd3fb90df419ca26eca69ba2b153eae13bd3dccf80ba47cbed1260cb0c1/data/OrionStar/' <--> 'lakefs://quickstart/main/data/OrionStar/'...
    
    ╔════════╦═════════╦═══════════════════════════╗
    ║ SOURCE ║ CHANGE  ║ PATH                      ║
    ╠════════╬═════════╬═══════════════════════════╣
    ║ local  ║ removed ║ EMPLOYEE_ADDRESSES.csv    ║
    ║ local  ║ removed ║ EMPLOYEE_DONATIONS.csv    ║
    ║ local  ║ removed ║ EMPLOYEE_ORGANIZATION.csv ║
    ║ local  ║ removed ║ EMPLOYEE_PAYROLL.csv      ║
    ║ local  ║ added   ║ RATINGS.csv               ║
    ╚════════╩═════════╩═══════════════════════════╝
    ```

8. Try to commit the changes 
    
    ```
    $ lakectl local commit . -m "Remove employee data and add ratings information" --pre-sign=false
    
    Getting branch: main
    
    diff 'local:///Users/rmoff/work/orion' <--> 'lakefs://quickstart/7eaeafd3fb90df419ca26eca69ba2b153eae13bd3dccf80ba47cbed1260cb0c1/data/OrionStar/'...
    
    diff 'lakefs://quickstart/38df1480d835fe52dc6db31b87ef35b78403d0c9c621c74a6d032c686551abc5/data/OrionStar/' <--> 'lakefs://quickstart/main/data/OrionStar/'...
    delete remote path: EMPLOYEE_ADDRESSES.~ ... fail! [%0 in 8ms]
    delete remote path: EMPLOYEE_ORGANIZATI~ ... fail! [%0 in 8ms]
    delete remote path: EMPLOYEE_DONATIONS.~ ... fail! [%0 in 8ms]
    delete remote path: EMPLOYEE_PAYROLL.csv ... fail! [%0 in 8ms]
    upload RATINGS.csv                       ... done! [6.86KB in 6ms]
    upload RATINGS.csv failed: upload to backing store: MissingRegion: could not find region configuration
    Error executing command.
    ```

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #6421

### Background

lakectl local commit had 2 modes pre-signed url and direct. Our direct flag is limited to support only AWS S3 and is planned to be deprecated.
Added ability to pass user metadata on our uploadObject API and used that instead

### Bug Fix

2 Problems in this issue:
1. lakectl local used direct upload when not using pre-sign mode
2. Our open API upload object did not support adding user metadata and therefore we could not use it for local operations
      
### Testing Details

Manual tested relevant scenario + added esti tests for commit

### Breaking Change?

No

### CODE REVIEW

**Comment by ozkatz** [comment]
Thanks! My only concern is the non-conventional use of passing metadata tags as JSON in a query parameter:

* S3, GCS and Azure Blob all use headers with a prefix (e.g. `X-Amz-Meta-<key>`, `X-Goog-Meta-<key>` and `X-Ms-Meta-<key>`, respectively)
* JSON in query parameters means doubly encoding values (first to JSON, then URL encoding). my concern here is not efficiency, it's ugly urls 🙂 - this is important for logging, auditing and human readability.

**Comment by nopcoder** [comment]
Agree with Oz about the ugly part - encoding a key/value like metadata is not easy to watch as escaped value in the query string.

File: pkg/api/helpers/upload.go [hunk 1]
```diff
@@ -6,21 +6,75 @@ import (
...
+func ClientUpload(ctx context.Context, client api.ClientWithResponsesInterface, repoID, branchID, objPath string, metadata map[string]string, contentType string, contents io.ReadSeeker) (*api.ObjectStats, error) {
+	pr, pw := io.Pipe()
+	defer func() {
+		_ = pr.Close()
+	}()
+	mpw := multipart.NewWriter(pw)
+	mpContentType := mpw.FormDataContentType()
+	go func() {
+		defer func() {
+			_ = pw.Close()
```
Comment (nopcoder) [inline pkg/api/helpers/upload.go:31]: 1. We should close `mpw` before `pw` - consider moving `mpw.Close` here
2. Verify if eveything works while calling `pw.CloseWithError` followed by all the defer Close class. (double close)

File: pkg/api/helpers/upload.go [hunk 2]
```diff
@@ -6,21 +6,75 @@ import (
...
+			_ = pw.CloseWithError(err)
+			return
+		}
+		_ = mpw.Close()
+	}()
+
+	resp, err := client.UploadObjectWithBodyWithResponse(ctx, repoID, branchID, &api.UploadObjectParams{
+		Path:         objPath,
+		UserMetadata: &api.ObjectUserMetadata{AdditionalProperties: metadata},
+	}, mpContentType, pr)
```
Comment (nopcoder) [inline pkg/api/helpers/upload.go:62]: The `pr` closes only in defer to `ClientUpload` - just wonder how the upload function reads under the end-of-file while we do not close the file/stream?

File: pkg/api/helpers/upload.go [hunk 3]
```diff
@@ -6,21 +6,75 @@ import (
...
+	if err != nil {
+		return nil, err
+	}
+	if resp.StatusCode() != http.StatusCreated {
```
Comment (nopcoder) [inline pkg/api/helpers/upload.go:66]: Prefer to compare JSON201 to non-nil instead of status code - had case where we had a valid status code with different content type.

File: pkg/api/helpers/upload.go [hunk 4]
```diff
@@ -6,21 +6,75 @@ import (
...
+}
+
 // ClientUploadDirect uploads contents as a file using client-side ("direct") access to underlying
 // storage.  It requires credentials both to lakeFS and to underlying storage, but
 // considerably reduces the load on the lakeFS server.
 func ClientUploadDirect(ctx context.Context, client api.ClientWithResponsesInterface, repoID, branchID, objPath string, metadata map[string]string, contentType string, contents io.ReadSeeker) (*api.ObjectStats, error) {
 	stagingLocation, err := getPhysicalAddress(ctx, client, repoID, branchID, &api.GetPhysicalAddressParams{
-		Path:    objPath,
-		Presign: swag.Bool(true),
+		Path: objPath,
```
Comment (nopcoder) [inline pkg/api/helpers/upload.go:77]: Thanks!

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/api/helpers/upload.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/api/helpers/upload.go:31]: 2. Works

File: pkg/api/helpers/upload.go (hunk 2 above)
Comment (N-o-Z) [reply pkg/api/helpers/upload.go:62]: The upload function copies `contents` into cw and then closes the mpw / pw pipe - which in turn causes pr to return EOF

File: pkg/api/controller.go [hunk 5]
```diff
@@ -2648,6 +2650,10 @@ func (c *Controller) UploadObject(w http.ResponseWriter, r *http.Request, reposi
 	} else {
 		entryBuilder.AddressType(catalog.AddressTypeFull)
 	}
+	meta := extractLakeFSMetadata(r.Header)
+	if meta != nil {
```
Comment (nopcoder) [inline pkg/api/controller.go:2654]: Use `len` it will catch nil and empty map (which is also the case for `extractLakeFSMetadata`

File: pkg/api/controller.go [hunk 6]
```diff
@@ -68,6 +68,8 @@ const (
 	httpStatusClientClosedRequest = 499
 	// httpStatusClientClosedRequestText text used for client closed request status code
 	httpStatusClientClosedRequestText = "Client closed request"
+
+	LakeFSHeaderPrefix = "x-lakefs-meta-"
```
Comment (nopcoder) [inline pkg/api/controller.go:72]:
```suggestion
	LakeFSMetaHeaderPrefix = "x-lakefs-meta-"
```

File: pkg/api/controller.go [hunk 7]
```diff
@@ -4830,3 +4836,14 @@ func encodeGCUncommittedMark(mark *catalog.GCUncommittedMark) (*string, error) {
 	token := base64.StdEncoding.EncodeToString(raw)
 	return &token, nil
 }
+
+func extractLakeFSMetadata(header http.Header) map[string]string {
```
Comment (nopcoder) [inline pkg/api/controller.go:4840]: 1. We can pass the prefix and this function will be more generic (extractMetadataByHeaderPrefix)
2. The metadata key should be without the prefix to make this one general solution for all the entry's metadata.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/api/controller.go (hunk 7 above)
Comment (N-o-Z) [reply pkg/api/controller.go:4842]: Please look again - I've made some adjustments

File: pkg/api/controller.go [hunk 8]
```diff
@@ -4830,3 +4838,18 @@ func encodeGCUncommittedMark(mark *catalog.GCUncommittedMark) (*string, error) {
...
+		lowerKey := strings.ToLower(k)
+		if strings.HasPrefix(lowerKey, LakeFSHeaderMetadataPrefix) {
+			_, metaKey, _ := strings.Cut(strings.ToLower(k), LakeFSHeaderMetadataPrefix)
+			meta[metaKey] = v[0]
+		} else if strings.HasPrefix(lowerKey, LakeFSHeaderInternalPrefix) {
+			_, metaKey, _ := strings.Cut(strings.ToLower(k), LakeFSHeaderInternalPrefix)
+			meta[LakeFSMetadataPrefix+metaKey] = v[0]
+		}
+	}
+	return meta
```
Comment (nopcoder) [inline pkg/api/controller.go:4854]: - reuse lowerKey instead of calling to lower again
- substring as we already matched the prefix

```suggestion
	meta := make(map[string]string)
	for k, v := range header {
		lowerKey := strings.ToLower(k)
		metaKey := ""
		if strings.HasPrefix(lowerKey, LakeFSHeaderMetadataPrefix) {
			metaKey = lowerKey[len(LakeFSHeaderMetadataPrefix):]
		} else if strings.HasPrefix(lowerKey, LakeFSHeaderInternalPrefix) {
			metaKey = LakeFSMetadataPrefix + lowerKey[len(LakeFSHeaderInternalPrefix):]
		} else {
			continue
		}
		meta[metaKey] = v[0]
	}
	return meta
```

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/local/sync.go [hunk 9]
```diff
@@ -284,8 +285,13 @@ func (s *SyncManager) upload(ctx context.Context, rootPath string, remote *uri.U
...
 	}()
 
+	mtimeKey := ClientMtimeHeaderKey
+	if s.presign {
+		mtimeKey = ClientMtimeMetadataKey
+	}
+
 	metadata := map[string]string{
-		ClientMtimeMetadataKey: strconv.FormatInt(fileStat.ModTime().Unix(), 10),
+		mtimeKey: strconv.FormatInt(fileStat.ModTime().Unix(), 10),
```
Comment (nopcoder) [inline pkg/local/sync.go:294]: can we pass the same metadata - the transport (upload presign) will detect the key type and add the header prefix to the key to transfer the headers

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/local/sync.go (hunk 9 above)
Comment (N-o-Z) [reply pkg/local/sync.go]: Done - hope it's ok now

File: pkg/local/sync.go [hunk 10]
```diff
@@ -285,9 +286,8 @@ func (s *SyncManager) upload(ctx context.Context, rootPath string, remote *uri.U
 	}()
 
 	metadata := map[string]string{
-		ClientMtimeMetadataKey: strconv.FormatInt(fileStat.ModTime().Unix(), 10),
+		ClientMtimeHeaderKey: strconv.FormatInt(fileStat.ModTime().Unix(), 10),
```
Comment (nopcoder) [inline pkg/local/sync.go]: Should use ClientMtimeMetadataKey

**Review by nopcoder — CHANGES_REQUESTED** [review]

**Review by nopcoder — APPROVED** [review]
LGTM!

**Comment by ozkatz** [comment]
Thanks @N-o-Z !! 
Is there a way to add this to Swagger (perhaps in a separate PR?) From what I gather, this is currently not exposed to generated clients..

**Comment by N-o-Z** [comment]
> Thanks @N-o-Z !! Is there a way to add this to Swagger (perhaps in a separate PR?) From what I gather, this is currently not exposed to generated clients.. not a blocked of course!

I'm assuming you mean for documentation purposes? I'll take a look into it
