### PR TITLE
Fix logging.IsTracing should check default logger level

### LINKED ISSUE #4251: Conditional logging.IsTracing doesn't work
The logging package IsTracing doesn't reflect the logging package tracing level.
Calling logging.SetLevel("trace") does not effect the return value from 'IsTracing' so any conditional code we use to print trace message does not execute.

### PR DESCRIPTION
**Pull request by nopcoder**
Fix #4251

### CODE REVIEW

**Review by Jonathan-Rosenberg — APPROVED** [review]
Thanks!

File: pkg/logging/logger.go [hunk 1]
```diff
@@ -271,7 +271,7 @@ func (l logrusEntryWrapper) Logf(level logrus.Level, format string, args ...inte
 }
 
 func (*logrusEntryWrapper) IsTracing() bool {
-	return logrus.IsLevelEnabled(logrus.TraceLevel)
+	return defaultLogger.IsLevelEnabled(logrus.TraceLevel)
```
Comment (arielshaqed) [inline pkg/logging/logger.go:274]: Neat!  I remember this line having a long and worrying history :-/

Comment (nopcoder) [reply pkg/logging/logger.go:274]: now I'm worried from the amount of logging while we trace.
