### PR TITLE
[Bug] Write headers just before writing contents

### LINKED ISSUE #6718: [Bug]: Unexpected error from gw -> get_object for small objects deleted from underlaying storage
### What happened?

When calling get_object through S3 gw on a small (or empty) object that has been deleted from the underlying storage, an unexpected `Internal Server Error` is returned.

### Expected behavior

Should return HTTP Status Code 410 (Gone)

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell
2023-10-06T07:12:35.199793485Z time="2023-10-06T07:12:35Z" level=error msg="encoding response failed" func="pkg/gateway/operations.(*PathOperation).EncodeError" file="build/pkg/gateway/operations/base.go:210" error="http: wrote more than the declared Content-Length"
```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by eladlachmi**
Closes #6718 

### Bug Fix

In S3 GW `get_object` operation, the headers (incl. `Content-Length`) are written too early. If we end up returning an error, there will be a mismatch between the returned content and the headers. 

For example, if an object is deleted from the underlying storage, we'd expect to get a response with HTTP status 410 (Gone). In practice, the response depends on the size of the object. If the object was smaller than the byte length of the error message, we'd get a server-side encoding error. If the object was larger than the byte length of the error message, we get a client-side error (depending on the client) since it reaches EOF before reading the expected content length.

Writing the headers after all the error checks and just before we write the object/range to the writer ensures this mismatch doesn't happen.

### Testing Details

The minio client used for S3 GW testing is too high-level to allow us to test the returned headers. It returns the object requested and abstracts away the underlying object store request. If also doesn't check the `Content-Length` header and reads the response buffer to completion. 

As validation, we'd like to see this PR pass existing tests (i.e., rule out regression). I'll open another issue to consider replacing the minio client used for our tests with one that allows lower-level testing of the response, incl. the returned headers.

### CODE REVIEW

File: esti/s3_gateway_test.go [hunk 1]
```diff
@@ -184,6 +208,27 @@ func TestS3ReadObject(t *testing.T) {
...
 		})
+
+		t.Run("Dosn't exist - should not have Content-Length header", func(t *testing.T) {
+			// using presigned URL so we can check the headers
+			preSignedUrl, err := client.Presign(ctx, "GET", repo, badPath, time.Second*60, url.Values{})
+			if err != nil {
+				t.Errorf("client.Presign(%s, %s): %s", repo, badPath, err)
+			}
+
+			req, err := http.NewRequest("GET", preSignedUrl.String(), nil)
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:219]:
```suggestion
			req, err := http.NewRequest(http.MethodGet, preSignedUrl.String(), nil)
```

File: esti/s3_gateway_test.go [hunk 2]
```diff
@@ -184,6 +208,27 @@ func TestS3ReadObject(t *testing.T) {
 					s3ErrorResponse, s3ErrorResponse.StatusCode)
 			}
 		})
+
+		t.Run("Dosn't exist - should not have Content-Length header", func(t *testing.T) {
+			// using presigned URL so we can check the headers
+			preSignedUrl, err := client.Presign(ctx, "GET", repo, badPath, time.Second*60, url.Values{})
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:214]:
```suggestion
			preSignedUrl, err := client.Presign(ctx, http.MethodGet, repo, badPath, time.Minute, url.Values{})
```

File: esti/s3_gateway_test.go [hunk 3]
```diff
@@ -168,6 +171,25 @@ func TestS3ReadObject(t *testing.T) {
...
+		t.Run("ExistsPreSigned", func(t *testing.T) {
+			// using presigned URL so we can check the headers
+			// We expect the Content-Length header to be set
+			preSignedUrl, err := client.Presign(ctx, http.MethodGet, repo, goodPath, time.Second*60, url.Values{})
+			if err != nil {
+				t.Fatalf("client.Presign(%s, %s): %s", repo, goodPath, err)
+			}
+
+			resp, err := http.Get(preSignedUrl.String())
+			defer func() { _ = resp.Body.Close() }()
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:183]: Move after the error check

File: esti/s3_gateway_test.go [hunk 4]
```diff
@@ -168,6 +171,25 @@ func TestS3ReadObject(t *testing.T) {
...
+			if err != nil {
+				t.Fatalf("http.DefaultClient.Do: %s", err)
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:185]:
```suggestion
				t.Fatalf("http.Get %s: %s", preSignedUrl.String(), err)
```

File: esti/s3_gateway_test.go [hunk 5]
```diff
@@ -168,6 +171,25 @@ func TestS3ReadObject(t *testing.T) {
 				t.Errorf("Got contents \"%s\" but expected \"%s\"", string(got), contents)
 			}
 		})
+		t.Run("ExistsPreSigned", func(t *testing.T) {
+			// using presigned URL so we can check the headers
+			// We expect the Content-Length header to be set
+			preSignedUrl, err := client.Presign(ctx, http.MethodGet, repo, goodPath, time.Second*60, url.Values{})
```
Comment (nopcoder) [inline esti/s3_gateway_test.go:177]: 1. Missed it before - can you rename `preSignedUrl` to `preSignedURL`
2. Didn't want to use `time.Minute`?

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: esti/s3_gateway_test.go (hunk 5 above)
Comment (eladlachmi) [reply esti/s3_gateway_test.go:177]: Since the presigned URL duration is in seconds, I thought it was more appropriate to use a Duration in seconds

File: esti/s3_gateway_test.go (hunk 3 above)
Comment (eladlachmi) [reply esti/s3_gateway_test.go]: Done

File: esti/s3_gateway_test.go (hunk 4 above)
Comment (eladlachmi) [reply esti/s3_gateway_test.go]: Done

File: esti/s3_gateway_test.go (hunk 5 above)
Comment (eladlachmi) [reply esti/s3_gateway_test.go]: No. 1 - Done

Comment (nopcoder) [reply esti/s3_gateway_test.go]: duration is in nanoseconds. and the constant time.Minute is 60 time.second

**Review by nopcoder — APPROVED** [review]
LGTM
