### PR TITLE
fixed broken Clipboard copy button

### LINKED ISSUE #1901: [UI] "Copy" buttons do not work
Clicks ok, but nothing gets copied to the clipboard.

### PR DESCRIPTION
**Pull request by ozkatz**
Closes #1901

### CODE REVIEW

File: webui/src/lib/components/controls.jsx [hunk 1]
```diff
@@ -235,7 +235,8 @@ export const ClipboardButton = ({ text, variant, onSuccess, icon = <ClippyIcon/>
                 show={show || isHovered}
                 target={target.current}>
                 {props => {
-                    updater = props.scheduleUpdate
+                    updater = (props.popper && props.popper.scheduleUpdate) ?
+                        props.popper.scheduleUpdate : null;
```
Comment (nopcoder) [inline webui/src/lib/components/controls.jsx:239]:
```suggestion
                    updater = props.popper && props.popper.scheduleUpdate;
```

**Review by nopcoder — APPROVED** [review]
LGTM!
