### PR TITLE
Fix login flow issues

### LINKED ISSUE #9505: Login flow issues when user is logged out
### What happened?

There are few issues in the login flow when running the lakeFS server while logged out (unauthenticated):

1. No redirect to login page from most of the endpoints: 
If we type any lakeFS path directly in the browser (other than /repositories, /auth/groups, or /auth/policies), instead of being redirected to the login page, we see this error:
Image

from /auth/credentials we see this error:
Image

from /auth/users we see no error, just emtpy page:
Image

When running lakeFS with no RBAC (auth.ui_config.rbac=none), the Users and Groups tabs under the Administration section are empty and dont redirect to the login page:
Image

2. Incorrect navbar on /auth/login
When first starting lakefs server while logged out (unauthenticated), the user is being redirected to /auth/login but the navbar displayed is the authenticated navbar (full navbar) instead of the simplified navbar:
Image

After refreshing the page, it changes to the expected simple navbar:
Image

* same happens If logged out, and we manually enter /repositories in the browser. We’re redirected to /auth/login but see the full navbar.

**Expected behavior:** When a user is not authenticated, the simple navbar should always be shown and not the full one, and all unauthenticated routes should consistently redirect to /auth/login.

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by Annaseli**
Closes #9505 

### Description

This PR fixes all the issues mentioned in the related issue.

I tested the login flow and confirmed that login flow works as expected, with all previously reported problems resolved in the following environments:
1. Local lakeFS OSS with no RBAC
2. Local lakeFS OSS with ACL
3. Local lakeFS Enterprise with local RBAC

### CODE REVIEW

File: webui/src/lib/components/auth/users.jsx [hunk 1]
```diff
@@ -4,17 +4,12 @@ export const allUsersFromLakeFS = async (resolveUserDisplayNameFN = (user => use
...
-        return [];
-    }
+    do {
+        const results = await auth.listUsers("", after, MAX_LISTING_AMOUNT);
+        usersList = usersList.concat(results.results);
+        after = results.pagination.next_offset;
+        hasMore = results.pagination.has_more;
+    } while (hasMore);
+    usersList.sort((a, b) => resolveUserDisplayNameFN(a).localeCompare(resolveUserDisplayNameFN(b)));
+    return usersList;
```
Comment (Annaseli) [inline webui/src/lib/components/auth/users.jsx:14]: The catch here prevented the error from being caught by useAPI, which is responsible for redirecting to `/auth/login`. Since this catch block didn’t do anything with the error, I removed it.

File: webui/src/lib/components/auth/layout.tsx [hunk 2]
```diff
@@ -9,62 +9,88 @@ import Card from "react-bootstrap/Card";
...
+                router.push({
+                    pathname: '/auth/login',
+                    params: {},
+                    query: { next: router.route, redirected: 'true' },
+                });
+                return;
+            }
+            setIsLogged(true);
+        }
+    }, [userWithId, loading, error, setIsLogged, router]);
```
Comment (Annaseli) [inline webui/src/lib/components/auth/layout.tsx]: By using useEffect, we can redirect to the login page from all of the Administration tabs instead of showing errors or an empty pages.

File: webui/src/lib/components/layout.tsx [hunk 3]
```diff
@@ -1,21 +1,33 @@
...
+    const userWithId = user as { id?: string } | null;
+
+    // Update isLogged state based on actual authentication status
+    useEffect(() => {
+        if (!loading) {
+            // If there's a user and no error, show authenticated (full) navbar
+            // If there's no user or there's an authentication error, show simple navbar
+            setIsLogged(Boolean((userWithId && userWithId.id !== "") && !error));
+        }
+    }, [userWithId, loading, error]);
```
Comment (Annaseli) [inline webui/src/lib/components/layout.tsx:21]: This fix ensures the navbar is displayed according to the user’s current authentication status.

File: webui/src/pages/repositories/repository/error.jsx [hunk 4]
```diff
@@ -30,7 +30,15 @@ const RepositoryInDeletionContainer = ({repoId}) => {
...
 
-export const RepoError = ({error}) => {
+export const RepoError = ({error, router}) => {
+    if (error instanceof AuthenticationError) {
+        router.push({
+            pathname: '/auth/login',
+            query: {next: router.route, redirected: true},
+        });
+        return null;
+    }
```
Comment (Annaseli) [inline webui/src/pages/repositories/repository/error.jsx]: Endpoints starting with /repositories return AlertError here before reaching the useAPI func that should redirect to /auth/login when the user is unauthenticated. i.e, the error occurs before the useAPI code executes, so before this change the error was simply displayed instead of triggering the redirect.

File: webui/src/lib/components/auth/layout.tsx [hunk 5]
```diff
@@ -9,62 +9,88 @@ import Card from "react-bootstrap/Card";
...
-        setIsLogged(true);
-    }, [setIsLogged]);
+        if (!loading) {
+            if (!userWithId || userWithId.id === "" || error) {
+                router.push({
+                    pathname: '/auth/login',
+                    params: {},
+                    query: { next: router.route, redirected: 'true' },
+                });
+                return;
```
Comment (itaigilo) [inline webui/src/lib/components/auth/layout.tsx]: This is very confusing.
Prefer `else` instead of `return` in this case.

File: webui/src/lib/components/auth/layout.tsx [hunk 6]
```diff
@@ -9,62 +9,88 @@ import Card from "react-bootstrap/Card";
...
     const [setIsLogged] = useLayoutOutletContext();
+    const { user, loading, error } = useUser();
+    const userWithId = user as { id?: string } | null;
+    const router = useRouter();
+
     useEffect(() => {
-        setIsLogged(true);
-    }, [setIsLogged]);
+        if (!loading) {
+            if (!userWithId || userWithId.id === "" || error) {
```
Comment (itaigilo) [inline webui/src/lib/components/auth/layout.tsx]: Can there be a `userWithId` which is not null but without `id`?

File: webui/src/lib/components/layout.tsx [hunk 7]
```diff
@@ -1,21 +1,33 @@
...
     const [isLogged, setIsLogged] = useState(logged ?? true);
+    const { user, loading, error } = useUser();
+    const userWithId = user as { id?: string } | null;
+
+    // Update isLogged state based on actual authentication status
+    useEffect(() => {
+        if (!loading) {
+            // If there's a user and no error, show authenticated (full) navbar
+            // If there's no user or there's an authentication error, show simple navbar
+            setIsLogged(Boolean((userWithId && userWithId.id !== "") && !error));
```
Comment (itaigilo) [inline webui/src/lib/components/layout.tsx]:
```suggestion
            setIsLogged(userWithId?.id !== "" && !error);
```

Comment (itaigilo) [reply webui/src/lib/components/layout.tsx]: But double-check this one ☝️ 😄

File: webui/src/pages/repositories/repository/error.jsx [hunk 8]
```diff
@@ -30,7 +30,15 @@ const RepositoryInDeletionContainer = ({repoId}) => {
     );
 };
 
-export const RepoError = ({error}) => {
+export const RepoError = ({error, router}) => {
```
Comment (itaigilo) [inline webui/src/pages/repositories/repository/error.jsx]: There's no need to pass `router` as param - 
You can have `useRouter()` here.

File: webui/src/pages/repositories/repository/error.jsx [hunk 9]
```diff
@@ -30,7 +30,15 @@ const RepositoryInDeletionContainer = ({repoId}) => {
...
+    if (error instanceof AuthenticationError) {
+        router.push({
```
Comment (itaigilo) [inline webui/src/pages/repositories/repository/error.jsx]: I would expect this `RepoError` component to contain only a rendering of the UI, not routing logic.
We should strive to have the routing logic at the "top" of the components tree, otherwise it becomes a nightmare to understand, for example, which component ended up causing the `router.push()`, making it very hard to maintain and to debug.

Have you tried placing it in the place where this error is originally produced?
I think that `RefContextProvider` should be it, but I'm not sure it's the source for all these `RepoError`s.

**Review by nopcoder — CHANGES_REQUESTED** [review]
Don't think that `RepoError` should redirect - at this level when we render a control to display an error we should not make this call.

The `useAPI` and similar that handle the API call should handle this state and update that we need to redirect user to the login page.

File: webui/src/lib/components/auth/layout.tsx (hunk 6 above)
Comment (Annaseli) [reply webui/src/lib/components/auth/layout.tsx]: we get userWithId from useUser(), which calls `auth.getCurrentUserWithCache()`. If the user data isn’t cached, this function fetches it from the `/user` endpoint.

According to Swagger, the `/user` endpoint when returns status code 200, returns a CurrentUser schema, which returns the User schema:

```
    User:
      type: object
      required:
        - id
        - creation_date
      properties:
        id:
          type: string
          description: A unique identifier for the user. Cannot be edited.
        creation_date:
          type: integer
          format: int64
          description: Unix Epoch in seconds
...
```

Because id is a required field in this schema, the id property must exist when userWithId is not null.

Also in the browser, when the user is unauthenticated, we see:

image

File: webui/src/lib/components/layout.tsx (hunk 7 above)
Comment (Annaseli) [reply webui/src/lib/components/layout.tsx]: For the:
`setIsLogged(userWithId?.id !== "" && !error);`

there will be an issue when userWithId is null or undefined:
`null?.id !== "" → undefined !== "" → true` so if there is no error we will get: `true && !error` -> true

while with the current code:
`null && * → false`

So the behavior differs.

But I did remove the redundant parentheses around (userWithId && userWithId.id !== "") and replaced the Boolean() cast with !! (since omitting it leads to a TypeScript error):

image

File: webui/src/pages/repositories/repository/error.jsx (hunk 9 above)
Comment (Annaseli) [reply webui/src/pages/repositories/repository/error.jsx]: I changed the code so that the `RefContextProvider` now uses `useAPI()` since `useAPI()` automatically redirects to the login page when the user is unauthenticated. Changed the `RefContextProvider` because `useRefs()` receives its data from the `RefContextProvider`, and the errors returned from `useRefs()` are passed to the `RepoError` component for display.

**Comment by Annaseli** [comment]
> Don't think that `RepoError` should redirect - at this level when we render a control to display an error we should not make this call.
> 
> The `useAPI` and similar that handle the API call should handle this state and update that we need to redirect user to the login page.

I changed the code so that the `RefContextProvider` now uses `useAPI()` since `useAPI()` automatically redirects to the login page when the user is unauthenticated. Changed the `RefContextProvider` because `useRefs()` receives its data from the `RefContextProvider`, and the errors returned from `useRefs()` are passed to the `RepoError` component for display.

File: webui/src/lib/components/auth/layout.tsx (hunk 6 above)
Comment (itaigilo) [reply webui/src/lib/components/auth/layout.tsx]: So `if (!userWithId || error) {` should be enough, no?
Since `id` can't be empty?

(It's nit, ofc.)

File: webui/src/lib/components/auth/layout.tsx [hunk 10]
```diff
@@ -9,62 +9,88 @@ import Card from "react-bootstrap/Card";
...
+            }
+        }
+    }, [userWithId, loading, error, setIsLogged, router]);
+
+    if (loading) {
+        return <Loading/>;
+    }
+
+    // Don't render anything if not authenticated (will redirect)
+    if (!userWithId || userWithId.id === "" || error) {
```
Comment (itaigilo) [inline webui/src/lib/components/auth/layout.tsx]: I suggest loading in this case as well (better see a loader than a blank screen that might look like something is stuck) - 
But up to you.

File: webui/src/lib/components/layout.tsx [hunk 11]
```diff
@@ -1,21 +1,32 @@
...
+    }, [userWithId, loading, error]);
 
     // handle global dark mode here
     const {state} = useContext(AppContext);
     document.documentElement.setAttribute('data-bs-theme', state.settings.darkMode ? 'dark' : 'light')
 
     return (
         <ConfigProvider>
-            <TopNav logged={isLogged}/>
+            {!loading && <TopNav logged={isLogged}/>}
```
Comment (itaigilo) [inline webui/src/lib/components/layout.tsx:29]: Is `loading == true` only after the login form is submitted?
Or are there other situations?

File: webui/src/lib/hooks/repo.jsx [hunk 12]
```diff
@@ -45,39 +46,29 @@ export const useRefs = () => {
...
-                setRefState({...refContextInitialState, loading: false, repo, reference, compare: comparedRef});
-            } catch (err) {
-                setRefState({...refContextInitialState, loading: false, error: err});
-            }
-        };
-        fetch();
+    const { response, error, loading } = useAPI(async () => {
+        if (!repoId) return null;
+        const repo = await repositories.get(repoId);
+        const reference = await resolveRef(repoId, (ref) ? ref : repo.default_branch);
```
Comment (itaigilo) [inline webui/src/lib/hooks/repo.jsx]: While you're at it:

Comment (itaigilo) [inline webui/src/lib/hooks/repo.jsx]:
```suggestion
        const reference = await resolveRef(repoId, ref || repo.default_branch);
```

File: webui/src/lib/hooks/repo.jsx [hunk 13]
```diff
@@ -45,39 +46,29 @@ export const useRefs = () => {
...
+        const comparedRef = await resolveRef(repoId, (compare)? compare : repo.default_branch);
```
Comment (itaigilo) [inline webui/src/lib/hooks/repo.jsx]:
```suggestion
        const comparedRef = await resolveRef(repoId, compare || repo.default_branch);
```

File: webui/src/lib/components/auth/layout.tsx (hunk 2 above)
Comment (itaigilo) [reply webui/src/lib/components/auth/layout.tsx]: You're already handling this in layout.tsx -
I think it's way better to do this routing there.
It keeps everything in one place, and doesn't require importing the useLayoutOutletContext.
It might catch future redirections that might occur in the "app layout" level.

File: webui/src/lib/components/auth/layout.tsx (hunk 6 above)
Comment (Annaseli) [reply webui/src/lib/components/auth/layout.tsx]: @itaigilo 
`userWithId.id` is always present, but it can be an empty string. It’s empty when the user is logged out. So, checking whether this value is empty is the key test for determining if the user is logged in or not.

File: webui/src/lib/components/auth/layout.tsx (hunk 10 above)
Comment (Annaseli) [reply webui/src/lib/components/auth/layout.tsx]: consulted about it also with chatGPT and it says:

short answer: show a loading state only when the auth status is still unknown; otherwise keep return null while you redirect.

**Why**

If you’re already sure isLogged === false, you immediately redirect in the effect. Rendering a spinner for a frame just before redirect often causes a flicker. return null is fine here.

Showing a spinner makes sense when auth is still loading (e.g., useUser() hasn’t resolved yet).

___

so I think i'll leave the return null and return the <Loading/> only while loading.

File: webui/src/lib/components/layout.tsx (hunk 11 above)
Comment (Annaseli) [reply webui/src/lib/components/layout.tsx:29]: The `loading` comes from the `useUser()` call.  It is `loading == true` only while waiting for the `/user` data to be fetched.

File: webui/src/lib/components/auth/layout.tsx (hunk 2 above)
Comment (Annaseli) [reply webui/src/lib/components/auth/layout.tsx]: As discussed, I’m keeping this `router.push()` code here and will open a relevant issue for refactoring.

File: webui/src/lib/components/auth/layout.tsx [hunk 14]
```diff
@@ -9,62 +9,76 @@ import Card from "react-bootstrap/Card";
...
 type AuthOutletContext = [(tab: string) => void];
 
 const rbacDismissedKey = "lakefs:ui:acl:dismissRBACAlert";
 export const AuthLayout = () => {
     const [showRBACAlert, setShowRBACAlert] = useState(!window.localStorage.getItem(rbacDismissedKey));
-    const [activeTab, setActiveTab] = useState("credentials");  
+    const [activeTab, setActiveTab] = useState("credentials");
     const {RBAC: rbac} = useLoginConfigContext();
-    const [setIsLogged] = useLayoutOutletContext();
+    const [loading, isLogged] = useLayoutOutletContext();
```
Comment (itaigilo) [inline webui/src/lib/components/auth/layout.tsx]: Shouldn't this be:
```const [isLogged, setIsLogged] = useLayoutOutletContext();```
?

Why it has a different structure?

Comment (Annaseli) [reply webui/src/lib/components/auth/layout.tsx]: @itaigilo 
I updated the parent Layout component to:
`<Outlet context={[loading, isLogged, setIsLogged] satisfies LayoutOutletContext}/>`

instead of:
`<Outlet context={[setIsLogged] satisfies LayoutOutletContext}/>`

I need `const [loading, isLogged] = useLayoutOutletContext();` and not `const [isLogged, setIsLogged] = useLayoutOutletContext();` because in AuthLayout I check whether the user is logged in. Since this check is already done in Layout, I can use the `isLogged` value passed through the context, rather than re-calling `useUser()`. So I needed the `isLogged ` and didn't need the `setIsLogged `. There is no usage in `setIsLogged ` in the updated AuthLayout component. (It also doesn't pass it to other components)

And I added `loading` to the `useLayoutOutletContext () ` because it is returned from calling to the `useUser` (which is called in Layout). I need the `loading` in the AuthLayout so that I can add this:
`if (loading) return <Loading/>`

So AuthLayout needs both `isLogged` and `loading` via useLayoutOutletContext, and not the `setIsLogged `

File: webui/src/pages/repositories/repository/objects.jsx
Comment (itaigilo) [inline webui/src/pages/repositories/repository/objects.jsx:1]: Pretty weird, to have only whitespace changes for files.
_Next time,_ please try to avoid this.

File: webui/src/lib/components/layout.tsx [hunk 15]
```diff
@@ -1,23 +1,34 @@
...
 const Layout: FC<{logged: boolean}> = ({logged}) => {
     const [isLogged, setIsLogged] = useState(logged ?? true);
+    const { user, loading, error } = useUser();
+    const userWithId = user as { id?: string } | null;
+
+    // Update isLogged state based on actual authentication status
+    useEffect(() => {
+        if (!loading) {
+            // If there's a user and no error, show authenticated (full) navbar
+            setIsLogged(!!(userWithId && userWithId.id !== "" && !error));
```
Comment (itaigilo) [inline webui/src/lib/components/layout.tsx]:
```suggestion
            setIsLogged(!(userWithId?.id) && !error);
```

File: webui/src/lib/components/auth/layout.tsx [hunk 16]
```diff
@@ -17,54 +18,65 @@ type AuthOutletContext = [(tab: string) => void];
...
     const {RBAC: rbac} = useLoginConfigContext();
-    const [setIsLogged] = useLayoutOutletContext();
+    const [isLogged] = useLayoutOutletContext();
+    const router = useRouter();
+
     useEffect(() => {
-        setIsLogged(true);
-    }, [setIsLogged]);
+        if (!isLogged) {
+            router.push({
```
Comment (itaigilo) [inline webui/src/lib/components/auth/layout.tsx:30]: Can you please add a comment here, explaining why this redirection is done here, and not it the place that gets the `isLogged` in first place (the top-level `layout`)?

File: webui/src/lib/hooks/repo.jsx [hunk 17]
```diff
@@ -45,39 +46,29 @@ export const useRefs = () => {
...
-        fetch();
+    const { response, error, loading } = useAPI(async () => {
+        if (!repoId) return null;
+        const repo = await repositories.get(repoId);
+        const reference = await resolveRef(repoId, ref || repo.default_branch);
+        const comparedRef = await resolveRef(repoId, compare || repo.default_branch);
+        return { repo, reference, compare: comparedRef };
     }, [repoId, ref, compare]);
 
+    const refState = {
```
Comment (itaigilo) [inline webui/src/lib/hooks/repo.jsx]: So refState is a const, and nothing changes it?
Or am I missing something?
What makes it a `state`?

File: webui/src/lib/components/layout.tsx (hunk 15 above)
Comment (Annaseli) [reply webui/src/lib/components/layout.tsx]: I think that `!(userWithId?.id) && !error` is the opposite of `!!(userWithId && userWithId.id !== "" && !error)` because:

for `!(userWithId?.id) && !error`:
if user is logged out and there is no error =>  `userWithId.id==""` => `userWithId?.id` is false   => !(userWithId?.id) is true => !(userWithId?.id) && !error is true
so in this case when user is logged out we get setIsLogged(true) instead of setIsLogged(false)

Did you mean this?
`setIsLogged(!!userWithId?.id && !error);` (!! equals Boolean())

I updated the code to this - `setIsLogged(!!userWithId?.id && !error);`
but LMK if you meant something else.

File: webui/src/lib/hooks/repo.jsx (hunk 17 above)
Comment (Annaseli) [reply webui/src/lib/hooks/repo.jsx]: The "state" behavior comes from the useAPI hook.
When the async operation in useAPI completes or dependencies [repoId, ref, compare] change, useAPI triggers a re-render.
On each re-render, a new refState object is created with the updated values from useAPI.
This new object gets passed through the context, notifying all consumers.
So while refState is const within each render, it's recreated on every render with potentially different values. 
So It's a derived state - refState is derived from the useAPI hook's internal state, not a state variable itself.

And useAPI already uses useEffect to execute the promise (fetch the data in this case).
It initializes state and manages loading and error handling internally, so we delegate that responsibility to useAPI.

Comment (itaigilo) [reply webui/src/lib/hooks/repo.jsx]: Great, thanks for the details.

To make things (maybe) clearer, I would've renamed `refState` to `refsState` (which is nit),
And change the `const [ refs ] = useContext(RefContext);` above to `const [ refsState ] = useContext(RefContext);`. This way, it might be clearer that this const is the only object that actually accesses the `refsState` you create here.

But that's not blocking.
