### PR TITLE
Stabilize lakectl ingest test by replacing equal match with contains

### LINKED ISSUE #3685: TestLakectlIngestS3 is flaky
Some failing ingest test, for example:
https://github.com/treeverse/lakeFS/runs/7395268455?check_suite_focus=true

### PR DESCRIPTION
**Pull request by itaiad200**
closes #3685

### CODE REVIEW

File: esti/lakectl_util.go [hunk 1]
```diff
@@ -134,6 +134,13 @@ func RunCmdAndVerifySuccessWithFile(t *testing.T, cmd string, isTerminal bool, g
 	runCmdAndVerifyWithFile(t, cmd, goldenFile, false, isTerminal, vars)
 }
 
+func RunCmdAndVerifyContainsText(t *testing.T, cmd string, isTerminal bool, expectedRaw string, vars map[string]string) {
+	t.Helper()
+	expected := sanitize(expectedRaw, vars)
+	sanitizedResult := runCmd(t, cmd, false, isTerminal, vars)
+	require.Contains(t, sanitizedResult, expected)
```
Comment (itai-david) [inline esti/lakectl_util.go:141]: Nice :+1:

**Review by itai-david — APPROVED** [review]
Nice and required addition to our lakectl testing infrastructure. Thanks
