### PR TITLE
Stabilize TestExecutor__BatchFor

### LINKED ISSUE #1647: TestExecutor_BatchFor is flaky
--- FAIL: TestExecutor_BatchFor (0.15s)
    executor_test.go:73: this should not be called, only r1's

### PR DESCRIPTION
**Pull request by talSofer**
fix #1647

**Background**
To reduce db access frequency, the executor intends to batch identical requests that are made in a pre-defined delay, and TestExecutor_BatchFor is to prove that read after write consistency is preserved with the batching logic. 
In this unit test, we simulate the following scenario: 
1. reader (r1) starts (Current version: v0)
2. writer (w1) writes v1
3. writer (w1) returns (Current version: v1)
4. reader (r2) starts
5. both readers (r1,r2) return with v1 as their response.

The root cause for the bug was that the test didn't guarantee that r1 and r2 are part of the same batch, causing r2 to trigger an additional call to the db. 

**Change list** 
1. Stabilize TestExecutor_BatchFor by forcing reader1 and reader2 to be part of the same batch. 
2. Fix the test failures in https://github.com/treeverse/lakeFS/runs/2119092066?check_suite_focus=true by eliminating the usage of t.Fatalf
3. Add two more unit tests for the batcher functionality.

### CODE REVIEW

File: pkg/batch/executor.go [hunk 1]
```diff
@@ -11,19 +11,31 @@ import (
 // dispatching new ones would start blocking.
 const RequestBufferSize = 1 << 17
 
+type Executable interface {
+	Execute() (interface{}, error)
+}
+
+type Batchable interface {
+	Batched()
```
Comment (arielshaqed) [inline pkg/batch/executor.go:19]: Can you document this method?  I _think_ it's what the JavaScript world would call `OnBatched`.

File: pkg/batch/executor.go [hunk 2]
```diff
@@ -11,19 +11,31 @@ import (
 // dispatching new ones would start blocking.
 const RequestBufferSize = 1 << 17
 
+type Executable interface {
```
Comment (arielshaqed) [inline pkg/batch/executor.go:14]: I think this should be

```suggestion
type Executer interface {
```

according to https://golang.org/doc/effective_go#interface-names.

File: pkg/batch/executor.go [hunk 3]
```diff
@@ -11,19 +11,31 @@ import (
...
+	Execute() (interface{}, error)
+}
+
+type Batchable interface {
```
Comment (arielshaqed) [inline pkg/batch/executor.go:18]: Similarly, this should also be a `-er` if possible.  In this case the name also misled me, because in fact we do allow non-`Batchable` operations to be batched.

File: pkg/batch/executor_test.go [hunk 4]
```diff
@@ -11,6 +11,50 @@ import (
 	"github.com/treeverse/lakefs/pkg/logging"
 )
 
+const accessedOnce = 1
+const accessedTwice = 2
+
+type reader struct {
+	Ch         chan bool
```
Comment (arielshaqed) [inline pkg/batch/executor_test.go:18]: Can you name this to refer to what it does, or alternatively add a comment?

Comment (arielshaqed) [inline pkg/batch/executor_test.go:18]: Also, AFAICT this could even be
```suggestion
	Ch         chan struct{}
```
since we only ever close it.

File: pkg/batch/executor_test.go [hunk 5]
```diff
@@ -11,6 +11,50 @@ import (
...
+	Get(key string) string
+	GetCount() int
+}
+
+func (d *db) Insert(key string, val string) {
+	d.KvStore.Store(key, val)
+}
+
+func (d *db) Get(key string) (interface{}, bool) {
+	d.AccessCount++
```
Comment (arielshaqed) [inline pkg/batch/executor_test.go:50]: Given that `KvStore` is a `sync.Map`, this is a race.  You might need to perform an atomic action here, or just lock the whole `db` and do away with the `sync.Map`.

File: pkg/batch/executor_test.go [hunk 6]
```diff
@@ -24,12 +68,13 @@ func testReadAfterWrite(t *testing.T) {
 	// 3. writer (w1) returns (Current version: v1)
 	// 4. reader (r2) starts
 	// 5. both readers (r1,r2) return with v1 as their response.
-	var db = sync.Map{}
-	db.Store("v", "v0")
+	var db = &db{sync.Map{}, 0}
```
Comment (arielshaqed) [inline pkg/batch/executor_test.go:71]: I think these are the defaults; you could just use

```suggestion
	var db = &db{}
```

File: pkg/batch/executor_test.go [hunk 7]
```diff
@@ -11,6 +11,50 @@ import (
 	"github.com/treeverse/lakefs/pkg/logging"
 )
 
+const accessedOnce = 1
+const accessedTwice = 2
```
Comment (arielshaqed) [inline pkg/batch/executor_test.go:15]: Not a fan of explicitly naming "1" and "2": they appear in the names, and cannot be changed without changing the name and all of its occurrences (and checking at each occurrence whether it needs to be kept or changed).  E.g., if for some reason the second number had to change to 17, the change would be
```go
const accessedSeventeenTimes = 17
```
rather than
```go
const accessedTwice = 17
```
and we would _still_ need to go over each `accessedTwice` to determine how many times we now want it to be accessed.

The same holds for `accessedOnce`: wherever we use it, it's easier for me just to read the number 1.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Cool, thanks!

Only _required_ change is the race on the counter in the test code.

File: pkg/batch/executor_test.go [hunk 8]
```diff
@@ -11,6 +11,50 @@ import (
...
+func (r *reader) Batched() {
+	close(r.Ch)
+}
+
+type db struct {
+	KvStore     sync.Map
+	AccessCount int
+}
+
+type Dao interface {
```
Comment (nopcoder) [inline pkg/batch/executor_test.go:39]: No need to Dao interface

File: pkg/batch/executor_test.go [hunk 9]
```diff
@@ -40,49 +85,154 @@ func testReadAfterWrite(t *testing.T) {
...
+	}(&r2)
+
 	<-read1Done
 	<-read2Done
+
+	r1Succeeded := r1.IsExecuted
+	r2Succeeded := r2.IsExecuted
+	if !(r1Succeeded && r2Succeeded) {
+		t.Error("both r1 and r2's exec functions should be executed but r1Succeeded=#{r1Succeeded} " +
+			"and r2Succeeded=#{r1Succeeded}")
```
Comment (itaiad200) [inline pkg/batch/executor_test.go:234]:
```suggestion
			"and r2Succeeded=#{r2Succeeded}")
```

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Great work on solving the flakiness and adding an important coverage to the executor! 
Requesting changes mainly due to a few nits, but otherwise looks good!

File: pkg/batch/executor_test.go [hunk 10]
```diff
@@ -11,6 +11,50 @@ import (
 	"github.com/treeverse/lakefs/pkg/logging"
 )
 
+const accessedOnce = 1
+const accessedTwice = 2
+
+type reader struct {
+	Ch         chan bool
+	IsExecuted bool
+	Fn         ExecFn
```
Comment (nopcoder) [inline pkg/batch/executor_test.go:20]: Think that adding `Fn` callback as part of the reader which is a callback can make the code a bit complex.
Based on the use of this function I suggest just adding another channel, one that the reader will close when it is executed.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/batch/executor_test.go [hunk 11]
```diff
@@ -11,6 +11,50 @@ import (
 	"github.com/treeverse/lakefs/pkg/logging"
 )
 
+const accessedOnce = 1
+const accessedTwice = 2
+
+type reader struct {
```
[the remark this answers is not in the document]
Comment (talSofer) [reply pkg/batch/executor_test.go:17]: Yes, thanks :)

File: pkg/batch/executor_test.go (hunk 7 above)
Comment (talSofer) [reply pkg/batch/executor_test.go:15]: > cannot be changed without changing the name and all of its occurrences
Good point, I removed the constants because they are no longer used by multiple unit tests but I agree.

File: pkg/batch/executor_test.go [hunk 12]
```diff
@@ -40,49 +85,154 @@ func testReadAfterWrite(t *testing.T) {
...
+	go func() {
+		<-read1Done // ensure r2 starts after r1 has returned
+		exec.BatchFor("k", time.Millisecond*50, batch.BatchFn(func() (interface{}, error) {
+			version, _ := db.Get("v")
+			return version, nil
+		}))
+		ac := db.GetAccessCount()
+		if ac != accessedTwice {
+			t.Errorf("r2 should have triggered the second db call, but access count= #{ac}")
 		}
```
[the remark this answers is not in the document]
Comment (talSofer) [reply pkg/batch/executor_test.go:172]: I changed the test logic so this part of the test no longer exists

File: pkg/batch/executor.go [hunk 13]
```diff
@@ -11,8 +11,20 @@ import (
...
```
[the remark this answers is not in the document]
Comment (talSofer) [reply pkg/batch/executor.go:18]: This is what I changed it to  would you add additional documentation to it?   
```
type BatchTracker interface {
	// This method should be called on adding a request to an existing batch
	Batched()
}

File: pkg/batch/executor.go [hunk 14]
```diff
@@ -83,20 +95,25 @@ func (e *Executor) Run(ctx context.Context) {
...
+				e.waitingOnKey[req.key] = []*request{req}
 				// this is a new key, let's fire a timer for it
 				go func(req *request) {
 					e.Delay(req.timeout)
 					e.execs <- req.key
 				}(req)
+			} else {
+				if b, ok := req.exec.(Batchable); ok {
+					b.Batched()
+				}
```
[the remark this answers is not in the document]
Comment (talSofer) [reply pkg/batch/executor.go]: You are right, there is is no chance that `req.exec` is not batchable, that was a misleading interface name. In the updated version of this code it is called "batchTracker". and there could be `req.exe` that are not trackable.

**Review by itaiad200 — APPROVED** [review]
More tests and less flakiness, good job!

File: pkg/batch/executor.go [hunk 15]
```diff
@@ -11,11 +11,12 @@ import (
...
 const RequestBufferSize = 1 << 17
 
-type Executable interface {
+type Executer interface {
 	Execute() (interface{}, error)
 }
 
-type Batchable interface {
+type BatchTracker interface {
+	// This method should be called on adding a request to an existing batch
```
Comment (arielshaqed) [inline pkg/batch/executor.go:19]: Go has weird documentation rules.  Here it should probably be
```suggestion
	// Batched is called when a request is added to an existing batch.
```

File: pkg/batch/executor.go [hunk 16]
```diff
@@ -28,14 +29,14 @@ func (b BatchFn) Execute() (interface{}, error) {
...
-	BatchFor(key string, dur time.Duration, exec Executable) (interface{}, error)
+	BatchFor(key string, dur time.Duration, exec Executer) (interface{}, error)
 }
 
 type nonBatchingExecutor struct {
 }
 
-func (n *nonBatchingExecutor) BatchFor(_ string, _ time.Duration, exec Executable) (interface{}, error) {
-	return exec.Execute()
+func (n *nonBatchingExecutor) BatchFor(_ string, _ time.Duration, ft Executer) (interface{}, error) {
```
Comment (arielshaqed) [inline pkg/batch/executor.go:38]: Not a fan of this renaming: it is not clear what "ft" means.  (I would be OK with a single-letter name because the scope is so short, and the single letter clearly means nothing.  Just "`ft`" makes me try to glean a meaning, which is unimportant here.)

**Review by arielshaqed — APPROVED** [review]
Thanks, nice work!

As discussed F2F, I find the channel-based reporting trickier to understand than an atomic variable would have been.  However, given that the standard Go API for atomics is so easy to skip, I can understand why you implement nonblocking signalling by channel.

No comments are required (let alone blocking).

File: pkg/batch/executor.go (hunk 16 above)
Comment (talSofer) [reply pkg/batch/executor.go:38]: nice catch thanks! this are the leftovers from the experimental rename I did to fetcher. I changed it back to exec

File: pkg/batch/executor_test.go [hunk 17]
```diff
@@ -115,12 +117,15 @@ func testReadAfterWrite(t *testing.T) {
...
-		if r.IsExecuted || db.GetAccessCount() != accessedOnce {
+		te := trackableExecuter{batchTracker: read2Batched, execTracker: make(chan struct{})}
+		r2, _ := exec.BatchFor("k", 50*time.Millisecond, &te)
+		r2v := r2.(string)
+		if r2v != "v1" {
+			t.Errorf("expected r2 to get v1, got %s instead", r2v)
+		}
+
+		// We expect r2's exec function to not execute because it should join r1's batch
+		if te.WasExecuted() || db.GetAccessCount() != 1 {
```
Comment (nopcoder) [inline pkg/batch/executor_test.go:128]: can you split the check into 2 if(s) so when it will fail we will know which one failed or capture the result of the check and print it

File: pkg/batch/executor_test.go [hunk 18]
```diff
@@ -198,40 +199,34 @@ func testBatchByKey(t *testing.T) {
...
 
-	r1Succeeded := r1.IsExecuted
-	r2Succeeded := r2.IsExecuted
+	r1Succeeded := te1.WasExecuted()
+	r2Succeeded := te2.WasExecuted()
 	if !(r1Succeeded && r2Succeeded) {
-		t.Error("both r1 and r2's exec functions should be executed but r1Succeeded=#{r1Succeeded} " +
-			"and r2Succeeded=#{r1Succeeded}")
+		t.Error("both r1's and r2's exec functions should be executed but r1Succeeded=#{r1Succeeded} " +
+			"and r2Succeeded=#{r2Succeeded}")
```
Comment (nopcoder) [inline pkg/batch/executor_test.go:229]:
```suggestion
		t.Errorf("both r1's and r2's exec functions should be executed but r1Succeeded=%t and r2Succeeded=%t", r1Succeeded, r2Succeeded)
```

File: pkg/batch/executor_test.go [hunk 19]
```diff
@@ -133,42 +138,37 @@ func testReadAfterWrite(t *testing.T) {
...
-			version, _ := db.Get("v")
-			return version, nil
+		r1, _ := exec.BatchFor("k", time.Millisecond*50, batch.BatchFn(func() (interface{}, error) {
+			return "v1", nil
 		}))
-		ac := db.GetAccessCount()
-		if ac != accessedOnce {
-			t.Errorf("r1 should have triggered a single db call, but access count= #{ac}")
+		if r1 != "v1" {
+			t.Errorf("expected r1 to get v1 but got #{r1} instead")
```
Comment (nopcoder) [inline pkg/batch/executor_test.go:160]:
```suggestion
			t.Errorf("expected r1 to get v1 but got '%s' instead", r1)
```

File: pkg/batch/executor_test.go [hunk 20]
```diff
@@ -133,42 +138,37 @@ func testReadAfterWrite(t *testing.T) {
...
-			version, _ := db.Get("v")
-			return version, nil
+		r2, _ := exec.BatchFor("k", time.Millisecond*50, batch.BatchFn(func() (interface{}, error) {
+			return "v2", nil
 		}))
-		ac := db.GetAccessCount()
-		if ac != accessedTwice {
-			t.Errorf("r2 should have triggered the second db call, but access count= #{ac}")
+		if r2 != "v2" {
+			t.Errorf("expected r2 to get v2 but got #{r2} instead")
```
Comment (nopcoder) [inline pkg/batch/executor_test.go:171]:
```suggestion
			t.Errorf("expected r2 to get v2 but got '%s' instead", r2)
```

**Review by nopcoder — CHANGES_REQUESTED** [review]

**Review by nopcoder — APPROVED** [review]
