### PR TITLE
Fix: S3 GW ListParts

### LINKED ISSUE #7599: Fix S3 Gateway ListParts
When using boto3, currently trying to list parts results the following error:

```
An error occurred (NoSuchKey) when calling the ListParts operation: The specified key does not exist.
```

This issue should cover support for AWS S3,
Other adapters will be tracked in separate issues

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #7599

### CODE REVIEW

File: pkg/block/blocktest/adapter.go [hunk 1]
```diff
@@ -217,11 +218,20 @@ func testAdapterMultipartUpload(t *testing.T, adapter block.Adapter, storageName
...
 		t.Run(c.name, func(t *testing.T) {
+			blockstoreType := adapter.BlockstoreType()
 			obj := block.ObjectPointer{
 				StorageNamespace: storageNamespace,
 				Identifier:       c.path,
 				IdentifierType:   block.IdentifierTypeRelative,
 			}
+			// List parts on non-existing part
+			_, err := adapter.ListParts(ctx, obj, "invalidId", block.ListPartsOpts{})
+			if blockstoreType != block.BlockstoreTypeS3 {
```
Comment (arielshaqed) [inline pkg/block/blocktest/adapter.go:229]: This is beautiful: it will force us to fix the test as soon as we fix Azure / GCS! :-)

File: pkg/block/blocktest/adapter.go [hunk 2]
```diff
@@ -233,11 +243,47 @@ func testAdapterMultipartUpload(t *testing.T, adapter block.Adapter, storageName
...
+				require.ErrorIs(t, err, block.ErrOperationNotSupported)
+			} else {
+				require.NoError(t, err)
+				require.Equal(t, len(parts), len(listResp.Parts))
+				for i, part := range listResp.Parts {
+					require.Equal(t, multiParts[i].PartNumber, part.PartNumber)
+					require.Equal(t, int64(len(parts[i])), part.Size)
+					require.Equal(t, multiParts[i].ETag, part.ETag)
+					require.False(t, listResp.IsTruncated)
```
Comment (arielshaqed) [inline pkg/block/blocktest/adapter.go:258]: I always prefer either to compare the entire struct for equality or to use `assert.Equal`.  That ensures that when the test fails I get as much information as possible.

File: pkg/block/blocktest/adapter.go [hunk 3]
```diff
@@ -233,11 +243,47 @@ func testAdapterMultipartUpload(t *testing.T, adapter block.Adapter, storageName
...
 				Part: multiParts,
 			})
 			require.NoError(t, err)
 
+			// List parts after complete should fail
+			_, err = adapter.ListParts(ctx, obj, resp.UploadID, block.ListPartsOpts{})
+			if blockstoreType != block.BlockstoreTypeS3 {
+				require.ErrorIs(t, err, block.ErrOperationNotSupported)
+			} else {
+				require.NotNil(t, err)
```
Comment (arielshaqed) [inline pkg/block/blocktest/adapter.go:284]: Prefer to test a specific error here.

File: pkg/block/s3/adapter.go [hunk 4]
```diff
@@ -775,6 +775,54 @@ func (a *Adapter) CompleteMultiPartUpload(ctx context.Context, obj block.ObjectP
...
+	for i, part := range resp.Parts {
+		partsResp.Parts[i] = block.MultipartPart{
+			ETag:         strings.Trim(aws.ToString(part.ETag), `"`),
+			PartNumber:   int(aws.ToInt32(part.PartNumber)),
+			LastModified: aws.ToTime(part.LastModified),
+			Size:         aws.ToInt64(part.Size),
+		}
+	}
+
+	lg.Debug("list multipart upload parts")
```
Comment (arielshaqed) [inline pkg/block/s3/adapter.go:821]: Consider returning some information from the response, maybe
```suggestion
	lg.WithField("num_parts", len(resp.Parts)).Debug("list multipart upload parts")
```

File: pkg/gateway/operations/getobject.go [hunk 5]
```diff
@@ -133,3 +147,81 @@ func (controller *GetObject) Handle(w http.ResponseWriter, req *http.Request, o
...
+	}
+	if partNumberMarker != "" {
+		opts.PartNumberMarker = &partNumberMarker
+	}
+
+	req = req.WithContext(logging.AddFields(req.Context(), logging.Fields{
+		logging.UploadIDFieldKey: uploadID,
+	}))
+
+	// handle the upload/copy itself
```
Comment (arielshaqed) [inline pkg/gateway/operations/getobject.go:184]: Need to change this comment?

File: pkg/block/adapter.go [hunk 6]
```diff
@@ -10,8 +10,10 @@ import (
 
 // MultipartPart single multipart information
 type MultipartPart struct {
-	ETag       string
-	PartNumber int
+	ETag         string
+	PartNumber   int
+	LastModified time.Time
+	Size         int64
```
Comment (arielshaqed) [inline pkg/block/adapter.go:16]: For this PR adding S3 support it doesn't matter, but I think it _will_ matter when we add support on Azure: an ongoing MPU will _not_ have these values.  So I would prefer that the new fields be optional, and then be handled by the caller.

As an alternative, you could add an error and document that the ListParts interface returns it for an MPU that started before ListParts support was added.

**Review by arielshaqed — APPROVED** [review]
Neat, thanks!  And here I was, thinking I'd have 2 weekdays before we needed to review it.

- How was this tested?
- Please wait for S3 Supremo @guy-har to review...
- Please consider how to write the code that _uses_ ListParts correctly, so that it will be able to handle...
  * a ListParts call
  * on a pre-existing MPU
  * with an adapter that cannot list parts in this case.
Because I'm pretty sure that this will happen once we add Azure support, and it will be too easy to miss it then.

**Review by guy-har — APPROVED** [review]
LGTM

File: pkg/block/blocktest/adapter.go (hunk 3 above)
Comment (N-o-Z) [reply pkg/block/blocktest/adapter.go:284]: Unfortunately, these are the block contract unit tests. These tests are generic but the errors are derived from the underlying blockstore and are not aligned.
The upside is we have esti tests to check the specific error codes

File: pkg/gateway/operations/getobject.go (hunk 5 above)
Comment (N-o-Z) [reply pkg/gateway/operations/getobject.go:185]: Removed redundant comment

File: pkg/block/adapter.go (hunk 6 above)
Comment (N-o-Z) [reply pkg/block/adapter.go:16]: These already exist in the serde struct (and cannot be optional) they will just get the default zero value

File: pkg/gateway/operations/getobject.go [hunk 7]
```diff
@@ -133,3 +147,81 @@ func (controller *GetObject) Handle(w http.ResponseWriter, req *http.Request, o
...
+	query := req.URL.Query()
+	uploadID := query.Get(QueryParamUploadID)
+	maxPartsStr := query.Get(QueryParamMaxParts)
+	partNumberMarker := query.Get(QueryParamPartNumberMarker)
+	resp := &serde.ListPartsOutput{
+		Bucket: o.Repository.Name,
+		Key:    path.WithRef(o.Path, o.Reference),
+	}
+	opts := block.ListPartsOpts{}
+	var maxParts32 int32
```
[the remark this answers is not in the document]
Comment (N-o-Z) [reply pkg/gateway/operations/getobject.go:163]: It has to do with the parameter typing between us and AWS
Moved and cleaned
