### PR TITLE
Fix: local sync parallelism

### LINKED ISSUE #6484: [Bug]: Limitation of max concurrent operations to perform in lakectl local commit doesn't work
### What happened?

I installed lakectl locally, and access to MinIo as S3-compatible object store. 

When I use `lakectl local commit [directory] --parallelism 25` to  commit aroud 4000+ objects, there is a 503 error with MinIo, which indicates the server is too busy likely. Then I use `lakectl local commit [directory] --parallelism 1` to commit, the error still exists.

I took a close look at the relevant code. A question confused me a lot , in `./pkg/local/sync.go`, we use `maxParallelism` to limit the number of running goroutines, but it seems like we don't wait until the goroutine ends and just release a slot in channel `ch` at once，can you explain this? Thanks a lot! :)

https://github.com/treeverse/lakeFS/blob/e02ece385d7e672957a7323d3f45ce69208767ef/pkg/local/sync.go#L94C8-L94C8

### Expected behavior

We can use the `parallelism` flag to actually control the number of concurrent goroutines.

Maybe we should releases a slot in the `ch` channel once the goroutine finishes executing.

### lakeFS version

v0.107.0

### How lakeFS is installed

locally

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

lyzhang@pku.edu.cn

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #6484

### Bug Fix

We release the ch which was supposed to control the amount of concurrent tasks immediately after invoking goroutine
Refactored code, now we only create the exact number of workers required to run
      
### Testing Details

Tested manually

### Breaking Change?

No

### CODE REVIEW

File: pkg/local/sync.go [hunk 1]
```diff
@@ -73,28 +73,22 @@ func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *C
...
-		default:
-			wg.Go(func() error {
-				return s.apply(ctx, rootPath, remote, c)
-			})
-		}
-		ch <- true // release
-		if done {
-			break
-		}
+	for i := 0; i < s.maxParallelism; i++ {
```
Comment (arielshaqed) [inline pkg/local/sync.go:77]: I don't understand why use an errgroup and then also try to control parallelism with a chan. Why not wg.SetLimit to parallelism and then just wg.Go each change in a simple loop?

**Review by arielshaqed — COMMENTED** [review]
I think this library allows for a much simpler solution.

File: pkg/local/sync.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/local/sync.go:77]: Because SetLimit is blocking, and using TryGo will just make us iterate on a loop unnecessarily

File: pkg/local/sync.go [hunk 2]
```diff
@@ -73,28 +73,22 @@ func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *C
...
+		wg.Go(func() error {
+			for change := range changeSet {
+				c := change
```
Comment (nopcoder) [inline pkg/local/sync.go:80]: pinning is not required - we consume the value from the channel

File: pkg/local/sync.go [hunk 3]
```diff
@@ -73,28 +73,22 @@ func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *C
...
+				select {
+				case <-ctx.Done():
+					return nil
+				default:
+					if err := s.apply(ctx, rootPath, remote, c); err != nil {
+						return err
+					}
+				}
```
Comment (nopcoder) [inline pkg/local/sync.go:88]: if `apply` accepts the context and use/check it - we can also drop the `select` from the loop.

**Review by nopcoder — CHANGES_REQUESTED** [review]
My concern with Sync API call is that it require getting a channel that we should close and based on the current code it must be done in a different goroutine.
So, not for this PR - but I think we should model the API in a way that we do not require the caller to stand in these requirements if possible.

File: pkg/local/sync.go [hunk 4]
```diff
@@ -105,6 +93,9 @@ func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *C
 }
 
 func (s *SyncManager) apply(ctx context.Context, rootPath string, remote *uri.URI, change *Change) (err error) {
+	if ctx.Err() != nil {
+		return ctx.Err()
+	}
```
Comment (nopcoder) [inline pkg/local/sync.go:98]: capture the err once some implementations work "harder" to get the err value
```suggestion
	if err := ctx.Err(); err != nil {
		return err
	}
```

**Review by nopcoder — APPROVED** [review]
LGTM!
(with minor suggestion)

File: pkg/local/sync.go (hunk 1 above)
Comment (arielshaqed) [reply pkg/local/sync.go:77]: I understand that SetLimit will make Go block when there is no goroutine ready to receive the change.  I don't understand why this is a bad thing: I have a changeSet, it has a capacity.  All this goroutine does is load parallelism goroutines and each of them tries to read changeSet.  If we called wg.Go() directly, it would occasionally block - until the next parallelism slot were opened.  I don't think you'll be able to measure a difference in performance, just I'd like to have a loop that looks like this:

```go
wg.SetLimit(parallelism)
for change:= range changeSet {
	c := change
	wg.Go(func() error { return s.apply(ctx, rootPath, remote, c) }
}
if err := wg.Wait(); err != nil {
	return err
}
// ...
```

**Review by arielshaqed — COMMENTED** [review]
:-(

File: pkg/local/sync.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/local/sync.go]: Thanks - I understand now what you mean - modified accordingly
