### PR TITLE
lakectl local: fix dir seek

### LINKED ISSUE #8104: BUG: lakectl local: fail to seek dir on NFS mounted directories

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #8104

### CODE REVIEW

File: pkg/local/sync.go [hunk 1]
```diff
@@ -305,10 +305,17 @@ func (s *SyncManager) upload(ctx context.Context, rootPath string, remote *uri.U
 		ClientMtimeMetadataKey: strconv.FormatInt(fileStat.ModTime().Unix(), 10),
 	}
 
-	reader := b.Reader(f)
+	readerWrapper := fileWrapper{
+		file:   f,
+		reader: b.Reader(f),
```
Comment (yonipeleg33) [inline pkg/local/sync.go:310]: Why do we need both?

**Review by yonipeleg33 — APPROVED** [review]
LGTM, had a question but not blocking

File: pkg/local/sync.go (hunk 1 above)
Comment (N-o-Z) [reply pkg/local/sync.go:310]: ProgressUpdater requires a reader for the progress bar but we also need the seek functionality for the upload so we need to wrap the progress reader with a seek implementation as well
