### PR TITLE
Fix: Lowercase object metadata keys and x-amz-missing-meta header support for S3 compatibility (#9730, #9727)

### LINKED ISSUE #9727: Implement x-amz-missing-meta header for dropped metadata
When S3 drops invalid metadata entries (e.g., empty keys, unprintable values), it returns the `x-amz-missing-meta` header in the response to indicate how many entries couldn't be stored. lakeFS should implement this behaviour for compatibility.

S3 behavior:
```
Input:  {'': 'value', 'valid': 'key'}

Response:
  Metadata: {'valid': 'key'}
  x-amz-missing-meta: 1
```

Current lakeFS behavior:
```
Input:  {'': 'value', 'valid': 'key'}

Response:
  Metadata: {'': 'value', 'Valid': 'key'}
  (no x-amz-missing-meta header)
```

From [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata):

> If some metadata contains unprintable characters, it is not returned. Instead, the x-amz-missing-meta header is returned with a value of the number of unprintable metadata entries.

While originally documented for SOAP API metadata with unprintable values, S3 also uses this header when dropping invalid metadata at write time.

### LINKED ISSUE #9730: Lowercase object metadata keys before storing
lakeFS currently stores object metadata keys with title-case (e.g., Foo, MyKey), but S3 stores them in lowercase per the [S3 specification](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata):

> Amazon S3 stores user-defined metadata keys in lowercase

Why this happens:
Go's HTTP library canonicalizes HTTP headers to title-case (e.g., `X-Amz-Meta-Foo`) which is correct HTTP behaviour. However, the metadata **key** (the part after `x-amz-meta-`) should be extracted and lowercased before storage, since it's data, not an HTTP header name.

Current behaviour:
```
HTTP Request: X-Amz-Meta-Foo: bar
lakeFS stores: Foo → bar          (title-cased)
S3 stores:     foo → bar          (lowercased)
```

Impact:

- Client code expecting `metadata['foo']` fails to find `metadata['Foo']`
- Breaks S3 compatibility

### PR DESCRIPTION
**Pull request by AliRamberg**
Improve S3 Gateway metadata handling to comply with the S3 specification,
which requires user-defined metadata keys to be stored in lowercase, and
adds validation and `X-Amz-Missing-Meta` header support for invalid keys.

Changes:
- Modified `amzMetaAsMetadata()` to lowercase metadata keys after
  extracting them from HTTP headers (`X-Amz-Meta-*`) and validate keys
  against HTTP token character rules (RFC 7230), silently skipping invalid ones
- Added `isValidMetadataKey()` to validate metadata key characters,
  rejecting non-ASCII, control chars, and characters that Go's HTTP server
  cannot send (e.g., parentheses)
- Updated `amzMetaWriteHeaders()` to validate metadata keys before writing
  response headers and set the `X-Amz-Missing-Meta` header with the count
  of skipped invalid keys, matching S3 behavior
- Expanded V4 auth signature regex (`V4AuthHeaderRegexp`) to accept
  special characters in signed headers (`.#!$%&'*+^` `` ` `` `|~`) that S3
  allows in metadata key names
- Added new unit test file `operation_utils_test.go` with tests for key
  validation, lowercasing, RFC 2047 decoding, and `X-Amz-Missing-Meta`
  header behavior
- Updated existing unit tests and integration tests (`TestS3CopyObject`,
  `TestS3PutObjectUserMetadata`) to verify lowercase key storage
- Added documentation about S3 metadata key casing in glossary and
  metadata search docs

Fixes #9730
Fixes #9727

### CODE REVIEW

**Comment by arielshaqed** [comment]
> Seems like there should be a product discussion involved.

@talSofer is aware of these issues; tagging for advice on these matters.

**Comment by talSofer** [comment]
> Why did we choose the approach of lower casing the key only for S3 GW?
> Why are we not doing it for all interfaces?

I would like to keep other non S3 gateway interfaces behavior as it is, meaning support case sensitive user metadata. Reasoning is that in nature user metadata in lakeFS can represent annotations and labels which may be case sensitive and enforcing lowercase would remove flexibility and break expected semantics.

> Also how will backwards compatibility work?
> Let's say I've set the metadata of an object via our API and then I fetch the metadata via s3 GW what is the expected behavior? Does this align with AWS S3 behavior?

For `GET` requests through the S3 gateway, we will continue returning only `x-amz-meta-*` metadata keys and will lowercase those keys to be consistent with AWS S3 behavior. Meaning, user metadata written via the API is not returned causing no backward compatibility violation. (Unless we will change it as suggested in https://github.com/treeverse/lakeFS/issues/9089 which is a separate decision).

**Comment by N-o-Z** [comment]
> > Why did we choose the approach of lower casing the key only for S3 GW?
> > Why are we not doing it for all interfaces?
> 
> I would like to keep other non S3 gateway interfaces behavior as it is, meaning support case sensitive user metadata. Reasoning is that in nature user metadata in lakeFS can represent annotations and labels which may be case sensitive and enforcing lowercase would remove flexibility and break expected semantics.
> 
> > Also how will backwards compatibility work?
> > Let's say I've set the metadata of an object via our API and then I fetch the metadata via s3 GW what is the expected behavior? Does this align with AWS S3 behavior?
> 
> For `GET` requests through the S3 gateway, we will continue returning only `x-amz-meta-*` metadata keys and will lowercase those keys to be consistent with AWS S3 behavior. Meaning, user metadata written via the API is not returned causing no backward compatibility violation. (Unless we will change it as suggested in #9089 which is a separate decision).

If we do decide to do that we will need to provide the `x-amz-missing-meta` [header as well ](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax) and not lower case unsupported metadata keys

**Comment by AliRamberg** [comment]
@N-o-Z @talSofer What should we do with this PR then? Can we move forward with it or should we wait till have `x-amz-missing-meta` support?

**Comment by N-o-Z** [comment]
I believe that as part of this task we need to also implement x-amz-missing-meta for the GW

File: esti/s3_gateway_test.go [hunk 1]
```diff
@@ -967,6 +968,27 @@ func stripKeyPrefix[T any](prefix string, m map[string]T) (map[string]T, error)
...
 
+// lowercaseKeys normalizes metadata keys for comparison with lakeFS storage.
+// According to the S3 specification, user-defined metadata keys are stored in lowercase.
+// This helper handles two cases:
+//  1. Keys with X-Amz-Meta- prefix: Preserves the prefix, lowercases only the key part
+//     Example: "X-Amz-Meta-MyKey" -> "X-Amz-Meta-mykey"
+//  2. Keys without prefix: Lowercases the entire key
+//     Example: "Ascii" -> "ascii"
+//
+// Use this when comparing expected metadata with actual metadata returned from lakeFS API.
```
Comment (arielshaqed) [inline esti/s3_gateway_test.go:1016]: This loses some information for the test.  A test should also look at whether or not we received a prefix.  Otherwise the gateway might not conform (e.g. strip the prefix when it shouldn't), and the test will detect no error.

File: pkg/gateway/operations/operation_utils.go [hunk 2]
```diff
@@ -4,20 +4,64 @@ import (
...
 var (
 	rfc2047Decoder = new(mime.WordDecoder)
 )
 
+// isValidMetadataKey checks if a metadata key can be sent as an HTTP header name
+// Valid characters match S3 behavior for HTTP headers:
+// - Letters: 'A'-'Z', 'a'-'z'
+// - Digits: '0'-'9'
+// - Special characters: '-', '_', '.', '#'
+// - Control characters: NUL (0x00), LF (0x0A)
```
Comment (arielshaqed) [inline pkg/gateway/operations/operation_utils.go]: This is a strange set of characters.  Please provide the source for the claim that this is, indeed, the correct set.

Alternatively, just support any printable non-space ASII character.

Comment (AliRamberg) [reply pkg/gateway/operations/operation_utils.go]: Using a builtin function like `unicode.IsPrint` won't do, because it includes characters that are invalid by S3. For example the `@` rune.
Regarding the two control characters here, I was not able to reproduce it for the NUL character but did for LF. We can skip them in any case as they are not really printable.

I see now I'm missing more characters like Slash `/`.

Comment (AliRamberg) [reply pkg/gateway/operations/operation_utils.go]: nvm, I was able to PutObject with a `/` in it, but when I HeadObject the metadata was empty!

**Comment by N-o-Z** [comment]
@AliRamberg Are we planning on pursuing this?

**Comment by AliRamberg** [comment]
@N-o-Z I actually think it's ready for re-review. I made couple of tests and it works as expected.
Regarding the comma-delimited list of same name keys – I couldn't reproduce it on actual S3 buckets using either AWS CLI or awcurl.

just for reference here are the commands I tried to run:
AWS CLI:
```
aws --profile works s3api put-object --bucket treeverse-ort-simulation-bucket --key yahli-asap/check/please --body here --metadata "hey=you,Hey=uuu"
```
The command didn't pass due to `The request signature we calculated does not match the signature you provided. Check your key and signing method.`

awscurl:
```
awscurl --service s3 \
    -H "X-Amz-Meta-TestKey: value1" \
    -H "x-amz-meta-testkey: value2" \
    -H "X-Amz-Meta-TESTKEY: value3" \
    --region us-east-1 \
    --profile works \
    -X PUT \
    --data "test content" \
    "https://treeverse-ort-simulation-bucket.s3.amazonaws.com/yahli-asap/check/please" -v
```
the command seemingly worked but when I query the object I get only the last lowered case metadata - `testkey:value3`

File: pkg/gateway/operations/operation_utils.go (hunk 2 above)
Comment (skshetry) [reply pkg/gateway/operations/operation_utils.go]: Isn’t this ultimately constrained by what [the HTTP header format itself supports](https://stackoverflow.com/a/69466459)? Do we actually need to validate this on `PUT` or equivalent (not sure about `GET`)?

Or, are there characters that are not supported by AWS S3 but allowed by http spec? (I guess that'd be `!$%&'*+^|~``?)

File: pkg/gateway/operations/operation_utils.go [hunk 3]
```diff
@@ -40,7 +78,15 @@ func amzMetaAsMetadata(req *http.Request) (catalog.Metadata, error) {
 			if userMetadataSize > maxUserMetadataSize {
 				return nil, gatewayerrors.ErrMetadataTooLarge
 			}
-			metadata[k] = value
+
+			// Extract the metadata key part after the prefix and lowercase it
+			// to comply with S3 spec: "Amazon S3 stores user-defined metadata keys in lowercase"
+			keyPart := strings.TrimPrefix(k, amzMetaHeaderPrefix)
```
Comment (skshetry) [inline pkg/gateway/operations/operation_utils.go]: There is a `name` var above without the meta prefix that you can use.
(I made the changes on this while this PR was under review).

Comment (AliRamberg) [reply pkg/gateway/operations/operation_utils.go]: Thanks!

File: esti/s3_gateway_test.go (hunk 1 above)
Comment (AliRamberg) [reply esti/s3_gateway_test.go:1016]: The prefix check is already there - see the `require.Truef(strings.HasPrefix(key, amzMetaHeaderPrefix))` loop right above the lowercaseKeys call. lowercaseKeys only handles the value comparison.

**Comment by AliRamberg** [comment]
@arielshaqed I know this is an old PR, but I'd appreciate you double checking it.
