### PR TITLE
Import: prohibit import from storage namespace

### LINKED ISSUE #8735: [Bug]: Importing Data from the Same S3 Repo Should Be Blocked but Isn't
### Description:
I was able to import data into a repository with S3 storage from the same repo namespace on S3, even though this should be blocked.

### Steps to Reproduce:
1. Run lakeFS OSS with S3 blockstore.
2. Create a new repository.
3. Upload data to that repository.
4. Attempt to import the same data from the same namespace in the S3 blockstore.

### Expected Behavior:
Importing data from the same S3 namespace into the same repository should be blocked.

### Actual Behavior:
The data gets imported into the repository without restriction.

### My Blockstore Configuration:
```
blockstore:
    type: s3
    s3:
      profile: cloud-dev
```

### Storage Namespace & Import Source:
Storage namespace: `s3://annaselibucket-us-east-1/repos/oss-s3-1-repo-1`
Import source: `s3://annaselibucket-us-east-1/repos/oss-s3-1-repo-1`

### Observed Behavior Based on Destination Used:
Importing to `lakefs://oss-s3-1-repo-1/main/` → Overwrites the existing data within the repository in main.
Importing to `lakefs://oss-s3-1-repo-1/main/import` → Adds the imported data to the "import" folder within the repository in main.

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #8735

### Background

Prevent imports from repository namespace as this might cause unexpected behavior

### Bug Fix

Go over import path and return an error in case any of them are in the destination repo namespace
      
### Testing Details

Added esti tests

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]
Checking the import path against the storage namespace at the request level will block `/import/from/ns/a` when the storage namespace is `/import/from/ns`.  

However, the import scan process imports all objects under the requested path. Therefore, if my import path is `/import/from/` and the storage namespace is `/import/from/ns`, it will eventually reach data within the storage namespace during the import process. 

The code found in `catalog.go` only addresses the first case.

File: esti/import_test.go [hunk 1]
```diff
@@ -353,3 +366,76 @@ func TestImportCancel(t *testing.T) {
...
+func TestImportToStorageNamespace(t *testing.T) {
+	t.Parallel()
+	ctx, _, repoName := setupTest(t)
+	defer tearDownTest(repoName)
+
+	repoResp, err := client.GetRepositoryWithResponse(ctx, repoName)
+	require.NoError(t, err)
+	require.NotNil(t, repoResp.JSON200)
+
+	branch := fmt.Sprintf("%s-%s", importBranchBase, "from-namespace")
```
Comment (nopcoder) [inline esti/import_test.go:379]:
```suggestion
	const branch = importBranchBase + "-from-namespace"
```

**Review by nopcoder — APPROVED** [review]
LGTM!
with very small suggestion

**Comment by jumpSnow** [comment]
Hi @N-o-Z ,

Thanks for working on this PR to prohibit imports from the storage namespace. I was wondering if you could help clarify the rationale behind preventing imports within the same repository?

Specifically:

What are the potential issues or risks that motivated this restriction?
For use cases where we need to copy data between branches in the same repository, what would be the recommended alternative approach now that direct imports are blocked?
I want to make sure we understand the implications and have a clear migration path for existing workflows that might rely on this functionality.

Appreciate any insights you can share!

**Comment by N-o-Z** [comment]
> Hi @N-o-Z ,
> 
> Thanks for working on this PR to prohibit imports from the storage namespace. I was wondering if you could help clarify the rationale behind preventing imports within the same repository?
> 
> Specifically:
> 
> 1. What are the potential issues or risks that motivated this restriction?
> 2. For use cases where we need to copy data between branches in the same repository, what would be the recommended alternative approach now that direct imports are blocked?
> 
> I want to make sure we understand the implications and have a clear migration path for existing workflows that might rely on this functionality.
> 
> Appreciate any insights you can share!

Yes,
1. Importing from the repository namespace can have some adverse affect. One principle in import is that imported data is not managed by lakeFS and also not garbage collected. importing the raw data from the repository namespace could have an adverse effect on the garbage collection and can lead to unspecified behavior. In addition to that it can result in potentially importing internal lakeFS metadata which when tampered could cause data loss.
2. The answer to that really relies on the specific use case but some of the options include:
    1. Using the `CopyObject` API will allow you to copy objects between branches. Whether this is a deep or shallow copy depends on the underlying block storage implementation of the copy object API.
    2. Branching out from the source branch which contains the data you wanted will in fact provide you with a "copy" of that data. This will be a shallow copy and will not require physical copy of the data
    3. `CherryPick` API will allow you to take changes done in a specific commit - this is a metadata operation as well and does not require actual duplication of the data.
    
Maybe you can expand on the use case and I'll try to provide the best alternative
