### PR TITLE
Fix: local adapter error on no space left on device

### LINKED ISSUE #7715: [Bug]: Local storage adaptor silently fails to upload when out of space
### What happened?

Lakefs opensource version was deployed in a Kubernetes cluster. The storage space was smaller than the size of files we wanted to upload. Using Aws cli tool to upload the files to the lakefs s3 interface , everything seems to have went fine. But storage fills up in the server and there is a mismatch on file sizes in the meta store vs the actual file size on disk. (Note this is using local storage for lakefs storage) . 
Steps to Reproduce:
1. Configure lakefs to use local storage, with small space
2. upload files that would be larger than the storage in one go
3. try to download the files once the upload "finished" , and errors like "expect x bytes, but recieved y " happen (this was using the lakefs python sdk to download, error maybe different on a different client)

### Expected behavior

The aws client or any other uploading tool should be notified and be aware of error if lakefs doesn't have enough storage.

### lakeFS version

treeverse/lakefs:1.18.0

### How lakeFS is installed

Kubernetes 

### Affected clients

Aws-cli s3 , python sdk 

### Relevant log output

```shell
probably this chat on lakefs slack help might be releavant than the logs... 
https://lakefs.slack.com/archives/C016726JLJW/p1713891191846399 

https://lakefs.slack.com/archives/C016726JLJW/p1714576349984149
```

### Contact details

kebedey@renci.org

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #7715

### Bug Fix

Add an explicit error for no space left on device and propagate it to the controller
Add debug logs on lakectl retries to indicate which status code is being retried
Fix error handling in upload flow

### Testing Details

Tested manually by creating a tmp FS with 4kb of space allocated

### Breaking Change?

No

Before:

Screenshot from 2025-12-16 15-44-36

```
lakectl fs upload lakefs://test/main/find.py -s ~/Downloads/find.py            !10711
Post "http://localhost:8000/api/v1/repositories/test/branches/main/objects?path=find.py": POST http://localhost:8000/api/v1/repositories/test/branches/main/objects?path=find.py giving up after 5 attempt(s)
Error executing command.
```

After:

Screenshot from 2025-12-16 16-16-32

```
lakectl fs upload lakefs://test/main/find.py -s ~/Downloads/find.py            !10711
time="2025-12-16T16:41:30-05:00" level=debug msg="loaded configuration from file" func=github.com/treeverse/lakefs/cmd/lakectl/cmd.preRunCmd file="/home/niro/dev/lakefs/cmd/lakectl/cmd/root.go:516" fields.file=/home/niro/.lakectl.yaml file="/home/niro/dev/lakefs/cmd/lakectl/cmd/root.go:516"
storage limit exceeded
400 Bad Request
```

### CODE REVIEW

File: pkg/block/local/adapter.go [hunk 1]
```diff
@@ -165,6 +166,11 @@ func (l *Adapter) Put(_ context.Context, obj block.ObjectPointer, _ int64, reade
 	}()
 	_, err = io.Copy(f, reader)
 	if err != nil {
+		// Remove the file if it was partially written.
+		_ = os.Remove(p)
+		if errors.Is(err, syscall.ENOSPC) {
+			return nil, block.ErrStorageLimitExceeded
+		}
```
Comment (nopcoder) [inline pkg/block/local/adapter.go]: I would avoid using syscall package here and just reflect that download/write failed.

Comment (idanovo) [inline pkg/block/local/adapter.go]: 1) A better handle here would upload the file to <file-name>.tmp and then move it to <file-name>.
This way, we won't delete an existing file in case we failed to upload the entire file.

2) I see no reason to return a different error here in case we got` syscall.ENOSPC`

Comment (N-o-Z) [reply pkg/block/local/adapter.go]: Regarding the handling - you are suggesting that from now on for each write we write to a tmp and then perform mv, instead of just doing cleanup on error. I tend to oppose to that. Also additional issues with this approach:
1. local adapter is restricted to write only to location configured so we should avoid writing to any other location
2. writing to tmp can result in a bug. consider a small tmp fs and trying to write a large file to lakeFS. It will fails on write to tmp although there's enough space on actual device. This is only one problem that can occur from that

**Comment by N-o-Z** [comment]
After CR Fixes:
image

File: pkg/block/local/adapter.go (hunk 1 above)
Comment (idanovo) [reply pkg/block/local/adapter.go]: Sorry, for not being clear.
I didn't mean to upload to tmp dir, I meant to upload object.txt.tmp and then mv to object.txt.
Anyway, not a blocker for this PR, I just think it's a better way to handle uploads

**Review by idanovo — APPROVED** [review]
