### PR TITLE
Fix quickstart bug: branch protection

### LINKED ISSUE #6674: [Bug]: Quickstart is broken when creating sample repo
### What happened?

What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. Run the container: `docker run --name lakefs --pull always \
             --rm --publish 8000:8000 \
             treeverse/lakefs:latest \
             run --quickstart`
2. Open the UI and login
3. Click `Create Sample Repository`

image

### Expected behavior

Sample repo is created successfully. 

### lakeFS version

0.111.0

### How lakeFS is installed

docker, local

### Affected clients

_No response_

### Relevant log output

```shell
2023/10/02 08:07:01 http: panic serving 172.17.0.1:50112: assignment to entry in nil map
goroutine 303 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xb0
panic({0x166c8a0, 0x4ebed40})
	/usr/local/go/src/runtime/panic.go:890 +0x248
github.com/treeverse/lakefs/pkg/samplerepo.AddBranchProtection({0x4ee1b30, 0x400e4e8060}, 0x400e1db9a0, {0x4f0a040, 0x40003aa820})
	/build/pkg/samplerepo/samplecontent.go:126 +0xe0
github.com/treeverse/lakefs/pkg/api.(*Controller).CreateRepository(0x400047a380, {0x4edeca0, 0x400e1ad818}, 0x400e1e7e00, {0x400e48b1e0, {0x400e4e2210, 0xa}, 0x400e4e220c, {0x400e0bbec0, 0x12}}, ...)
	/build/pkg/api/controller.go:1623 +0x89c
github.com/treeverse/lakefs/pkg/api/apigen.(*ServerInterfaceWrapper).CreateRepository.func1({0x4edeca0?, 0x400e1ad818?}, 0x1980001?)
	/build/pkg/api/apigen/lakefs.gen.go:20518 +0x68
github.com/treeverse/lakefs/pkg/api/apigen.(*ServerInterfaceWrapper).CreateRepository(0x400c6bcba0, {0x4edeca0, 0x400e1ad818}, 0x400e1e7d00)
	/build/pkg/api/apigen/lakefs.gen.go:20525 +0x4ac
net/http.HandlerFunc.ServeHTTP(0x400cc86910?, {0x4edeca0?, 0x400e1ad818?}, 0xffffbc338108?)
	/usr/local/go/src/net/http/server.go:2122 +0x38
....
```
```


### Contact details

_No response_

### PR DESCRIPTION
**Pull request by johnnyaug**
Resolves #6674.

1. Fix nil check in quickstart.
2. Fix delete branch protection rule in UI.
3. Do not use checksum from the KV store as the ETag.

### CODE REVIEW

File: pkg/graveler/graveler.go [hunk 1]
```diff
@@ -1493,15 +1494,18 @@ func (g *Graveler) GCNewRunID() string {
...
+func (g *Graveler) GetBranchProtectionRules(ctx context.Context, repository *RepositoryRecord) (*BranchProtectionRules, *string, error) {
 	return g.protectedBranchesManager.GetRules(ctx, repository)
 }
 
 func (g *Graveler) SetBranchProtectionRules(ctx context.Context, repository *RepositoryRecord, rules *BranchProtectionRules, lastKnownChecksum *string) error {
 	if lastKnownChecksum == nil {
 		return g.protectedBranchesManager.SetRules(ctx, repository, rules)
 	}
-	return g.protectedBranchesManager.SetRulesIf(ctx, repository, rules, *lastKnownChecksum)
+	if *lastKnownChecksum == "" {
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:1505]: Seem like the logic should be reversed?:
1. lastKnownChecksum is nil -> SetIf
2. lastKnownChecksum is "" -> Set
And of course change the logic in the invoking methods accordingly

File: pkg/graveler/graveler.go [hunk 2]
```diff
@@ -611,10 +611,11 @@ type VersionController interface {
 
 	// GetBranchProtectionRules return all branch protection rules for the repository.
 	// The returned checksum represents the current state of the rules, and can be passed to SetBranchProtectionRules for a conditional update.
-	GetBranchProtectionRules(ctx context.Context, repository *RepositoryRecord) (*BranchProtectionRules, string, error)
+	GetBranchProtectionRules(ctx context.Context, repository *RepositoryRecord) (*BranchProtectionRules, *string, error)
 
 	// SetBranchProtectionRules sets the branch protection rules for the repository.
 	// If lastKnownChecksum doesn't match the current state, the update fails with ErrPreconditionFailed.
+	// If lastKnownChecksum is the empty string, the update is performed only if no rules exist.
```
Comment (N-o-Z) [inline pkg/graveler/graveler.go:618]: Should be nil and not empty

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Some comments.
In addition:
Can we add an esti test for S3 which checks the creation of the sample repo?

File: pkg/graveler/graveler.go (hunk 1 above)
Comment (johnnyaug) [reply pkg/graveler/graveler.go]: Agree that this is ugly. I argue that "" as the "skip validation checksum" is just as problematic. Added a dedicated skip-validation constant to overcome this. This will be removed once the legacy API is dropped.

**Comment by johnnyaug** [comment]
@N-o-Z, added an Esti test for sample repo creation.

**Review by N-o-Z — APPROVED** [review]
LGTM

File: pkg/graveler/settings/manager.go [hunk 3]
```diff
@@ -70,39 +68,64 @@ func (m *Manager) Save(ctx context.Context, repository *graveler.RepositoryRecor
...
 // SaveIf persists the given setting under the given repository and key. Overrides settings key in KV Store.
 // The setting is persisted only if the current version of the setting matches the given checksum.
-func (m *Manager) SaveIf(ctx context.Context, repository *graveler.RepositoryRecord, key string, setting proto.Message, lastKnownChecksum string) error {
+// If lastKnownChecksum is nil, the setting is persisted only if it does not exist.
+func (m *Manager) SaveIf(ctx context.Context, repository *graveler.RepositoryRecord, key string, setting proto.Message, lastKnownChecksum *string) error {
 	logSetting(logging.FromContext(ctx), repository.RepositoryID, key, setting, "saving repository-level setting")
-	decodedChecksum, err := base64.StdEncoding.DecodeString(lastKnownChecksum)
-	if err != nil {
-		return fmt.Errorf("decode checksum: %w", err)
+	valueWithPredicate, err := m.store.Get(ctx, []byte(graveler.RepoPartition(repository)), []byte(graveler.SettingsPath(key)))
```
Comment (nopcoder) [inline pkg/graveler/settings/manager.go:74]: Case `lastKnownChecksum` is nil we don't need to `Get` the current value, we can just return from SetMsg - it will also remove the check if valueWithPredicate is nil later as successful call should return non-nil.

File: pkg/graveler/settings/manager.go [hunk 4]
```diff
@@ -70,39 +68,64 @@ func (m *Manager) Save(ctx context.Context, repository *graveler.RepositoryRecor
...
+		if err != nil {
+			return err
+		}
+		currentPredicate = valueWithPredicate.Predicate
+	}
+	if swag.StringValue(currentChecksum) != swag.StringValue(lastKnownChecksum) {
+		return graveler.ErrPreconditionFailed
+	}
+	err = kv.SetMsgIf(ctx, m.store, graveler.RepoPartition(repository), []byte(graveler.SettingsPath(key)), setting, currentPredicate)
+	if err != nil && errors.Is(err, kv.ErrPredicateFailed) {
```
Comment (nopcoder) [inline pkg/graveler/settings/manager.go:93]: Simplify
```suggestion
	if errors.Is(err, kv.ErrPredicateFailed) {
```

File: pkg/graveler/settings/manager.go [hunk 5]
```diff
@@ -70,39 +68,64 @@ func (m *Manager) Save(ctx context.Context, repository *graveler.RepositoryRecor
...
+		}
+		if err != nil {
+			return err
+		}
+		currentPredicate = valueWithPredicate.Predicate
+	}
+	if swag.StringValue(currentChecksum) != swag.StringValue(lastKnownChecksum) {
+		return graveler.ErrPreconditionFailed
+	}
+	err = kv.SetMsgIf(ctx, m.store, graveler.RepoPartition(repository), []byte(graveler.SettingsPath(key)), setting, currentPredicate)
```
Comment (nopcoder) [inline pkg/graveler/settings/manager.go:92]: Main concern here is just the flow where we call `SetMsgIf` while using `currentPredicate` value that was not part of `valueWithPredicate`.
The promise from kv is to support SetIf only with predicate that was returned from Get or explicit call with `nil` to indicate that the value should not be exists.

Suggest to check if lastKnownChecksum is "" and call SetIf with nil - for all the rest we can compare the checksum as above and call SetMsgIf

File: pkg/graveler/settings/manager.go [hunk 6]
```diff
@@ -70,39 +68,64 @@ func (m *Manager) Save(ctx context.Context, repository *graveler.RepositoryRecor
...
-	return pred, nil
+	return swag.String(hex.EncodeToString(h.Sum(nil))), nil
 }
 
 // GetLatest returns the latest setting under the given repository and key, without using the cache.
 // The returned checksum represents the version of the setting, and can be passed to SaveIf for conditional updates.
-func (m *Manager) GetLatest(ctx context.Context, repository *graveler.RepositoryRecord, key string, settingTemplate proto.Message) (proto.Message, string, error) {
-	data := settingTemplate.ProtoReflect().Interface()
-	pred, err := m.getWithPredicate(ctx, repository, key, data)
+func (m *Manager) GetLatest(ctx context.Context, repository *graveler.RepositoryRecord, key string, settingTemplate proto.Message) (proto.Message, *string, error) {
```
Comment (nopcoder) [inline pkg/graveler/settings/manager.go:110]: Accept `protoreflect.ProtoMessage` as settingMsg and unmarshal the data into it instead of template+reflect+create and return.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: pkg/api/controller.go [hunk 7]
```diff
@@ -1816,6 +1816,9 @@ func (c *Controller) SetBranchProtectionRules(w http.ResponseWriter, r *http.Req
 		}
 	}
 	eTag := params.IfMatch
+	if swag.StringValue(eTag) == "" {
+		eTag = nil
```
[the remark this answers is not in the document]
Comment (johnnyaug) [reply pkg/api/controller.go:1820]: This API does not allow skipping the validation.
