### PR TITLE
Fix/delete branch #956

### LINKED ISSUE #956: Delete branch button is missing

### PR DESCRIPTION
**Pull request by shamikakumar**
In Branches page, added delete functionality for non-default branches. Fixes #956

### CODE REVIEW

File: webui/src/components/BranchesPage.js [hunk 1]
```diff
@@ -131,6 +156,16 @@ const BranchesPage = ({repo, branches, listBranches, listBranchesPaginate, creat
                                 </div>
                                 <div className="float-right">
                                     <ButtonGroup className="branch-actions">
+                                        {(repo.default_branch !== branch) ?
```
Comment (itaiad200) [inline webui/src/components/BranchesPage.js:159]: Please add a description when the mouse hover on the button (see 'tooltip' from other buttons):
"delete the branch"

**Review by itaiad200 — CHANGES_REQUESTED** [review]

**Review by itaiad200 — APPROVED** [review]

**Comment by itaiad200** [comment]
LGTM
Great job @shamikakumar !
