### PR TITLE
Double-up catalog and graveler errors in api

### LINKED ISSUE #1212: Filling in "compare" branch in UI crashes it
Trying type "tr" ("...unk") into the dropdown for compare crashes the UI.

This is the failing request (which ends up crashing the UI):
```json
{
	"GET": {
		"scheme": "http",
		"host": "localhost:8000",
		"filename": "/api/v1/repositories/foo/branches/tr",
		"remote": {
			"Address": "127.0.0.1:8000"
		}
	}
}
```

Response:
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
X-Request-Id: 0436b6ac-86f6-4c5a-8616-0a1f2771176e
Date: Sun, 17 Jan 2021 14:30:00 GMT
Content-Length: 31
```

`lakefs` logs:
```
DEBUG  [2021-01-17T16:34:37+02:00]api/api_controller.go:96 api.(*Dependencies).LogAction performing API action                         action=list_branches host="localhost:8000" message_type=action method=GET path="/api/v1/repositories/foo/branches?after=t&amount=300" request_id=4822a93f-5834-4aae-bfe2-e70dd4b87662 service_name=rest_api user=me
INFO   [2021-01-17T16:34:37+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo t 1000]" duration="364.505µs" query="\n\t\t\tSELECT id, staging_token, commit_id\n\t\t\tFROM graveler_branches\n\t\t\tWHERE repository_id = $1\n\t\t\tAND id >= $2\n\t\t\tORDER BY id ASC\n\t\t\tLIMIT $3" type="start query"
TRACE  [2021-01-17T16:34:37+02:00]httputil/tracing.go:143 httputil.TracingMiddleware.func1 HTTP call ended                               host="localhost:8000" method=GET path="/api/v1/repositories/foo/branches?after=t&amount=300" request_body="[]" request_headers="map[Accept:[application/json] Accept-Encoding:[gzip, deflate] Accept-Language:[en-US,en;q=0.5] Authorization:[Basic QUtJQUpJNldITFdMSjRDVzdVNVE6TCtTTCtVNXc1U29tNFJtWlRSRnhuY1RNSW1tL1RIaXd4alhuZlJkRw==] Connection:[keep-alive] Content-Type:[application/json] Cookie:[access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA5NTU3NjEsImlhdCI6MTYxMDM1MDk2MSwic3ViIjoiZm9vIn0.0dgackpgYkQtu5sbYwbXF6r3KxtzUTM7gLk0Ct9KwNw] Referer:[http://localhost:8000/repositories/foo/compare] User-Agent:[Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0] X-Jwt-Authorization:[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA5NTU3NjEsImlhdCI6MTYxMDM1MDk2MSwic3ViIjoiZm9vIn0.0dgackpgYkQtu5sbYwbXF6r3KxtzUTM7gLk0Ct9KwNw]]" request_id=4822a93f-5834-4aae-bfe2-e70dd4b87662 response_body="{\"pagination\":{\"has_more\":false,\"max_per_page\":1000,\"results\":1},\"results\":[\"trunk\"]}\n" response_headers="map[Content-Type:[application/json] X-Request-Id:[4822a93f-5834-4aae-bfe2-e70dd4b87662]]" sent_bytes=0 service_name=rest_api status_code=200 took="757.517µs" user=me
DEBUG  [2021-01-17T16:34:37+02:00]api/api_controller.go:96 api.(*Dependencies).LogAction performing API action                         action=list_branches host="localhost:8000" message_type=action method=GET path="/api/v1/repositories/foo/branches?after=tr&amount=300" request_id=4e8e868f-76b3-4f38-a79b-ce96c13b1f7f service_name=rest_api user=me
INFO   [2021-01-17T16:34:37+02:00]db/logged_rows.go:34 db.(*LoggedRows).logDuration rows done                                     args="[foo tr 1000]" duration="380.818µs" query="\n\t\t\tSELECT id, staging_token, commit_id\n\t\t\tFROM graveler_branches\n\t\t\tWHERE repository_id = $1\n\t\t\tAND id >= $2\n\t\t\tORDER BY id ASC\n\t\t\tLIMIT $3" type="start query"
TRACE  [2021-01-17T16:34:37+02:00]httputil/tracing.go:143 httputil.TracingMiddleware.func1 HTTP call ended                               host="localhost:8000" method=GET path="/api/v1/repositories/foo/branches?after=tr&amount=300" request_body="[]" request_headers="map[Accept:[application/json] Accept-Encoding:[gzip, deflate] Accept-Language:[en-US,en;q=0.5] Authorization:[Basic QUtJQUpJNldITFdMSjRDVzdVNVE6TCtTTCtVNXc1U29tNFJtWlRSRnhuY1RNSW1tL1RIaXd4alhuZlJkRw==] Connection:[keep-alive] Content-Type:[application/json] Cookie:[access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA5NTU3NjEsImlhdCI6MTYxMDM1MDk2MSwic3ViIjoiZm9vIn0.0dgackpgYkQtu5sbYwbXF6r3KxtzUTM7gLk0Ct9KwNw] Referer:[http://localhost:8000/repositories/foo/compare] User-Agent:[Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0] X-Jwt-Authorization:[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA5NTU3NjEsImlhdCI6MTYxMDM1MDk2MSwic3ViIjoiZm9vIn0.0dgackpgYkQtu5sbYwbXF6r3KxtzUTM7gLk0Ct9KwNw]]" request_id=4e8e868f-76b3-4f38-a79b-ce96c13b1f7f response_body="{\"pagination\":{\"has_more\":false,\"max_per_page\":1000,\"results\":1},\"results\":[\"trunk\"]}\n" response_headers="map[Content-Type:[application/json] X-Request-Id:[4e8e868f-76b3-4f38-a79b-ce96c13b1f7f]]" sent_bytes=0 service_name=rest_api status_code=200 took="838.765µs" user=me
DEBUG  [2021-01-17T16:34:37+02:00]api/api_controller.go:96 api.(*Dependencies).LogAction performing API action                         action=get_branch host="localhost:8000" message_type=action method=GET path=/api/v1/repositories/foo/branches/tr request_id=764d823c-38e7-42d9-9d1f-509c06c32eae service_name=rest_api user=me
TRACE  [2021-01-17T16:34:37+02:00]db/tx.go:79 db.(*dbTx).Get SQL query returned no results                 args="[foo tr]" query="SELECT commit_id, staging_token FROM graveler_branches WHERE repository_id = $1 AND id = $2" took="3.451µs" type=get
TRACE  [2021-01-17T16:34:37+02:00]httputil/tracing.go:143 httputil.TracingMiddleware.func1 HTTP call ended                               host="localhost:8000" method=GET path=/api/v1/repositories/foo/branches/tr request_body="[]" request_headers="map[Accept:[application/json] Accept-Encoding:[gzip, deflate] Accept-Language:[en-US,en;q=0.5] Authorization:[Basic QUtJQUpJNldITFdMSjRDVzdVNVE6TCtTTCtVNXc1U29tNFJtWlRSRnhuY1RNSW1tL1RIaXd4alhuZlJkRw==] Connection:[keep-alive] Content-Type:[application/json] Cookie:[access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA5NTU3NjEsImlhdCI6MTYxMDM1MDk2MSwic3ViIjoiZm9vIn0.0dgackpgYkQtu5sbYwbXF6r3KxtzUTM7gLk0Ct9KwNw] Referer:[http://localhost:8000/repositories/foo/compare] User-Agent:[Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0] X-Jwt-Authorization:[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTA5NTU3NjEsImlhdCI6MTYxMDM1MDk2MSwic3ViIjoiZm9vIn0.0dgackpgYkQtu5sbYwbXF6r3KxtzUTM7gLk0Ct9KwNw]]" request_id=764d823c-38e7-42d9-9d1f-509c06c32eae response_body="{\"message\":\"branch not found\"}\n" response_headers="map[Content-Type:[application/json] X-Request-Id:[764d823c-38e7-42d9-9d1f-509c06c32eae]]" sent_bytes=0 service_name=rest_api status_code=500 took="527.569µs" user=me
```

### PR DESCRIPTION
**Pull request by arielshaqed**
There are currently double errors for catalog and for graveler.  This *temporary* solution
just checks each error on both.  Once mvcc goes away, we can stay with the graveler error,
catalog will go away with mvcc.

Fixes #1212 (verified manually -- compare UI works).

### CODE REVIEW

**Review by nopcoder — APPROVED** [review]

File: api/api_controller.go [hunk 1]
```diff
@@ -849,6 +850,7 @@ func (c *Controller) RefsDiffRefsHandler() refs.DiffRefsHandler {
 			Limit: limit,
 			After: after,
 		})
+		// TODO(ariels): check if yoni added something for here!
```
Comment (johnnyaug) [inline api/api_controller.go:853]: mmm me?

**Review by johnnyaug — APPROVED** [review]

**Comment by arielshaqed** [comment]
Pulling once tests pass.
