### PR TITLE
Metaclient: fix bucket region check

### LINKED ISSUE #6283: GC fails when the bucket is not in the provided region
Arguably, this should not be a failure. But at the moment this is supported.

When the bucket is in a different region, the region check fails. Moreover, it takes a very long while.

Root cause for long time: HeadBucket request takes a long time.
Root cause for failure: GetBucketLocation fails with the following erro:
> ``` Retry com.amazonaws.services.s3.model.GetBucketLocationRequest@6bbad473 @2023-07-30T13:28:06.548Z: Other client exception: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: T6BEDTVQBYZG9Y9W; [ommitted]```

### PR DESCRIPTION
**Pull request by johnnyaug**
Resolves #6283.

When the bucket is not in the provided region, GC would fail. Moreover, it would take a long time to fail.
Fixes:
1. Do not use the HeadBucket request, which returned only after a very long while.
2. Check the region using a region-less client, otherwise we got:

> ``` Retry com.amazonaws.services.s3.model.GetBucketLocationRequest@6bbad473 @2023-07-30T13:28:06.548Z: Other client exception: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: T6BEDTVQBYZG9Y9W; [ommitted]```
3. Added timeout to GetBucketLocation request.

### CODE REVIEW

File: clients/spark/core/src/main/scala/io/treeverse/clients/StorageUtils.scala [hunk 1]
```diff
@@ -99,66 +100,61 @@ object StorageUtils {
...
-                      e.getMessage: Any
-                     )
-          false
-      }
-    }
-
     private def getAWSS3Region(client: AmazonS3, bucket: String): String = {
-      val bucketRegion = client.getBucketLocation(bucket)
+      var request = new GetBucketLocationRequest(bucket)
+      request = request.withSdkClientExecutionTimeout(TimeUnit.SECONDS.toMillis(15).intValue())
```
Comment (Jonathan-Rosenberg) [inline clients/spark/core/src/main/scala/io/treeverse/clients/StorageUtils.scala:156]: I think that you can set this value in the `configuration` (`ClientConfiguration`) that is passed to `initializeS3Client`.
It's constructed in the `S3ClientBuilder` files.

**Review by Jonathan-Rosenberg — APPROVED** [review]
COOL

File: clients/spark/core/src/main/scala/io/treeverse/clients/StorageUtils.scala (hunk 1 above)
Comment (johnnyaug) [reply clients/spark/core/src/main/scala/io/treeverse/clients/StorageUtils.scala:156]: Since this timeout applies to the entirety of an SDK operation (and not specific API requests), I don't want to take the risk of applying it globally.
