### PR TITLE
[GC] Fixed timeout in get request to lakeFS client when running GC on Azure 

### LINKED ISSUE #3814: Flaky GC on Azure integration test
The integration test of GC on Azure is flaky, and some times failing with timeout:
```
io.lakefs.clients.api.ApiException: java.net.SocketTimeoutException: timeout
	at io.lakefs.clients.api.ApiClient.execute(ApiClient.java:945)
	at io.lakefs.clients.api.RetentionApi.getGarbageCollectionRulesWithHttpInfo(RetentionApi.java:158)
	at io.lakefs.clients.api.RetentionApi.getGarbageCollectionRules(RetentionApi.java:136)
	at io.treeverse.clients.ApiClient.getGarbageCollectionRules(ApiClient.scala:106)
	at io.treeverse.clients.GarbageCollector$.main(GarbageCollector.scala:339)
	at io.treeverse.clients.GarbageCollector.main(GarbageCollector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
Full log can be found [here](https://github.com/treeverse/lakeFS/runs/7562349892?check_suite_focus=true).

### PR DESCRIPTION
**Pull request by lynnro314**
Close #3814, #3921

Added the possibility to add a configuration flag to spark-submit job to configure the timeout in lakeFS client.

### CODE REVIEW

File: clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala [hunk 1]
```diff
@@ -53,11 +53,19 @@ private object ApiClient {
...
+    apiUrl: String,
+    accessKey: String,
+    secretKey: String,
+    connectionTimeout: String = ""
+) {
   private val client = new api.ApiClient
   client.setUsername(accessKey)
   client.setPassword(secretKey)
   client.setBasePath(apiUrl.stripSuffix("/"))
+  if ((connectionTimeout != null) && (!connectionTimeout.isEmpty)) {
```
Comment (Jonathan-Rosenberg) [inline clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala:66]:
```suggestion
  if (connectionTimeout != null && !connectionTimeout.isEmpty) {
```

File: clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala [hunk 2]
```diff
@@ -53,11 +53,19 @@ private object ApiClient {
   }
 }
 
-class ApiClient(apiUrl: String, accessKey: String, secretKey: String) {
+class ApiClient(
+    apiUrl: String,
+    accessKey: String,
+    secretKey: String,
+    connectionTimeout: String = ""
```
Comment (Jonathan-Rosenberg) [inline clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala:60]: not sure if necessary to set a default value here

File: docs/reference/garbage-collection.md [hunk 3]
```diff
@@ -188,6 +188,7 @@ spark-submit --class io.treeverse.clients.GarbageCollector \
 * GC on Azure is supported from Spark client version >= v0.2.0.
 * In case you don't have `hadoop-azure` package as part of your environment, you should add the package to your spark-submit with `--packages org.apache.hadoop:hadoop-azure:3.2.1`
 * For GC to work on Azure blob, [soft delete](https://docs.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-overview) should be disabled.
+* If you're running into timeout error calling to lakeFS client in GC, consider adding to the sark-submit command the configuration: `-c spark.hadoop.lakefs.api.connection.timeout=TIMEOUT_IN_SECONDS`, in order to increase the timeout (the default is 10 seconds).
```
Comment (talSofer) [inline docs/reference/garbage-collection.md:191]: The documentation says that the use should insert the timeout in seconds but the code expects it to be in milliseconds. It is friendlier to let the user insert seconds and convert it by code. please fix the mismatch

**Review by talSofer — CHANGES_REQUESTED** [review]
Thanks! we need to fix a units mismatch

File: clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala (hunk 2 above)
Comment (lynnro314) [reply clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala:60]: There is use of this client in export too, so I added this default value instead of passing none to all places.

File: clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala [hunk 4]
```diff
@@ -53,11 +53,21 @@ private object ApiClient {
...
+) {
   private val client = new api.ApiClient
   client.setUsername(accessKey)
   client.setPassword(secretKey)
   client.setBasePath(apiUrl.stripSuffix("/"))
+  if (connectionTimeout != null && !connectionTimeout.isEmpty) {
+    // converting the connection timeout from seconds to milliseconds
+    val connectionTimeoutMillisec = connectionTimeout.toInt * 1000
```
Comment (talSofer) [inline clients/spark/core/src/main/scala/io/treeverse/clients/ApiClient.scala:68]: please use scala constant for milliseconds 
import scala.concurrent.duration.{Duration, MILLISECONDS}, see this for example https://www.programcreek.com/scala/scala.concurrent.duration.MILLISECONDS

**Review by talSofer — APPROVED** [review]
Approved but please look into the comment and address it, thanks!
