### PR TITLE
Control number of concurrent range writer uploaders

### LINKED ISSUE #1319: Control the amount of concurrent closed sstable writers
A flux of ongoing uploads on a slow internet connection is bound to starve some requests and fail the entire metarange write operation

### PR DESCRIPTION
**Pull request by arielshaqed**
Fixes #1319.

Requires replacing use of mock range writers with fake range writers!  Goroutines, go testing
and go mocks cannot work together: if a mock receives an unexpected parameter it cannot throw
an exception (because Go...), so it calls some `testing.t.Fa*`.  Unfortunately testing cannot
support failing in goroutines.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -105,11 +106,11 @@ const (
...
 
-	CommittedLocalCacheSizeBytesKey        = "committed.local_cache.size_bytes"
-	CommittedLocalCacheDirKey              = "committed.local_cache.dir"
-	CommittedLocalCacheRangeProportion     = "committed.local_cache.range_proportion"
-	CommittedLocalCacheMetaRangeProportion = "committed.local_cache.metarange_proportion"
-
+	CommittedLocalCacheSizeBytesKey             = "committed.local_cache.size_bytes"
+	CommittedLocalCacheDirKey                   = "committed.local_cache.dir"
+	CommittedLocalCacheNumUploadersKey          = "committed.local_cache.max_uploaders_per_writer"
+	CommittedLocalCacheRangeProportion          = "committed.local_cache.range_proportion"
```
Comment (itaiad200) [inline config/config.go:112]:
```suggestion
	CommittedLocalCacheRangeProportionKey          = "committed.local_cache.range_proportion"
```

File: config/config.go [hunk 2]
```diff
@@ -105,11 +106,11 @@ const (
...
+	CommittedLocalCacheMetaRangeProportion      = "committed.local_cache.metarange_proportion"
```
Comment (itaiad200) [inline config/config.go:113]:
```suggestion
	CommittedLocalCacheMetaRangeProportionKey      = "committed.local_cache.metarange_proportion"
```

File: catalog/migrate/migrate_test.go [hunk 3]
```diff
@@ -169,6 +169,7 @@ func NewEntryCatalogForTesting(t testing.TB, conn db.Database) (*rocks.EntryCata
 		MinRangeSizeBytes:          10240,
 		MaxRangeSizeBytes:          10240,
 		RangeSizeEntriesRaggedness: 1024,
+		MaxUploaders:               1,
```
Comment (itaiad200) [inline catalog/migrate/migrate_test.go:172]: Why so little?

File: graveler/committed/batch.go [hunk 4]
```diff
@@ -45,18 +52,24 @@ func (bc *BatchCloser) CloseWriterAsync(w ResultCloser) error {
...
 
 	bc.wg.Add(1)
-	go bc.closeWriter(w)
+	bc.ch <- w
 
 	return nil
 }
 
+func (bc *BatchCloser) handleClose() {
+	for w := range bc.ch {
```
Comment (itaiad200) [inline graveler/committed/batch.go:61]: Very elegant

File: graveler/committed/meta_range_writer.go [hunk 5]
```diff
@@ -79,7 +79,12 @@ func (w *GeneralMetaRangeWriter) WriteRecord(record graveler.ValueRecord) error
 	return nil
 }
 
+var ErrNeedBatchClosers = errors.New("need at least 1 batch uploaded")
+
 func (w *GeneralMetaRangeWriter) closeCurrentRange() error {
+	if w.params.MaxUploaders < 1 {
```
Comment (itaiad200) [inline graveler/committed/meta_range_writer.go:85]: Why wait until the first range is already written and is being closed to return this error?
Fail it when you first receive this value and create `GeneralMetaRangeWriter`.

**Review by itaiad200 — APPROVED** [review]
LGTM - I like this elegant go channeling solution!

Just a couple of small comments.

**Comment by arielshaqed** [comment]
Thanks!

Rebasing, waiting for tests, and pushing...

**Comment by arielshaqed** [comment]
Not sure why tests timing out, I reproduce no deadlock in `TestBranchLock` (or anywhere in graveler), with or without race detector.

So I just rebased and am trying again.

**Comment by arielshaqed** [comment]
Passed upon rebase.  Hopefully a breakage and not flakiness, but in any case appears unrelated to this PR.
Pushing, thanks for the review!
