### PR TITLE
Fix Name Display In Path

### LINKED ISSUE #9819: Fix Name Display In Path
This issue was opened to address one part of the original issue in [#1026](https://github.com/treeverse/product/issues/1026), which actually contains two separate problems.

This issue focuses on the case where a user has an `id` and a `friendly_name` but no `email`. In the `/auth/users` page, the UI correctly displays the user by `friendly_name`. but, after clicking the user , in the Users/{userID} path, the subsequent pages display the user’s id instead of the friendly_name, i.e:

Image

### PR DESCRIPTION
**Pull request by Annaseli**
Closes #9819 

Original issue: [1026](https://github.com/treeverse/product/issues/1026)

### Change Description 

The user reports that their username is not shown correctly in two places:
1. The Commits tab.
2. The user path in the Group Membership page, which they reach by selecting their user in Administration → Users.

#### What I did
1. I asked Offir to request additional debugging details from the customer in a comment on the issue.
2. Suspected Root Cause and Fix

Based on the customer’s screenshots, I think the issue is from inconsistent logic used to determine how a user’s name is displayed in different parts of the application:
a. In Administration → Users (/auth/users), the UI uses the `resolveUserDisplayName` function to determine what to show. This function prioritizes: email -> friendly_name -> id
The UsersContainer uses this logic when generating the paginationData passed to the DataTable to show the list of all the user.

But on the `User / {userId}` path, the displayed {userId} is derived from the former `getUserEmailById` in UsersIndexPage. This function only checks `email` and then falls back to `id`, ignoring `friendly_name`.
As a result, the display logic is not aligned with `resolveUserDisplayName`.

I updated `getUserEmailById` to use the same decision logic as `resolveUserDisplayName` and renamed the func name.

Although the customer hasn’t yet answered to confirm whether their `friendly_name` holds the correct username while their identity provider (Azure Entra SSO) fills `email` or `id` with the user ID, my explanation above aligns with the behavior shown in the screenshots because the customer didn't complain regarding the display name of the users in the `/auth/users`. So it is likely that the username they expect to see is stored in `friendly_name`, which previously was not being used outside `/auth/users` .

Even if this assumption ends up not being the exact root cause, the fix is still valid: all user display locations should use the same logic already established by `resolveUserDisplayName`.

b. Commit Display Issue
In the Commits page, the committer name shown in CommitWidget comes from the API call to `/repositories/{repository}/refs/{ref}/commits`. The server populates the `committer` via the `Committer() `function in model.go.

Here too, `friendly_name` was not included in the displayed info, leading to the same inconsistency. This has also been addressed so the committer display now respects the same naming resolution logic.

### CODE REVIEW

File: pkg/auth/model/model.go [hunk 1]
```diff
@@ -117,6 +117,9 @@ func (u *User) Committer() string {
 	if u.Email != nil && *u.Email != "" {
 		return *u.Email
 	}
+	if u.FriendlyName != nil && *u.FriendlyName != "" {
```
Comment (arielshaqed) [inline pkg/auth/model/model.go]: It is important to be friendly to users.  But "friendly names" might not be unique.  It is more important to identify a single user as the committer. :-(

So please revert this change.

We have a long-standing issue around documentation of the various fields on User, #6684.  Or go down this entire rabbit _warren_ starting from #6909.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Like the front-end changes!  But I believe the change to CommitRecord.User is incorrect and should be reverted - this is the requested change.  IIUC it is independent of the rest of the PR.

**Comment by Annaseli** [comment]
Manually tested by creating a user with an `id` and `friendly_name` but no `email`. Confirmed that the user is now correctly displayed using the `friendly_name` in the User/{user} path and in the deletion modal as expected as described in #9819

**Review by arielshaqed — APPROVED** [review]
Neat, thanks!
