### PR TITLE
Truncated long value names in confirmation window

### LINKED ISSUE #8669: [Bug]: A long value for a user name causes overflow in the credential window
### What happened?

A long value for a user name causes overflow in the credential window 

### Screenshot of the issue:

Image

    
### Steps to Reproduce:
1. Run ACL server with lakeFS
2. create a user with a long name
3. Go to Administration -> Users -> click on the long user name -> Access Credentials tab -> Create Access Key

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

```shell

```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by Annaseli**
Closes #8669

## Issue
Long user names overflowed "Confirmation" window 

## Fix
1. Applied truncation for long values in selected section modals.
2. Users can hover to see full value and copy the truncated value.

### In "Users" Page
1. create long user name under "Users"
2. Go to Administration -> Users -> click on the long user name -> Access Credentials tab -> Create Access Key

#### The issue screenshot:
long_user_name_in_confirm_issue

#### The fix screenshot:
long_user_name_in_confirm_fix

#### Changed in file:
webui/src/pages/auth/users/user/credentials.jsx (getMsg function)

## Testing
Verified on lakeFS OSS using local DB & object store & ACL

### CODE REVIEW

File: webui/src/pages/auth/users/user/credentials.jsx [hunk 1]
```diff
@@ -31,19 +31,39 @@ const UserCredentialsList = ({ userId, after, onPaginate }) => {
...
+                        text-nowrap
+                        overflow-hidden
+                        text-truncate
+                        align-middle
+                    "
+                title={email}
+            >
+                {email}
+                </strong>
+            <br/>
```
Comment (itaigilo) [inline webui/src/pages/auth/users/user/credentials.jsx:63]: Why the newline after the email?
I think it's better to have it on the same line...

**Review by itaigilo — CHANGES_REQUESTED** [review]
I think it's better to keep the `?` on the same line.

File: webui/src/pages/auth/users/user/credentials.jsx (hunk 1 above)
Comment (Annaseli) [reply webui/src/pages/auth/users/user/credentials.jsx:63]: Yes, I was wondering about that. Okay, I'll move the question mark to the same line as the email.

A related question: In your opinion, what should the expected behavior be?
Currently, long emails wrap to a new line, while short emails remain on the same line. Guy thinks the behavior should be the same for short, long, and overly long (requiring truncation) emails in terms of the line on which they appear.

What do you think should be the standard behavior for all cases?

I believe it would be better if all emails—whether short, long, or too long (requiring truncation)—appear on a new line, with the question mark positioned next to them.

Currently, here's what happens:
image

image

Comment (Annaseli) [reply webui/src/pages/auth/users/user/credentials.jsx]: 1. You're right—the question mark should be placed immediately after the email/name, so I fixed that.
2. The second question is: Do we agree that regardless of whether the email/name is short, long, or too long, the email/name should always be placed on a new line (with the question mark right after the email/name)? This way, all cases will appear as shown in these images. In other words, the length of the email/name won't determine whether it stays on the same line as "Create..." or moves to the next line.

image
image
image

Instead of the previous behavior, where a **short** name like "admin" remained on the same line, while a **long** email moved to the next line.

short email/name:
image

long email/name:
image

File: webui/src/pages/auth/users/user/credentials.jsx [hunk 2]
```diff
@@ -43,7 +45,24 @@ const UserCredentialsList = ({ userId, after, onPaginate }) => {
...
+                            text-nowrap
+                            overflow-hidden
+                            text-truncate
+                            align-bottom
+                            ${email.length > EMAIL_TRUNCATION_THRESHOLD_LENGTH ? "w-75" : ""}`}
+                title={email}
+            >
+                {email}
+            </strong>
+            {" "}?
```
Comment (itaigilo) [inline webui/src/pages/auth/users/user/credentials.jsx:63]: Nitpicking again:
I would've removed the `{" "}`, unless there's a good reason.
But that's your decision.

**Review by itaigilo — APPROVED** [review]
Nice fix 😄

File: webui/src/pages/auth/users/user/credentials.jsx (hunk 2 above)
Comment (Annaseli) [reply webui/src/pages/auth/users/user/credentials.jsx:63]: You're right, it looks better without it :)
