### PR TITLE
Import should use repo default branch

### LINKED ISSUE #1411: import doesn't work when default branch isn't master
When it's the first import, the import branch is created from "master" instead if the user-chosen branch.

### PR DESCRIPTION
**Pull request by itaiad200**
close #1411

### CODE REVIEW

File: onboard/import.go [hunk 1]
```diff
@@ -26,12 +29,13 @@ type Importer struct {
 type Config struct {
 	CommitUsername     string
 	InventoryURL       string
-	Repository         string
+	RepoID             graveler.RepositoryID
```
Comment (nopcoder) [inline onboard/import.go:32]:
```suggestion
	RepositoryID             graveler.RepositoryID
```

File: onboard/import.go [hunk 2]
```diff
@@ -26,12 +29,13 @@ type Importer struct {
...
+	Repo               *catalog.Repository
```
Comment (nopcoder) [inline onboard/import.go:33]: Don't think this one should be part of the configuration if we already passing the RepositoryID.
We need the full Repository information because we do not have access to the entry catalog - ask just Reposoty without passing the repository ID.

File: onboard/catalog_actions.go [hunk 3]
```diff
@@ -112,18 +114,18 @@ func (c *CatalogRepoActions) Init(ctx context.Context, baseCommit graveler.Commi
 }
 
 func (c *CatalogRepoActions) initBranch(ctx context.Context) error {
-	c.branchID = catalog.DefaultImportBranchName
-	branch, err := c.entryCataloger.GetBranch(ctx, c.repoID, catalog.DefaultImportBranchName)
+	c.branchID = DefaultImportBranchName
+	branch, err := c.entryCataloger.GetBranch(ctx, c.repoID, DefaultImportBranchName)
```
Comment (nopcoder) [inline onboard/catalog_actions.go:118]: When we get the branch and we fail, not with 'not found' we need to return the error - like we are doing when we try to create the branch.

**Review by nopcoder — CHANGES_REQUESTED** [review]

File: onboard/catalog_actions.go (hunk 3 above)
Comment (itaiad200) [reply onboard/catalog_actions.go:118]: Right, done.

File: onboard/import.go (hunk 1 above)
Comment (itaiad200) [reply onboard/import.go]: Done.

File: onboard/import.go (hunk 2 above)
Comment (itaiad200) [reply onboard/import.go]: Passed just what's mandatory - default branch id

**Review by nopcoder — APPROVED** [review]
