### PR TITLE
Multipart Bug (#7822)

### LINKED ISSUE #7822: Failure to Complete Multipart Upload for Large Files via S3 GW with GCS
When using lakeFS with GCS as the block adapter, moving ~8GB files via AWS CLI through S3 GW (default multipart upload chunk size of 8MB) fails on complete multipart upload due to unexpected number of parts.

Addition by Nadav:
OK I believe that I reproduced the problems(with Elad's help)

Command line:
nadavsteindler@Nadavs-MacBook-Pro Downloads % aws --endpoint-url http://localhost:8000 s3 cp ~/Desktop/bigfile.txt s3://gcptest/main/
upload failed: ../Desktop/bigfile.txt to s3://gcptest/main/bigfile.txt An error occurred (InternalError) when calling the CompleteMultipartUpload operation (reached max retries: 2): We encountered an internal error, please try again.

lakefs Log:
ERROR  [2024-06-30T19:01:47+03:00]pkg/gateway/operations/postobject.go:122 pkg/gateway/operations.(*PostObject).HandleCompleteMultipartUpload could not complete multipart upload           error="part list mismatch - expected 76 parts, got 954: multipart part list mismatch" host="localhost:8000" matched_host=false method=POST operation_id=post_object path=bigfile.txt physical_address=data/gf6or3eiuvokunnmsks0/cq0nt2miuvokunnmsli0 ref=main repository=gcptest request_id=737df8cf-2535-4a4b-8e8a-5a784ce9433a service_name=s3_gateway upload_id=data/gf6or3eiuvokunnmsks0/cq0nt2miuvokunnmsli0 user=admin

Ah but this is after the CLI does a retry- the error from the 1st try is
ERROR  [2024-07-03T16:13:07+03:00]pkg/block/gs/adapter.go:525 pkg/block/gs.(*Adapter).CompleteMultiPartUpload CompleteMultipartUpload failed                error="context canceled" host="localhost:8000" key=data/gf4rde6iuvolaihdbt40/cq2kot6iuvolaihdbt4g matched_host=false method=POST operation_id=post_object path=bigfile.txt physical_address=data/gf4rde6iuvolaihdbt40/cq2kot6iuvolaihdbt4g qualified_key=data/gf4rde6iuvolaihdbt40/cq2kot6iuvolaihdbt4g qualified_ns=nadav_bucket_7822 ref=main repository=gcptest request_id=486dfb58-1cec-46e1-aca6-0e534bef4bfa service_name=s3_gateway upload_id=data/gf4rde6iuvolaihdbt40/cq2kot6iuvolaihdbt4g user=admin
ERROR  [2024-07-03T16:13:07+03:00]pkg/gateway/operations/postobject.go:122 pkg/gateway/operations.(*PostObject).HandleCompleteMultipartUpload could not complete multipart upload           error="context canceled" host="localhost:8000" matched_host=false method=POST operation_id=post_object path=bigfile.txt physical_address=data/gf4rde6iuvolaihdbt40/cq2kot6iuvolaihdbt4g ref=main repository=gcptest request_id=486dfb58-1cec-46e1-aca6-0e534bef4bfa service_name=s3_gateway upload_id=data/gf4rde6iuvolaihdbt40/cq2kot6iuvolaihdbt4g user=admin

Which seems to indicate a timeout from the aws cli 

Filesize Partsize Result
1GB, 1MB, SUCCEED
4GB, 1MB, SUCCEED
6GB, 8MB, SUCCEED
8GB, 5MB part list mismatch - expected 627 parts, got 1526
8GB, 8MB, part list mismatch - expected 76 parts, got 954, expected 30 parts, got 954, expected 117 parts, got 954, etc.
8GB, 16MB SUCCEED
10GB, 8MB part list mismatch - expected 46 parts, got 1193:

BUT if I increase the AWS CLI Timeout it succeeds
aws --cli-read-timeout 300 --endpoint-url http://localhost:8000 s3 cp ~/Desktop/bigfile.txt s3://gcptest/main/

Root Cause:
When we try to upload large files with many parts to merge, the AWS CLI hits a timeout on the CompleteMultipart call. It then retries the call and this time fails when the number of parts doesn't match, since we have already concatenated some of the parts.

Note on gs.adapter.go:composeMultipartUploadParts
1. on the one hand we seem to want to support retry on failure mid-merge of the parts i.e. we list the current part files and merge those files specifically(so that if we already merged some it should continue where we left off)
2. on the other hand the validation checks that the file names we get from the list operation match exactly the uploaded file list from the S3 adapter call, so this validation will fail on retry since we already concatenated some of the part objects

Proposed fix:
We can support retry on timeout by loosening up the validate criteria. Instead of insisting on an exact match, we can check
1. number of parts listed <= number of expected parts
2. expected part names CONTAINS each listed part name, ETAG
PROBLEM: merge parts isn't atomic, so when it recovers it merges some of the parts twice because they were already merged but not deleted the previous time

Fix option 2:
Retrying the CompleteMultipartUpload call starts from scratch i.e. it lists the parts and starts the cup stacking algorithms on them from scratch. As such, if it does a retry, you should immediately get a file not found error.
We can use multithreading to make the upload much faster, making client-side timeouts a much rarer occurrence

Testing
Correctness & Performance tests here
https://docs.google.com/spreadsheets/d/1YWDpyDAFyeoZDJ-7XJyflCrvGgZs4oJ1zpll4TEdldM/edit?usp=sharing

### PR DESCRIPTION
**Pull request by nadavsteindler**
Closes #7822 

### Background

Share context and relevant information for the PR: offline discussions, considerations, design decisions etc.

### Bug Fix

If this PR is a bug fix, please let us know about:

1. Problem - The reason for opening the bug
2. Root cause - Discovered root cause after investigation
3. Solution - How the bug was fixed
      
### New Feature

If this PR introduces a new feature, describe it here.

### Testing Details

How were the changes tested?

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

## Additional info

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

### Contact Details

How can we get in touch with you if we need more info? (ex. email@example.com)

### CODE REVIEW

File: pkg/block/gs/adapter.go [hunk 1]
```diff
@@ -539,17 +527,56 @@ func (a *Adapter) CompleteMultiPartUpload(ctx context.Context, obj block.ObjectP
 	}, nil
 }
 
+func (a *Adapter) getPartNames(ctx context.Context, bucketName, uploadID string, multipartList *block.MultipartUploadCompletion) ([]string, error) {
+	// list bucket parts because maybe this is a retry and some have already been concatenated
+	bucketParts, err := a.listMultipartUploadParts(ctx, bucketName, uploadID)
```
Comment (nadavsteindler) [inline pkg/block/gs/adapter.go:532]: since we are not supporting retry, maybe we can just generate these

File: pkg/block/gs/adapter.go [hunk 2]
```diff
@@ -539,17 +527,56 @@ func (a *Adapter) CompleteMultiPartUpload(ctx context.Context, obj block.ObjectP
...
+	parts := make([]string, len(bucketParts))
+	for i, part := range bucketParts {
+		parts[i] = part.Name
+	}
+	return parts, nil
+}
+
 func (a *Adapter) validateMultipartUploadParts(uploadID string, multipartList *block.MultipartUploadCompletion, bucketParts []*storage.ObjectAttrs) error {
-	if len(multipartList.Part) != len(bucketParts) {
+	if len(multipartList.Part) < len(bucketParts) {
```
Comment (nadavsteindler) [inline pkg/block/gs/adapter.go:551]: Validation less relevant if we are not supporting retry continuing

File: pkg/block/gs/compose.go [hunk 3]
```diff
@@ -2,13 +2,17 @@ package gs
...
 	"fmt"
+	"sync"
+
+	"cloud.google.com/go/storage"
 )
 
 const MaxPartsInCompose = 32
 
-type ComposeFunc func(target string, parts []string) error
+type ComposeFunc func(target string, parts []string) (*storage.ObjectAttrs, error)
```
Comment (nadavsteindler) [inline pkg/block/gs/compose.go:12]: Errors should be handled with a stream

File: pkg/block/gs/adapter.go [hunk 4]
```diff
@@ -502,23 +502,11 @@ func (a *Adapter) CompleteMultiPartUpload(ctx context.Context, obj block.ObjectP
 		"key":           obj.Identifier,
 	})
```
Comment (nadavsteindler) [inline pkg/block/gs/adapter.go:504]: debug log time

File: pkg/block/blocktest/adapter.go
Comment (eladlachmi) [inline pkg/block/blocktest/adapter.go:1]: The problem with refactoring in this way is that, just by looking at the diff, it's hard to tell which part has changed because of a verbatim copy/paste and which part has substantive changes, which require review.

File: pkg/block/blocktest/multipart_suite.go
Comment (eladlachmi) [inline pkg/block/blocktest/multipart_suite.go:1]: Do we have a test that would fail before and pass after the fix? AFAIK, we get this issue as a bug report. It would be good to make up this coverage before applying the fix. Assuming we don't already have one, of course.

File: pkg/block/blocktest/adapter.go
Comment (nadavsteindler) [reply pkg/block/blocktest/adapter.go:1]: I understand, but these test files are really hard to navigate since they are so long, so I think it's worth splitting them

Comment (eladlachmi) [reply pkg/block/blocktest/adapter.go:1]: I see. Ok, that's good to know. Thank you.

File: pkg/block/blocktest/multipart_suite.go
Comment (eladlachmi) [reply pkg/block/blocktest/multipart_suite.go:1]: I see... ok, I was under the impression that the bug was related initially to our method of counting the uploaded parts.

In that case, am I correct that the upload can still timeout? We've solved a timeout by making the process go faster? What do we do for other adapters? I'd expect this to be an issue with any HTTP request, not specific to GCS.

Comment (nadavsteindler) [reply pkg/block/blocktest/multipart_suite.go:1]: Sorry I updated at the daily you missed. The parts count was after the AWS CLI retried after the first call timed out and left a partial state.

The fix is to multi-thread the merging of the parts, so it takes under 10 seconds even for very large uploads

Comment (eladlachmi) [reply pkg/block/blocktest/multipart_suite.go:1]: Don't get me wrong. I think it's a worthy improvement. I'm just thinking if it actually solves the issue that it's connected to... 🤔

Comment (eladlachmi) [reply pkg/block/blocktest/multipart_suite.go:1]: Ok, thanks for the clarification. That brings me back to my question... ok, so we've made it less likely that the request would time out. But does it actually fix the issue? I mean, the request can still time out.

What I'm suggesting...  
Aside from the speeding up of multipart uploads (which is a good idea anyway, where possible), maybe the problem is that we don't return/log the correct error. Not sure if and how much control we have over what the AWS CLI ultimately displays, but IMO, it's worth looking into.

Comment (nadavsteindler) [reply pkg/block/blocktest/multipart_suite.go:1]: So the code no longer lists parts- it computes the precise part names. So the retry will ignore the partial result of the 1st attempt and probably time out with the same "client reset connection" error. The user can then increase the AWS CLI timeout

Comment (eladlachmi) [reply pkg/block/blocktest/multipart_suite.go:1]: Ok, that makes sense. Thank you!

Comment (nadavsteindler) [reply pkg/block/blocktest/multipart_suite.go:1]: Also I wouldn't be surprised if 1TB upload comes out under 60 seconds. I'm taking benchmarks of smaller cases, so that should give us a good projection for very large objects...

File: pkg/block/gs/adapter.go [hunk 5]
```diff
@@ -26,10 +25,7 @@ const (
 )
 
 var (
-	ErrMismatchPartETag    = errors.New("mismatch part ETag")
```
Comment (nadavsteindler) [inline pkg/block/gs/adapter.go:29]: Did we lose our verification that content matches original?

File: pkg/block/gs/adapter.go [hunk 6]
```diff
@@ -26,10 +25,7 @@ const (
...
-	ErrMismatchPartName    = errors.New("mismatch part name")
```
Comment (nadavsteindler) [inline pkg/block/gs/adapter.go:30]: Do we need to still return this for compatability?

File: pkg/block/gs/adapter.go [hunk 7]
```diff
@@ -7,7 +7,6 @@ import (
 	"io"
```
Comment (nadavsteindler) [inline pkg/block/gs/adapter.go:7]: We should also test that this doesn't break Multipart Upload REST API(LakeCTL)

File: pkg/block/gs/adapter.go (hunk 6 above)
Comment (nadavsteindler) [reply pkg/block/gs/adapter.go:30]: So we are not 100% S3 compatible with regard to errors. See documentation here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

For example, if the ETAG doesn't match, there is a specific error:
Error Code: InvalidPart
Description: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified ETag might not have matched the uploaded part's ETag.
HTTP Status Code: 400 Bad Request

Our code contains this error but does not invoke it, see pkg/gateway/errors/errors.go
There is an ErrInvalidPart but no one uses it

File: pkg/block/gs/adapter.go (hunk 5 above)
Comment (nadavsteindler) [reply pkg/block/gs/adapter.go:29]: OK yes S3 sends etags for the parts with the complete request with the expectation that we will through an error in the case of a mismatch

Comment (eladlachmi) [reply pkg/block/gs/adapter.go:29]: Yeah, both validations are critical to the MPU functionality. Reliability is the top concern.

Comment (nadavsteindler) [reply pkg/block/gs/adapter.go]: OK so I had to return the list to do this- I did add a filter so that previous calls that time out will not effect the next call

**Review by guy-har — APPROVED** [review]
Looks Good! 
Great improvement 💪 
Does this solve the issue completely or reduce the risk of it happening because things are faster now. Basically, my question is, is there a file size that can cause this issue again, and if it happens again will we understand from the result/logs or need to do the research all over again, if that's the case maybe we should document it somewhere (code or issue)

File: pkg/block/gs/adapter.go (hunk 7 above)
Comment (nadavsteindler) [reply pkg/block/gs/adapter.go]: LakeCTL doesn't do multipart upload
That leaves the REST API for multipart- I read the code- seems like a low risk that anything in this change would break it- not sure it's worth testing

**Review by eladlachmi — APPROVED** [review]
LGTM. Thank you!
