### PR TITLE
Delta Diff fails on certain operations

### LINKED ISSUE #5862: Delta Diff fails: `failed to run diff`
lakeFS v0.100.0

`Show table changes` fails

CleanShot_2023-05-12_at_14 53 00

`failed to run diff`

CleanShot_2023-05-12_at_14 52 42

lakeFS log shows: 

```
2023-05-12T13:51:52.203Z [DEBUG] delta.delta: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Aborted, message: "Creating operation history aborted due to:\nUnknownOperation(\"CREATE OR REPLACE TABLE AS SELECT\")", source: None }', src/main.rs:148:80
time="2023-05-12T13:51:52Z" level=error msg="failed to perform diff" func="pkg/plugins/diff.(*Service).RunDiff" file="build/pkg/plugins/diff/service.go:124" error="rpc error: code = Canceled desc = stream terminated by RST_STREAM with error code: CANCEL" host="localhost:8000" method=GET operation_id=OtfDiff params="{TablePaths:{Left:{Ref:data_load@ Path:aggs/agg_variety/} Right:{Ref:data_load Path:aggs/agg_variety/} Base:{Ref: Path:}} S3Creds:{Key:AKIAIOSFODNN7EXAMPLE Secret:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY Endpoint:http://0.0.0.0:8000} Repo:example}" path="/api/v1/repositories/example/otf/refs/data_load%40/diff/data_load?table_path=aggs%2Fagg_variety%2F&type=delta" request_id=d3b6fdc7-2544-4c12-8e05-376f16e35a80 service_name=rest_api type=delta user=docker
time="2023-05-12T13:51:52Z" level=error msg="OTF Diff service failed" func="pkg/api.(*Controller).OtfDiff" file="build/pkg/api/controller.go:4253" error="failed to run diff" host="localhost:8000" method=GET operation_id=OtfDiff path="/api/v1/repositories/example/otf/refs/data_load%40/diff/data_load?table_path=aggs%2Fagg_variety%2F&type=delta" repo=example request_id=d3b6fdc7-2544-4c12-8e05-376f16e35a80 service=api_gateway service_name=rest_api table_diff_paths="{Left:{Ref:data_load@ Path:aggs/agg_variety/} Right:{Ref:data_load Path:aggs/agg_variety/} Base:{Ref: Path:}}" type=delta user=docker
```

The table is question is built with a `CREATE OR REPLACE TABLE AS SELECT` statement in each of the versions being compared.

### PR DESCRIPTION
**Pull request by Isan-Rivkin**
Closes #5862

In this code, after the initial None check, the code filters the `OP_TYPES` hashmap to find all key-value pairs where the key is a prefix of op_name. These prefix matches are collected into a vector of tuples (key, value).

Then, based on the number of prefix matches, the code handles different cases:

- If no prefix matches are found, an error is returned.
- If only one prefix match is found, the corresponding value is returned.
- If multiple prefix matches are found, the code chooses the longest matching prefix and retrieves the corresponding value from `OP_TYPES`.

It was tested manually by executing delta query's.

### CODE REVIEW

File: pkg/plugins/diff/delta_diff_server/src/delta_ops.rs [hunk 1]
```diff
@@ -52,6 +52,7 @@ lazy_static! {
         hm.insert("WRITE", OperationType::Update as i32);
         hm.insert("INSERT", OperationType::Update as i32);
         hm.insert("DELETE", OperationType::Delete as i32);
+        hm.insert("CREATE", OperationType::Create as i32);
```
Comment (Jonathan-Rosenberg) [inline pkg/plugins/diff/delta_diff_server/src/delta_ops.rs:55]: If you're at it, do you mind adding the following as well:
```rust
        hm.insert("ALTER", OperationType::Update as i32);
        hm.insert("SYNC", OperationType::Update as i32);
        hm.insert("LOAD", OperationType::Update as i32);
        hm.insert("COMMENT ON", OperationType::Update as i32);
        hm.insert("GENERATE", OperationType::Create as i32);
        hm.insert("DROP", OperationType::Delete as i32);
```

**Review by Jonathan-Rosenberg — CHANGES_REQUESTED** [review]
Thanks!
I know that the comment I've added isn't related to this bug specifically but it will probably prevent the next one 😅

**Review by Jonathan-Rosenberg — APPROVED** [review]
