### PR TITLE
Action hook run results fix listing hooks order

### LINKED ISSUE #1532: Actions list hook run results order
Hook results are sorted by hook run ID.  The ID is composed of a timestamp and a random part.  Because we allocate the running hooks information at the same time - all same the same prefix and the sort order is based on the random part.
Using the order the allocate the tasks for execution or the actual time will produce a better sort order for listing these results.

### PR DESCRIPTION
**Pull request by nopcoder**
Fix #1532

Remove the random part from the hook run ID, in order to get a consistent and more meaningful order of the list of hook results.
Kept the task allocation and ID assignment at the same place - used a sequence number to assign IDs.

### CODE REVIEW

File: actions/service.go [hunk 1]
```diff
@@ -421,3 +423,8 @@ func (s *Service) PostMergeHook(ctx context.Context, record graveler.HookRecord)
 	// post merge actions will be enabled here
 	return nil
 }
+
+func NewHookRunID(id int) string {
+	tm := time.Now().UTC().Format("02150405")
+	return fmt.Sprintf("H%s%06d", tm, id)
```
Comment (itaiad200) [inline actions/service.go:429]: What does the `H` stand for?

File: actions/service.go [hunk 2]
```diff
@@ -421,3 +423,8 @@ func (s *Service) PostMergeHook(ctx context.Context, record graveler.HookRecord)
 	// post merge actions will be enabled here
 	return nil
 }
+
+func NewHookRunID(id int) string {
+	tm := time.Now().UTC().Format("02150405")
```
Comment (itaiad200) [inline actions/service.go:428]: You don't use the same time for the tasks, so we already have prefix which is sorted and unique, no?

**Review by itaiad200 — CHANGES_REQUESTED** [review]

File: actions/service.go (hunk 1 above)
Comment (nopcoder) [reply actions/service.go:429]: Will remove it - used it first to identify the hook run id

File: actions/service.go (hunk 2 above)
Comment (nopcoder) [reply actions/service.go:428]: right, f2f chat - will use action and hook idx to identify the specific task

Comment (nopcoder) [reply actions/service.go:428]: went with 4 digits for each range - just in case.

**Review by itaiad200 — APPROVED** [review]
